### ISSUE TITLE
Release on F-Droid

### ISSUE THREAD

**Issue by jcgruenhage** [jellyfin/jellyfin-android#1]

**Comment by jcgruenhage** [comment]
Oh, this doesn't even build? Well yeah, then an F-Droid release is sort of low priority :D

**Comment by winters-brown** [comment]
Does this project successfully build so far?

**Comment by dkanada** [comment]
Yes, we have it building with a few workarounds. The first step to get the app on F-Droid is building the app with no hacks and updated build tools. After that we will need to build all the dependencies from source. Currently there are several libraries that just use jar files.

**Comment by dkanada** [comment]
@IzzySoft we can't include this app in the main repository yet because it requires play services and a few jar files still need to be removed. Would it be accepted on your repository? We can tag releases and upload the signed APK files to GitHub, which I think is the usual procedure.

We should have an official release out in the next few days for Google Play and we're working on Amazon as well, but F-Droid would be really nice to have.

**Comment by IzzySoft** [comment]
I cannot tell for sure without having seen an APK. You know there's e.g. a size limit (20M per app) in my repo. No problem with the JARs on my end, and if it's only Play Services (and not also Firebase Analytics etc), that shouldn't be a show-stopper for me.

**Comment by dkanada** [comment]
Do you allow multiple architectures? We have three in the build at the moment, but are debating on whether or not we want to keep the library that depends on it. All three are under the size limit, although I had forgotten that one. We also have an AndroidTV client getting released soon, do you allow those apps or is the repository strictly Android?

**Comment by IzzySoft** [comment]
I can give a "yes" to that (we support multi-architecture). We're not sure concerning AndroidTV: does that require any proprietary stuff?

**Comment by dkanada** [comment]
I don't think so, and I honestly didn't know F-Droid supported it before someone mentioned it on Riot or something. I think the only use case is for people who sideload F-Droid onto their televisions, so not a very big audience.

**Comment by IzzySoft** [comment]
Funny that when I asked for that, noone seemed to know. I'd say that means there isn't yet any such app in our repos. And yes, audience is probably rather small.

**Comment by atcommander** [comment]
Curious as to where things stand with getting jellyfin in F-Droid?

**Comment by dkanada** [comment]
That depends on whether a custom repository or the IzzyOnDroid repository would be preferable for users. This app will likely never get on the official repository because I don't want to rely on hacks to work around Cordova.

**Comment by IzzySoft** [comment]
@dkanada There are Cordova apps in F-Droid. I'm no packager, so I'm not aware of "hacks" being needed for that; IIRC all that's needed is the project folder being added to your repo.

I see your releases now have APK files attached, so I could easily pick them for my repo. But I'd need an app description (from your README I cannot get an idea what the app is about); preferably also some screenshots (maybe establishing [Fastlane file structure](https://gitlab.com/snippets/1895688) in your repo would be a good idea).

**Comment by dkanada** [comment]
> all that's needed is the project folder being added to your repo

Yeah that's kind of a hack in my opinion, the project folder is basically the generated code from the build step. It's not bytecode but it's the Cordova equivalent.

**Comment by IzzySoft** [comment]
Well, that can't be helped then. A pity though it stops you. But adding Fastlane (or providing description/summary/screenshots some other way) hopefully would not be considered a hack? :wink:

**Comment by dkanada** [comment]
See #308 for the planned release on F-Droid in the next week or two. I will close this issue in favor of that one, and we can track any issues with the release there.
