### ISSUE TITLE
Internal/ external player failed to load media info from server

### ISSUE THREAD

**Issue by CrazyWolf13** [jellyfin/jellyfin-android#1008]
### Describe the bug

1. Set the player in the app to internal or external and if you try to play anything it will show unable to load media info from server.
2. The standart webplayer works fine.

### Logs

```shell
Not really possible.
If really needed i could try to get them.
```

### Application version

2.4.4

### Where did you install the app from?

Google Play

### Device information

SamsungGalaxy S22

### Android version

Android 13

### Jellyfin server version

10.8.9

### Which video player implementations does this bug apply to?

- [ ] Web player (default)
- [X] Integrated player (ExoPlayer)
- [X] External player (VLC, mpv, MX Player)

**Comment by nielsvanvelzen** [comment]
With the provided information this issue is not reproducible.

**Comment by CrazyWolf13** [comment]
> 

Well, on my end it behaves like this.

**Comment by CrazyWolf13** [comment]
> With the provided information this issue is not reproducible.

Did some further testing, and while building the app directly from github files it does not act like that, self compiled works without issues.

**Comment by CrazyWolf13** [comment]
> With the provided information this issue is not reproducible.

Signed up for play store beta-tester and there the issue seems to be gone.
