### ISSUE TITLE
Subtitle track selection not taking effect from Integrated Player

### ISSUE THREAD

**Issue by silentTeee** [jellyfin/jellyfin-android#1017]
### Describe the bug

1. Begin playing file with at least one subtitle track, with none selected
2. While playing the video, use the UI to change to one track.
3. Observe the current setting not take effect.

In comparison, back out of the video and apply the Subtitle track setting from the synopsis page and begin playback again, which _will_ work. 

Audio track selection from the player appears to work fine for files with multiple supported streams.

### Application version

2.5.0-beta.3

### Where did you install the app from?

Sideloaded APK (proprietary build)

### Device information

Google Pixel 7

### Android version

Android 13

### Jellyfin server version

10.8.9 stable

### Which video player implementations does this bug apply to?

- [ ] Web player (default)
- [X] Integrated player (ExoPlayer)
- [ ] External player (VLC, mpv, MX Player)

**Comment by silentTeee** [comment]
It might be worth mentioning that every time I try to apply a new subtitle setting from within the player, after tapping the radio button once and witnessing the prompt close, if I open it again, the radio button that is highlighted is for the previous selection. But if press it again, the UI element will change when I check it for the third time, but it still won't be applied.

**Comment by Maxr1998** [comment]
Could you add some more information on the media you're trying to stream?

Also, are you direct playing or transcoding?

**Comment by silentTeee** [comment]
Of course! Below is the metadata for just one file I tested with, I can reproduce this bug with files that use PGS-based subtitles as well. Without subtitles on the info bubble teports Im DirectPlaying, and once I get them to properly shoe up the info bubble reports Transcoding.

My Bride is a Mermaid - S01E11
Container: mkv
Size: 200 MB

Video
Title: 720p HEVC SDR
Codec: HEVC
Profile: Main 10
Level: 93
Resolution: 1280x720
Aspect ratio: 16:9
Interlaced: No
Framerate: 23.976025
Bitrate: 1153 kbps
Bit depth: 10 bit
Video range: SDR
Video range type: SDR
Pixel format: yuv420p10le
Ref frames: 1

Audio
Title: English - AAC - Stereo - Default
Language: eng
Codec: AAC
Profile: LC
Layout: stereo
Channels: 2 ch
Bitrate: 91 kbps
Sample rate: 48000 Hz
Default: Yes
Forced: No
External: No

Subtitle
Title: Signs/Songs (Doki) - English - Default - ASS
Language: eng
Codec: ASS
Default: Yes
Forced: No
External: No

Audio
Title: Japanese - AAC - Stereo
Language: jpn
Codec: AAC
Profile: LC
Layout: stereo
Channels: 2 ch
Bitrate: 98 kbps
Sample rate: 48000 Hz
Default: No
Forced: No
External: No

Subtitle
Title: Dialogue (Doki) - Japanese - ASS
Language: jpn
Codec: ASS
Default: No
Forced: No
External: No

**Comment by silentTeee** [comment]
Wow, you have good instincts: turning on "allow ssa/ass in direct play" got the in-player Subtitle selection to work!

**Comment by Maxr1998** [comment]
Awesome, I could reproduce this issue on one of my shows as well, I'll try to fix it before we go stable with 2.5.0.
