### ISSUE TITLE
Android 9.0 has cleartext support disabled by default, so unable to connect to http jellyfin instance

### ISSUE THREAD

**Issue by Matt07211** [jellyfin/jellyfin-android#102]
This means if someone is connecting via a http connection (E.g. Local network connecting via http://192.168.1.111:8096) will fail to connect.

Refernce: https://developer.android.com/training/articles/security-config#CleartextTrafficPermitted

**Comment by dkanada** [comment]
I ran into [this](https://github.com/dpa99c/cordova-plugin-cloud-settings/issues/5) issue while trying to fix the build. @thornbill how do you think we should proceed?
