### ISSUE TITLE
Server address not remembered

### ISSUE THREAD

**Issue by molitar** [jellyfin/jellyfin-android#1047]
**Describe the feature you'd like**
For it to save server address I am really tired of entering in http://<domain name>:8096 EVERY SINGLE TIME!  Seriously it is not hard to give a place to save address!

**Additional context**
Just allow the app to save the stupid location so don't have to keep entering it/

**Comment by nielsvanvelzen** [comment]
Feature requests go to features.jellyfin.org

**Comment by nielsvanvelzen** [comment]
In addition this is already supported.

**Comment by Maxr1998** [comment]
The server address is remembered, if it isn't that sounds like a misconfiguration (or bug that happens in very specific circumstances).
