### ISSUE TITLE
Jellyfin can't connect to https server from Android app

### ISSUE THREAD

**Issue by aardbol** [jellyfin/jellyfin-android#1048]
### Describe the bug

I recently put my server behind an nginx reverse proxy using a let's encrypt certificate. Everything works well on my TV and in my browser, but the android app can't manage to connect to it. The error is "Unable to reach server" My phone is on the same subnet as the firewall allows traffic from.

### Application version

2.4.4

### Where did you install the app from?

F-Droid

### Device information

Fairphone 4

### Android version

12

### Jellyfin server version

10.8.10

### Which video player implementations does this bug apply to?

- [ ] Web player (default)
- [ ] Integrated player (ExoPlayer)
- [ ] External player (VLC, mpv, MX Player)

**Comment by Maxr1998** [comment]
This might be the same issue as #571, could you ensure your certificate configuration is correct?

**Comment by aardbol** [comment]
It was indeed the same issue: I didn't configure the fullchain cert, but instead one of the other.
