### ISSUE TITLE
HEVC Rext 10Bit Not Playable

### ISSUE THREAD

**Issue by StevMaHo** [jellyfin/jellyfin-android#1049]
### Describe the bug

![Screenshot_2023-05-15-20-57-18-701_org jellyfin mobile-01](https://github.com/jellyfin/jellyfin-android/assets/105807526/f713505a-97be-42a1-a18a-0a622ca0bcc5)
![Screenshot_2023-05-15-21-06-16-785_org jellyfin mobile-01](https://github.com/jellyfin/jellyfin-android/assets/105807526/97542a85-4304-424c-8f6a-bff09406aac4)

Happens with both Hardware decode and software

### Application version

2.5.0

### Where did you install the app from?

Sideloaded APK (libre build)

### Device information

Xiaomi Mi Pad 5

### Android version

Android 12

### Jellyfin server version

1.8.10

### Which video player implementations does this bug apply to?

- [ ] Web player (default)
- [X] Integrated player (ExoPlayer)
- [ ] External player (VLC, mpv, MX Player)

**Comment by StevMaHo** [comment]
Now i have a x264 File that is Not playelbel too
![Screenshot_2023-05-22-16-08-05-712_org jellyfin mobile~2](https://github.com/jellyfin/jellyfin-android/assets/105807526/533b24e4-90fa-4ff9-b69e-76e5a72a9b19)

**Comment by Maxr1998** [comment]
Possibly an ExoPlayer bug, please check if it's fixed in the upcoming release (2.5.2).

**Comment by StevMaHo** [comment]
Nope still happens, when i force it to Transcode with .ass sub or with Lower Resolution it plays fine. Mabye it trys to direkt Play but can't?

**Comment by StevMaHo** [comment]
When i Play it localy with MX player, only the Software decoder works. possibly because my device dosent Support the Profile. (HEVC Main 10 can be played with Hardware decoder) Mabye... Only Mabye jellyfin Looks only on the Codex but Not on the Profil? for direkt play
