### ISSUE TITLE
Music controls overlap with Navigation bar

### ISSUE THREAD

**Issue by GopinathVaddem** [jellyfin/jellyfin-android#105]
**Describe the bug**
When trying to play music, music controls in bottom app bar overlapping with navigation bar. Unable to change/control music from bottom bar.

**To Reproduce**
0. Make sure 'Navigation type' set to 'Navigation buttons' in Settings
1. In Jellyfin app, Click on 'Sandwich icon' top left
2. Click on 'Music' under 'Media'
3. Select any album and play song
4. Notice media controls in bottom overlap with Navigation bar

**Expected behavior**
Expected to have Bottom app bar above Navigation bar.

**Screenshots**
![Screenshot_20200907-203855_Jellyfin_1](https://user-images.githubusercontent.com/26093139/92425569-3d36d180-f14d-11ea-910d-83b8d915da64.jpg)
Overlap is highlighted in the bottom of screenshot

**System (please complete the following information):**
 - App version: jellyfin-android-v2.0.0-rc.3-release.apk
 - Android version: Android 10
 - Device manufacturer and model: Samsung Galaxy S10+

**Comment by timonoj** [comment]
Can confirm the same in my Galaxy S10e.

**Comment by nielsvanvelzen** [comment]
Duiplicate of #88
