### ISSUE TITLE
Pressing any button on the ExoPlayer UI causes the phone's status bar to appear and then not disappear.

### ISSUE THREAD

**Issue by maru801** [jellyfin/jellyfin-android#1051]
### Describe the bug

When playing a video in the landscape orientation, Android's top-bound status/info bar should disappear to not block the video.

When a video is started, the status bar goes away. However, if any of the UI buttons are pressed (audio button, subs button, quality changer, etc.), the status bar on top will appear and never disappear again.

The only way to remove the status bar is to double-press on the "enter full-screen" icon to reset the window.

### Application version

2.5.0

### Where did you install the app from?

Google Play

### Device information

Samsung Note9

### Android version

Android 10 (Samsung's One UI 2.5)

### Jellyfin server version

10.8.10

### Which video player implementations does this bug apply to?

- [ ] Web player (default)
- [X] Integrated player (ExoPlayer)
- [ ] External player (VLC, mpv, MX Player)

**Comment by Maxr1998** [comment]
That's odd, I can't reproduce this on my end (Pixel 5 Android 13). Might need to fire up an emulator to specifically check Android 10 as well.

**Comment by Maxr1998** [comment]
Confirmed to be a version-specific bug. And there was me thinking that libraries for compatibility would have the same behavior on all versions…
