### ISSUE TITLE
F-Droid inclusion?

### ISSUE THREAD

**Issue by timonoj** [jellyfin/jellyfin-android#106]
Hi, do you guys plan to include this app in the F-Droid repo, instead of the Google Playstore? Since it's all open source, it shouldn't be much of a hassle.

Thanks!

**Comment by nielsvanvelzen** [comment]
We're planning to add the app to F-Droid as discussed in the [Android 2.0.0 release plan](https://github.com/jellyfin/jellyfin-android/issues/36). We do need to make some changed for that though (adding a build flavor without chromecast and adding f-droid metadata) so it won't be for the 2.0.0 release, hopefully 2.1 :)

**Comment by herbsmn** [comment]
"only problem left is the reproducible build failing for some reason"
https://gitlab.com/fdroid/fdroiddata/-/merge_requests/7682

Looks like we are getting really close to seeing jellyfin land in f-droid! exciting!

**Comment by nielsvanvelzen** [comment]
The issues should be fixed and the next release should work on F-Droid. Stay tuned! :)

**Comment by herbsmn** [comment]
Thanks for all your work on this! It is very much appreciated!
