### ISSUE TITLE
Android app doesn't allow library scrolling

### ISSUE THREAD

**Issue by Universezero** [jellyfin/jellyfin-android#1074]
When trying to scroll my Jellyfin library on the Android app, the scrolling appears to be broken. It keeps jumping back to the start of the list, preventing me from reaching shows further down the list. This bug also seems to happen on the home screen.

**Comment by nielsvanvelzen** [comment]
When you open the app, does it show a big warning to not use the TV app on touch screen devices? And if not; are you still sure you're not using the app for televisions?
