### ISSUE TITLE
Can't stream live tv from HDHR

### ISSUE THREAD

**Issue by skug67** [jellyfin/jellyfin-android#108]
When I try to watch livetv via HDHR-Prime the android app times out and gives the message: "No compatible streams are currently available."

I've got no problem watching livetv via the web interface -- including using chrome on my android phone.  So obviously, not a huge problem given the easy workaround.  But just thought I'd flag it.

**Comment by flowlee** [comment]
I also have this problem, but with a tvheadend server that's integrated as an M3U Tuner in Emby.

**Comment by Astate** [comment]
Same probleme here, livetv on jellyfin-web work but not on jellyfin-AndroidTV or jellyfin-Android.
i also use use hdHomerun.

**Comment by hobesman** [comment]
Writing to confirm that I too am having this problem. The android app actually reports "Playback Error" and then "PlaybackErrorNoCompatibleStream"

**Comment by m0ngr31** [comment]
Have the same issue with any kind of live stream. Doesn't have to be from just HDHR.

**Comment by Fma965** [comment]
+1

**Comment by JustAMan** [comment]
Could this be caused by https://github.com/jellyfin/jellyfin/issues/2035, https://github.com/jellyfin/jellyfin/issues/2030 or https://github.com/jellyfin/jellyfin/issues/1749?

**Comment by Fma965** [comment]
> Could this be caused by [jellyfin/jellyfin#2035](https://github.com/jellyfin/jellyfin/issues/2035), [jellyfin/jellyfin#2030](https://github.com/jellyfin/jellyfin/issues/2030) or [jellyfin/jellyfin#1749](https://github.com/jellyfin/jellyfin/issues/1749)?

[jellyfin/jellyfin#2035](https://github.com/jellyfin/jellyfin/issues/2035),  - No basepath set
[jellyfin/jellyfin#2030](https://github.com/jellyfin/jellyfin/issues/2030)  - no specific IP set
[jellyfin/jellyfin#1749](https://github.com/jellyfin/jellyfin/issues/1749)? - don't think so although i am using xteve

**Comment by m0ngr31** [comment]
Did the app get a version bump?

**Comment by thornbill** [comment]
Not yet. This should be fixed in the next release though!
