### ISSUE TITLE
rotation bug 2.5.1+

### ISSUE THREAD

**Issue by Mapienator** [jellyfin/jellyfin-android#1085]
### Describe the bug

Opening videos on android 12 (one plus nord2) plays all videos always in portrait until you press the full screen button. Can't seem to find a option to change this.

### Application version

2.5.1

### Where did you install the app from?

F-Droid

### Device information

oneplus nord 2 5G

### Android version

12

### Jellyfin server version

10.8.9

### Which video player implementations does this bug apply to?

- [ ] Web player (default)
- [ ] Integrated player (ExoPlayer)
- [ ] External player (VLC, mpv, MX Player)

**Comment by Maxr1998** [comment]
Are you using the integrated player? Please read the discussion in #809. You can change the behavior in the app's client settings.
