### ISSUE TITLE
Battery Optimization Message

### ISSUE THREAD

**Issue by cesalo** [jellyfin/jellyfin-android#110]
I noticed this message in my phone (Oneplus Android 9) and my tablet (Chrome OS) but even in my phone even when the option is disabled I still see the message every time I open the app (Beta 7).
Is this something that can be disabled? I don't want affect the usability, maybe is something that tons of people needs in android but the fact that it always popping up must be some sort of bug.
An option to disable this check would be very helpful.

**Comment by anthonylavado** [comment]
Work on this has started with #111.

**Comment by cesalo** [comment]
Thanks for the update.

**Comment by dkanada** [comment]
This will be fixed in the next update, thanks for reporting the issue.
