### ISSUE TITLE
Transcoding instead remuxing

### ISSUE THREAD

**Issue by IIeTp** [jellyfin/jellyfin-android#1121]
### Describe the bug

Greetings. I tested the file with external audio tracks on android phone. If you open the file in the chrome browser, then the remux starts, if you open it through the application, then the transcode starts. I tried changing the web player in the app to exo player, same result.
[Agents.of.S.H.I.E.L.D.zip](https://github.com/jellyfin/jellyfin-android/files/9121731/Agents.of.S.H.I.E.L.D.zip)

### Logs

[logcat.txt](https://github.com/jellyfin/jellyfin-android/files/9121726/logcat.txt)

### Application version

2.4.4

### Where did you install the app from?

Google Play

### Device information

Leeco le pro 3

### Android version

Android 9. Lineage OS

### Jellyfin server version

10.8.10

### Which video player implementations does this bug apply to?

- [X] Web player (default)
- [X] Integrated player (ExoPlayer)
- [ ] External player (VLC, mpv, MX Player)

**Comment by IIeTp** [comment]
if you disable transcoding, then it works fine, but this is not the option i think

**Comment by Maxr1998** [comment]
Please upgrade to 2.5.0 and try again.

**Comment by IIeTp** [comment]
@Maxr1998 Thanks a lot. This is my old, reopened ticket, this file doesn't seem to have any problems anymore. Client ver 2.5.0. I have another file that is having problems right now. [here](https://github.com/jellyfin/jellyfin-android/files/11892773/temp.zip) is the file.
[android_client.FFmpeg.Remux.log](https://github.com/jellyfin/jellyfin-android/files/11892798/android_client.FFmpeg.Remux-2023-06-28_12-39-45_f3c02f172c2bef79d2629462e36977a3_bf0e300a.log)
[android_client.FFmpeg.Transcode.log](https://github.com/jellyfin/jellyfin-android/files/11892799/android_client.FFmpeg.Transcode-2023-06-28_12-37-34_f3c02f172c2bef79d2629462e36977a3_e1f9ec9c.log)
Remux only works if transcode is forced off.

**Comment by IIeTp** [comment]
@Maxr1998 it looks like I have more examples of incorrect work when the transcode is turned on, including when the sound starts to be encoded. for example truehd, although when the sound is in the mkv container, the transcode is not turned on.
please tell me the best way to collect information. whether sample files are needed or just logs.
