### ISSUE TITLE
MediaButton events in Jellyfin Web Player not working

### ISSUE THREAD

**Issue by PaulWoitaschek** [jellyfin/jellyfin-android#1130]
### Describe the bug

1. Play a video using the Web Player
2. Press a bluetooth headset button
3. The player should pause but it doesn't

This works correctly with the media implementation

### Application version

2.5.2

### Where did you install the app from?

Sideloaded APK (proprietary build)

### Device information

Pixel 7

### Android version

13

### Jellyfin server version

10.8.10

### Which video player implementations does this bug apply to?

- [X] Web player (default)
- [ ] Integrated player (ExoPlayer)
- [ ] External player (VLC, mpv, MX Player)

**Comment by PaulWoitaschek** [comment]
Ping, this is a bug

**Comment by polyzen** [comment]
Seems to be a similar issue with the integrated ExoPlayer. Play/Pause button only works to play, not pause.

Hopefully resolved the [migration to Media3](https://github.com/jellyfin/jellyfin-android/issues/1010), though [apparently you have to double-click to pause there](https://github.com/androidx/media/issues/159).
