### ISSUE TITLE
Can't scroll library on Android TV Box (AOSP) using airmouse 

### ISSUE THREAD

**Issue by mefistofeel** [jellyfin/jellyfin-android#1136]
### Describe the bug

On Android TV Box (Ugoos x4 Pro) with Jellyfin android (not AndroidTV) version, scrolling doesn't work with airmouse gestures. (click + pull up)

### Application version

2.5.2

### Where did you install the app from?

Google Play

### Device information

Ugoos X4 Pro

### Android version

Android 11

### Jellyfin server version

10.8.9

### Which video player implementations does this bug apply to?

- [ ] Web player (default)
- [ ] Integrated player (ExoPlayer)
- [ ] External player (VLC, mpv, MX Player)

**Comment by mefistofeel** [comment]
Any updates here?

**Comment by nielsvanvelzen** [comment]
The mobile app is not supported on televions.
