### ISSUE TITLE
Bluetooth Play/Pause not working

### ISSUE THREAD

**Issue by bm751613** [jellyfin/jellyfin-android#114]
While connected to a Bluetooth device and playing music the track skip control buttons work as well as volume but the Play/Pause button doesn't seem to be working.

Version 2.8.54
Pixel 2
Android 9
Bluetooth 4.1 (Multiple Devices)

**Comment by Froghut** [comment]
this should be fixeed with PR https://github.com/jellyfin/jellyfin-android/pull/119

**Comment by dkanada** [comment]
Can either of you confirm that this has been fixed in the latest update?

**Comment by bm751613** [comment]
Yup, just updated to bata9 and everything seems to be working as expected.
