### ISSUE TITLE
Chromecast only plays one or two things, nothing more, and can't go to previous thing

### ISSUE THREAD

**Issue by BloodyIron** [jellyfin/jellyfin-android#1148]
### Describe the bug

Open Jellyfin App
Connect to Chromecast
Play music Album, or show Series
Media plays, skip to next song/episode
Cannot go to previous song/episode, cannot go to next (3rd) song/episode, as in the back/forward buttons just stop doing anything

### Logs

```shell
I didn't see logs actually show anything in response (monitoring Jellyfin server logs).
```

### Application version

2.5.2

### Where did you install the app from?

Google Play

### Device information

Samsung Galaxy xCoverPro6

### Android version

Android 13

### Jellyfin server version

10.8.10

### Which video player implementations does this bug apply to?

- [ ] Web player (default)
- [ ] Integrated player (ExoPlayer)
- [ ] External player (VLC, mpv, MX Player)

**Comment by BloodyIron** [comment]
The above is with Stable version of Chromecast in Jellyfin Android App. Switching to Unstable actually is worse as I only see "Ready..." text, and no media plays when telling it to play media.

**Comment by cbz** [comment]
This also applies to trying to play an arbitrary track in an album, with the same lineup above the album always starts playing from the first track regardless of which track is picked.

**Comment by BloodyIron** [comment]
Chromecast on Jellyfin is effectively useless in its current state. Really need devs to actually fix Chromecast problems like this.

**Comment by BloodyIron** [comment]
This is effectively solved (mostly, "good enough for now"), details here : https://github.com/jellyfin/jellyfin-chromecast/pull/107

**Comment by Maxr1998** [comment]
Happy to hear that!
