### ISSUE TITLE
Casting Interlaced/MBAFF media that doesn't need to be transcoded from Android app to Chromecast results in failure.

### ISSUE THREAD

**Issue by stevanov** [jellyfin/jellyfin-android#1157]
### Describe the bug

I mainly download AVC media since I have an older chromecast that doesn't seem to support HEVC. My Jellyfin server doesn't have hardware accelerated transcoding which leads me to have this setup. Which works fine for me. 

However recently I ran into some media that I've never experienced before. When starting some specific media the chromecast will basically play the video sort of at a 45 degree angle. Every few scanlines the pixels are shifted left.

This isn't an issue when playing in Android natively or when playing the same video on the Windows client.

So there's a definite link to Chromecast and Android I believe. The video in question isn't progressive but interlaced. Either chromecast doesn't  support that or Jellyfin does not communicate that to the chromecast correctly.

> Video
> ID                                       : 1
> Format                                   : AVC
> Format/Info                              : Advanced Video Codec
> Format profile                           : Main@L4
> Format settings                          : CABAC / 4 Ref Frames
> Format settings, CABAC                   : Yes
> Format settings, Reference frames        : 4 frames
> Format settings, GOP                     : M=3, N=15
> Codec ID                                 : V_MPEG4/ISO/AVC
> Duration                                 : 1 h 31 min
> Bit rate                                 : 4 618 kb/s
> Width                                    : 1 920 pixels
> Height                                   : 1 080 pixels
> Display aspect ratio                     : 16:9
> Frame rate mode                          : Constant
> Frame rate                               : 25.000 FPS
> Standard                                 : Component
> Color space                              : YUV
> Chroma subsampling                       : 4:2:0
> Bit depth                                : 8 bits
> Scan type                                : MBAFF
> Scan type, store method                  : Interleaved fields
> Scan order                               : Top Field First
> Bits/(Pixel*Frame)                       : 0.089
> Stream size                              : 2.96 GiB (97%)
> Language                                 : English
> Default                                  : Yes
> Forced                                   : No
> Color range                              : Limited
> Color primaries                          : BT.709
> Transfer characteristics                 : BT.709
> Matrix coefficients                      : BT.709

### Logs

```shell
Video
ID                                       : 1
Format                                   : AVC
Format/Info                              : Advanced Video Codec
Format profile                           : Main@L4
Format settings                          : CABAC / 4 Ref Frames
Format settings, CABAC                   : Yes
Format settings, Reference frames        : 4 frames
Format settings, GOP                     : M=3, N=15
Codec ID                                 : V_MPEG4/ISO/AVC
Duration                                 : 1 h 31 min
Bit rate                                 : 4 618 kb/s
Width                                    : 1 920 pixels
Height                                   : 1 080 pixels
Display aspect ratio                     : 16:9
Frame rate mode                          : Constant
Frame rate                               : 25.000 FPS
Standard                                 : Component
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 8 bits
Scan type                                : MBAFF
Scan type, store method                  : Interleaved fields
Scan order                               : Top Field First
Bits/(Pixel*Frame)                       : 0.089
Stream size                              : 2.96 GiB (97%)
Language                                 : English
Default                                  : Yes
Forced                                   : No
Color range                              : Limited
Color primaries                          : BT.709
Transfer characteristics                 : BT.709
Matrix coefficients                      : BT.709
```

### Application version

2.5.0

### Where did you install the app from?

Google Play

### Device information

Google Pixel 6a

### Android version

Android 13

### Jellyfin server version

10.8.8

### Which video player implementations does this bug apply to?

- [ ] Web player (default)
- [ ] Integrated player (ExoPlayer)
- [ ] External player (VLC, mpv, MX Player)

**Comment by Maxr1998** [comment]
I suspect the specific file isn't supported by your Chromecast. The Android app doesn't have a lot of influence over it, it's the cast client that handles the playback and which file to play or to transcode or not.
