### ISSUE TITLE
Download not working

### ISSUE THREAD

**Issue by anandcu3** [jellyfin/jellyfin-android#116]
Downloading a movie is not working. I tap on the Download button and nothing happens. The download is working with the same user on other browser/clients.

Phone: Oneplus 5t
Android Version: 9

**Comment by anthonylavado** [comment]
Hey there! The download feature is currently not supported with Jellyfin. We hope to bring it back soon, but we don’t have an ETA at this moment.

Sorry!

**Comment by dkanada** [comment]
Actually the download works perfectly on browsers, it's only broken on Android at the moment.

**Comment by anthonylavado** [comment]
Yes, that’s what I meant to say - in the app, it’s not supported.

**Comment by anandcu3** [comment]
Thanks for the update!

**Comment by fidelix** [comment]
Any news on this?

**Comment by Robert-D** [comment]
Also looking for this feature for my wife's ebook collection, currently cannot download via the app. Any time frame?

**Comment by dkanada** [comment]
The feature will be implemented as soon as a developer decides to implement the required methods in the shim library. I don't think it's too hard, but Cordova isn't very fun to work with so we haven't had many volunteers for this project as a result.

**Comment by Robert-D** [comment]
I've tinkered in Xamarin maybe I can take a look at Cordova. Can you point me to where this shim library is?

**Comment by dkanada** [comment]
Basically, all we need is a method [here](https://github.com/jellyfin/jellyfin-android/blob/master/src/NativeShell/src/NativeShell.java) that downloads the files to a directory, and then to invoke the native method [here](https://github.com/jellyfin/jellyfin-android/blob/master/src/NativeShell/www/nativeshell.js#L38) and uncomment [this](https://github.com/jellyfin/jellyfin-android/blob/master/src/NativeShell/www/apphost.js#L7) line.

**Comment by Robert-D** [comment]
Awesome. I'll try to get the IDE setup tonight so I can start working with it. Thanks for the details this helps greatly.

**Comment by dkanada** [comment]
Quick note about Android Studio, it doesn't play well with Cordova at all. I did most of my editing from a console and then only used the IDE once I wanted to debug and test the final versions.

**Comment by Robert-D** [comment]
Maybe I'll try VS: 
https://visualstudio.microsoft.com/vs/features/cordova/

**Comment by arantes555** [comment]
I would love to see this too. The optimal would be a "caching" feature, a bit like Netflix, which would allow the app to play the files offline. But even a simple good-old download to disk would be great to have.

**Comment by winters-brown** [comment]
Also doesn't work on photos. Ill dig into the code a little later today

**Comment by dkanada** [comment]
We have a PR open right now that should fix this issue, it's currently being worked on.

**Comment by winters-brown** [comment]
Thanks! hadnt gotten there yet

**Comment by thornbill** [comment]
Download support was added in the 1.0.0 release! 🎉
