### ISSUE TITLE
Support DNS WAN Address (breaking change in jellyfin-server)

### ISSUE THREAD

**Issue by Phlogi** [jellyfin/jellyfin-android#117]
See: https://github.com/jellyfin/jellyfin/pull/1151
This merge will cause the login to the server to fail. The android app needs to handle a DNS name as the advertised public WAN endpoint.

**Comment by anthonylavado** [comment]
Paging @thornbill, but I think he mentioned on Riot that we should be fine.

**Comment by Phlogi** [comment]
True, just tested app version 2.8.54 over WAN with jellyfin-server master from yesterday. This one can be closed.
