### ISSUE TITLE
App slows down when dc.services.visualstudio.com is blocked

### ISSUE THREAD

**Issue by sushruth** [jellyfin/jellyfin-android#1175]
### Describe the bug

1. Have a dns filter blocking `dc.services.visualstudio.com`
2. Use the app
3. Observe delayed response of loading media and playback and buffering

### Logs

```shell
I don't think I can do that on my phone. I'll update the issue later with logs after a clean repro of the bug.
```

### Application version

2.5.2

### Where did you install the app from?

Google Play

### Device information

Google Pixel 7 pro

### Android version

Android 14

### Jellyfin server version

10.8.10

### Which video player implementations does this bug apply to?

- [ ] Web player (default)
- [X] Integrated player (ExoPlayer)
- [ ] External player (VLC, mpv, MX Player)

**Comment by Maxr1998** [comment]
I don't think this is an issue with this app, it doesn't use anything related to Visual Studio/dotnet/Microsoft.
The app only connects to your personal Jellyfin instance, which data is then loaded from any potential other sources is determined by the server.
