### ISSUE TITLE
2.0.0 RC4 cannot play video from anything but web player

### ISSUE THREAD

**Issue by SteveDinn** [jellyfin/jellyfin-android#119]
**Describe the bug**
When attempting to play a video from the "native player" the app simply crashes.
When attempting to play a video from the "external player" (in my case, this would be VLC), I get an error screen saying "The client isn't compatible with the media and the server isn't sending a compatible media format." This clearly isn't the case, because VLC can play the file natively.

**To Reproduce**

* Select "Settings / Client Settings / Video player type" and select anything other than "web player".
* Play a video.
* See crash or error.

**Expected behavior**
Videos should play in the selected type of player.

**Logs**
I will figure out how to produce logs and edit this bug when I have them.

**Screenshots**

**System (please complete the following information):**
 - App version: 2.0.0 RC4
 - Android version: 10 (Oxygen OS 10.3.5) 
 - Device manufacturer and model: OnePlus 6
 - Jellyfin server version: 10.6.4

**Comment by nielsvanvelzen** [comment]
I expect this issue is related to #116

**Comment by nielsvanvelzen** [comment]
It should work now in the latest release! Please let us know if it doesn't.
https://github.com/jellyfin/jellyfin-android/releases/tag/v2.0.0-rc.5
