### ISSUE TITLE
[Bug] If "always ask" is chosen for which player to use the option to resume a movie is missing.

### ISSUE THREAD

**Issue by gummykage** [jellyfin/jellyfin-android#1197]
### Describe the bug

1. Play Movie forward anything more than 10% so jellyfin will save your progress when you exit.
2. Go to settings enable "Always Ask" for Preferred Media Player.
3. Go back to movie to resume, the ability to resume is replaced with a play with a drop down to select which media player.

### Application version

Latest

### Where did you install the app from?

Amazon Appstore

### Device information

Firestick TV 4K Max

### Android version

Latest (Updated 9-6-2023)

### Jellyfin server version

10.8.10

### Which video player implementations does this bug apply to?

- [ ] Web player (default)
- [X] Integrated player (ExoPlayer)
- [ ] External player (VLC, mpv, MX Player)

**Comment by Maxr1998** [comment]
I believe you're using the TV app, this is the repo for the mobile application.

You may want to file your issue again here: https://github.com/jellyfin/jellyfin-androidtv

**Comment by gummykage** [comment]
Oh! Thx
