### ISSUE TITLE
`Play all from here` in music or books section not functional

### ISSUE THREAD

**Issue by foss-** [jellyfin/jellyfin-android#1199]
### Describe the bug

1. go to album in music section
2. tap three vertical dots on any track other than the last track
3. select `Play all from here`
4. turn off device screen

**Currently**

When the device screen is turned off, the player gets stuck on the last second of the current track and does not progress to the next track. This isn't 100 % reproducible. When skipping forward, disabling device screen continuing to the next track worked fine, so make sure to play entire track with screen turned off without skipping forward. Might be either a timing bug or skipping may do something that prevents the bug to occur.

**Expected**

Player should not get stuck and always continue to next track until all album tracks are played.

**Additional info**

- Issue is not limited to music section but also affects audio books in books section, were a track is played and player also gets stuck on last second and does not continue to next track of album.
- this is not a problem when display is active
- this is not a problem in webUI

Player stuck when then turning on display:
<img src="https://github.com/jellyfin/jellyfin-android/assets/5708172/aa2ae05a-12ad-49b4-a0b0-112f06730636" width="200">

### Logs

```shell
1 year: https://bin.disroot.org/?2635968bb42cef52#3qLPXZTFw9kUi2ZG9ceAxwUVn2H5qmogmkEVra63tJb9
```

### Application version

2.5.3

### Where did you install the app from?

F-Droid

### Device information

Xiaomi 11 Lite 5G NE

### Android version

ArrowOS 13.1

### Jellyfin server version

10.8.10

### Which video player implementations does this bug apply to?

- [ ] Web player (default)
- [X] Integrated player (ExoPlayer)
- [ ] External player (VLC, mpv, MX Player)

**Comment by nielsvanvelzen** [comment]
Does this issue also happen when you try to reproduce it in the browser (either on mobile or desktop)?

**Comment by foss-** [comment]
Sorry forgot to mention that webUI is fine, tested on desktop.

**Comment by foss-** [comment]
Persisting

**Comment by foss-** [comment]
Peristing with 2.6.1
Jellyfin Server 10.8.3

**Comment by foss-** [comment]
This seems no longer to be a problem with
Jellyfin Server 10.9.8
Jellyfin Android 2.6.2

Unsure which change resolved this problem but both music and books now continue to next track after selecting `Play all from here` with android device screen turned off.

❤️ 🚀
