### ISSUE TITLE
Large amount of music seems to cause issues with Android Auto

### ISSUE THREAD

**Issue by ryandikdan** [jellyfin/jellyfin-android#1206]
### Describe the bug

When running Jellyfin in Android Auto mode, there's no search so you have to select artist or album or whatever and then go through it by letter, but only A and B are there. When I had a smaller music collection this wasn't an issue. Perhaps a search would help to make it usable still. I tried it on the beta channel too in order to see if there was a difference and there wasn't.

Oh and the jellyfin app is playing a song. While it will continue to play, it doesn't show up as playing on the Android Auto app, like it does with Spotify and Youtube Music, so it can't be controlled then.

### Application version

2.6.0

### Where did you install the app from?

Google Play

### Device information

Pixel 7

### Android version

Android 13

### Jellyfin server version

10.8.10

### Which video player implementations does this bug apply to?

- [ ] Web player (default)
- [ ] Integrated player (ExoPlayer)
- [ ] External player (VLC, mpv, MX Player)

**Comment by fieldsalad2** [comment]
I have the exact same issues. By far the most annoying one is that Jellyfin seems to start a second instance behind the first one when you hand-pick media from your phone, and then it can't be controlled from Android Auto because the first instance (that auto-started when Android Auto started) is still in place and visualized in Android Auto.

**Comment by ryandikdan** [comment]
While I'd like this to work, I moved to the paid Symfonium app which has great Android Auto support and works fantastic for all music needs. If the Jellyfin app improves please let me know and I'll check it out.
