### ISSUE TITLE
Android 14, Google password manager not working

### ISSUE THREAD

**Issue by MominRaza** [jellyfin/jellyfin-android#1207]
Android 14, using Google password manager.
It is **not offering** to save password after logging in.
I manually added password for Jellyfin app in Google password manager, but it still **not auto filling the password**.

Chrome on laptop/android is working fine.

_Originally posted by @MominRaza in https://github.com/jellyfin/jellyfin-android/issues/163#issuecomment-1748882175_

**Comment by pascalwei** [comment]
Please provide more details:

- what device do you use?
- is your version of Android 14 marked as stable or beta by your device manufacturer?
- what is your keyboard app & version?

Just now I could not reproduce your described issue. On the Android 14 emulator Autofill by Google works in Jellyfin.

Emulator on Android 14 - API Level 34 x86_64 (Google APIs)
Google Play Services version: 23.18.18
Gboard version: 12.4.05.482060964-preload-x86_64
build.fingerprint: google/sdk_gphone64_x86_64/emu64xa:14/UE1A.230829.019/10866155:userdebug/dev-keys


![Screenshot 2023-10-13 174018](https://github.com/jellyfin/jellyfin-android/assets/103744505/70720666-2600-43cc-94c1-6069f0fc41db)
