### ISSUE TITLE
No AC3 or DTS playback

### ISSUE THREAD

**Issue by topdollar3** [jellyfin/jellyfin-android#121]
**Describe the bug**

Having my jellyfin server on pi4 in LAN, and transcoding is disabled. 

When trying to playback video files with 5.1 AC3 or DTS codec, no audio is played. I transcoded the audio part of these videofiles to AAC 5.1 and its all good. 

According https://jellyfin.org/docs/general/clients/codec-support.html, android is compatible with both these audio codecs.

**To Reproduce**

1. Disable transcodes in server settings
2. Playback a video file with AC3 or DTS audio codec
3. Video plays fine but there is no audio.

**Expected behavior**

Video with audio playback

**System (please complete the following information):**

 - App version: 2.0.0-rc.5
 - Android version: Android 10
 - Device manufacturer and model: Samsung A30, Samsung S9
 - Jellyfin server version: 10.6.4
 - The type of video player implementation used: web player (for DTS and AC3) and ExoPlayer (for DTS)

**Comment by Maxr1998** [comment]
Relates to #28
