### ISSUE TITLE
Bug - Text and button display issue

### ISSUE THREAD

**Issue by krizly** [jellyfin/jellyfin-android#121]
Text fields and buttons are including additional text entries and are missing spaces, see attachments. 

![Screenshot_2019-04-08-07-24-41-693_org jellyfin mobile](https://user-images.githubusercontent.com/22738801/55688716-d2b9b900-59cf-11e9-8038-7fa5d534d406.png)
![Screenshot_2019-04-08-07-24-47-564_org jellyfin mobile](https://user-images.githubusercontent.com/22738801/55688717-d2b9b900-59cf-11e9-9fa6-6d65d77c966e.png)
![Screenshot_2019-04-08-07-28-17-232_com android settings](https://user-images.githubusercontent.com/22738801/55688733-22988000-59d0-11e9-97b9-36d75c87a114.png)

**Comment by anthonylavado** [comment]
This is a text string issue - what you’re seeing is what happens when we’re either missing text or something is broken in the fallback for translation.

Did you build this yourself, or download a beta? If you downloaded it, could you tell us what version it was?

**Comment by krizly** [comment]
I downloaded the beta directly from the binary - https://repo.jellyfin.org/releases/client/android/

Tried both release beta 7 and 8.
I didn't get the bug on my previous device (Xiaomi Mi Max 3) using the same APK files but when I moved onto my current device (Mi Mix 3) I noticed the bug.

**Comment by cvium** [comment]
I think there were reports that clearing app data fixed it

**Comment by krizly** [comment]
Just tried clearing the app data but didn't fix the issue. Did a sanity check and uninstalled and re-installed the v8 beta from the binary but still not displaying properly unfortunately.

**Comment by dkanada** [comment]
Is this issue only on pages before you login or any page throughout the app?

**Comment by krizly** [comment]
Seems to only be the pre-login screen, once I've signed in to a server it doesn't have the same issues.
I can then navigate to the 'change server' screen and everything looks normal.
If I sign out and remove the server the original issue re-occurs.

**Comment by dkanada** [comment]
I haven't been able to reproduce the issue on my phone. Do you have the same issue with any of the debug builds? If you could follow the instructions [here](https://developers.google.com/web/tools/chrome-devtools/remote-debugging/) and post a sanitized log to pastebin I might be able to find the issue.

**Comment by dkanada** [comment]
If you have any experience with debugging you can also add a breakpoint [here](https://github.com/jellyfin/jellyfin-web/blob/master/src/controllers/selectserver.js#L24) while remote debugging to see why your phone doesn't show the proper strings. Otherwise I can take a look at the logs.

**Comment by jkcclemens** [comment]
For what it's worth, I also have this issue after installing beta8 on my Pixel XL running LineageOS 16.0. Not sure if it matters, but my locale is en-GB.

**Comment by krizly** [comment]
Looks like @jkcclemens figured it out, changing my language settings to en-US fixed the issue, reverting back to en-GB brought back the bug.

**Comment by dkanada** [comment]
this has been fixed for the next release :)
