### ISSUE TITLE
Auto quality selection does not behave as expected

### ISSUE THREAD

**Issue by alexbgameson** [jellyfin/jellyfin-android#1214]
### Describe the bug

The selection of "Auto" quality in Playback -> Video Quality does nothing and continues to stream media at the highest possible bitrate.

### Application version

2.5.0

### Where did you install the app from?

Google Play

### Device information

NA

### Android version

NA

### Jellyfin server version

NA

### Which video player implementations does this bug apply to?

- [X] Web player (default)
- [ ] Integrated player (ExoPlayer)
- [ ] External player (VLC, mpv, MX Player)

**Comment by branches78** [comment]
See https://github.com/jellyfin/jellyfin-androidtv/issues/1753 for reference.
