### ISSUE TITLE
Problems connecting remotely

### ISSUE THREAD

**Issue by HDmaniac** [jellyfin/jellyfin-android#122]
Opening this as a blank issue because it's not a bug per se but it's causing me an issue.

I've been using the app from here and I understand this current project is a complete rewrite, and different from the Play Store version, however I don't know how much was kept/thrown away.

I use Zerotier to connect to my server from outside my network, it works great with everything except Jellyfin on my android device, at first I thought it was Zerotier so went through those settings but no, everything was good and I can connect to other services I have running on the RPi4.

Just to see if it was this app in particular I deleted it and downloaded the version from Play Store, which connected effortlessly. It also worked using Firefox android and DuckDuckGo. Which is to say there's something about how the new app works and connects that doesn't work properly while I am using 4G & the Zerotier network, everything is fine while on Wi-Fi with both the new and old apps, but whenever I try to connect remotely with the new app, the logo comes and just hangs there for a minute, then just disappears, never getting to sign-in.

**To Reproduce**
1. Open app while using Zerotier & Cellular data
2. Type in server address 
3. Try to connect

**System**
 - App version: [2.0.0-rc.5 & previous]
 - Android version: [Android 10]
 - Device manufacturer and model: [Xiaomi Poco F1]
 - Jellyfin server version: [10.6.4]

Not sure of LogCats are necessary but I can add them if so? One when using the old app and one for the new?

Thanks!

**Comment by Maxr1998** [comment]
I'm not very familiar with Zerotier (in fact, I had to google what it is), so logs would definitely be appreciated. For now, logs of the new app not working would be enough.

**Comment by HDmaniac** [comment]
That's cool! Here's the logs: [https://paste.ubuntu.com/p/7tvbJRjcmN/](url)

I started it just before launching the app and about 10 seconds after the logo disappeared. Let me know if you need it running longer or anything else.

**Comment by HDmaniac** [comment]
Okay so after messing about some more using other devices I've realised something.
Sometimes it can hang on other devices and browsers when connected via Zerotier, however I am able to refresh (F5) the page and it loads up instantly again on the sign-in screen.

So if I may so bold as to make a workaround suggestion? How about a small box with some text that shows up after 10/15 seconds with "Things seem to be taking a while, would you like to refresh?" with an "OK" button underneath, which functions as an F5 key and refreshes the process, and should then load the sign-in screen.

It is still worth noting that the version from the Play Store works without any issue whatsoever.
