### ISSUE TITLE
Custom CSS URLs that can't be reached cause you to get kicked back out to the server selection screen

### ISSUE THREAD

**Issue by SteveDinn** [jellyfin/jellyfin-android#1221]
## How to reproduce this bug:
1. Use the latest beta, 2.6.0-beta.2.
2. Navigate to Dashboard --> General.
3. Add a line such as `@import url("https://cdn.doesnotexist.net/custom.css");` to the **Custom CSS code** section.
4. Kill and reload the Android Jellyfin client.
5. Get kicked back out to the server selection screen.

## Background
I originally posted about this on the Jellyfin Forums trying to work out what had happened because I hadn't changed any configuration. It turns out the Pi-Hole had blocked `cdn.jsdelivr.net` because of an automated blocklist update and I was pulling in some CSS from Ultrachromic, which were hosted there.

**This bug only seems to manifest if the domain is unresolvable. I couldn't reproduce it using a valid domain but a file that did not exist.**

This *may* also be an issue with the Android TV client.

https://forum.jellyfin.org/t-solved-jellyfin-android-client-suddenly-can-t-connect-to-my-existing-server

### Application version

2.6.0-beta.2

### Where did you install the app from?

Google Play

### Device information

LG Velvet

### Android version

Android 13

### Jellyfin server version

10.8.13

### Which video player implementations does this bug apply to?

- [ ] Web player (default)
- [ ] Integrated player (ExoPlayer)
- [ ] External player (VLC, mpv, MX Player)

**Comment by Maxr1998** [comment]
Duplicate of #574 and imo a case of misconfiguration, nonetheless the app should be able to handle this better.

**Comment by SteveDinn** [comment]
In my case configuration did not change at all. It was the result of a third party block list changing and affecting my DNS resolution. I would expect the jelly fin Android client to behave the same as a web browser does in this case and simply ignore the CSS files that cannot be loaded, for whatever reason.
