### ISSUE TITLE
Subtitles are not available in mpv

### ISSUE THREAD

**Issue by budel** [jellyfin/jellyfin-android#1258]
### Describe the bug

First of all: Thank you for an amazing app! I really appreciate all the effort and features!
I just updated today to 2.6.0 and wanted to watch a video with subtitles. I use mpv (Version 2023-11-30-release) as external player. 
The subtitles were unfortunately not available in mpv, so I removed 2.6.0 and installed 2.5.3 from f-droid again and voila - the subtitles are once again available in mpv.

I hope this is enough, but if you need more information, I'd be happy to assist.

### Application version

2.6.0

### Where did you install the app from?

F-Droid

### Device information

OnePlus 5T

### Android version

LineageOS 20

### Jellyfin server version

10.8.13

### Which video player implementations does this bug apply to?

- [ ] Web player (default)
- [ ] Integrated player (ExoPlayer)
- [X] External player (VLC, mpv, MX Player)

**Comment by garvongithub** [comment]
Same here. Embedded subtitles are available, it's just external subtitles having this bug. Also it's not just mpv, all external players are having this problem.

**Comment by sudoeste** [comment]
Same. ANDROID 13, jellyfin 2.6.0 and mx player free as external. Rolling back fixes it

**Comment by Maxr1998** [comment]
Most likely caused by #1181. I'll look into it, thank you!
