### ISSUE TITLE
video playback not working in beta 9

### ISSUE THREAD

**Issue by Jonas337** [jellyfin/jellyfin-android#126]
I am running the latest 1.0.3.0r2 server on windows 10, and trying to connect with the latest beta 9 android client.

play a video does not work. it will show the first frame, but that is it.

the server is giving this error message during playback: [20:50:09] [WRN] HTTP Response 200 to xxx.xxx.xxx.xxx. Time (slow): 0:17:20.8365185

**Comment by Jonas337** [comment]
going back to beta 8 client fixes the issue

**Comment by dkanada** [comment]
Can you check if the issue is still present on the latest version? We fixed a few playback issues recently that might help you as well.

**Comment by Jonas337** [comment]
I've switched over to the Google play release, and I'm now running on 1.0.3.5, but that has solved my Playback issues.

**Comment by anthonylavado** [comment]
@jonass337 Is everything working now?

**Comment by Jonas337** [comment]
Yes, everything with this setup seems to be working, we can close the issue.
