### ISSUE TITLE
Modify save button to be sticky

### ISSUE THREAD

**Issue by fireXtract** [jellyfin/jellyfin-android#1265]
**Describe the feature you'd like**
Placing the save button more prominently on android devices would improve the user experience. In particular by having the Save button float/attach to the bottom of the page after a setting is modified (or always if we can just inject CSS).

**Additional context**
For example, when a phone network is of shoddy quality, one may have to go through the following sequence to prevent stuttering
Profile > Playback > Music Quality > Internet quality > *modify / lower bitrate* > scroll all the way to the bottom > Save

I often forget to hit the save button because
1. I cannot see it
2. Generally android applications automatically save settings upon change (ex. Profile > Client Options).

**Comment by nielsvanvelzen** [comment]
The Android app is a wrapper for the [jellyfin-web](https://github.com/jellyfin/jellyfin-web) project so this suggestion should be made for the mobile layout in that repository. Alternatively you could work on this yourself and submit a pull request.
