### ISSUE TITLE
Notification permissions issue on recent Samsung phones - All notifications from this app are blocked

### ISSUE THREAD

**Issue by scblakely** [jellyfin/jellyfin-android#1271]
### Describe the bug

I installed Jellyfin Android on my S23+ recently (One UI 6.0, Android 14, Google Play update 1 October 2023).

In _Settings > Apps> App Info_ for Jellyfin, _Notifications_ are set to **Blocked**, and cannot be changed.
In _Settings > Notifications > App notifications_, **Jellyfin** is not listed.

The notifications from **Jellyfin** can be seen in the _Notification History_

There is a Samsung thread on this issue
  https://eu.community.samsung.com/t5/galaxy-s20-series/all-notifications-from-this-app-are-blocked/td-p/8159784

The consensus seems to be that this may be due to the recent One UI System update, but that app developers can address this via an update to the app permissions. However, I cannot determine what the required changes are.

### Application version

2.6.0

### Where did you install the app from?

Google Play

### Device information

Samsung S23+

### Android version

Android 14

### Jellyfin server version

10.8.13

### Which video player implementations does this bug apply to?

- [ ] Web player (default)
- [ ] Integrated player (ExoPlayer)
- [ ] External player (VLC, mpv, MX Player)

**Comment by nielsvanvelzen** [comment]
The app does not use notifications so I don't see the problem
