### ISSUE TITLE
ExoPlayer fails LiveTV playback

### ISSUE THREAD

**Issue by jellouser** [jellyfin/jellyfin-android#1277]
### Describe the bug

1. Set up M3U live channels providing MPEG-TS stream
2. Play live channel in app, using ExoPlayer as player
3. ExoPlayer makes request GET /LiveTv/LiveStreamFiles/\<guid\>/stream.ts HTTP/1.1 seen in server tcpdump
4. Player shows message "Source error"

### Logs

```shell
ExoPlayerImplInternal: Playback error
ExoPlayerImplInternal:  com.google.android.exoplayer2.ExoPlaybackException: Source error
ExoPlayerImplInternal:      at o5.o0.k(SourceFile:17)
ExoPlayerImplInternal:      at o5.o0.handleMessage(SourceFile:382)
ExoPlayerImplInternal:      at android.os.Handler.dispatchMessage(Handler.java:102)
ExoPlayerImplInternal:      at android.os.Looper.loopOnce(Looper.java:226)
ExoPlayerImplInternal:      at android.os.Looper.loop(Looper.java:313)
ExoPlayerImplInternal:      at android.os.HandlerThread.run(HandlerThread.java:67)
ExoPlayerImplInternal:  Caused by: com.google.android.exoplayer2.ParserException: Input does not start with the #EXTM3U header.{contentIsMalformed=true, dataType=4}
ExoPlayerImplInternal:      at y6.n.f(SourceFile:259)
ExoPlayerImplInternal:      at l7.i0.a(SourceFile:30)
ExoPlayerImplInternal:      at l7.d0.run(SourceFile:41)
ExoPlayerImplInternal:      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
ExoPlayerImplInternal:      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
ExoPlayerImplInternal:      at java.lang.Thread.run(Thread.java:1012)
```

### Application version

2.6.0

### Where did you install the app from?

Google Play

### Device information

Samsung Galaxy S23

### Android version

Android 13

### Jellyfin server version

10.8.13

### Which video player implementations does this bug apply to?

- [ ] Web player (default)
- [X] Integrated player (ExoPlayer)
- [ ] External player (VLC, mpv, MX Player)

**Comment by jellouser** [comment]
I believe this is because of client QueueManager.createVideoMediaSource PlayMethod.DIRECT_PLAY logic:

`PlayMethod.DIRECT_PLAY -> {
                when (sourceInfo.protocol) {
                    MediaProtocol.FILE -> {
                        val url = videosApi.getVideoStreamUrl(
                            itemId = source.itemId,
                            static = true,
                            playSessionId = source.playSessionId,
                            mediaSourceId = source.id,
                            deviceId = apiClient.deviceInfo.id,
                        )

                        url to get<ProgressiveMediaSource.Factory>()
                    }
                    MediaProtocol.HTTP -> {
                        val url = requireNotNull(sourceInfo.path)
                        val factory = get<HlsMediaSource.Factory>().setAllowChunklessPreparation(true)

                        url to factory
                    }
                    else -> throw IllegalArgumentException("Unsupported protocol ${sourceInfo.protocol}")
                }
            }`

HlsMediaSource.Factory is used and M3U source expected, but it seems incorrect, and I think ProgressiveMediaSource.Factory should be used for this LiveStream instead.

**Comment by jellouser** [comment]
By compiling my own version of the app I can confirm that the playback issue is fixed by using `url to get<ProgressiveMediaSource.Factory>()` in MediaProtocol.HTTP instead of `HlsMediaSource.Factory`

**Comment by Maxr1998** [comment]
Thanks for debugging this. It's somewhat odd that the protocol is HTTP in that case, since that should (to my understanding) imply HTTP Live Streaming aka HLS. It seems like we need to handle another case there.

**Comment by jellouser** [comment]
I am not sure how these different cases should be handled if direct play source can also produce HLS / M3U, but HTTP is indeed the protocol for both cases, only different content type.

This previously reported issue looks exactly the same, .mkv direct play fails https://github.com/jellyfin/jellyfin-android/issues/1217

**Comment by Kevinjil** [comment]
The problem still persist with Jellyfin 10.9.1 and Jellyfin Android version 2.6.1.

**Comment by Kevinjil** [comment]
This problem still seems to persist. Is there a reason we don't use the same logic here as https://github.com/jellyfin/jellyfin-web/blob/v10.10.7/src/utils/mediaSource.ts#L8 to determine if a stream is HLS?
