### ISSUE TITLE
Stopping playback sends incomplete PlaybackStopInfo

### ISSUE THREAD

**Issue by jellouser** [jellyfin/jellyfin-android#1279]
### Describe the bug

1. Play TV LiveStream DirectPlay (M3U Tuner for example)
2. Stop playback (exit player view)
3. Server is notified POST /Sessions/Playing/Stopped HTTP/1.1 but M3U tuner is not released properly and still streaming to server

For stopping LiveStream `info.LiveStreamId` is required because of server side implementation OnPlaybackStopped:

```
if (!string.IsNullOrEmpty(info.LiveStreamId))
            {
                try
                {
                    await _mediaSourceManager.CloseLiveStream(info.LiveStreamId).ConfigureAwait(false);
                }
```

Android client fails to send proper PlaybackStopInfo message. 

For example Jellyfin Mediaplayer sends a lot information in PlaybackStopInfo payload:

```
{"VolumeLevel":100,"IsMuted":false,"IsPaused":true,"RepeatMode":"RepeatNone","ShuffleMode":"Sorted","MaxStreamingBitrate":140000000,"PositionTicks":64920000,"PlaybackStartTimeTicks":17049102192930000,"PlaybackRate":1,"AudioStreamIndex":-1,"BufferedRanges":[],"PlayMethod":"DirectPlay","LiveStreamId":"guid","PlaySessionId":"","PlaylistItemId":"playlistItem0","MediaSourceId":"guid","CanSeek":true,"ItemId":"guid","NowPlayingQueue":[{"Id":"guid","PlaylistItemId":"playlistItem0"}]}
```

Android client sends only few fields in payload:

```
// Report stopped playback
                playStateApi.reportPlaybackStopped(
                    PlaybackStopInfo(
                        itemId = mediaSource.itemId,
                        positionTicks = lastPositionTicks,
                        playSessionId = mediaSource.playSessionId,
                        failed = false,
                    ),
                )
```
```
{"ItemId":"guid","PositionTicks":161880000,"PlaySessionId":"guid","Failed":false}
```

### Application version

2.6.0

### Where did you install the app from?

Google Play

### Device information

Samsung Galaxy S23

### Android version

Android 13

### Jellyfin server version

10.8.13

### Which video player implementations does this bug apply to?

- [ ] Web player (default)
- [X] Integrated player (ExoPlayer)
- [ ] External player (VLC, mpv, MX Player)

**Comment by jellouser** [comment]
By compiling my own version of the app I can confirm that the playback stop issue is fixed by adding liveStreamId to JellyfinMediaSource constructor, modifying it's constructor call and then by modifying PlaybackStopInfo constructor call by adding liveStreamId = mediaSource.liveStreamId

**Comment by Maxr1998** [comment]
Thanks for debugging this! Would you like to create a PR for this? That would be super helpful.

**Comment by VTRunner** [comment]
I had found this bug, and was working to try to fix it, when I found this issue report with the resolution.  I have implemented the fix from jellouser's Jan 10 comment and it is working in a local build.  I've tested and verified that it releases the tuner using a HDHR OTA device.   

@jellouser - It doesn't look like you have submitted a PR for this - my apologies if I'm missing something.  Since it's been a month, are you ok if I submit the PR?  I just want to see it fixed, and will be happy to give you credit. 

@Maxr1998 - On which branch would you want this PR submitted?

**Comment by nielsvanvelzen** [comment]
Pull requests should target the master branch
