### ISSUE TITLE
Connection error when connecting to a server running on a subpath

### ISSUE THREAD

**Issue by tedvdb** [jellyfin/jellyfin-android#128]
**Describe the bug**
Connecting to a Jellyfin instance listening on a subpath doesn't work.

**To Reproduce**
1. Have Jellyfin running on a subpath as described [here](https://jellyfin.org/docs/general/networking/nginx.html#nginx-with-subpath)
2. Start the app
3. Enter the url
A 404 error flashes by, and and error message is shown that the connection can not be established.

**Expected behavior**
The connection succeeds.

**Logs**
```
D/TimberLogger: Adding request to queue: https://<snip>/jellyfin//System/Info/Public?format=json
I/TimberLogger: Response received from: https://<snip>/jellyfin//System/Info/Public?format=json
E/MainActivity$initialize: Received WebView HTTP 404 error: null - https://<snip>/web/index.html
E/MainActivity$initialize: Received WebView HTTP 404 error: null - https://<snip>/svg/404.svg
```

**Screenshots**
![image](https://user-images.githubusercontent.com/1628614/93128383-aaa7ac80-f6cf-11ea-9f17-3e9dfdf7dcf2.png)

**System (please complete the following information):**
 - App version: v2.0.0-rc.5
 - Android version: Android 10
 - Device manufacturer and model: Samsung Galaxy Note 9
 - Jellyfin server version: 10.6.4
 - The type of video player implementation used: N/A

**Comment by nielsvanvelzen** [comment]
When you open `https://<server>/jellyfin/` in your browser will it redirect correctly to the web interface or not?

**Comment by tedvdb** [comment]
Ah that was indeed the issue. It showed an 404 error.
After fixing the `BaseUrl` setting and updating the Nginx reverse proxy config it works.
