### ISSUE TITLE
Sound stop when app is not on top of the pile

### ISSUE THREAD

**Issue by proline** [jellyfin/jellyfin-android#1280]
### Describe the bug

Since the update of One UI 6.0 (samsung) when the app is not on the top of the pile (the last app used) the sound stop after few second. I don't have the problem with other application like vanilla music or NewPipe

### Application version

2.6.0

### Where did you install the app from?

F-Droid

### Device information

Samsung Galaxy S22

### Android version

android 14

### Jellyfin server version

10.8.13

### Which video player implementations does this bug apply to?

- [ ] Web player (default)
- [ ] Integrated player (ExoPlayer)
- [ ] External player (VLC, mpv, MX Player)

**Comment by rlichtenwalter** [comment]
Can confirm. Motorola Moto G7 Power, Android 10. Same issue.
