### ISSUE TITLE
Unnecessary transcode because of mp2  audio

### ISSUE THREAD

**Issue by jellouser** [jellyfin/jellyfin-android#1281]
### Describe the bug

1. Play LiveTV TS stream with mp2 audio
2. This results in Transcode (audio mp2 -> mp3, video copy) because of mp2 is not reported as supported audio codec.

The issue is fixed by "forcing" mp2 support in DeviceProfileBuilder 

```        
private val FORCED_AUDIO_CODECS = arrayOf(*PCM_CODECS, "alac", "aac", "ac3", "eac3", "dts", "mlp", "truehd", "mp2") <-- "mp2" added
```

Stream now plays DirectPlay (also requires DirectPlay fix https://github.com/jellyfin/jellyfin-android/issues/1277). I am not sure if there should be player-specific override or something, to make this ExoPlayer (and other supported players) only.

### Application version

2.6.0

### Where did you install the app from?

Google Play

### Device information

Samsung Galaxy S23

### Android version

Android 13

### Jellyfin server version

10.8.13

### Which video player implementations does this bug apply to?

- [ ] Web player (default)
- [X] Integrated player (ExoPlayer)
- [ ] External player (VLC, mpv, MX Player)

**Comment by huasbryan14** [comment]
The same thing happens in the web version, it does all the transcoding due to the mp2 format in the audio
