### ISSUE TITLE
Burn in subtitle option in client doesn't apply to web player

### ISSUE THREAD

**Issue by Youwenqwq** [jellyfin/jellyfin-android#1282]
### Describe the bug

When using Web Player, this option:`App Settings -> Subtitles -> Burn subtitles` doesn't work.
That means, when I select `All Complex Formats` and save, the videos with ass subtitle are still streamed directly and haven't been transcoded. This problem can't be reproduced in web client in chrome.

### Application version

2.6.0

### Where did you install the app from?

Google Play

### Device information

Oneplus 8 Pro

### Android version

Android 13, ColorOS 13.1

### Jellyfin server version

10.8.13

### Which video player implementations does this bug apply to?

- [X] Web player (default)
- [ ] Integrated player (ExoPlayer)
- [ ] External player (VLC, mpv, MX Player)

**Comment by boydaihungst** [comment]
Confirmed this problem happen in every device.
