### ISSUE TITLE
Can't enter local ip to add server

### ISSUE THREAD

**Issue by n00bhax** [jellyfin/jellyfin-android#130]
I just downloaded the app (beta 9 I think). If I enter my local IP address of my server, it asks to enter a URL. I don't have my server linked to a URL. Is this a bug or do I need to make a URL? 

![image](https://user-images.githubusercontent.com/28760191/56527860-9b5e1700-654e-11e9-9a40-3a38fe91c3bd.png)

**Comment by lostmypillow** [comment]
Add "http://"

**Comment by lostmypillow** [comment]
Add "http://" as in "http://192.168.0.68", then it'll work

**Comment by dkanada** [comment]
We did fix this just a bit ago so you won't have issues in the next release.

**Comment by n00bhax** [comment]
adding "http://" does let me click the connect button, but the connection fails. I hope it's not my fault and that it will be fixed in beta10.

**Comment by DragonRoco** [comment]
I can second this bug, I'm trying to connect and the IP alone doesn't work, http:// or https:// out the front doesn't work nor even removing the port field and putting the port in the URL. Connects fine on the same device through chrome. I don't know how to get logs if that would be any help. 

I'm running the latest jellyfin.

**Comment by lostmypillow** [comment]
https://github.com/jellyfin/jellyfin-web/pull/258

**Comment by dkanada** [comment]
@n00bhax is this issue still present in v0.9.0 or has it been fixed?

**Comment by n00bhax** [comment]
> @n00bhax is this issue still present in v0.9.0 or has it been fixed?

I just checked and it's fixed

**Comment by dkanada** [comment]
That's good to hear, let us know if it happens again.
