### ISSUE TITLE
Since 2.0.0 rc-2 videos don't play through the app

### ISSUE THREAD

**Issue by tuxrinku** [jellyfin/jellyfin-android#130]
When using the rc-1, I have no problems playing all the videos on my server, but I tried rc-2/3/4/5 and videos don't play anymore, I just have a black screen.

**To Reproduce**

1. Launch the app
2. Play any videos from the jellyfin server

**Expected behavior**
Video starts without any problems

**System (please complete the following information):**
 - App version: 2.0.0-rc.2
 - Android version: 8.1
 - Device manufacturer and model: ZTE Axon 7
 - Jellyfin server version: 10.6.4
 - The type of video player implementation used: web

**Comment by tuxrinku** [comment]
It does work with the native player option tho

**Comment by nielsvanvelzen** [comment]
The initial release candidate had the native player enabled by default. I think this is why it didn't work for you since the second release candidate, where we disabled it by default.

**Comment by asgardius** [comment]
Same problem on my Samsung SM-A300H with Android 7. On my Moto G7 Power with Android 10 i can play videos without issues. Here is my logcat from my Samsung SM-A300H running Release 2.0.0-rc.5. Server address has changed to my.server
[logcat.txt](https://github.com/jellyfin/jellyfin-android/files/5241503/logcat.txt)

**Comment by tuxrinku** [comment]
I just had to set the player to native in the app settings. Maybe it would be better to enable the native player as default option ? That would avoid people thinking it doesn't work at all. Great work anyway !

**Comment by nielsvanvelzen** [comment]
It's not enabled by default because it's still experimental and needs some work before we consider it stable.

**Comment by asgardius** [comment]
I could fix this changing WebView implementation to Google Chrome in development options. [This webview implementation](https://play.google.com/store/apps/details?id=com.google.android.webview) also fix the issue for me
![Screenshot_20200919-142026](https://user-images.githubusercontent.com/43385234/93689707-02566700-fa86-11ea-8123-b86508f10214.png)
