### ISSUE TITLE
Subtitles out of sync on android version

### ISSUE THREAD

**Issue by DiogoCoelhoWeb** [jellyfin/jellyfin-android#1301]
### Describe the bug

Go to the android app, play any movie with subtitles, the subs appear 2 seconds before they are supposed to although they are synced when they movie is played via the browser or via VLC Media Player. The Integrated player works fine its just the web player that does this. 

### Application version

2.6.0

### Where did you install the app from?

Google Play

### Device information

Xiaomi Redmi Note 8 Pro

### Android version

Android 11 | MiUI Gloal 12.5.7

### Jellyfin server version

10.8.13

### Which video player implementations does this bug apply to?

- [X] Web player (default)
- [ ] Integrated player (ExoPlayer)
- [ ] External player (VLC, mpv, MX Player)

**Comment by tdedobbeleer** [comment]
Same bug here with version 2.6.1.
Tried every setting to fix this, also changed players, but nothing helped. Also tried different (older) server versions. When I don't start the episode from the beginning, the subs are off.
The only "solution" I found is using a different client app. Using Findroid the subs are fine. On android TV (same problems) I have to use Kodi with the Jellyfin plugin to watch episodes with correct subs. Not ideal.
Obviously, I'd rather use the jellyfin app, but this is a deal-breaker.
