### ISSUE TITLE
Add the option to sort books by folder name to respect read order

### ISSUE THREAD

**Issue by Betonhaus** [jellyfin/jellyfin-android#1304]
If you have a books library with books sorted in folders as so:
-Author/
--Series/
---1 Book A/
----booka.epub
---2 Book B/
----bookb.epub

There is no sort option that will correctly sort books by read order. Even when metadata is correctly added, the books will be in an incorrect order not matter which sort option is used. Sorting by year doesn't seem to work either as sometimes the book gets mistaken for a rerelease or just has 100 for the year.

Please add the option to sort books by folder name.

**Comment by nielsvanvelzen** [comment]
This is a feature request for the web client, which should be posted to features.jellyfin.org.
