### ISSUE TITLE
Option to change Download Preference from WiFi to Mobile Data not available after initial selection

### ISSUE THREAD

**Issue by adripo** [jellyfin/jellyfin-android#1326]
### Describe the bug

I encountered a limitation within the Jellyfin Android app regarding the download settings. Initially, when prompted to select a download preference, I chose ‘WiFi only’. However, I now wish to enable downloads over mobile data as well, but the app does not offer an option to change this setting post the initial choice. The only workaround seems to be clearing the app’s data and starting the configuration process anew.

Steps to Reproduce:

1. Go to a movie or episode page
2. Go into options (3 dots) and select Download
3. When prompted to select a download preference, choose ‘WiFi only’.
4. Attempt to change the download preference to ‘WiFi + Mobile Data’ at a later stage.
5. Notice that there is no option available in the app settings to modify this preference.

The only solution appears to be clearing the app’s data and reconfiguring from scratch.
This issue has been discussed in the Jellyfin forum ([see the thread](https://forum.jellyfin.org/t-trying-to-download-shows-over-mobile-data-on-android-cant-waiting-for-wifi)), where it was suggested to clear app preferences as a solution. However, this is not a practical long-term solution, as it requires reconfiguration of the app settings. An option to change the download preference within the app settings would greatly enhance user flexibility and experience.

### Application version

2.6.0

### Where did you install the app from?

Google Play

### Device information

Samsung S24

### Android version

Android 14

### Jellyfin server version

latest

### Which video player implementations does this bug apply to?

- [ ] Web player (default)
- [ ] Integrated player (ExoPlayer)
- [ ] External player (VLC, mpv, MX Player)

**Comment by taitsmith** [comment]
@Maxr1998 
i'm happy to work on this when i have time in the next few days- from a quick glance i assume the preferred way to handle it would be adding a section to the Downloads part of `buildSettingsScreen()` in `SettingsFragment` and treating it like the other preferences?

**Comment by Maxr1998** [comment]
Yep, that would be the way to go. You can probably use a selection preference like we do for the player implementation 👍
