### ISSUE TITLE
No option to download over non-roaming mobile networks

### ISSUE THREAD

**Issue by taitsmith** [jellyfin/jellyfin-android#1330]
I suppose this is tangentially related to #1326 and can be rolled into a PR for that, or one of its own.

When attempting to download some media for the first time, users are presented with a choice of allowed network types, which currently consists of 'wifi only' and 'mobile data and roaming':
![ss_no_mobile](https://github.com/jellyfin/jellyfin-android/assets/18432394/e7982957-9ebd-41a3-abf3-9fd194bef7b9)

When the dialog is created [here](https://github.com/jellyfin/jellyfin-android/blob/ae437d163d12de067563e4fbe09104140a8f2acb/app/src/main/java/org/jellyfin/mobile/utils/SystemUtils.kt#L82), `setPositiveButton()` is called twice which turns 'mobile data' to 'mobile data and roaming'. Changing one to `setNeutralButton()` (and swapping negative/positive for order) provides users all three options:
![ss_mobile_roaming](https://github.com/jellyfin/jellyfin-android/assets/18432394/6946645d-0f9b-4b08-9c5f-2e773b2e0889)

**Comment by Maxr1998** [comment]
That's definitely an oversight! You are welcome to create a pull request to fix that too :+1:
