### ISSUE TITLE
Unable to access buttons on bottom of screen

### ISSUE THREAD

**Issue by luigi311** [jellyfin/jellyfin-android#135]
**Describe the bug**

When casting to device the controls appear at the bottom of the screen for seeking play and skip underneath the home and back button. Opening the remote control view has the same issue but this time with the volume button and the menu button being covered. 
**To Reproduce**

1. Click on Cast
2. Click on device to cast 
3. Bottom of the screen contains play/skip issue
4. Click on cast button
5. Click on Remote control
6. Volume issue is on the bottom of screen

**Expected behavior**

The play/skip buttons and the volume/menu buttons should be accessable
**Logs**

**Screenshots**

Here is a screenshot showing the volume issue
![Screenshot_20200918-105447](https://user-images.githubusercontent.com/4695527/93625555-62bea900-f99f-11ea-8812-9bb199e41e9d.png)

**System (please complete the following information):**
 - App version: 2.0.0-rc.5
 - Android version: Android 11
 - Device manufacturer and model: Pixel 3a XL
 - Jellyfin server version: 10.6.4
 - The type of video player implementation used: Cast on webplayer

**Additional context**

**Comment by luigi311** [comment]
Looks like this doesnt always happen. I exited the app and when i reopened it it reloaded everything and now all the buttons appear above the navigation bar.

**Comment by Maxr1998** [comment]
This should've been fixed in rc.4/rc.5, specifically #74. Not sure why it still happens for you then.

**Comment by luigi311** [comment]
Looks like its only happened once. Will close for now and will reopen if the problem reappears
