### ISSUE TITLE
Add a "Download" menu item for music albums, not only tracks

### ISSUE THREAD

**Issue by Kvaks** [jellyfin/jellyfin-android#1355]
When viewing a music album, there's a three dot "kebab menu" with various items, but there's no "download" among them. However, each track also has a kebab menu, and they _do_ have a "download" item (which works as expected). It's tedious to download each track separately, so it'd be nice to have a feature to download the whole album in one go (it should also put the files in a new and appropriately named subfolder).

![20240419_185521](https://github.com/jellyfin/jellyfin-android/assets/995037/c0460234-66a9-4b1f-97a4-a39ba4f299d3)

**Comment by Arne-DH** [comment]
Would love to see this, I also requested this feature for the windows desktop app with 2 possible implementation methods
https://github.com/jellyfin/jellyfin-media-player/issues/604

**Comment by nielsvanvelzen** [comment]
This needs to be implemented in jellyfin-web. The Android app is just a wrapper for it.
