### ISSUE TITLE
Android app only allows first track in album to be played when casting to Chromecast Audio

### ISSUE THREAD

**Issue by RavyDavyGravy** [jellyfin/jellyfin-android#136]
**Describe the bug**
When casting to chromecast audio from Android app, selecting any track in an album always plays the first track.
The same behaviour is not seen when not casting.

**To Reproduce**
1. Start Jellyfin server on Windows 10
2. Open Jellyfin app on Android phone and connect to server
3. Open music library and select an album
4. Select Cast, then Google Cast, then "Chromecast Audio" - get confirmation sound from Chromecast Audio
5. Select a track other than the first track on the album
6. First track on the album plays

**Expected behavior**
The track selected plays

**Screenshots**
![Screenshot_20200919_094537_org jellyfin mobile](https://user-images.githubusercontent.com/31000687/93663481-3e76d100-fa60-11ea-8e79-28e6ad8d6ae0.jpg)
![Screenshot_20200919_094642_org jellyfin mobile](https://user-images.githubusercontent.com/31000687/93663483-4171c180-fa60-11ea-96eb-d839c3fd45d7.jpg)

**System (please complete the following information):**
 - App version: v2.0.0-rc.5 and also latest in Google Play store as at 19/09/2020
 - Android version: Android 10
 - Device manufacturer and model: Huawei P-20
 - Jellyfin server version: 10.6.0

**Logs**
[log_20200919-edit.log](https://github.com/jellyfin/jellyfin-android/files/5249448/log_20200919-edit.log)

**Additional context**
Can't tie it down, but looks like it might be linked to a queing system - possibly with current track and next track lined up.  Playing an album from the start seems to flow through the tracks OK, but similar issues to above start when you try to jump to the next track.

**Comment by neopc10** [comment]
https://github.com/jellyfin/jellyfin-chromecast/pull/65

**Comment by x-real-ip** [comment]
4 years later... I am seeing this same problem
