### ISSUE TITLE
[Webplayer} Unable to seek it will jump back to beginning of video

### ISSUE THREAD

**Issue by molitar** [jellyfin/jellyfin-android#1368]
### Describe the bug

Watch a video.  Move the seek bar to jump ahead.   File location jumps to beginning of screen starting over. 

### Application version

2.6.0

### Where did you install the app from?

Google Play

### Device information

Google Pixel Fold

### Android version

Android 14

### Jellyfin server version

10.8.13

### Which video player implementations does this bug apply to?

- [X] Web player (default)
- [ ] Integrated player (ExoPlayer)
- [ ] External player (VLC, mpv, MX Player)

**Comment by ThaChillera** [comment]
I had the same issue as well, just updated to jellyfin 10.9.x, that did not help
