### ISSUE TITLE
Chromecast with .strm files

### ISSUE THREAD

**Issue by kinv** [jellyfin/jellyfin-android#137]
Hi,

All my files are .strm. These play fine in jellyfin web ui, on my phone via this android app and on screenplay for lg tv.

However when I cast from my phone using this app all I get is a blank screen. I have looked through the logs but have not been able to find anything to suggest why (jellyfin seems to think the file is playing fine).

Additional info;

I have tried via https (nginx reverse-proxy)
http via ip:port
I have not been able to get the web app to recognise my chromecast to test
It works using emby

Edit 

Tested with jellyfin web casting. Same as above.

**Comment by DrPandemic** [comment]
If you think the other issue is the right one, could this one be closed? I personally think it's web related not android.
