### ISSUE TITLE
Subtitles aren't sync with videos on resume or seeking

### ISSUE THREAD

**Issue by tuxrinku** [jellyfin/jellyfin-android#137]
**Describe the bug**
When resuming or seeking a video, subtitles get out of sync by a few seconds

**To Reproduce**

1. Resume a video with subtitles

**Expected behavior**
Synchronized subtitles

**System (please complete the following information):**
 - App version: 2.0.0-rc.5
 - Android version: Android 8
 - Device manufacturer and model: ZTE
 - Jellyfin server version: 10.6.4
 - The type of video player implementation used: native

**Comment by Maxr1998** [comment]
I haven't observed this happening yet, and couldn't reproduce it while testing it locally. Could you give some more details about the played file (format), subtitle format and whether they're bundled within the media file or loaded externally? I'm a bit confused how this could happen though, as we just pass the media (and external subtitle stream, if applicable) into ExoPlayer, which then handles playback and everything.

**Comment by tuxrinku** [comment]
It's a mkv file. Video is 1080p h264 and subtitles are bundled within the video in subt format. Here's an exemple :
https://youtu.be/P9p2nHMU8xY

**Comment by redactedscribe** [comment]
I'm also experiencing this. First time using the app.

```
Input #0, matroska,webm, from '.\video.mkv':
…
Stream #0:0(und): Video: h264 (High), yuv420p(progressive), 1920x1080, SAR 1:1 DAR 16:9, 23.98 fps, 23.98 tbr, 1k tbn, 47.95 tbc (default)
…
Stream #0:2(und): Subtitle: ass (default)
```

Seems to happen when I seek. Somewhat related: the subtitle offset feature steps in too large increments to accurately compensate for the delay. Seeking some more can help knock the subtitle delay around, making it align with a degree of selected offset. Also, I recall having to manually select the subtitle each time I started the video, even though the subtitle already had a tick next to it (toggling the subtitle to Off and back again). Haven't tested whether this still happens with an external subtitle.

Another observation I made was that, when testing SyncPlay, I noticed the subtitles on my Android seemed to always stay in time with the ones being shown on my PC. I'm new to Jellyfin so I don't know what level of synchronisation to expect from SyncPlay, but the two videos seemed out by a couple seconds, but as I said, the subtitles were in synch. Might not necessarily be a clue, but I thought I'd mention it regardless.

- App version: 2.0.0-rc.5
- Android version: Android 8
- Jellyfin server version: 10.6.4

**Comment by Maxr1998** [comment]
@redactedscribe I think you're talking about the web player though, right? The native player doesn't even support syncplay (yet).

**Comment by redactedscribe** [comment]
I don't actually know. I guess it must've been then. I just downloaded the app and used whatever player launched when I hit play (seemed native to the app but perhaps it wasn't).

**Comment by Maxr1998** [comment]
@redactedscribe ah yes, that's the web player then, the native player based on ExoPlayer has to be chosen in client settings. Could you re-post your report in #46? It fits better there.

**Comment by tuxrinku** [comment]
Here's the details of the file that causes the issue (but it's not the only one) :
`Stream #0:0(eng): Video: h264 (High), yuv420p(tv, bt709, progressive), 1920x816, SAR 1:1 DAR 40:17, 23.98 fps, 23.98 tbr, 1k tbn, 47.95 tbc (default)`
`Stream #0:1(fre): Audio: ac3, 48000 Hz, 5.1(side), fltp, 448 kb/s (default)`
`Stream #0:2(eng): Audio: ac3, 48000 Hz, 5.1(side), fltp, 448 kb/s`
`Stream #0:3(fre): Audio: aac (LC), 48000 Hz, stereo, fltp`
`Stream #0:4(fre): Subtitle: subrip`
`Stream #0:5(eng): Subtitle: subrip`
Also I wonder why the native player says it's transcoding, it should be able to play natively this file right ?

**Comment by jorritsmit** [comment]
I have the same issue using exoplayer. What would you need to debug this?

**Comment by Maxr1998** [comment]
I fear that bug is an ExoPlayer one, but I can't tell for sure. For now, some info on the played back media would help (container, codecs, subtitle format).

**Comment by dkanada** [comment]
@cvium noticed similar issues syncing subtitles recently, but I'm not sure if it's related.

**Comment by mkelzeer** [comment]
I have this issue too, any updates?

**Comment by Maxr1998** [comment]
Does it only happen while transcoding or also when playing a file directly?

**Comment by mkelzeer** [comment]
> Does it only happen while transcoding or also when playing a file directly?

In my case it was "re-muxing", while Video & Audio both showed "direct". So, it's not exclusive to transcoding.

**Comment by mkelzeer** [comment]
Update: I was playing with the app settings, I figured that this only happens in the Web player (HTML player), which is the default option (the same one I see when playing on desktop browser)

ExoPlayer (_native_) & External players are just fine, skipping, pausing & resuming works properly.

**Comment by jorritsmit** [comment]
For me it is specifically happening for exoplayer. Maybe I have to reinstall

**Comment by moleculezz** [comment]
I can confirm this is still happening. I have Jellyfin running on Google TV and this happens all the time.

**Comment by keilun** [comment]
I was running into this same issue in jellyfin-androidtv 0.15.10. I know it's a separate repo, but I thought I'd share that I managed to fix for my setup by disabling transcoding on my users. Might be worth a shot here as well and perhaps a clue as to the underlying issue.
