### ISSUE TITLE
[FR] Passout / "Still watching ?" protection (Basically sleep timer)

### ISSUE THREAD

**Issue by Ge082** [jellyfin/jellyfin-android#1370]
**Describe the feature you'd like**
Jellyfin doesn't seem to have a "passout protection" or any "still watching ?" feature, meaning that if I start a TV show (or anything with a moving picture really) at evening, it'll still be running when I wake up. It's a waste of energy
Plex added this feature in both app pameters (auto-trigger playback stop if no input from user from a certain amount of time) and video OSD, where a sleep timer can be set, after the time runs out, it stops playback.

Wonder if this kind of feature can be implemented in Jellyfin
Thanks

**Comment by nielsvanvelzen** [comment]
https://features.jellyfin.org/posts/814/are-you-still-watching-prompt
