### ISSUE TITLE
Push 2.6.1 to F-Droid 

### ISSUE THREAD

**Issue by pwd-github** [jellyfin/jellyfin-android#1376]
**Describe the feature you'd like**

Please push 2.6.1 to F-Droid

**Additional context**

2.6.1 was pushed to the Play Store but not F-Droid for some reason.

**Comment by nielsvanvelzen** [comment]
Seems to be updated to me

https://gitlab.com/fdroid/fdroiddata/-/blob/master/metadata/org.jellyfin.mobile.yml

**Comment by pwd-github** [comment]
https://f-droid.org/packages/org.jellyfin.mobile/

It's not there

**Comment by nielsvanvelzen** [comment]
F-Droid did pick up the release, they just haven't build it yet. We don't control that so we can't do anything about it.
