### ISSUE TITLE
Downloading video for offline use won't download the external subtitle alongside

### ISSUE THREAD

**Issue by amalgame21** [jellyfin/jellyfin-android#1379]
### Describe the bug

1. click "Download" button for offline use
2.  Video with name "Movie.mp4" download complete.
3. The external subtitle with name "Movie.eng.mp4" is not downloaded

The external subtitle works perfectly with online use though.
It happens on android, linux jellyfin-media-player and web client

### Application version

2.6.1

### Where did you install the app from?

F-Droid

### Device information

Google Pixel 5

### Android version

Android 14

### Jellyfin server version

10.8.13

### Which video player implementations does this bug apply to?

- [X] Web player (default)
- [X] Integrated player (ExoPlayer)
- [X] External player (VLC, mpv, MX Player)

**Comment by nielsvanvelzen** [comment]
The download feature is part of the web ui, not the app.
