### ISSUE TITLE
SyncPlay is missing

### ISSUE THREAD

**Issue by GodBleak** [jellyfin/jellyfin-android#1386]
### Describe the bug

The SyncPlay feature seems to be missing from the app. From what I've seen from old screenshots, like other clients, the SyncPlay button should be to the left of the cast button, but as seen here, it's missing. 
![Screenshot_20240515_114929](https://github.com/jellyfin/jellyfin-android/assets/38085518/9b057893-5412-4eca-8cc6-57557bf79d0c)

### Application version

2.6.1

### Where did you install the app from?

Google Play

### Device information

Samsung Galaxy S21, Samsung Galaxy S9

### Android version

Android 11, Android 10

### Jellyfin server version

10.9.0

### Which video player implementations does this bug apply to?

- [x] Web player (default)
- [x] Integrated player (ExoPlayer)
- [x] External player (VLC, mpv, MX Player)

**Comment by nielsvanvelzen** [comment]
You most likely removed the "syncPlay/plugin" entry from your config.json, which is part of jellyfin-web.

Closing as this is is not an app issue.

**Comment by GodBleak** [comment]
@nielsvanvelzen If that were the case, I would simply put the entry back rather than frivolously opening an issue. I haven't touched config.json. And SyncPlay works on the web and desktop clients. I'm also not the only one to have this issue:
![image](https://github.com/jellyfin/jellyfin-android/assets/38085518/a2dce276-2ce9-43ee-9244-77e70781dded)
![image](https://github.com/jellyfin/jellyfin-android/assets/38085518/d77cab6a-db9b-436b-8aa2-68827025df95)


Reopen the issue.
