### ISSUE TITLE
ASS subtitles not rendered properly but fine on browsers

### ISSUE THREAD

**Issue by SodaWithoutSparkles** [jellyfin/jellyfin-android#1388]
### Describe the bug

1. Have a video file that:
    - has ASS subtitles with special styles and fonts
 2. Playback the videp file on jellyfin android and select that subtitle
 3. observe that the subtitles are not working correctly
     - Incorrect font
     - Correct color
     - Black background behind text
     - Simultaneous subtitles became jibbrish mess after displaying "correct-ish" subtitles for 1 frame
4. Use a browser to view the same video
5. observe that everything works correctly when the video was remuxed:
    - Font is correct without dark background
    - Simultaneous subtitles are displayed correctly

------

- When using web player, video gets transcoded, but without the correct font
- When client settings > ass support in direct play is disabled, video gets transcoded without the correct font
- when using VLC as external player, most things are normal but still without correct font
- When using firefox or chrome, zero issues occur. Font, background and simultaneous subtitles are all fine.
- System subtitles settings does not affect the outcome
- subtitle file can be provided upon request

### Logs

_Attached upon further request_

### Application version

2.6.1

### Where did you install the app from?

Google Play

### Device information

Poco X4 GT

### Android version

Android 13, MIUI 13.2.5.0

### Jellyfin server version

10.9.1

### Which video player implementations does this bug apply to?

- [ ] Web player (default)
- [X] Integrated player (ExoPlayer)
- [ ] External player (VLC, mpv, MX Player)

**Comment by vincejv** [comment]
Last time i recalled JMP doesn't have any control on external players like Android's ExoPlayer, integrated means it's *embedded in the app* and doesnt call an external activity to trigger it, but still it's an external library or dependency which the project cant control

You may want to report the issue here https://github.com/google/ExoPlayer/issued

**Comment by vincejv** [comment]
Actually the issue is already known in upstream

https://github.com/google/ExoPlayer/issues/8435

**Comment by vincejv** [comment]
Also dupe of #252

**Comment by SodaWithoutSparkles** [comment]
Sorry for the dupe. My search didnt found that issue probably because of different symptoms. I was searching for jibbrish ASS subtitle phenomenon as shown in Pic5.

It could also be related to https://github.com/google/ExoPlayer/issues/10295

**Comment by SodaWithoutSparkles** [comment]
It should also be noted that ExoPlayer is deprecated and this bug is probably not going to be fixed (if we dont move to the suggested library):

> This project is deprecated. All users should migrate to AndroidX Media3. Please refer to our migration guide and script to move your codebase to the Media3 package names.
