### ISSUE TITLE
Back gesture has dead spot

### ISSUE THREAD

**Issue by CaesarPepsel** [jellyfin/jellyfin-android#1390]
### Describe the bug

On any screen in the app, the back gesture doesn't register on the left side in the middle area. The left-top and left-bottom area work fine. 

### Logs

```shell
No logs
```

### Application version

2.6.1

### Where did you install the app from?

Google Play

### Device information

Samsung galaxy s23

### Android version

Android 14

### Jellyfin server version

10.9.2

### Which video player implementations does this bug apply to?

- [ ] Web player (default)
- [ ] Integrated player (ExoPlayer)
- [ ] External player (VLC, mpv, MX Player)

**Comment by AllegraCodes** [comment]
Android lets you exclude certain areas from triggering the back gesture to maintain compatibility with other gestures used in your app, like swiping in from the left to open a sidebar menu
https://developer.android.com/develop/ui/views/touch-and-input/gestures/gesturenav#back-gestures

This app apparently uses the maximum height for this exclusion zone
https://github.com/jellyfin/jellyfin-android/blob/16aebe31397595549c00d6e0295a41ee60d05d5b/app/src/main/java/org/jellyfin/mobile/webapp/WebViewFragment.kt#L133-L155

I agree it feels like a dead zone and should probably be shrunk. Even better imo would be to eliminate both the old gesture and the exclusion zone, but idk how easy that is
