### ISSUE TITLE
Unable to connect to server with mobile data.

### ISSUE THREAD

**Issue by lorenzolamas** [jellyfin/jellyfin-android#1397]
### Describe the bug

Unable to connect to server with mobile data, but OK with internet browser (and ok when i'm connected on wifi, on the same network)

### Application version

2.6.1

### Where did you install the app from?

Google Play

### Device information

Poco X3 pro

### Android version

Android 13

### Jellyfin server version

10.9.2

### Which video player implementations does this bug apply to?

- [ ] Web player (default)
- [ ] Integrated player (ExoPlayer)
- [ ] External player (VLC, mpv, MX Player)

**Comment by solidsnake1298** [comment]
Are you using a reverse proxy?

**Comment by lorenzolamas** [comment]
> Are you using a reverse proxy?
Hi,
nope

**Comment by lorenzolamas** [comment]
I uninstalled and reinstalled and it works...
