### ISSUE TITLE
Jellyfin pauses music playback after 20 - 30 seconds of the app being in the background

### ISSUE THREAD

**Issue by Britishblue** [jellyfin/jellyfin-android#1401]
### Describe the bug

I play a song on the app, exit out and it continues playing, then after 30 seconds or so it stops and will only play again once I click on the app. I use graphene os if that has anything to do with it? I disabled all the graphene os memory stuff for the app but it still doesnt work. Battery optimisation is on unoptimised. Thanks

### Application version

2.6.1

### Where did you install the app from?

F-Droid

### Device information

Google Pixel 7

### Android version

Graphene OS

### Jellyfin server version

10.8.13

### Which video player implementations does this bug apply to?

- [X] Web player (default)
- [X] Integrated player (ExoPlayer)
- [X] External player (VLC, mpv, MX Player)

**Comment by Britishblue** [comment]
I believe I know what the issue is. Apparently its something to do with the android api level. Another app called Finamp which is a jellyfin music client fixed this issue by downgrading it to level 33. I dont know the technical reasoning behind it but I believe this is it. For the meantime until it gets fixed just use Finamp. Its on fdroid and the play store

**Comment by wistro** [comment]
I'm having this same issue.

Application version
2.6.1

Where did you install the app from?
Google Play Store

Device information
Nothing Phone (1)

Android version
14 (Nothing OS 2.5.5)

Jellyfin server version
10.9.3

**Comment by Britishblue** [comment]
> I'm having this same issue.
> 
> Application version 2.6.1
> 
> Where did you install the app from? Google Play Store
> 
> Device information Nothing Phone (1)
> 
> Android version 14 (Nothing OS 2.5.5)
> 
> Jellyfin server version 10.9.3

It still does it for me. Best solution is just to use finamp. It actually has a nicer UI for music so I think ill continue using it. Fixes the issue completely.

**Comment by michd** [comment]
Same as #1378 I think?
