### ISSUE TITLE
Connection cannot be established

### ISSUE THREAD

**Issue by artyums** [jellyfin/jellyfin-android#1406]
### Describe the bug

![Без имени](https://github.com/jellyfin/jellyfin-android/assets/95072339/a6d03f0d-e790-4528-8d6b-2d263517c1b8)

Using Jellyfin Android and successfully login to my Jellyfin account. But after some seconds/minutes browsing menus/collections or right after starting playback of any content - I get an error "Connection cannot be established. Please check the hostname and your network connection".

It doesn't matter if I use cellular network (via public IP or fqdn with original 8096 port or 80 port and reverse proxy) or WiFi (via internal IP or fqdn...) to access Jellyfin.

When I'm using any mobile web browser - it's no problem to use Jellyfin Web (but there is problem with black-filled status bar, so fullscreen is not real fullscreen. And that is why I want to use Jellyfin Android).

**Important!** This issue is only happen on **second** (and later) application run (second after (re)installation or clearing all apps data). First application run works well.

### Application version

2.6.1

### Where did you install the app from?

Sideloaded APK (proprietary build)

### Device information

Xiaomi Mi 11 

### Android version

HyperOS by xiaomi.eu 1.0.1.0.UKBCNXM, Android 14 UKQ1.231207.002

### Jellyfin server version

10.9.0

### Which video player implementations does this bug apply to?

- [X] Web player (default)
- [ ] Integrated player (ExoPlayer)
- [ ] External player (VLC, mpv, MX Player)

**Comment by nielsvanvelzen** [comment]
Update to at least 10.9.3
