### ISSUE TITLE
Enable portrait mode 

### ISSUE THREAD

**Issue by dlnraja** [jellyfin/jellyfin-android#141]
Would like to enable the portrait mode .

Not to be locked on landscape mode when playing video .

Best regards.

**Comment by nielsvanvelzen** [comment]
As far as I am aware we support portrait mode. Can you be more specific on what doesn't work for you so we can help fix it?

**Comment by dlnraja** [comment]
Each video are in landscape mode, the main interface also

:(

**Comment by neopc10** [comment]
Portrait mode works here.

**Comment by eglia** [comment]
For me portrait mode works, but the video automatically switches to landscape on playback start (exoplayer). So to get back to portrait mode, I have to physically rotate my phone to landscape and back, which is annoying.

**Comment by Maxr1998** [comment]
Orientation handling is a lot better now, especially for portrait videos. Please let me know if this can be closed.

**Comment by ekos2001** [comment]
For me it still work as described by @eglia in https://github.com/jellyfin/jellyfin-android/issues/141#issuecomment-697297972
It would be better if video doesn't switch to landscape on playback start.

**Comment by Maxr1998** [comment]
The thing is, though - we don't show any other information (like YouTube does with video description, recommendations, comments) that world warrant showing a landscape video in portrait. Even worse, for those who want to watch in landscape anyway, it would mean another click (if auto-rotation is off).

**Comment by chino** [comment]
If they want to watch in landscape they can simply turn their phone and interact with it that way?  This is my first time using the app and it was very non-intuitive compared to other apps.  I didn't have auto rotate enabled so for a minute I thought it simply didn't support portrait at all until this issue made me realize what happened.

On that note is there another issue tracking `mini floating window` support?  Youtube and others can now continue to play in a small floating window while you multitask around the phone. That would be really nice!
