### ISSUE TITLE
Add Brightness slider

### ISSUE THREAD

**Issue by vikingnope** [jellyfin/jellyfin-android#1411]
**Describe the feature you'd like**

A brightness slider should be added within the video player so that we can increase the brightness without having to miss part of the show.

Netflix has a good example of this:

![netflix-app-brightness-issue-1_4d470f76dc99e18ad75087b1b8410ea9.png](https://github.com/jellyfin/jellyfin-android/assets/81376423/59c77f4e-577b-403c-81d3-6d4b9b1573ed)

**Additional context**

**Comment by FreesphereTom** [comment]
This is already a feature. If it's not working for you, check "client settings"

**Comment by vikingnope** [comment]
@FreesphereTom you are correct, had to change to the integrated player. Thanks a lot 😊
