### ISSUE TITLE
Connection dropping after 2~ minutes

### ISSUE THREAD

**Issue by hardcoregandhi** [jellyfin/jellyfin-android#1415]
### Describe the bug

Connect to a server from the app, wait a few minutes and it will disconnect. Doesn't matter if you are playing content or just browsing the Library

### Logs

```shell
....Regular drawLayers logging intervals...
06-28 10:19:43.424 12734 12734 I WebView : Requesting url without automatic networking: http://<my-ip>:8096/Sessions/Playing/Progress, http://<my-ip>:8096/web/node_modules.jellyfin-apiclient.bundle.js?3b140e0ac043bcbb303b (2)
......
06-28 10:19:51.722 12734 12734 I WebView : fetchWithTimeout: timed out connecting to url: https://169.254.86.21:8920/system/info/public, http://<my-ip>:8096/web/node_modules.jellyfin-apiclient.bundle.js?3b140e0ac043bcbb303b (2)

^^ Note it is connecting to somewhere else, not my server
```

### Application version

2.6.1

### Where did you install the app from?

Google Play

### Device information

Samsung Z Fold 4

### Android version

Android 14

### Jellyfin server version

10.9.2

### Which video player implementations does this bug apply to?

- [ ] Web player (default)
- [ ] Integrated player (ExoPlayer)
- [ ] External player (VLC, mpv, MX Player)

**Comment by drfarmerdave** [comment]
I've been experiencing the same on three different android phones connecting to the same Jellyfin server.
Application version
2.6.1

Where did you install the app from?
Google Play

Device information
Oppo A53s
Nokia 3.4
Motorola Moto G5

Jellyfin server version
10.9.7

**Comment by robsee** [comment]
I've got the same problem using the github version on a Pixel Tablet. When this occurs the audio track continues while the login screen is displayed.
