### ISSUE TITLE
Could we have a new release please?

### ISSUE THREAD

**Issue by joshuamkite** [jellyfin/jellyfin-android#1416]
**Please could we have a new release to app stores**
An annoying bug was fixed recently: [Fix background playback stopping on Android 14 #1412](https://github.com/jellyfin/jellyfin-android/pull/1412). Please could we have a new release incorporating this so that users can make use of it. So far as I can tell the most recent prior release was v2.6.1 on Apr 27 and the only other commits to `master` since have been translations or housekeeping. Thanks

**Comment by nielsvanvelzen** [comment]
Version 2.6.2 is now released and will be available for download in the stores within the coming days.

https://github.com/jellyfin/jellyfin-android/releases/tag/v2.6.2
