### ISSUE TITLE
"Google Cast Version" config is empty

### ISSUE THREAD

**Issue by agilob** [jellyfin/jellyfin-android#1418]
### Describe the bug

When I go to the playback config in Jellyfin Android installed from GPlay the dropdown list is empty.

Another problem is that jellyfin doesn't detect any of my chromecast devices.

![image](https://github.com/jellyfin/jellyfin-android/assets/2544251/c33df7e7-0d55-44d7-9803-34b65ce7447a)

### Application version

2.6.1

### Where did you install the app from?

Google Play

### Device information

Google

### Android version

14

### Jellyfin server version

10.9.7

### Which video player implementations does this bug apply to?

- [ ] Web player (default)
- [ ] Integrated player (ExoPlayer)
- [ ] External player (VLC, mpv, MX Player)

**Comment by nielsvanvelzen** [comment]
This is a common issue when downgrading from 10.9 back to 10.8 and then upgrading again. Not a problem with the app.

**Comment by agilob** [comment]
I didn't downgrade anything. I installed it today fresh from GPlay

**Comment by Septem151** [comment]
Any fix for this?
