### ISSUE TITLE
Account Manager login 

### ISSUE THREAD

**Issue by Xyz00777** [jellyfin/jellyfin-android#142]
Heyho
When i select the Name field and want to autofill automaticly it only autofill the Name and for the password i have to autofill Again for the password field.
I using bitwarden as Account Manager at my oneplus nord Android 10.
Did you need any Additional informarions? When yes what?

Greetings
Xyz00777

**Comment by nielsvanvelzen** [comment]
Hi, I noticed this issue does not use one of our issue templates. We provide these templates to get the information necessary in order to help. I will close this issue but I encourage you to recreate it using the template so we can help.

**Comment by Xyz00777** [comment]
excuse me when i created the issue i didnt find a template. i was confused too
