### ISSUE TITLE
Cast to a nearby device

### ISSUE THREAD

**Issue by pb1051** [jellyfin/jellyfin-android#143]
When using Jellyfin I receive the "Cast to a nearby device" pop-up constantly. I will even receive this pop-up when not in the app. I then have to Force Stop the app to stop the behavior.

```
Pixel 2
Android P
Jellyfin 2.8.54
```

**Comment by petermcneil** [comment]
Occurs with me as well.

Android P
Nokia 8
Jellyfin 2.8.54

**Comment by NoShinSekai** [comment]
Same issue here.

Android 8 Oreo
Samsung S7 non-Edge
Jellyfin 2.8.54

**Comment by kjkeane** [comment]
I am having the same issue on the most recent build:

* OnePlus 6t
* Android 9 Pie
* jellyfin-android 0.9.0

**Comment by dkanada** [comment]
Can any of you confirm a specific beta version that doesn't have this issue? I don't have a Chromecast so I am unable to test or debug this efficiently without a little more information.

**Comment by kjkeane** [comment]
@dkanada I can do some testing.

Right now on 0.9.0 this issue occurs, but I don't see it happening on [beta9](https://repo.jellyfin.org/releases/client/android/versions/beta9/)

**Comment by kjkeane** [comment]
So I had a plan to do testing on other devices and give my feedback, but now it's just acting weird.  For instance it was constantly popping up on `0.9.0` but after removing installing other versions I don't see it happening.

```
An update on what I have seen with different versions (In order of install)
**NOTE:** This was done with the normal release APK and not the `unminified` or `debug` version

Version 0.9.0:
* As described above, constant pop-up of "Cast to a nearby device"

Version [beta9](https://repo.jellyfin.org/releases/client/android/versions/beta9/)
* Same issue as 0.9.0

Version [beta8](https://repo.jellyfin.org/releases/client/android/versions/beta8/)
* I saw it on the initial install, but after a reinstall it no longer appears

Version [beta7](https://repo.jellyfin.org/releases/client/android/versions/beta7)
* I did not see this
```

**Comment by kjkeane** [comment]
Going to give an update on something I noticed since the official release in the Play store.  I had this issue occur on first setup of the application/ (connecting to a server and login), but after I closed the app and re-opened it, this notification went away.

**Comment by pb1051** [comment]
> Going to give an update on something I noticed since the official release in the Play store. I had this issue occur on first setup of the application/ (connecting to a server and login), but after I closed the app and re-opening it, this notification went away.

I have not seen an official release... ?

**Comment by mindcombatant** [comment]
Also happening here, both on my old and new phone
both Android P
Pixel XL and Pixel 3a XL
using this binary: https://repo.jellyfin.org/releases/client/android/jellyfin-android_0.9.0.apk
Only special things about my phones: the 3a XL is rooted, and they both are connected to my home network via OpenVPN.
There are no chromecasts on my home network, and the issue also occurs when i'm disconnected from OpenVPN and on my home network.
My home network also has a Samsung Smart TV that allows Youtube to cast to it, but no other chromecast stuff has ever worked or popped up with it.
I hope this is helpful. Is there anything I can do to help further, like capture logs or something?

**Comment by pceiley** [comment]
Just adding a "me too" to this issue. Additionally, it seems to trigger the jellyfin app loading on the Chromecast again - even when I have manually stopped casting. If I have turned the TV off as well then this bug turns my TV back on!

**Comment by dkanada** [comment]
Just wanted to give you guys an update. I had an hour at a friend's house to test with a smart TV and wasn't able to reproduce the issue. I will look into it again soon since it sounds quite annoying, there must be an issue with the chromecast plugin we use.

**Comment by pceiley** [comment]
Thanks @dkanada for taking the time to look into this!

It's probably worth noting that I'm experiencing this on a Pixel 3 running Android 9.

**Comment by mindcombatant** [comment]
I get the feeling it has something to do with this "feature" of chromecast: https://www.omgchrome.com/ultrasonic-chromecast-sound-for-wifi-free-pairing/
I do tend to get the pop-ups near the outer wall of my house, so maybe the sound is bleeding through the walls from my neighbors. Either way, the issue is that the prompt pops up on it's own, repeatedly, and not just when you click something to pair.

**Comment by pb1051** [comment]
That sounds very likely!

**Comment by dkanada** [comment]
I think I fixed the issue with jellyfin-web#365 but we will need to test it out first.

**Comment by dkanada** [comment]
We have binaries up on GitHub if anyone has time to try them out. If the issue is fixed we will release to Google Play shortly.

**Comment by pceiley** [comment]
Been testing the GitHub version and have not experienced this issue. Appreciate the fix - thanks!

After a while, my phone app seems to disconnect from the chromecast and I need to re-connect, then bring up the remote in order to stop or pause. I'm not sure if this is intended behaviour - but given it's a minimum of 3 touches just to connect to the chromecast it can be quite cumbersome!
