### ISSUE TITLE
Category "plugin" missing in the settings ?

### ISSUE THREAD

**Issue by koopernick** [jellyfin/jellyfin-android#1441]
Hello,

I'm looking for the option to enable a plugin (intro-skipper in my case).
It seems the category "plugin" is missing from the android app ? 

I can see it in the windows client only.

![TinyTake12-07-2024-05-29-52](https://github.com/user-attachments/assets/6faba1c8-b135-4a0d-98ef-b0dd6fa70ffc)

Is it planned to add it at some point ?
Or maybe I'm missing something obvious and it's already there ? 

Thank you for the app overall, it's working like a charm.

**Comment by nielsvanvelzen** [comment]
We do not support third party plugins in official clients.

**Comment by koopernick** [comment]
Sounds weird, since it's available on the official windows app.

Thanks for the info tho !
