### ISSUE TITLE
All http links are treated as HSL for ExoPlayer

### ISSUE THREAD

**Issue by DaRealHansForSure** [jellyfin/jellyfin-android#1443]
### Describe the bug

1. Make a .strm File which includes a http:// Video Link
2. Play that file over Jellyfin Android and ExoPlayer
3. Source error

The logic code of the Apps seems wrong for me? Not everything that is http, is automatically hsl?
Especally when it works in every other Client (Also under Android TV with ExoPlayer)
![image](https://github.com/user-attachments/assets/ede7ef19-6e06-471d-854d-d1eeef280e90)

### Application version

2.6.2

### Where did you install the app from?

Google Play

### Device information

Nothing Phone 2a

### Android version

Android 14

### Jellyfin server version

10.9.7

### Which video player implementations does this bug apply to?

- [ ] Web player (default)
- [X] Integrated player (ExoPlayer)
- [ ] External player (VLC, mpv, MX Player)

**Comment by nielsvanvelzen** [comment]
We do not support strm files in the Android clients. If they work that's great, if they don't we can't do so much about it.

**Comment by DaRealHansForSure** [comment]
But why do you assume, when its http, its always HLS?

I mean, everything works great in Android TV App, also with ExoPlayer?

**Comment by DaRealHansForSure** [comment]
When i set to the ProgressiveMediaSource Class inside "Http Protocol", it works as expected.

So my thoughts are, thinking everything what is "http" is "hls" is wrong.

**Comment by DaRealHansForSure** [comment]
Is there a reason, why you don't use "MediaSource.Factory"?

It also works fine with http links as i tried, will do more Tests for you, for HLS etc., but would be awesome, that having a working exoplayer :)

**Comment by Maxr1998** [comment]
> But why do you assume, when its http, its always HLS?

Probably decided due to a lack of documentation back then. `MediaSource.Factory` might be worth a try, but I haven't looked into it and am unaware of the implications.

**Comment by DaRealHansForSure** [comment]
The MediaSource.Factory got defined like that:
![image](https://github.com/user-attachments/assets/ce1a43ef-290e-4aee-9344-20c04f575239)

and the DefaultMediaSourceFactory has the feature like that:
![image](https://github.com/user-attachments/assets/53b6b1f6-98c5-42a4-9c02-4e31e94bc6d6)


I will try to do some tests, but i think it would be great and supports directly lot more stuff for the http protocol

**Comment by Sanket9225** [comment]
Any feedback x planned for this.
I want to be able to play strm files in integrated player.

**Comment by DaRealHansForSure** [comment]
I don't think so...

I have still my "workaround" running and crafting the URLs especally for Android App user for tricking the App

**Comment by mjulian87** [comment]
@DaRealHansForSure 

Can you explain your workaround? I would also like to get strm files working in the android app.
