### ISSUE TITLE
Cannot cast to Google Cast receiver

### ISSUE THREAD

**Issue by neopc10** [jellyfin/jellyfin-android#145]
I don't have any reverse proxy issues here. This issue is experienced solely on the Kotlin app.

**To Reproduce**
1. User Playback Settings -> Nightly Chromecast Client
2. Press Save, then forceclose the app.
3. Open a cast session and begin playback.
4. Playback is attempted on the Stable Chromecast client and not the Nightly Google Cast client -- it fails. 

**Expected behavior**
Successfully casting on the nightly Google Cast client just as one would from Chrome (mobile) or the 1.0 Cordova app. As the old Chromecast caster is being deprecated in favor of a functional Google Cast client, the new Android app should share the same ability to access the Google Cast client as the old.

**System (please complete the following information):**
 - App version 2.0.0-rc.6
 - Android 11
 - Jellyfin server 10.6

**Additional context**

**Comment by Bhooty** [comment]
I seem to be able to cast through app
When u click cast button then click my device then the cast button will show chromecast
But on the web side through chrome the Chromecast doesn't show up

**Comment by Maxr1998** [comment]
@Bhooty that's unrelated to the app though, mobile Chrome doesn't support casting in Jellyfin afaik.

**Comment by Bhooty** [comment]
> @Bhooty that's unrelated to the app though, mobile Chrome doesn't support casting in Jellyfin afaik.

Ok but the app doesn't show Chromecast unless i click the icon and select my device first
Then it appears 
Should i open another thread for this?

**Comment by hamburglar2160** [comment]
> @Bhooty that's unrelated to the app though, mobile Chrome doesn't support casting in Jellyfin afaik.

It does

**Comment by Maxr1998** [comment]
> > @Bhooty that's unrelated to the app though, mobile Chrome doesn't support casting in Jellyfin afaik.
> 
> Ok but the app doesn't show Chromecast unless i click the icon and select my device first
> Then it appears 
> Should i open another thread for this?

I'm not really sure on what you're trying to archieve. A Chromecast connection is always local to the current device.
