### ISSUE TITLE
https://github.com/jumoog/intro-skipper   is the newly maintained skip intro / credits. can we add support to the android app

### ISSUE THREAD

**Issue by gaming09** [jellyfin/jellyfin-android#1450]
https://github.com/jumoog/intro-skipper   is the newly maintained skip intro / credits. can we add support to the android app

Skip intros did work on web player but not on exos player

**Comment by nielsvanvelzen** [comment]
No

**Comment by polyzen** [comment]
https://github.com/jellyfin/jellyfin-android/issues/985#issuecomment-1474777105

**Comment by polyzen** [comment]
Native support is being worked on:
https://github.com/jellyfin/jellyfin-meta/discussions/30
https://github.com/jellyfin/jellyfin/pull/10530
