### ISSUE TITLE
Why are the server version and web version displayed on the Android client different?

### ISSUE THREAD

**Issue by mdk-ML** [jellyfin/jellyfin-android#1453]
My Android client is 2.6.2
it shows the server version is 10.9.8
web version is 10.9.4
build version is 10.9.4
Why are the server version and web version displayed on the Android client different?
What's the difference between them?

![微信图片_20240723105440](https://github.com/user-attachments/assets/5f39a43e-9e20-4fa0-8970-ec9ce36b4fec)

**Comment by fatexs** [comment]
Most likely just a caching issue:
Can you try to go to your Preferences--> Apps-> Jellyfin -> delete data -> delete cache

Most likely will be fixed by: https://github.com/jellyfin/jellyfin-web/pull/5730

**Comment by mdk-ML** [comment]
Thank you@fatexs The method you mentioned is very effective
