### ISSUE TITLE
Admin page is broken after latest update. 

### ISSUE THREAD

**Issue by XDark187** [jellyfin/jellyfin-android#1454]
The admin page on the android app doesn't show anything after updating jellyfin server to latest update. 
Multiple people on discord have the same issue.
The issue seems to affect JMP for windows and Jellyfin for android too.

![Screenshot_2024-07-23-22-03-16-975_org.jellyfin.mobile.png](https://github.com/user-attachments/assets/be5cf446-cecd-46bc-8631-f6d65a827e91)

**Comment by fatexs** [comment]
Can you try to go to your Preferences--> Apps-> Jellyfin -> delete data -> delete cache
