### ISSUE TITLE
Possibility of Adding libVLC player to Android

### ISSUE THREAD

**Issue by FT129** [jellyfin/jellyfin-android#1458]
Would it be possible to add the libVLC player to Android mobile app?

The experimental libVLC player on the Jellyfin Android TV app works great, and it let's me play H.265 encoded videos on devices without a HEVC hardware decoder. Using VLC via the existing external player option on the Jellyfin Android mobile app doesn't offer the same seamless experience libVLC does.

**Comment by nielsvanvelzen** [comment]
We do not have plans to add LibVLC to the mobile app, for similar reasons as why it is removed in the next update of the TV app.
