### ISSUE TITLE
Forcing subtitle burning does not work on web player

### ISSUE THREAD

**Issue by paulzzh** [jellyfin/jellyfin-android#1464]
### Describe the bug

1. Go to `Settings`
2. Click on `Subtitles`
3. Choose `All` in `Burn subtitles`
4. Scroll down and click `Save`
5. Play a video
6. Subtitles are rendered on the client side and messed up the fonts
7. This option works on the Integrated player
8. This option works in a real web browser

### Application version

latest branch master, commit 7805cec

### Where did you install the app from?

Sideloaded APK (proprietary build)

### Device information

Oneplus 7T

### Android version

Android 14, PixelOS Unofficial

### Jellyfin server version

10.9.9

### Which video player implementations does this bug apply to?

- [X] Web player (default)
- [ ] Integrated player (ExoPlayer)
- [ ] External player (VLC, mpv, MX Player)

**Comment by paulzzh** [comment]
Android web player always POST SubtitleProfiles with SSA/ASS supported
When set `Burn subtitles` to `All`, it should be empty `[]`
![image](https://github.com/user-attachments/assets/cbb2b747-f6d2-43f7-ba13-2c7802b86fa8)

**Comment by paulzzh** [comment]
They come from `nativeshell.js`
Before getDeviceProfile is called, SubtitleProfiles is empty.
https://github.com/jellyfin/jellyfin-android/blob/0d1b3790a8ab4df7df9a57732a52c084aabac31a/app/src/main/assets/native/nativeshell.js#L98-L116

After setting `SubtitleProfiles` to `[]` from the debugger, I got the encoded subtitles.
![image](https://github.com/user-attachments/assets/36205a15-f45f-4455-9c7f-60f1c7a7e7ee)

**Comment by paulzzh** [comment]
related 9513041 #421 #440
Set `Burn subtitles` to `Auto` and there are already values in `SubtitleProfiles`
Perhaps we don't need to modify this value.
![image](https://github.com/user-attachments/assets/29ca19a9-625f-42cd-aaf8-e131a3cc177d)

**Comment by solidsnake1298** [comment]
Another user and I are having this issue with the integrated player with PGS subs.
