### ISSUE TITLE
No tracking for mpv-android external player

### ISSUE THREAD

**Issue by vegedb** [jellyfin/jellyfin-android#149]
![image](https://user-images.githubusercontent.com/72070424/94532394-6809d680-0270-11eb-8d7c-f8e9ad020a7c.png)

MX-player is closed (bad track record on pinging to unknown servers), VLC player has tons of features that are **not needed**/ **BLOAT** for just jellyfin playback. mpv-android is the best foss minimalist player perfect for jellyfin. Do take a look.

https://github.com/mpv-android/mpv-android

**Comment by CarlosOlivo** [comment]
In this case you need to go to https://github.com/mpv-android/mpv-android and open a new issue where you kindly ask if they can implement returning a result from an activity when using an Intent like in MX Player and VLC Player. Without this we cannot know if the playback was successful, failed or ended at some point, so playback tracking is not supported in your best FOSS minimalist player.

They have already implemented a part in mpv-android/mpv-android#65 based on the MX Player definition, only the other is missing with the result of the activity

Reference MX Player: https://mx.j2inter.com/api#:~:text=%5BResult%3A%20%20com.mxtech.intent.result.VIEW%5D
Reference Android: https://developer.android.com/training/basics/intents/result?hl=en
Reference VLC Implementation: https://code.videolan.org/videolan/vlc-android/-/commit/c66a40bb16d29cabf3b2dcf6371fc4c2e866187d

**Comment by vegedb** [comment]
> In this case you need to go to https://github.com/mpv-android/mpv-android and open a new issue where you kindly ask if they can implement returning a result from an activity when using an Intent like in MX Player and VLC Player. 

Ok done,
https://github.com/mpv-android/mpv-android/issues/316

Hopefully they can implement it before your official release.
