### ISSUE TITLE
Let us be able to seek +30 seconds instead of to next nearest 30 seconds interval

### ISSUE THREAD

**Issue by galmok** [jellyfin/jellyfin-android#1496]
**Describe the feature you'd like**
Currently, when skipping ahead, the client always skips to the next nearest 30 seconds interval, making it skip anywhere from 1 second to 29 seconds ahead. This is unpredictable and not really useful. Intros are often 30 seconds and using this skip method, you are almost guaranteed to never be able to skip exactly ahead 30 seconds. 

I suggest to simply skip ahead 30 seconds. This is predictable and useful.

**Comment by Bollhav64** [comment]
The feature seems to already be working the way you want for me, on the latest 2.6.2 version of the app, using the integrated player.

When I double tap the right side of the screen, it skips 30 seconds ahead, not to the nearest 30 seconds interval as you describe.

**Comment by galmok** [comment]
Yes, version 2.6.2 on Android phone does this already. I may have reported this the wrong place, but on Android TV, it always seems to the next 30 interval and not just 30 seconds ahead. I just noticed the Android tv version is 0.17.9 which means this must belong to a different repository.

**Comment by Maxr1998** [comment]
That's right, the AndroidTV app is a different codebase, located at https://github.com/jellyfin/jellyfin-androidtv. Closing this issue here.
