### ISSUE TITLE
Can't connect to server without protocol

### ISSUE THREAD

**Issue by nielsvanvelzen** [jellyfin/jellyfin-android#15]
When I input just "demo.jellyfin.org/stable" I expect the app to try `https://` and if that fails `http://` automatically.

**Comment by Maxr1998** [comment]
I decided against that when first implementing it, and show an error message instead, cause I didn't want to implicitly infer the protocol. But I agree the current system is less than ideal, and should be fixed.
Loading the webview and waiting for error is a bit awkward though, so maybe I should pull in the apiclient and attempt a login there first, before even showing the webview? Or is there even an unauthenticated check for a Jellyfin server without loggin in?

**Comment by Maxr1998** [comment]
Oh, I think `/System/Info/Public` would be nice for that check, even works unauthenticated. Neat!

**Comment by Maxr1998** [comment]
Closed in 26943d5df33b0c8da9efaff3924f5956f089d5f3.

**Comment by nielsvanvelzen** [comment]
I think using the apiclient for this is not a bad idea, eventually it will be used anyway and it helps making sure both the TV and mobile app have the same behavior (it has a function to add the procotocol; `jellyfin.discovery.addressCandidates(address: String) : Iterable<String>`)
