### ISSUE TITLE
Accrescent app store

### ISSUE THREAD

**Issue by ellie3-36** [jellyfin/jellyfin-android#1522]
**Describe the feature you'd like**
Accrescent is an Android app store focused on security, privacy, and usability. Would love to see Jellyfin android app available in Accrescent.

Some relevant links:

Official website: https://accrescent.app/

Docs: https://accrescent.app/docs/index.html

App submission: https://accrescent.app/faq#app-submission

Contact: [contact@accrescent.app](mailto:contact@accrescent.app)

### Why do you want this feature?

Because of Accrescent features:
https://accrescent.app/features

**Additional context**

**Comment by nielsvanvelzen** [comment]
Closing as duplicate of jellyfin/jellyfin-androidtv#4302 as this issue covers both apps.
