### ISSUE TITLE
[Enhancement] Add in-app purchases as donations

### ISSUE THREAD

**Issue by 97carmine** [jellyfin/jellyfin-android#157]
Reason why I provide that:

I use Google Opinion Rewards, and over time I have accumulated money, and that earned money can only be used exclusively within the Google Play Store.

I understand that this money lasts one year and because I do not use that money at all, I think it's a shame to waste it.

I know that this idea can give a lot of controversy, but I think it may be an option. Unlike Emby, with Jellyfin I do not waste money.

**Comment by anthonylavado** [comment]
Ehhh... I'd *like* to help you here, but I know that adding IAP directly in the app adds a whole world of complexity we haven't even thought about yet. Not sure this will be possible.
