### ISSUE TITLE
Live TV Playback Causes App To Crash

### ISSUE THREAD

**Issue by seniorm0ment** [jellyfin/jellyfin-android#158]
Live TV Playback is not working, it causes the app to crash.

Server, Jellyfin 10.6.0 Windows 10
Reverse Proxy, NGINX
Client, Android 10, Jellyfin v2-rc6

**Comment by grravity** [comment]
Tested on rc-8, same issue.

However, it looks to be related to exoplayer. changing player to web from native seems to fix the issue and play fine.

**Comment by nielsvanvelzen** [comment]
Can you provide us logs of the crash so we can look into it? Thanks

**Comment by grravity** [comment]
Looks related to this?

```
Stream mapping: Stream #0:6 -> #0:0 (h264 (h264_cuvid) -> h264 (h264_nvenc)) Stream #0:1 -> #0:1 (aac (native) -> mp3 (libmp3lame)) Press [q] to stop, [?] for help [h264_nvenc @ 000002020f744f00] [Eval @ 000000eb53dfdfa0] Undefined constant or missing '(' in 'constrainedbaseline' [h264_nvenc @ 000002020f744f00] Unable to parse option value "constrainedbaseline" [h264_nvenc @ 000002020f744f00] Error setting option profile to value constrainedbaseline. Error initializing output stream 0:0 -- Error while opening encoder for output stream #0:0 - maybe incorrect parameters such as bit_rate, rate, width or height Conversion failed!
```

**Comment by Maxr1998** [comment]
Aren't those server logs? We need logs of the crash from the device, see [here](https://wiki.lineageos.org/logcat.html) for more information.

**Comment by grravity** [comment]
@Maxr1998 Ah, I won't be able to grab those until tomorrow. Will report back.

**Comment by Bhooty** [comment]
Same here
If i play through web browser
It plays smooth
But stucks on app but sometimes play
