### ISSUE TITLE
Endless loading screen after updating

### ISSUE THREAD

**Issue by misterbit-pro** [jellyfin/jellyfin-android#159]
**Describe the bug**
After uograding from rc2 ro rc8 I get a endless loading screen 

**To Reproduce**
1. Update from rc2 to rc8
2. Open Jellyfin
3. Get endless loading screen

**Expected behavior**
<Get to main screen like in rc2

**Logs**
Where do i find the logs? Dir?

**Screenshots**
![Screenshot_20201001-070235_Jellyfin.jpg](https://user-images.githubusercontent.com/47662866/94770152-2aae6180-03b4-11eb-8b6c-b1de9fedd2e3.jpg)

**System:**
 - App version: 2.0.0-rc.8
 - Android version: Android 10
 - Device manufacturer and model: Samsung Galaxy Note 10+
 - Jellyfin server version: 10.6.4
 - The type of video player implementation used: integrated player (ExoPlayer)

**Comment by nielsvanvelzen** [comment]
Can you try clearing the app's data? There might be some breaking changes between rc2 and rc8

**Comment by misterbit-pro** [comment]
Ok, i got to the login screen, but now I get this error message, but server is available an I can connect with Kodi and from the Web without any problems, also rc2 works after reinstalling it again.

![Screenshot_20201001-194510_Jellyfin.jpg](https://user-images.githubusercontent.com/47662866/94844663-e015ff00-041e-11eb-8d4c-5253229eda75.jpg)

**Comment by misterbit-pro** [comment]
Issue #172 descriebes how to fix it
