### ISSUE TITLE
Unable to connect to server

### ISSUE THREAD

**Issue by nielsvanvelzen** [jellyfin/jellyfin-android#16]
Version: 2.0.0-rc1
Flavor: Both release and debug tested 

It's not possible to connect to a server within my Pixel 2 (API 30) emulator. I tried both my personal server and the demo server. Opening both in chrome or another app works. Logcat does not show anything.

![image](https://user-images.githubusercontent.com/2305178/90607482-8dcba680-e201-11ea-8819-6f7119221b76.png)

**Comment by nielsvanvelzen** [comment]
Same issue when trying to connect to the local ip address too (`http://192.168.1.10:8096/`), so it can't be DNS

**Comment by Maxr1998** [comment]
This is weird, it's working for me on both versions, and the demo server is fine as well. I'm doing an InetAdress reachability check, maybe that one fails on the Emulator? Do you have any special router or network configuration?

**Comment by nielsvanvelzen** [comment]
I cloned the repository and set some breakpoints, it looks like the `isReachable` function (in `InetAddress`) will always return false. I was able to "fix" the issue by removing that check. It will check if the server is reachable anyway using the `fetchServerInfo` function.

**Comment by Maxr1998** [comment]
> I cloned the repository and set some breakpoints, it looks like the `isReachable` function (in `InetAddress`) will always return false. I was able to "fix" the issue by removing that check. It will check if the server is reachable anyway using the `fetchServerInfo` function.

Ok, I thought the `isReachable` would be preferable since it's quicker than attempting a full request if it fails, but if it's broken on some devices/setups, might as well remove it.
