### ISSUE TITLE
no sound in Exoplayer

### ISSUE THREAD

**Issue by stvber** [jellyfin/jellyfin-android#160]
audio: eng TRUEHD 7.1 default/eng dolby digital 5.1

**System:**
 - App version: [2.0.0-rc.8]
 - Android version: [not given]
 - Device manufacturer and model: [not given]
 - Jellyfin server version: [10.6.4]
 - The type of video player implementation used: [ExoPlayer]

**Comment by stvber** [comment]
client:rc2.0.0-rc.8
server:10.6.4
audio:eng TRUEHD 7.1 default
          eng dolby digital 5.1

**Comment by nielsvanvelzen** [comment]
Please include the details in the issue instead of a comment and provide additional information like the mediainfo.

**Comment by stvber** [comment]
> Please include the details in the issue instead of a comment and provide additional information like the mediainfo.

EnableVideoPlaybackTranscoding: False EnableAudioPlaybackTranscoding: False

**Comment by stvber** [comment]
not support h265 hevc ?

**Comment by Maxr1998** [comment]
Is that related to the audio issue or independent? Regardless, see #28. I think the issues you're describing are related to that, so I'm closing this one as a duplicate.
