### ISSUE TITLE
Pause when Bluetooth disconnects

### ISSUE THREAD

**Issue by anthonylavado** [jellyfin/jellyfin-android#161]
As per a user review on Google Play. Currently, we support playback pausing when wired headphones are disconnected. 

The user would like to see the same behaviour when a Bluetooth audio device disconnects.

**Comment by Rijul-A** [comment]
I can look at it this weekend, if unresolved. Hopefully I should be able to add the capability to respond to media buttons from a headset (in a separate PR).
