### ISSUE TITLE
Cannot Download Multiple Items or Albums, Artists, Playlist, etc. in Music Library

### ISSUE THREAD

**Issue by DrJMKatz** [jellyfin/jellyfin-android#162]
**Describe the bug**

Selecting "Download" in the multiselect menu in a music library doesn't download selected items. No error or message, menu simply closes after selecting.

**To Reproduce**

1. Got to "Music"
2. Long press an item (i.e. Artist, Album, Playlist, etc.) to multiselect
3. Click the menu button
4. Select Download

**Expected behavior**

The selected item(s) to be download to the phone. If downloading multiple items isn't support, then the "Download" option should be removed to avoid confusion.

**System (please complete the following information):**
 - App version: 2.0.0-rc.8
 - Android version: Android 10
 - Device manufacturer and model: Essential PH-1
 - Jellyfin server version: 10.6.4
 - The type of video player implementation used: N/A

**Additional context**

If downloading multiple items, albums, artists, playlists, etc. locally isn't supported and the Download option is a misnomer, I will put in a feature request for it to actually be an option =)

**Comment by nielsvanvelzen** [comment]
Looks like this menu item is constructed [here](https://github.com/jellyfin/jellyfin-web/blob/19edc734b85896a7812f2451a2c8dd2389946671/src/components/multiSelect/multiSelect.js#L198-L204). And it seems that no callback is implemented for it, thus no download starting.

**Comment by nielsvanvelzen** [comment]
Since this issue was mentioned, I did some further digging an it appears that the menu-item was enabled in this pull request: https://github.com/jellyfin/jellyfin-web/pull/74 but a callback was never added.

**Comment by Morgan-6Freedom** [comment]
Hello. this issue is that you cannot download multiple items. But I did not find how to download a single item. Is that possible ?

**Comment by nielsvanvelzen** [comment]
Single item downloads are possible, multi-item download has been removed in 10.7 because it never communicated to the app.
