### ISSUE TITLE
Crash in ExoPlayer when server is restarted while watching

### ISSUE THREAD

**Issue by ghost** [jellyfin/jellyfin-android#164]
**Describe the bug**

Jellyfin app crashes when jellyfin server is restarted

**To Reproduce**

1. Connect to jellyfin server
2. Start playing video
3. `systemctl restart jellyfin` on server
4. "Unfortunately, Jellyfin has stopped" popup shows up on Android
5. Video stops playing; audio keeps playing

**Expected behavior**

Handle disconnection from restarted jellyfin server

**Logs**

```
--------- beginning of crash
E AndroidRuntime: FATAL EXCEPTION: main
E AndroidRuntime: Process: org.jellyfin.mobile, PID: 12513
E AndroidRuntime: org.jellyfin.apiclient.model.net.HttpException: VolleyError com.android.volley.ServerError:
E AndroidRuntime:        at h.a.b.e$b.run(ExecutorDelivery.java:22)
E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:815)
E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:104)
E AndroidRuntime:        at android.os.Looper.loop(Looper.java:207)
E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:5763)
E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
E AndroidRuntime:        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679)
E AndroidRuntime: Caused by: com.android.volley.ServerError
E AndroidRuntime:        at h.a.b.o.b.f(BasicNetwork.java:31)
E AndroidRuntime:        at h.a.b.h.a(NetworkDispatcher.java:10)
E AndroidRuntime:        at h.a.b.h.run(NetworkDispatcher.java:2)
W ActivityManager:   Force finishing activity org.jellyfin.mobile/.player.PlayerActivity
```

**Screenshots**

**System (please complete the following information):**
 - App version: 2.0.0-rc.8
 -   Android version: 5
 -   Device manufacturer and model: Samsung Galaxy S5 Neo
 -   Jellyfin server version: 10.6.0
 -   The type of video player implementation used: ExoPlayer

**Additional context**

**Comment by nielsvanvelzen** [comment]
We'll need to see what happens after we migrate to the new apiclient, not worth trying to fix right now IMO

**Comment by willymilkytron** [comment]
The same crash happens when the device temporary loses/changes network

**Comment by Maxr1998** [comment]
> We'll need to see what happens after we migrate to the new apiclient, not worth trying to fix right now IMO

This, the new api client should handle this a lot more gracefully. If not, we can always add try/catch then.

**Comment by Maxr1998** [comment]
This should be fixed by the new apiclient, anyone still observing crashes should open a new issue.
