### ISSUE TITLE
Specific TV show does not provide player controls when being cast to Chromecast

### ISSUE THREAD

**Issue by Xarano-GIT** [jellyfin/jellyfin-android#164]
Facing a strange issue, 

Casting from the app to my chromecast is normal for every piece of media I have tried, except one specific one, where the cast controls do not show up.

The show in question is Jojo's Bizarre adventure.

You can see the issue in this video
https://gfycat.com/ifr/ThisElectricAkitainu

**Comment by LeoVerto** [comment]
Does the file still play on the TV normally? What container and audio/video formats does it use?

**Comment by lewazo** [comment]
Most likely same as 
https://github.com/jellyfin/jellyfin-web/issues/440
