### ISSUE TITLE
Unable to connect to Emby

### ISSUE THREAD

**Issue by EspadaV8** [jellyfin/jellyfin-android#171]
I realise this is likely to be somewhat controversial, but after updating to the new client I am no longer able to connect to my Emby server.

I am running Emby 3.5.3.0 because I don't want to upgrade it. I also can't easily move to Jellyfin because I'm running Emby on FreeNAS (FreeBSD). When TrueNAS SCALE I plan on switching. Until then I have been using the Jellyfin client to connect to it.

I really just wanted to see if this was intended or if it should still work. I have downgraded to 1.0.2 and can connect again. When attempting to connect to the server I don't get any error message, entering an invalid IP/port and I do get a message, so it seems like it should be able to do something.

**Comment by dkanada** [comment]
It wasn't intentional, but we also don't plan on debugging any issues outside our software. My best guess is that the API client now uses a minimum server version that blocks older versions of Emby since they have a smaller version number, perhaps compiling a custom version with that change would work? This issue should probably be closed though, for the reason stated above.

**Comment by EspadaV8** [comment]
@dkanada yeah, I wasn't sure if this might also impact other, older Jellyfin servers too, since their APIs were the same.

Happy for this to be closed, I wouldn't expect Jellyfin to support Emby servers in general, and I'm fine using the 1.0.2 client until I can upgrade the server.

**Comment by dkanada** [comment]
Does FreeBSD support Docker? Our usual suggestion for NAS devices or other unsupported platforms is Docker, since it almost always exists on the target system and we provide an official image there.

**Comment by EspadaV8** [comment]
It doesn't directly support docker, no. Docker doesn't support the FreeBSD kernel (or the other way around). It can run a Linux VM and then run docker inside that, which I did for a while, but I wasn't a fan. Once TrueNAS SCALE has been released (FreeNAS on a Linux kernel) it will support docker natively and is how I was planning on running Jellyfin.

**Comment by joshuaboniface** [comment]
If you can get the .NET Core runtime running on FreeBSD (there are guides), you should be able to run the Portable release builds just fine. I unfortunately can't help much there but I believe @mcarlton00 was working on this in the past, and he might have some guidance.

**Comment by mcarlton00** [comment]
I've spent some time on getting JF running on BSD, but I haven't checked in recent months.  I've seen a few posts saying that they've gotten further in BSD support for dotnet, but I just haven't had time to revisit.  My findings at the time/test steps are recorded here if you want to experiment some: https://github.com/mcarlton00/jellyfin-bsd-testing

**Comment by EspadaV8** [comment]
Thanks @joshuaboniface and @mcarlton00 for the info. It's unlikely I'm going to be staying with the FreeBSD version once the Linux based TrueNAS is released (just more comfortable with Linux), so it's unlikely I'll dig into getting Jellyfin running in a jail.

I just wanted to make sure that the break with the API wasn't an unexpected accident. Looking forward to updating once I can run actual Jellyfin though :smile:
