### ISSUE TITLE
Unresolvable hostname crashes client

### ISSUE THREAD

**Issue by jcdick1** [jellyfin/jellyfin-android#173]
**Describe the bug**
If the saved server hostname is unresolvable, the client crashes.

**To Reproduce**
These are the steps to reproduce in my situation
1. Have a JF server with a LAN hostname that is different than the hostname that is used for remote viewing, i.e. behind a reverse proxy
2. While connected to local network, enter the LAN server hostname and log in to the server.  Home page is presented and playback is available.
3. Close client, and use app management to terminate it.
4. Switch WiFI off so that the client is connecting over cell data to force remote access.
5. Open client.  There is immediately an upside down Android logo or other crash indicator.  No option to change servers.
6. Close and terminate the client app
7. Reactivate wifi
8 Reopen app, and the home page is accessible again.
9. Use "select server" to change the hostname saved in the app to the remote access hostname.
10. Close the app
11. Turn off Wifi to trigger remote access
12. Reopen the app, and the homepage becomes accessible via the remote hostname

**Expected behavior**
Some notice of server unavailable or method to switch servers

**Logs**

**Screenshots**
![Screenshot_20201007-092257](https://user-images.githubusercontent.com/49927327/95365027-2e9c2100-0897-11eb-83e3-1c5fc69a25db.png)

**System (please complete the following information):**
 - App version: 2.0.0
 - Android version: Android 11
 - Device manufacturer and model: Google Pixel 3a
 - Jellyfin server version: 10.6.4
 - The type of video player implementation used: Exoplayer

**Comment by CarlosOlivo** [comment]
#44

**Comment by nielsvanvelzen** [comment]
Closing in favor of #44
