### ISSUE TITLE
Cast button > forever loading in new version 

### ISSUE THREAD

**Issue by zilexa** [jellyfin/jellyfin-android#176]
**Describe the bug**
Cast button > forever loading. Also with the nightly Chromecast driver, selected in App Settings.

**To Reproduce**

1. Go to Play Store, install Jellyfin (uninstalled old version first since this is a brand new app).
2. Click on cast button (after logging in to server on my local LAN).
3. See error.

**Expected behavior**
See my 2 devices in a list, to select one to cast to. 

App 2.0, Android 10, Pixel 1.

How to go back to the old app? Without casting the Android app has little use for me.

**Comment by nielsvanvelzen** [comment]
Older versions of the app are in our repository: https://repo.jellyfin.org/releases/client/android/versions/

Can you provide us logs of the app so we can help solve this issue?

**Comment by zilexa** [comment]
Sure, I looked in Settings but couldn't find an option to turn on (debug) logging. Where can I find the log file on Android? There is no Jellyfin folder in /storage or /etc/data/. There is a folder in /etc/data/apps but it doesn't contain logs.

**Comment by nielsvanvelzen** [comment]
Pplease see here for information on how to capture a logcat: https://wiki.lineageos.org/logcat.html

**Comment by zenitraM** [comment]
I have the same issue, here's my logcat:

```
10-13 12:23:32.395 26714 26714 I chromium: [INFO:CONSOLE(266)] "Requesting url without automatic networking: http://IP:8096/Sessions?ControllableByUserId=XXXX", source: http://IP:8096/web/bundle.js?v=13 (266)
10-13 12:23:32.406 26714 26714 I chromium: [INFO:CONSOLE(1)] "inputManager: tried to process command with no action assigned: unknown", source: http://IP:8096/web/scripts/inputManager.js?v=13 (1)
10-13 12:23:32.447 26714 26714 I chromium: [INFO:CONSOLE(0)] "Uncaught (in promise) #<Response>", source: http://IP:8096/web/index.html#!/home.html (0)
10-13 12:23:32.450 26714 26714 E MainActivity$initialize: Received WebView HTTP 500 error: null
10-13 12:23:32.487 26714 26714 I HwViewRootImpl: removeInvalidNode all the node in jank list is out of time
```

**Comment by Maxr1998** [comment]
> I have the same issue, here's my logcat:
> 
> ```
> 10-13 12:23:32.395 26714 26714 I chromium: [INFO:CONSOLE(266)] "Requesting url without automatic networking: http://IP:8096/Sessions?ControllableByUserId=XXXX", source: http://IP:8096/web/bundle.js?v=13 (266)
> 10-13 12:23:32.406 26714 26714 I chromium: [INFO:CONSOLE(1)] "inputManager: tried to process command with no action assigned: unknown", source: http://IP:8096/web/scripts/inputManager.js?v=13 (1)
> 10-13 12:23:32.447 26714 26714 I chromium: [INFO:CONSOLE(0)] "Uncaught (in promise) #<Response>", source: http://IP:8096/web/index.html#!/home.html (0)
> 10-13 12:23:32.450 26714 26714 E MainActivity$initialize: Received WebView HTTP 500 error: null
> 10-13 12:23:32.487 26714 26714 I HwViewRootImpl: removeInvalidNode all the node in jank list is out of time
> ```

What Jellyfin version are you on?

**Comment by zenitraM** [comment]
@Maxr1998 it seems that could have been the problem :sweat_smile:. I was on 10.6.4 but not sure if Jellyfin got properly restarted after upgrading it, restarting it fixed the issue so it's possible I might have been running an older version.

**Comment by Maxr1998** [comment]
Ah, glad that it works now.  It seems that it still served the old web client before..

**Comment by Maxr1998** [comment]
Looks like it's fixed, closing.
