### ISSUE TITLE
User installed CA no longer trusted (missing network security config)

### ISSUE THREAD

**Issue by sopidos** [jellyfin/jellyfin-android#178]
**Describe the bug**
Can not connect to server over https that use user installed CA. This works in pre-2 with 1.0.2, which had a network security config, tho I cant find that now, but the relevant part of it should be https://developer.android.com/training/articles/security-config#trust-anchors.

**To Reproduce**

1. Have a jellyfin server exposed over https with a cert issued by a custom CA
2. Install said CA on device
3. Connecting to server in app
4. Connection fails

**Expected behavior**
Connection succeeds 

**System (please complete the following information):**
 - App version: v2.0.0-rc.8
 - Android version: 10
 - Device manufacturer and model: Moto G8 plus / Lenovo Tab
 - Jellyfin server version: 10.6.4

**Comment by Maxr1998** [comment]
Thanks for the link, this should be easy to add. Gonna look at this later.

**Comment by dkanada** [comment]
@sopidos can you check if [Gelli](https://github.com/dkanada/gelli) has the same issue? I'm thinking of implementing a similar fix for that application. A check for HTTP connections would also be appreciated if you have it enabled on your server.

**Comment by sopidos** [comment]
Build of master at 7049677ec4e5a9610112691f5af3152f56dceae8, can confirm that does indeed fix it.

@dkanada Yes, it has, as it has no config either. I did test run and while I didn't check the logs, I got a generic credentials error, which it looks like it is the only error given, regardless of issue https://github.com/dkanada/gelli/blob/8eb4f515e3a717d5db04bfbe3a902282ad03c53c/app/src/main/java/com/dkanada/gramophone/ui/activities/LoginActivity.java#L92. A less generic error would probably handy, maybe just showing the exception in an alert dialog instead.
