### ISSUE TITLE
App crash when clicking on Chromecast notfication banner

### ISSUE THREAD

**Issue by ownbee** [jellyfin/jellyfin-android#183]
**Describe the bug**
App crash when clicking on e.g. "pause", or "play" on Chromecast banner when the app has lost Chromecast connection or the Android OS has suspended the Jellyfin app.

**To Reproduce**

1. Start casting a movie onto a Chromecast
2. Lock the phone and wait for maybe 30 minutes (or disconnect Wifi? Not tried this).
3. Now if the app has been suspended or randomly lost connection, click "pause" twice in the Chromecast notification banner. First time nothing happens, the second, the app crash.

**Expected behavior**
No crash, Chromecast connection should be reconnected else nothing should happen (if there is no way to reconnec).

**Logs**
I don't have any.

**Screenshots**

**System (please complete the following information):**
 - App version: v2.0.1
 - Android version: Android 9
 - Device manufacturer and model: Samsung Galaxy S8+
 - Jellyfin server version: e.g. 10.6.3
 - The type of video player implementation used: ?? Chromecast

**Comment by EchoApeiron** [comment]
Similar to the issue. I am using a Samsung S20 Verizon Edition. Whenever I use Jellyfin and leave the app open from the previous session connected to a Chrome cast instance. If I open Jellyfin at a later date it will never disconnect itself from the Chrome cast after leaving range or anything.

So when reopening the app I have to manually disconnect from the Chrome cast. No issue there except anytime I do it crashes the app. I can't find any real determination to what causes the issue or steps to recreate it exactly. 

But it's come to a point in the system manager where Jellyfin's app is being flagged for frequent crashes. If needed I can provide whatever system logs from my mobile device.

**Comment by idittansikte** [comment]
Recent app version has made this issue less frequent for me due to app not being suspended/killed equally often by android for some reason (battery optimization has always been off in my case so that is not the issue). But there are still synchronization issues between the notification banner and the app in regards to chromecast connectivity. It is basically only the "good-path"/"simplest use-case" that works.
