### ISSUE TITLE
Android App Chromecast Registration Name Duplication

### ISSUE THREAD

**Issue by sheckandar** [jellyfin/jellyfin-android#191]
**Describe the bug**
When Android client connects to Chromecast it registers itself with name Chromecast on JellyFin server. All other Chromecasts do the same. I have 3 Chromecasts and all of them register as Chromecast.

Not only it's impossible to tell which one is which, but it creates a mess in Home Assistant.

Home Assistant keeps creating new devices every time it sees a new "Chromecast" device on JelllyFin server even though these entries are the same devices. In only a span of a few days I have over a dozen entries and they never stop multiplying.

**To Reproduce**

1. Cast from device 1 to Chromecast 1.
2. Cast from device 2 to Chromecast 2.
3. JellyFin server now has 2 entries with "Chromecast" as device name.
4. Restart both Chromecasts.
5. Repeat Step 1 and 2.
6. JellyFin server now has 4 entries with "Chromecast" as device name.
7. Home Assistant now has 4 entries with previous 2 as unavailable.

**Expected behavior**

Chromecasts should register with their names (eg.. Bedroom TV, Basement TV).

**Logs**
No errors produced.

**Screenshots**

![image](https://user-images.githubusercontent.com/60163776/96219369-ea1e1e80-0f43-11eb-8577-b3ba79bf843b.png)

![image](https://user-images.githubusercontent.com/60163776/96219428-0de16480-0f44-11eb-8571-d1cf3baaf795.png)

**System (please complete the following information):**
 - App version: 2.0.1
 - Android version: Android 9
 - Device manufacturer and model: Pixel 3A
 - Jellyfin server version: 10.6.4
 - The type of video player implementation used: Chromecast

**Additional context**

Downgrading to version 1.0.2 of Android app resolves the issue.

**Comment by nielsvanvelzen** [comment]
I think this is a jellyfin-web or jellyfin-chromecast issue. What do you think @YouKnowBlom?

**Comment by YouKnowBlom** [comment]
Yeah I believe it is a combined issue between web and cc

**Comment by sheckandar** [comment]
This is still present in 10.7.0

Do I need to file this some place else ?

**Comment by sheckandar** [comment]
Is there an ETA at all ? Or a possible workaround ?

Thx.
