### ISSUE TITLE
Android mobile app can't connect to https using self-signed certs

### ISSUE THREAD

**Issue by bengalih** [jellyfin/jellyfin-android#193]
**Describe the bug**
The android mobile app will fail to connect to a server over https if that server is configured with a certificate that the android device does not have in its trusted certificate store.

This is a problem for a couple of reasons:
1) Chromecast devices won't enumerate via Chrome (web) when not accessing them over a secure site.  This means that configuring SSL on JF (either directly of via reverse proxy is recommended).
2) Once SSL is configured, most reasonable way to configure a connection would be over this interface using the public address.  This is true regardless as to how user tries to access since you don't want to have to configure multiple connections when internal vs external.
3) Obtaining a 3rd party certificate is not trivial for some users.  Creating a self-signed certificate via openssl is a 2 minute process.  Trying to work around limitation of something like LetsEncrypt could take hours, days, or might not be possible at all depending on user's network/ISP.
4) Depending on Android version, installing a trusted cert is not always trivial.

**To Reproduce**
1. Attempt to add a server to the mobile app with the https:// prefix which is using a certificate not trusted by the local android device.

**Expected behavior**
Connection!

**Logs**

**Screenshots**

**System (please complete the following information):**
 - OS: Andoid (multiple versions)
 - Browser: n/a
 - Jellyfin Version: 10.3.7
 - Reverse proxy: nginx

**Additional context**
Many android apps which connect to secure services provide the option to disregard non trusted certs and connect regardless.  It would be nice to include this feature.

**Comment by JustAMan** [comment]
@dkanada I thought you've fixed untrusted SSL certs a while ago, was it broken?

**Comment by thornbill** [comment]
We have only supported user installed certificates. https://github.com/jellyfin/jellyfin-android/blob/master/res/android/xml/network_security_config.xml#L6

Trusting any certificate seems like a really bad idea. Cordova explicitly [recommends against this](https://cordova.apache.org/docs/en/latest/guide/appdev/security/#self-signed-certificates).

If you are unable to install the self-signed certificate on Android or get a certificate signed by a trusted CA, then perhaps you should stick to using http. You should be able to configure the server or reverse proxy to allow both http and https connections.

**Comment by sparky8251** [comment]
You can install your own CA to android and generate a cert from it. If you do this, it will be trusted and work fine.

Android won't like you installing a CA, it warns that someone might be snooping on your communications but it *will* work.

This is to be expected on locked down platforms like TV, Roku, Android, iOS, etc.

I agree with @thornbill, we should not attempt to bypass this "protection" by default even if we disagree with its reasoning. This would be a horrible hack and we don't want those in the code base.

**Comment by JustAMan** [comment]
@bengalih could you please report if you're seeing a dialog as was added in #73 about `Untrusted Certificate`, as that PR was supposed to address your problem way before now, but no one confirmed if it worked or not.

**Comment by thornbill** [comment]
It seems my original comment was inaccurate. We did attempt to support prompting to accept self-signed certificates (https://github.com/jellyfin/jellyfin-android/blob/master/src/NativeShell/src/CustomWebViewClient.java). Thanks @JustAMan for pointing this out.

However based on this issue and my testing (in Android 5.1, 6, and 10), it seems that approach does not work. A self-signed certificate prompts a connection error and the user is not prompted to proceed. Researching this issue leads me to believe that this is not possible to accomplish in Cordova without modifying the Cordova Android platform code. This would be a bad practice and would be difficult for us to maintain in the future.

It may be worth noting that the other apps behave in the same way. The jellyfin-androidtv and jellyfin-expo (iOS) apps also return errors when attempting to connect with a self-signed certificate.

We are limited here by what the mobile platforms and development frameworks we are using support. Unless support for this is added to the underlying framework (Cordova) it seems this feature is not possible to add.

Supported options would be to:
1. use a certificate from a trusted CA.
2. install the self-signed certificate on the device.
3. configure the server or reverse proxy to allow both http and https and use http in the app.

**Comment by bengalih** [comment]
> Trusting any certificate seems like a really bad idea. Cordova explicitly [recommends against this](https://cordova.apache.org/docs/en/latest/guide/appdev/security/#self-signed-certificates).

100% disagree.  To trust a certificate or not should ultimately be in the hands of the user, not the underlying application framework.

> We are limited here by what the mobile platforms and development frameworks we are using support. Unless support for this is added to the underlying framework (Cordova) it seems this feature is not possible to add.

Understood.  While I disagree if Apache has chosen to take this ability away in their underlying code, I certainly understand that it could be a large undertaking to code in this type of functionality.
However, would it at least be possible to properly document and possible show a proper error?

When I tried to connect to the server using the app with an untrusted cert it simply wouldn't connect.  No error dialog, etc.  For now, this bug report appears to be the sole way to know this would be an issue.

FWIW, I have been using self-signed certificates for years.  I have secured all my internal app servers with them (plex, JF, sonarr, cp, sab, deluge, etc, etc).  While the configuration has not always been well documented, I have functioned with all of them.  This includes mobile apps that support these applications.

In general, I have tried to install my CA on my android device (or laptop, etc).  However - especially due to the difficult nature of installing custom root CA on old versions of Android, there were times (especially after reloading a new ROM on my device) where I would not have the certificate installed.
In these cases I would occasionally have an issue with a mobile app not connecting until I went in and enabled the available option to allow untrusted certs.

I realize the lack of security of certain configurations, but the pushback against being able to use-self signed certs (and JF's issues with SSL in general) has caused me to invest probably 10 hours in configuration changes to what has worked for years for other apps that provide similar functions.

TBH, I'm not complaining as I wasn't running a reverse proxy before and now I'm kind of digging it, but I wanted to give you some insight from the user perspective.  I consider myself (conservatively) in the top 25% of users from a technical perspective, and really just had/have a hell of a time setting up this product to work right/logically/similar to every other client/server home media/automation app I've configured in the past.

So, again, that's just a bit of feedback and maybe I'm really in the minority here, but I wish you guys luck making JF the best you can and I hate to see more widespread adoption hindered by these types of things.

thanks for your efforts.

**Comment by veerendra2** [comment]
Any workaround anyone? I'm trying to run Jellyfin behind nginx reverse proxy with sub-path and self-signed certs (at nginx). I followed [this](https://gist.github.com/fntlnz/cf14feb5a46b2eda428e000157447309) and [here](https://docs.ansible.com/ansible/latest/collections/community/crypto/docsite/guide_ownca.html) to generate certs and installed root CA cert in my Android 12 phone. But no luck!

**Comment by bengalih** [comment]
> Any workaround anyone? I'm trying to run Jellyfin behind nginx reverse proxy with sub-path and self-signed certs (at nginx). I followed [this](https://gist.github.com/fntlnz/cf14feb5a46b2eda428e000157447309) and [here](https://docs.ansible.com/ansible/latest/collections/community/crypto/docsite/guide_ownca.html) to generate certs and installed root CA cert in my Android 12 phone. But no luck!

Fairly certain if you read through this thread and the linked ones the final consensus was that self-signed won't work.  I believe there was belief they would if the self-signed was installed in the root store, but skimming through again it doesn't appear that was ever validated.  As the OP, I certainly didn't have any success with it.

My solution was to abandoned self-signed certs.  There are very few cases where you can't use LE or another free provider to generate scripts on or offline.  Yes, it is a bit more work initially, but moving forward you are likely to have fewer problems all around.  I uprooted my entire infrastructure of hosted services from self-signed to LE certs and am happy I took the time.

good luck

**Comment by veerendra2** [comment]
@bengalih Thanks the comment, let's hope we will get any workaround. Until then I decided to allow HTTP as well for jellyfin service at my nginx reverse proxy.
