### ISSUE TITLE
Playback progress tracking on external player

### ISSUE THREAD

**Issue by Altereno** [jellyfin/jellyfin-android#195]
Not sure if this is already a post but when playing a video using the external player (VLC) error pops up after closing the stream. (No valid external player selected. Playback tracking disabled)

**Comment by CarlosOlivo** [comment]
I assume that then you can play multimedia correctly.  Could you share the following data?

- Your Android Versión
- Application ID / Package Name of VLC
- Version of VLC Installed

**Comment by Altereno** [comment]
> I assume that then you can play multimedia correctly.  Could you share the following data?
> 
> - Your Android Versión
> - Application ID / Package Name of VLC
> - Version of VLC Installed
> 
> Also can you try with [MX Player](https://play.google.com/store/apps/details?id=com.mxtech.videoplayer.ad) to see if the same happens?

Android 10, on the Tab s5e
Not sure on the package name, can you point me towards where to find it?
VLC version 3.3.1

Worked fine on MX player.

**Comment by CarlosOlivo** [comment]
> Not sure on the package name, can you point me towards where to find it?

See [here](https://www.techmesto.com/find-android-app-package-name/). I'm not sure if is the same as the mobile versión.

**Comment by Altereno** [comment]
> > Not sure on the package name, can you point me towards where to find it?
> 
> See [here](https://www.techmesto.com/find-android-app-package-name/). I'm not sure if is the same as the mobile versión.

Thanks for the info, not sure if it notifies people when I edit my response so I'll just reply.

org.videolan.vlc

**Comment by CarlosOlivo** [comment]
> Thanks for the info, not sure if it notifies people when I edit my response so I'll just reply.

Yep, they do

> org.videolan.vlc

Ok, is the same for mobile & tablet

Can you try this?, download [jellyfin-android.zip](https://dev.azure.com/jellyfin-project/7cce6c46-d610-45e3-9fb7-65a6bfd1b671/_apis/build/builds/16562/artifacts?artifactName=jellyfin-android&api-version=6.0&%24format=zip), extract and try to install `jellyfin-android-v0.0.0-dev.1-debug.apk` then
- Login
- Go to client settings
- Choose `External Player` for `Video Player Type`
- Choose `VLC Player` for `External player app`

See if there is any improvement

![Screenshot_20201018-204354_Jellyfin_Debug](https://user-images.githubusercontent.com/25919231/96392765-afee9000-1182-11eb-8401-a0a619042a2e.png)

**Comment by Altereno** [comment]
> > Thanks for the info, not sure if it notifies people when I edit my response so I'll just reply.
> 
> Yep, they do
> 
> > org.videolan.vlc
> 
> Ok, is the same for mobile & tablet
> 
> Can you try this?, download [jellyfin-android.zip](https://dev.azure.com/jellyfin-project/7cce6c46-d610-45e3-9fb7-65a6bfd1b671/_apis/build/builds/16562/artifacts?artifactName=jellyfin-android&api-version=6.0&%24format=zip), extract and try to install `jellyfin-android-v0.0.0-dev.1-debug.apk` then
> - Login
> - Go to client settings
> - Choose `External Player` for `Video Player Type`
> - Choose `VLC Player` for `External player app`
> 
> See if there is any improvement
> 
> ![Screenshot_20201018-204354_Jellyfin_Debug](https://user-images.githubusercontent.com/25919231/96392765-afee9000-1182-11eb-8401-a0a619042a2e.png)
> 

The option to choose which external player is not there for me. It played the video through VLC though. Still says that playback tracking is disabled.

**Comment by CarlosOlivo** [comment]
> The option to choose which external player is not there for me.

Sorry, wrong link, try [this](https://dev.azure.com/jellyfin-project/7cce6c46-d610-45e3-9fb7-65a6bfd1b671/_apis/build/builds/16537/artifacts?artifactName=jellyfin-android&api-version=6.0&%24format=zip).

**Comment by Altereno** [comment]
> > The option to choose which external player is not there for me.
> 
> Sorry, wrong link, try [this](https://dev.azure.com/jellyfin-project/7cce6c46-d610-45e3-9fb7-65a6bfd1b671/_apis/build/builds/16537/artifacts?artifactName=jellyfin-android&api-version=6.0&%24format=zip).
That worked, when do these small get released(on the play store or github)?

**Comment by CarlosOlivo** [comment]
> when do these small get released

No ETA, soon™, maybe...

**Comment by Ferk** [comment]
Maybe this should be discussed with the VLC team at https://code.videolan.org/videolan/vlc-android/-/issues ?

If VLC is behaving in a non-standard way for the video player to play nicely with other android apps when using it via Intents I'd say it's something that VLC itself could benefit from fixing on their side.

Both for the Playback Tracking and the Subtitles (do the subtitles also work in MX Player?). It would be a pitty to not have proper support for a fully open source external player like VLC. And it has features that both the web and exo players are missing (like modifying the playback speed)

**Comment by CarlosOlivo** [comment]
Note: `libVLC` != `VLC Android Port`

> Maybe this should be discussed with the VLC team at https://code.videolan.org/videolan/vlc-android/-/issues ?

Unfortunately the VLC (Android) team decided that the MX Player API is "half insane". But they haven't fixed/improved their API either.

https://trac.videolan.org/vlc/ticket/17133
https://trac.videolan.org/vlc/ticket/14705
https://trac.videolan.org/vlc/ticket/18736

And I don't really like the attitude they take, but you can try discuss with them if you want.

https://code.videolan.org/videolan/vlc-android/-/issues/502

> If VLC is behaving in a non-standard way for the video player to play nicely with other android apps on some devices when using it via Intents I'd say it's something that VLC itself could benefit from fixing on their side.

(Un)fortunately in Android there is no such standard, so the implementation depends on each player.

- [MX Player](https://mx.j2inter.com/api)
- [VLC Android](https://wiki.videolan.org/Android_Player_Intents/)

> Both for the Playback Tracking and the Subtitles (do the subtitles also work in MX Player?).

Yep

> It would be a pitty to not have proper support for a fully open source external player like VLC.

[mpv-android](https://github.com/mpv-android/mpv-android) is supported.

**Comment by Doc-4** [comment]
This problem still exists between current releases of VLC and Jellyfin Android. It also seems to exist between VLC and other 3rd party clients, so it seems to be some kind of VLC 
android problem.
