### ISSUE TITLE
Exoplayer causes transcoding LiveTV to Fail. Suspect: constrainedbaseline 

### ISSUE THREAD

**Issue by Artiume** [jellyfin/jellyfin-android#202]
Using the exoplayer, livetv that requires transcoding will fail but will work with webviewer...

Diffing the two requests, I get

Successful
```
&TranscodingMaxAudioChannels=2
&h264-profile=high,main,baseline,constrainedbaseline
h264-level=41
```

Unsuccessful
```
&h264-profile=constrainedbaseline,baseline,main,constrainedhigh,high
h264-level=52
```

Of the ffmpeg commands

successful
```
-profile:v high -level 4.1
```
Unsuccessful
```
-profile:v constrainedbaseline -level 4.1
```

Substituting another ffmpeg command that used high with constrainedbaseline, it failed on me. So I suspect constrainedbaseline is broken.

<details>
<summary>WebViewer, Successful transcoding</summary>
http://domain/videos/d70ec592-246b-dacb-334e-e9463c906346/live.m3u8?DeviceId=02dda0886e28525b&MediaSourceId=707aeffdac47a593417673aad6ec4aee&VideoCodec=h264&AudioCodec=mp3,aac,opus&AudioStreamIndex=-1&VideoBitrate=1107962&AudioBitrate=131250&PlaySessionId=e793cc0da05b450699015283d04ec8cb&api_key=zzz&LiveStreamId=a17c75760a04e99b68cf766e11316e1c_09efa0d56b934a82adec00a87b837fb0_707aeffdac47a593417673aad6ec4aee&TranscodingMaxAudioChannels=2&RequireAvc=false&SegmentContainer=ts&MinSegments=1&BreakOnNonKeyFrames=False&h264-profile=high,main,baseline,constrainedbaseline&h264-level=41&TranscodeReasons=ContainerNotSupported,VideoCodecNotSupported,AudioCodecNotSupported

{"Protocol":"Http","Id":"707aeffdac47a593417673aad6ec4aee","Path":"http://127.0.0.1:8096/LiveTv/LiveStreamFiles/c0a0db9cbdfe4b61a92cb05ae820f4fc/stream.ts","Type":"Default","Container":"mpegts","IsRemote":true,"ReadAtNativeFramerate":false,"IgnoreDts":true,"IgnoreIndex":false,"GenPtsInput":false,"SupportsTranscoding":true,"SupportsDirectStream":true,"SupportsDirectPlay":false,"IsInfiniteStream":true,"RequiresOpening":true,"RequiresClosing":true,"LiveStreamId":"a17c75760a04e99b68cf766e11316e1c_09efa0d56b934a82adec00a87b837fb0_707aeffdac47a593417673aad6ec4aee","RequiresLooping":false,"SupportsProbing":true,"MediaStreams":[{"Codec":"h264","TimeBase":"1/90000","CodecTimeBase":"1001/60000","VideoRange":"SDR","DisplayTitle":"720p H264","NalLengthSize":"0","IsInterlaced":false,"BitRate":8000000,"BitDepth":8,"RefFrames":1,"IsDefault":false,"IsForced":false,"Height":720,"Width":1280,"AverageFrameRate":29.97003,"RealFrameRate":29.97003,"Profile":"Main","Type":"Video","AspectRatio":"16:9","Index":-1,"IsExternal":false,"IsTextSubtitleStream":false,"SupportsExternalStream":false,"PixelFormat":"yuv420p","Level":32,"IsAnamorphic":false},{"Codec":"aac","TimeBase":"1/90000","CodecTimeBase":"1/48000","DisplayTitle":"AAC stereo","IsInterlaced":false,"ChannelLayout":"stereo","BitRate":131250,"Channels":2,"SampleRate":48000,"IsDefault":false,"IsForced":false,"Profile":"LC","Type":"Audio","Index":-1,"IsExternal":false,"IsTextSubtitleStream":false,"SupportsExternalStream":false,"Level":0}],"MediaAttachments":[],"Formats":[],"Bitrate":8131250,"RequiredHttpHeaders":{"User-Agent":"Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:47.0) Gecko/20100101 Firefox/47.0"},"AnalyzeDurationMs":3000}

/usr/lib/jellyfin-ffmpeg/ffmpeg -analyzeduration 3000000 -user_agent "Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:47.0) Gecko/20100101 Firefox/47.0" -fflags +igndts -f mpegts -i "http://127.0.0.1:8096/LiveTv/LiveStreamFiles/c0a0db9cbdfe4b61a92cb05ae820f4fc/stream.ts" -map_metadata -1 -map_chapters -1 -threads 0 -sn -codec:v:0 libx264 -pix_fmt yuv420p -preset veryfast -crf 23 -maxrate 1107962 -bufsize 2215924 -profile:v high -level 4.1 -x264opts:0 subme=0:me_range=4:rc_lookahead=10:me=dia:no_chroma_me:8x8dct=0:partitions=none -force_key_frames "expr:gte(t,n_forced*3)" -vf "scale=trunc(min(max(iw\,ih*dar)\,720)/2)*2:trunc(ow/dar/2)*2" -flags -global_header -vsync cfr -codec:a:0 libmp3lame -ac 2 -ab 131250  -f segment -max_delay 5000000 -avoid_negative_ts disabled -start_at_zero -segment_time 3  -individual_header_trailer 0 -segment_format mpegts -segment_list_entry_prefix "hls/cae44968d398f6bcdef2032e3c51f5f5/" -segment_list_type m3u8 -segment_start_number 0 -segment_list "/transcode/cae44968d398f6bcdef2032e3c51f5f5.m3u8" -y "/transcode/cae44968d398f6bcdef2032e3c51f5f5%d.ts"

ffmpeg version 4.3.1 Copyright (c) 2000-2020 the FFmpeg developers
  built with gcc 8 (Debian 8.3.0-6)
  configuration: --prefix=/usr/lib/jellyfin-ffmpeg --target-os=linux --disable-doc --disable-ffplay --disable-shared --disable-libxcb --disable-sdl2 --disable-xlib --enable-gpl --enable-version3 --enable-static --enable-libfontconfig --enable-fontconfig --enable-gmp --enable-gnutls --enable-libass --enable-libbluray --enable-libdrm --enable-libfreetype --enable-libfribidi --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libwebp --enable-libx264 --enable-libx265 --enable-libzvbi --arch=amd64 --enable-libzimg --enable-opencl --enable-vaapi --enable-amf --enable-libmfx --enable-vdpau --enable-cuda --enable-cuda-llvm --enable-cuvid --enable-nvenc --enable-nvdec --enable-ffnvcodec --enable-libdav1d
  libavutil      56. 51.100 / 56. 51.100
  libavcodec     58. 91.100 / 58. 91.100
  libavformat    58. 45.100 / 58. 45.100
  libavdevice    58. 10.100 / 58. 10.100
  libavfilter     7. 85.100 /  7. 85.100
  libswscale      5.  7.100 /  5.  7.100
  libswresample   3.  7.100 /  3.  7.100
  libpostproc    55.  7.100 / 55.  7.100
Input #0, mpegts, from 'http://127.0.0.1:8096/LiveTv/LiveStreamFiles/c0a0db9cbdfe4b61a92cb05ae820f4fc/stream.ts':
  Duration: N/A, start: 54700.884922, bitrate: N/A
  Program 1 
    Metadata:
      service_name    : Service01
      service_provider: FFmpeg
    Stream #0:0[0x100]: Video: h264 (Main) ([27][0][0][0] / 0x001B), yuv420p(progressive), 1280x720 [SAR 1:1 DAR 16:9], Closed Captions, 29.97 fps, 29.97 tbr, 90k tbn, 59.94 tbc
    Stream #0:1[0x101]: Audio: aac (LC) ([15][0][0][0] / 0x000F), 48000 Hz, stereo, fltp, 131 kb/s
Stream mapping:
  Stream #0:0 -> #0:0 (h264 (native) -> h264 (libx264))
  Stream #0:1 -> #0:1 (aac (native) -> mp3 (libmp3lame))
Press [q] to stop, [?] for help
[libx264 @ 0x55eae8367140] using SAR=404/405
[libx264 @ 0x55eae8367140] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX FMA3 BMI2 AVX2
[libx264 @ 0x55eae8367140] profile Main, level 4.1
[segment @ 0x55eae8369540] Opening '/transcode/cae44968d398f6bcdef2032e3c51f5f50.ts' for writing
Output #0, segment, to '/transcode/cae44968d398f6bcdef2032e3c51f5f5%d.ts':
  Metadata:
    encoder         : Lavf58.45.100
    Stream #0:0: Video: h264 (libx264), yuv420p, 720x404 [SAR 404:405 DAR 16:9], q=-1--1, 29.97 fps, 90k tbn, 29.97 tbc
    Metadata:
      encoder         : Lavc58.91.100 libx264
    Side data:
      cpb: bitrate max/min/avg: 1107000/0/0 buffer size: 2215000 vbv_delay: N/A
    Stream #0:1: Audio: mp3 (libmp3lame), 48000 Hz, stereo, fltp, 131 kb/s
    Metadata:
      encoder         : Lavc58.91.100 libmp3lame
frame=   52 fps=0.0 q=29.0 size=N/A time=00:00:01.77 bitrate=N/A speed=3.52x    
[segment @ 0x55eae8369540] Opening '/transcode/cae44968d398f6bcdef2032e3c51f5f5.m3u8.tmp' for writing
[segment @ 0x55eae8369540] Opening '/transcode/cae44968d398f6bcdef2032e3c51f5f51.ts' for writing
frame=  112 fps=111 q=29.0 size=N/A time=00:00:03.67 bitrate=N/A speed=3.65x    
frame=  166 fps=110 q=29.0 size=N/A time=00:00:05.52 bitrate=N/A speed=3.66x    
[segment @ 0x55eae8369540] Opening '/transcode/cae44968d398f6bcdef2032e3c51f5f5.m3u8.tmp' for writing
[segment @ 0x55eae8369540] Opening '/transcode/cae44968d398f6bcdef2032e3c51f5f52.ts' for writing
frame=  219 fps=109 q=29.0 size=N/A time=00:00:07.24 bitrate=N/A speed= 3.6x    
frame=  281 fps=112 q=29.0 size=N/A time=00:00:09.28 bitrate=N/A speed=3.69x    
[segment @ 0x55eae8369540] Opening '/transcode/cae44968d398f6bcdef2032e3c51f5f5.m3u8.tmp' for writing
[segment @ 0x55eae8369540] Opening '/transcode/cae44968d398f6bcdef2032e3c51f5f53.ts' for writing
frame=  349 fps=116 q=29.0 size=N/A time=00:00:11.61 bitrate=N/A speed=3.85x   
</details>

<details>
<summary>ExoPlayer, transcoding Fails</summary>

```
http://domain/videos/d70ec592-246b-dacb-334e-e9463c906346/live.m3u8?DeviceId=02dda0886e28525b&MediaSourceId=707aeffdac47a593417673aad6ec4aee&VideoCodec=h264&AudioCodec=mp3,aac,ac3&AudioStreamIndex=-1&VideoBitrate=1107962&AudioBitrate=131250&PlaySessionId=ba45b17d56a446169a91660a77e84557&api_key=zzz&LiveStreamId=a17c75760a04e99b68cf766e11316e1c_09efa0d56b934a82adec00a87b837fb0_707aeffdac47a593417673aad6ec4aee&RequireAvc=false&SegmentContainer=ts&MinSegments=1&BreakOnNonKeyFrames=False&h264-profile=constrainedbaseline,baseline,main,constrainedhigh,high&h264-level=52&TranscodeReasons=ContainerNotSupported,VideoCodecNotSupported,AudioCodecNotSupported

{"Protocol":"Http","Id":"707aeffdac47a593417673aad6ec4aee","Path":"http://127.0.0.1:8096/LiveTv/LiveStreamFiles/c7cecca54c384dbe8270629c607dac75/stream.ts","Type":"Default","Container":"mpegts","IsRemote":true,"ReadAtNativeFramerate":false,"IgnoreDts":true,"IgnoreIndex":false,"GenPtsInput":false,"SupportsTranscoding":true,"SupportsDirectStream":true,"SupportsDirectPlay":false,"IsInfiniteStream":true,"RequiresOpening":true,"RequiresClosing":true,"LiveStreamId":"a17c75760a04e99b68cf766e11316e1c_09efa0d56b934a82adec00a87b837fb0_707aeffdac47a593417673aad6ec4aee","RequiresLooping":false,"SupportsProbing":true,"MediaStreams":[{"Codec":"h264","TimeBase":"1/90000","CodecTimeBase":"1001/60000","VideoRange":"SDR","DisplayTitle":"720p H264","NalLengthSize":"0","IsInterlaced":false,"BitRate":8000000,"BitDepth":8,"RefFrames":1,"IsDefault":false,"IsForced":false,"Height":720,"Width":1280,"AverageFrameRate":29.97003,"RealFrameRate":29.97003,"Profile":"Main","Type":"Video","AspectRatio":"16:9","Index":-1,"IsExternal":false,"IsTextSubtitleStream":false,"SupportsExternalStream":false,"PixelFormat":"yuv420p","Level":32,"IsAnamorphic":false},{"Codec":"aac","TimeBase":"1/90000","CodecTimeBase":"1/48000","DisplayTitle":"AAC stereo","IsInterlaced":false,"ChannelLayout":"stereo","BitRate":131250,"Channels":2,"SampleRate":48000,"IsDefault":false,"IsForced":false,"Profile":"LC","Type":"Audio","Index":-1,"IsExternal":false,"IsTextSubtitleStream":false,"SupportsExternalStream":false,"Level":0}],"MediaAttachments":[],"Formats":[],"Bitrate":8131250,"RequiredHttpHeaders":{"User-Agent":"Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:47.0) Gecko/20100101 Firefox/47.0"},"AnalyzeDurationMs":3000}

/usr/lib/jellyfin-ffmpeg/ffmpeg -analyzeduration 3000000 -user_agent "Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:47.0) Gecko/20100101 Firefox/47.0" -fflags +igndts -f mpegts -i "http://127.0.0.1:8096/LiveTv/LiveStreamFiles/c7cecca54c384dbe8270629c607dac75/stream.ts" -map_metadata -1 -map_chapters -1 -threads 0 -sn -codec:v:0 libx264 -pix_fmt yuv420p -preset veryfast -crf 23 -maxrate 1107962 -bufsize 2215924 -profile:v constrainedbaseline -level 4.1 -x264opts:0 subme=0:me_range=4:rc_lookahead=10:me=dia:no_chroma_me:8x8dct=0:partitions=none -force_key_frames "expr:gte(t,n_forced*3)" -vf "scale=trunc(min(max(iw\,ih*dar)\,720)/2)*2:trunc(ow/dar/2)*2" -flags -global_header -vsync cfr -codec:a:0 libmp3lame -ac 2 -ab 131250  -f segment -max_delay 5000000 -avoid_negative_ts disabled -start_at_zero -segment_time 3  -individual_header_trailer 0 -segment_format mpegts -segment_list_entry_prefix "hls/aef89ad4963a46ff5e598d495081d3b0/" -segment_list_type m3u8 -segment_start_number 0 -segment_list "/transcode/aef89ad4963a46ff5e598d495081d3b0.m3u8" -y "/transcode/aef89ad4963a46ff5e598d495081d3b0%d.ts"


ffmpeg version 4.3.1 Copyright (c) 2000-2020 the FFmpeg developers
  built with gcc 8 (Debian 8.3.0-6)
  configuration: --prefix=/usr/lib/jellyfin-ffmpeg --target-os=linux --disable-doc --disable-ffplay --disable-shared --disable-libxcb --disable-sdl2 --disable-xlib --enable-gpl --enable-version3 --enable-static --enable-libfontconfig --enable-fontconfig --enable-gmp --enable-gnutls --enable-libass --enable-libbluray --enable-libdrm --enable-libfreetype --enable-libfribidi --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libwebp --enable-libx264 --enable-libx265 --enable-libzvbi --arch=amd64 --enable-libzimg --enable-opencl --enable-vaapi --enable-amf --enable-libmfx --enable-vdpau --enable-cuda --enable-cuda-llvm --enable-cuvid --enable-nvenc --enable-nvdec --enable-ffnvcodec --enable-libdav1d
  libavutil      56. 51.100 / 56. 51.100
  libavcodec     58. 91.100 / 58. 91.100
  libavformat    58. 45.100 / 58. 45.100
  libavdevice    58. 10.100 / 58. 10.100
  libavfilter     7. 85.100 /  7. 85.100
  libswscale      5.  7.100 /  5.  7.100
  libswresample   3.  7.100 /  3.  7.100
  libpostproc    55.  7.100 / 55.  7.100
[h264 @ 0x5561656b45c0] sps_id 0 out of range
[h264 @ 0x5561656b45c0] non-existing PPS 0 referenced
[h264 @ 0x5561656b45c0] sps_id 0 out of range
[h264 @ 0x5561656b45c0] non-existing PPS 0 referenced
[h264 @ 0x5561656b45c0] decode_slice_header error
[h264 @ 0x5561656b45c0] no frame!
[h264 @ 0x5561656b45c0] sps_id 0 out of range
[h264 @ 0x5561656b45c0] non-existing PPS 0 referenced
[h264 @ 0x5561656b45c0] sps_id 0 out of range
[h264 @ 0x5561656b45c0] non-existing PPS 0 referenced
[h264 @ 0x5561656b45c0] decode_slice_header error
[h264 @ 0x5561656b45c0] no frame!
[h264 @ 0x5561656b45c0] sps_id 0 out of range
[h264 @ 0x5561656b45c0] non-existing PPS 0 referenced
[h264 @ 0x5561656b45c0] sps_id 0 out of range
[h264 @ 0x5561656b45c0] non-existing PPS 0 referenced
[h264 @ 0x5561656b45c0] decode_slice_header error
[h264 @ 0x5561656b45c0] no frame!

Failed attempts truncated.

Input #0, mpegts, from 'http://127.0.0.1:8096/LiveTv/LiveStreamFiles/c7cecca54c384dbe8270629c607dac75/stream.ts':
  Duration: N/A, start: 54656.959589, bitrate: N/A
  Program 1 
    Metadata:
      service_name    : Service01
      service_provider: FFmpeg
    Stream #0:0[0x100]: Video: h264 (Main) ([27][0][0][0] / 0x001B), yuv420p(progressive), 1280x720 [SAR 1:1 DAR 16:9], Closed Captions, 29.97 fps, 29.97 tbr, 90k tbn, 59.94 tbc
    Stream #0:1[0x101]: Audio: aac (LC) ([15][0][0][0] / 0x000F), 48000 Hz, stereo, fltp, 127 kb/s
Stream mapping:
  Stream #0:0 -> #0:0 (h264 (native) -> h264 (libx264))
  Stream #0:1 -> #0:1 (aac (native) -> mp3 (libmp3lame))
Press [q] to stop, [?] for help
[h264 @ 0x5561658064c0] co located POCs unavailable
[h264 @ 0x556165809c40] co located POCs unavailable
x264 [error]: invalid profile: constrainedbaseline
[libx264 @ 0x5561656ed940] Error setting profile constrainedbaseline.
[libx264 @ 0x5561656ed940] Possible profiles: baseline main high high10 high422 high444
Error initializing output stream 0:0 -- Error while opening encoder for output stream #0:0 - maybe incorrect parameters such as bit_rate, rate, width or height
[libmp3lame @ 0x5561656ef780] 4 frames left in the queue on closing
Conversion failed!
```

</details>

**Comment by Artiume** [comment]
There's no such profile as constrainedbaseline. It is part of the baseline bitmap with constraints set. I believe this is an encodinghelper.cs in backend issue, not an exo issue.

https://stackoverflow.com/questions/23494168/h264-profile-iop-explained

**Comment by Maxr1998** [comment]
Upstream issue is fixed, thus should be working now. Closing.
