### ISSUE TITLE
Server Conection dialog

### ISSUE THREAD

**Issue by jakobroehrl** [jellyfin/jellyfin-android#203]
Please update the description from: 192.168.1.100 or https://myserver.com
to: 192.168.1.100:8096 or https://myserver.com:myportnumber

I tried the IP a lot until I found out only IP:port is working

**Comment by thornbill** [comment]
This has been updated in jellyfin-web and should be corrected in the app in the next update https://github.com/jellyfin/jellyfin-web/blob/bcb13acccdd82576761fb11cbe7313961e48cd51/src/strings/en-us.json#L814
