### ISSUE TITLE
Image viewer when building with cordova

### ISSUE THREAD

**Issue by HugoPourrierNunez** [jellyfin/jellyfin-android#207]
Hi, I would like to work on this project and I to begin I start by setting up my environnement and compile the project to run the apk on an emulater (I'm on Windows).
Everything works fine, I have execute all the command from the readme but after login into my server I notice that I can't view a picture. I see my personal photo albums and all folders, I can play my videos but when I click on a picture to see it in big it doesn't work. I've linked a screenshot : 
![Image viewer pb jellyfin](https://user-images.githubusercontent.com/10737991/66229724-c3979780-e6e2-11e9-8a6a-d057bdd84604.JPG)

This error happends both in the emulator and on my phone. I tried to checkout the tag v0.9.4  but the result is the same. When I download the same version of jellyfin from the playstore everything works right. Am I missing something ? 
Thanks in advance

**Comment by JustAMan** [comment]
cc @dkanada

**Comment by dkanada** [comment]
@HugoPourrierNunez this issue should be fixed in the latest version but please let us know if you still have any issues.
