### ISSUE TITLE
Companion issues with custom UI idea

### ISSUE THREAD

**Issue by Essasetic** [jellyfin/jellyfin-android#21]
I'm just going to directly quote Sparky8251 here: "Being able to set a theme for each app would just require each app to be able to handle themeing. The web UI already can (how extensive I'm unsure) and that's the only one in this repo."

**Comment by JustAMan** [comment]
Please leave a link at parent issue in main repo.

**Comment by Essasetic** [comment]
https://github.com/jellyfin/jellyfin/issues/292

**Comment by thornbill** [comment]
I’m closing this since the app will now support custom css added to the server
