### ISSUE TITLE
Client settings for emby server

### ISSUE THREAD

**Issue by xp-1000** [jellyfin/jellyfin-android#211]
**Describe the feature you'd like**
Make available the "client settings" option on emby server in addition to jellyfin.

**Additional context**
In my understanding, some options from jellyfin client could be usable to emby server but are just not available to configure. For example, the exiting exoplayer feature should also work on emby server but while client settings is not available on this we cannot enable it.
I still manage emby server in addition to jellyfin and I use only the jellyfin android client app for both because it still works on emby for now.

If the emby compatibility is not possible or simply not a goal I understand.

**Comment by nielsvanvelzen** [comment]
We do not support the proprietary Emby server, ask their own developers to improve their apps if you want a function we provide.

**Comment by xp-1000** [comment]
just to be accurate for others: jellyfin android app (as for almost every emby/jellyfin clients) work fine with emby server.

so in fact you are currently supporting emby server but I understand it is not a goal.

**Comment by nielsvanvelzen** [comment]
No we do not support Emby server. If it works for you: great.

**Comment by joshuaboniface** [comment]
To further clarify our position:

Our fork was a hostile one, by Emby's choice. Over the past ~2 years, our policy was to not intentionally break API compatibility, but as we move throughout the code to improve things, we can make no guarantees that our API will remain compatible with Emby Server. As you're seeing they're starting to diverge. And of course, our clients will follow our version of the API, not Emby's, and we will not expend any amount of effort to keep our clients compatible with Emby Server. As Niels says, if it works for you: great. If things do not work, we will not support them and recommend contacting Emby to request the functionality you want from them.

**Comment by xp-1000** [comment]
Thanks for clarification, I already assumed this, my initial question was innocent this is why I finished by:

> If the emby compatibility is not possible or simply not a goal I understand.

Never I would suggest to do the extra work to maintain compatibility in long term with emby.

But while your app (jellyfin client) is currently compatible with emby server may be it could have been possible to make the "jellyfin specificities" like exoplayer available for emby server too without extra work.

The day when emby will break compatibility (their fault, not yours) so your app will not work at all and so "client settings" option availability will not be useful anymore (and this issue too).

I am pretty sure this day will come but waiting for this I would prefer to keep only one client (jellyfin here) for my multiple servers (emby and jellyfin).

I would prefer to got an answer about the technical ability to make available this setting in every cases instead of "the general will of the project" (what I understand) to eventually propose a PR if it seems possible but my question was most likely either clumsy or simply not relevant.

**Comment by ferferga** [comment]
We don't know because we don't use Emby, that's it. I don't know about Niels but I wasn't even aware that it's still compatible, as they're diverging the API and we're doing the same while adding new features and during our cleaning process. You must figure out yourself.

If you know how to make it work in a way that doesn't interfere with how the app should work with **our Jellyfin server** and it **doesn't add a ton of clutter**, you are welcome to do a PR for that of course. But sadly I doubt that will be possible. This is FOSS so you will always be able to fork our code and maintain a version with as much compatibility with Emby as possible. But as said before, it's not our goal. **What you're asking is like asking Netflix to make their app compatible with our servers**. Its not their apps' goal to communicate with our servers, neither our app to communicate with Emby's.

**Comment by xp-1000** [comment]
Thanks, it was not clear for me it was not **technically** supposed to works.

I installed the first release candidate few time ago and yesterday upgrading to the v2.1.1 and for now it still works with my emby server 4.5.0.50 but I cannot see the "client settings" option in menu. Videos play correctly but in the web player.

I tested exoplayer enabling it when I connect this app to my jellyfin server where the "client settings" option is available and it works very fine thanks for your work.

So I supposed it was only (for now and until api break) a question of simple setting access and that you could be have clue for me.

sorry for the misunderstanding I will try to figure out how it works.
