### ISSUE TITLE
Android client connection failure

### ISSUE THREAD

**Issue by linucksrox** [jellyfin/jellyfin-android#217]
After setting up jellyfin 10.4.0 on Docker behind a reverse proxy, I can access the web interface fine through the proxy (with https enforced on the proxy). However, the android client just says connection failure, even if I specify the port (I've tried specifying port 80 and port 443).

Extra details: using Traefik 2.0 listening on port 80 and 443, redirecting http to https, and proxying to port 8096 on the jellyfin container. Using a custom domain https://jellyfin.mydomain.com and using a self signed certificate from Traefik at this point.

Could it be an issue with the self signed cert? I don't see anything new in the server logs when attempting to connect from Android.

**Comment by thornbill** [comment]
Self signed certificates are not supported by the apps due to platform limitations. See: https://github.com/jellyfin/jellyfin-android/issues/193#issuecomment-535055466
