### ISSUE TITLE
Exiting external player reloads Jellyfin?

### ISSUE THREAD

**Issue by Altereno** [jellyfin/jellyfin-android#218]
When playing a video with VLC, after pressing the  back button, jellyfin flashes white and restarts with the splash screen.
I'm wondering if this is something with the way have batter optimizations set up?

**Comment by Maxr1998** [comment]
Could you retry this on the latest version? This might have been a crash or and issue with the WebView handling.
However, it's also possible that playing a movie uses so much RAM that Jellyfin is killed, then we can't do a lot about it unfortunately (webview state can't really be persisted).
