### ISSUE TITLE
Using Android app against Jellyfin server with BaseUrl set

### ISSUE THREAD

**Issue by mazzystr** [jellyfin/jellyfin-android#220]
I'm sure this has been answered before but my google-foo is failing me.

I'm having trouble getting the Android app to connect to my Jellyfin server. I run the server within a podman container. The server is set for standard http and uses "Base URL: /jellyfin". I have HAProxy in front of the server configured for reverse-proxy and ssl offload. My web browser runs the dashboard and streams perfectly using the url https://server.local:8443/jellyfin.

I've been setting the app to "host: https://192.168.0.10:8443/jellyfin" and "Port: 8443". I keep getting the connection failure pop-up.  I've tried some variations of Host and Port with no luck.

Does anyone know the magic to get this to work?

**Comment by dkanada** [comment]
It sounds like Android needs a new release with the changes from web, I'll get that started.
