### ISSUE TITLE
Jellyfin play video randomly after some time when minimized

### ISSUE THREAD

**Issue by dausruddin** [jellyfin/jellyfin-android#222]
Hi. I have a weird issue. I think this happened to me 3 times since I started to use Jellyfin a few weeks ago.

Basically while the app is playing a video, I minimize the app and after some a while, the app autoplay the same video. This is rare tho, so I don't know how to properly reproduce the bug.

Last time it happened was a few hours ago. I plugged in my charger and somehow Jellyfin autoplay the video I was watching.

Thanks

**Comment by anthonylavado** [comment]
I think the current build will unpause in certain conditions with Bluetooth. Basically:

- start watching something
- pause what you’re watching
- connect via Bluetooth, stays paused
- disconnect from Bluetooth
- becomes unpaused, starts playing again

**Comment by dausruddin** [comment]
Weird because I was watching with a wired earphone. 

1. I was watching a movie
2. Pulled out the earphone
3. Plugged in the charger
4. A few seconds passed by and it started to play the video.

I can't remember much for other 2 incidents that happened a while back.
But I can remember once I put the phone into my pocket, it starts playing.
3 times happened when I had my volume increased. I usually have my phone completely silenced, so I'm not sure if they ever happened in that time too or not.

I don't know if I will ever can reproduce the bug or not because I'm movinh to Kodi. Jellyfin app started to play every single video from the beginning and not from the point I paused.

Maybe I'll try again after a new version release.
Thanks
