### ISSUE TITLE
Music sometimes doesn't advance to the next playlist entry 

### ISSUE THREAD

**Issue by digitalentity** [jellyfin/jellyfin-android#222]
**Describe the bug**
When the app is playing music in the background sometimes playback stalls at the end of song and doesn't advance to the next song. When unlocking the phone and opening the app at this time I see client being sure that the song is still "playing" (not stopped, not paused) and the music timer stuck at the last or the previous-last second.

**To Reproduce**
This is not easily reproducible. I notice this when the song is allowed to play from the beginning to the end (phone locked, music plays in the background). Using the progress bar to advance the music forward usually results in things working as they should.

**System (please complete the following information):**
 - App version: 2.0.1
 - Android version: Android 10
 - Device manufacturer and model: Xiaomi Mi A3
 - Jellyfin server version: 10.6.4

**Comment by digitalentity** [comment]
Screenshot of the stuck playback:
![Screenshot_20201101-155017](https://user-images.githubusercontent.com/11059099/97806108-35ca0b00-1c5a-11eb-964f-1e77a02a0fa4.jpg)

At this point clicking "Pause/Play" will cause the playback timer to reset to zero. Subsequent presses to "Play/Pause" button will do nothing. It's only possible to "unstick" the playback by using the seek-bar or use the Next/Previous buttons.

**Comment by Japhys** [comment]
I have bee experiencing exactly the same for quite some time now. I was hoping this would be fixed in new releases but so far it still happens.

Using LineageOS 17 and Jellyfin Beta

Having the same problem with OOS and jellyfin stable

**Comment by Maxr1998** [comment]
This is probably caused by the handling of webviews in Android and the webclient itself. We probably can't fix this, but it won't be an issue anymore once we have a fully native client, which is in the works.

In the meantime, I suggest using [Gelli](https://github.com/dkanada/Gelli) for music playback.

**Comment by Japhys** [comment]
> 
> 
> This is probably caused by the handling of webviews in Android and the webclient itself. We can't fix this, but it won't be an issue anymore once we have a fully native client, which is in the works.
> 
> In the meantime, I suggest using [Gelli](https://github.com/dkanada/Gelli) for music playback.

Thanks!

**Comment by e10kstarfire** [comment]
> We can't fix this, but it won't be an issue anymore once we have a fully native client, which is in the works.

Just wondered what sort of timescale we are looking at for the native client? 

Thanks!

**Comment by nielsvanvelzen** [comment]
At least not any time soon

**Comment by e10kstarfire** [comment]
Oh ok ☹️

**Comment by chrstfer** [comment]
> At least not any time soon

Is there something holding it up, or is the focus just on the video player for now?

**Comment by nielsvanvelzen** [comment]
The Android app is mostly maintained by @Maxr1998 and me. Both of us are busy with other things. The fully native client is in a separate branch on this repository but it's very early stage.

**Comment by analogsunset** [comment]
bummer- is this still an issue on IOS or am iissing a setting?

**Comment by analogsunset** [comment]
ps. finamp doesn’t seem to have the issue

**Comment by j-luis29** [comment]
You have to turn off battery optimization for the app in Android system settings. When you first open the app there's a message encouraging you to do this but since you can still use the app without changing this setting, you might ignore this (i did).
Turning it off for the app solved this issue for me, hope that's your problem too.

**Comment by maurom88** [comment]
I did experience the issue consistently, but turning off battery optimization in the Android settings as suggested by @j-luis29 solved it!
