### ISSUE TITLE
Android Auto Compliance Issues

### ISSUE THREAD

**Issue by anthonylavado** [jellyfin/jellyfin-android#226]
In our latest review from Google, some issues were highlighted that are preventing publishing of the app.

Here is the list:

**No Auto functionality**
The app did not appear in the Auto screen or lens picker when we attempted to test functionality.
>_For example, your app does not contain an Intent filter for action "android.media.action.MEDIA_PLAY_FROM_SEARCH"._

**App does not perform as expected**
Your app does not perform all functions properly or as expected from a user perspective.
>_For example, audio tracks are silent when the microphone is not active._

**Driver distraction features**
Your app includes features that distract the driver.
>_For example, your app does not pause or reduce the volume of the audio being played while the microphone is active._

**Comment by timusus** [comment]
FWIW, Google have recently started rejecting my app for the same reason - despite the presence of that intent, and correct/working Auto & Voice Search functionality. It looks to me like their automated tests are broken.

**Comment by nielsvanvelzen** [comment]
Some of the mentioned problems are confirmed by our users/team members to be our fault so we've made some changes (#232) that should help. We will review it thoroughly on our side before submitting again to the Play Store. Hopefully this will just work, but considering the issues with the Play team a lot of users are facing I'm unfortunately not too optimistic.

**Comment by Maxr1998** [comment]
> FWIW, Google have recently started rejecting my app for the same reason - despite the presence of that intent, and correct/working Auto & Voice Search functionality. It looks to me like their automated tests are broken.
> 
> https://issuetracker.google.com/issues/173038385

That seems to be the case. I was a bit confused when I read the feedback from Google, as some of the points seem a bit contradicting to me.
But there also seem to be some issues generally with search in Android Auto/Google Assistant, I couldn't get the Assistant to direct proper queries at the Jellyfin app in my testing - when I didn't specify a playback app, it always chose Spotify (which is the default music provider in my Google account), regardless whether Jellyfin was already running or not; when I specified to play media on Jellyfin, it did direct the query at the app, but also included the "on Jellyfin" part in the search query - something it didn't do for Spotify when I explicitly selected it.
