### ISSUE TITLE
Can't add jellyfin server running in docker

### ISSUE THREAD

**Issue by asturnauta** [jellyfin/jellyfin-android#226]
Hi

I have installed jellyfin official docker image in a raspberry pi (updated to the latest version 10.4.2) and i can't add the server on the android app.

I can access via web browser without problems (http://server_IP:8096/jellyfin/)

I have installed the android app from google play store and when i try to add jellyfin server, but the app does not connect.

The smartphone is connected in the same network and it connects to jellyfin using without problems  the web explorer.

Is this a problem because i am using a docker version of jellyfin?

Thanks.

**Comment by anthonylavado** [comment]
In the Android app, did you put in exactly what you use in the browser? The full address and port, including the “/Jellyfin” at the end?

**Comment by asturnauta** [comment]
> 
> 
> In the Android app, did you put in exactly what you use in the browser? The full address and port, including the `/jellyfin` at the end?

Ok, it's working now, the problem was the /jellyfin. I was putting the ip address and the port but not '/jellyfin'. I thinked that append was only for the web interface.

Thanks a lot.
