### ISSUE TITLE
Add "Copy Stream URL" option

### ISSUE THREAD

**Issue by arhamqureshi** [jellyfin/jellyfin-android#232]
The web version of Jellyfin has an option to "Copy Stream URL" which can be accessed by clicking on the three dots of the movie/episode. It would be nice to have this available on the app as well since using an external player isn't supported yet. 

<img width="222" alt="Screen Shot 2019-12-17 at 10 24 19 pm" src="https://user-images.githubusercontent.com/29435325/70991687-1991ae00-211c-11ea-997c-30cfa5535a9b.png">

**Comment by dkanada** [comment]
This should be added in the next release, feel free to comment again if it still doesn't show up.
