### ISSUE TITLE
Make now playing notification non-dismissable

### ISSUE THREAD

**Issue by mcarlton00** [jellyfin/jellyfin-android#235]
Report from `/u/_user_name__` on reddit.

> One problem with this that's a little weird is that if you dismiss the jellyfin now playing notification on your phone it stops playing on the chromecast. This has caused me issues several times, as I'll hit the "dismiss all" button to clear messages and it'll turn off the movie or show I was watching.

In chat it was mentioned that we should be able to make the notification non-dismissable which would prevent this from happening.

```
Niels
App probably closes because there is no notification left
I think this behavior is since Android 8 or 9, but when an app is running in the background it needs to show a notification or it will be closed

cromefire_
Then just make it non-dismissable while it's playing. Many apps do that
```

**Comment by thornbill** [comment]
Looks like this should have been resolved by #319.
