### ISSUE TITLE
src code does not get updated when modified

### ISSUE THREAD

**Issue by Stampede10343** [jellyfin/jellyfin-android#236]
Not sure if I have the wrong workflow, but I'm trying to work on the native player but my changes don't get propagated until I completely delete all ignored directories that get generated by Cordova by doing `git clean -dfX`.

Is there a better workflow? Especially because Android Studio isn't really happy with working on the source outside of the normal app/src setup. And working on the cordova generated code isn't really possible since that all is ignored by git.

**Comment by dkanada** [comment]
I don't know of one, especially if you want to use the debugging functionality in Android Studio. @thornbill might know more, but this is definitely a huge pain to deal with.

**Comment by Stampede10343** [comment]
The [link](https://cordova.apache.org/docs/en/latest/reference/cordova-cli/#cordova-platform-command) command looks sorta like what we would want, but I'll have to give it a try.

**Comment by Rijul-Ahuja** [comment]
I briefly mentioned this issue in #200 but we didn't work on figuring out why this happens.

**Comment by Stampede10343** [comment]
I figured it out. Might be worth throwing in the readme, basically just run

npx cordova plugins rm org.jellyfin...



Then npx cordova plugins add src/NativeShell --link
