### ISSUE TITLE
libre-release.apk added non-libre elements

### ISSUE THREAD

**Issue by IzzySoft** [jellyfin/jellyfin-android#243]
v2.2.0 just introduced [Firebase Data Transport](https://github.com/firebase/firebase-android-sdk/tree/master/transport), Google Mobile Services, Google Cast… bringing the `*libre-release.apk` even in size to `*proprietary-release.apk`. None of these were present in v2.1.3 – and none of these are "libre".

It hopefully was just an accident. Can you please "revert" that? Thanks in advance!

**Comment by nielsvanvelzen** [comment]
This shouldn't happen, I'll investigate.

**Comment by nielsvanvelzen** [comment]
We added a new dependency on `com.google.android.exoplayer:extension-cast:2.12.1` in #232. This added some proprietary libraries to our build.

**Comment by IzzySoft** [comment]
Ah, thanks – so I was on the right track. I suspected something being dragged-in by dependency, but wasn't sure where to look. Good you found it that fast :+1:

**Comment by nielsvanvelzen** [comment]
No problem, I'm glad you told us otherwise we wouldn't have noticed :)

**Comment by IzzySoft** [comment]
I wouldn't have noticed either, but my library scanner yelled at me. Always good to have some safe-guards in place(s) :smile:

**Comment by IzzySoft** [comment]
Thanks Niels! Looking forward to v2.2.1 then. Any ETA for its release, so I can make sure to check (and remove those AntiFeatures again)?

**Comment by nielsvanvelzen** [comment]
Working on the release now. We decided for a quick release that fixes this issue and it also includes some changes needed for the fdroiddata merge request (to hopefully have reproducible builds working).

**Comment by nielsvanvelzen** [comment]
It's released now!
Downloads at the usual places:
- https://github.com/jellyfin/jellyfin-android/releases/tag/v2.2.1
- https://repo.jellyfin.org/releases/client/android/

**Comment by IzzySoft** [comment]
That was fast, thanks! Triggered the update manually (to have scanner results and be able to fix AntiFeatures before the sync) – this was a full success! Removed the AntiFeatures right away. So in about 2 hours from now, the changes will go live – with Jellyfin showing up shiny, new and clean, yay! :tada:

So again: Thanks to @nielsvanvelzen for picking up quickly – and to @Maxr1998 for fixing it that quickly as well!
