### ISSUE TITLE
Can't login over the internet

### ISSUE THREAD

**Issue by baarkerlounger** [jellyfin/jellyfin-android#243]
On Android when I open the Jellyfin App I see my server, and click connect, after a couple of spins I get:

```
We're unable to connect to the selected server right now. Please ensure it is running and try again.
```

This only happens when trying to log in over the internet, it's fine when I log in while connected to my home network. It also only happens on the Android client, when I log in on Firefox (on the same device, same network) it's fine.

I don't see any errors in the server logs with debug logging enabled. Client App version is 0.9.7 and was working fine until recently (not sure exactly when, but noticed this a couple of days ago).

I've also tried uninstalling and reinstalling the app but same issue.

**Comment by JustAMan** [comment]
Are you using a self-signed certificate by any chance?

**Comment by baarkerlounger** [comment]
Nope, let's encrypt issued cert. SSL is terminated by my reverse proxy (Apache).

**Comment by JustAMan** [comment]
How did you get your server in the app? Any chance it stored your internal address or IP? Maybe try adding it manually?

**Comment by baarkerlounger** [comment]
Added it manually via domain name previously so not sure why it stopped working. Deleting it and re-adding it in the same way seems to have done the trick though. Odd. Thanks, will close this.
