### ISSUE TITLE
Download media to device storage

### ISSUE THREAD

**Issue by Psylocybit** [jellyfin/jellyfin-android#247]
Per the title, I see a lack of this feature currently. A very useful feature of many popular media apps is the ability to download from the server and store locally on a phone. It's very common that people will prefetch all the content they want on a non-cellular network to avoid using up data throughout their day. I think Jellyfin's mobile app would benefit greatly from this, mainly in the context of music media.

**Comment by JustAMan** [comment]
This is top-wanted feature, we know of such requests: https://features.jellyfin.org/posts/218/jellyfin-mobile-app-offline-downloads
No one has step up at implementing it, though...
