### ISSUE TITLE
Native ExoPlayer ASS subtitles not using correct format.

### ISSUE THREAD

**Issue by vegedb** [jellyfin/jellyfin-android#252]
**Describe the bug**

**To Reproduce**

1. Play video file with ASS subs/fonts
2. Use Native ExoPlayer

**Expected behavior**

The subtitles on the native ExoPlayer replaces the subtitle with its own **black white** background as seen in the screenshot

**Screenshots**

MPV External Player
![bd66653a-f200-4f66-9eed-173b5f7fe5f1](https://user-images.githubusercontent.com/72070424/99903711-0199b580-2d01-11eb-92c2-c127daf2c22f.png)
ExoPlayer Native
![298c03c3-fce1-4478-9237-59fbcac9672a](https://user-images.githubusercontent.com/72070424/99903715-03fc0f80-2d01-11eb-870e-ba400a82d7b4.png)

**System (please complete the following information):**
 - App version: [v2.2.0]
 - Android version: [Android 11]
 - Device manufacturer and model: [Google Pixel 4]
 - Jellyfin server version: [10.6.4]
 - The type of video player implementation used: [(ExoPlayer)]

**Additional Info**

EMBY's ExoPlayer natively supports ASS and fonts. Hopefully you can fix this.

**Comment by nielsvanvelzen** [comment]
Works as expected, ExoPlayer doesn't support ASS styling. Please create an issue with them if you want this fixed.

**Comment by jakobkukla** [comment]
Just FYI I created an issue there https://github.com/google/ExoPlayer/issues/8435. If someone has the skill-set and wants to help out, they would appreciate it. Sry for necromancy.
