### ISSUE TITLE
ASS Styling for Native ExoPlayer

### ISSUE THREAD

**Issue by vegedb** [jellyfin/jellyfin-android#253]
**Describe the feature you'd like**

ASS Styling for Native ExoPlayer

**Screenshots**

MPV External Player
![bd66653a-f200-4f66-9eed-173b5f7fe5f1](https://user-images.githubusercontent.com/72070424/99903711-0199b580-2d01-11eb-92c2-c127daf2c22f.png)
ExoPlayer Native
![298c03c3-fce1-4478-9237-59fbcac9672a](https://user-images.githubusercontent.com/72070424/99903715-03fc0f80-2d01-11eb-870e-ba400a82d7b4.png)

**Additional context**

According to @nielsvanvelzen ExoPlayer don't support ASS styling, I'd like to say EMBY plays ASS with styling **no problem** on their ExoPlayer. So there might be a confusion here.

**Comment by nielsvanvelzen** [comment]
Please don't make duplicate issues.

**Comment by vegedb** [comment]
You told me to 

> Please create an issue with them if you want this fixed.

So i created an issue.

**Comment by nielsvanvelzen** [comment]
I meant with the ExoPlayer developers.

**Comment by vegedb** [comment]
Gotcha, no way around it? Seems weird emby has it enabled.

**Comment by nielsvanvelzen** [comment]
They might bake in the subtitles serverside or use a different player frontend. I'm not sure, never used that product.

**Comment by vegedb** [comment]
You're right, its definitely server side as it can't play karaoke opening songs. 

On another note I can **definitively and objectively** say, Jellyfin now has the superior client for android after 2.2.0 update where you enabled MPV external player with **resume** feature. Great job guys!
