### ISSUE TITLE
[unstable] No chromecasts found when using 10.7 backend

### ISSUE THREAD

**Issue by idittansikte** [jellyfin/jellyfin-android#254]
**Describe the bug**
I been waiting for chromecast support behind proxy so I decided to try lastest 10.7 build. But when installed it, the android app did not discover any chromecast at all. Tried both with and without proxy and different settings. Downgraded to 10.6.2 again and it started working as before.

**To Reproduce**
* Install 10.7 server
* Open Android app
* Click on cast button
* Only cast on this device or any other web browers currenlty opened. But no chromecasts.

**Expected behavior**
All 3 of my chromecast appear as when I use 10.6.2 server.

**Logs**
Can be provided on request.

**System (please complete the following information):**
 - App version: 2.2.0
 - Device manufacturer and model: Samsung Galaxy S8+
 - Jellyfin server version: 10.7 (master 22-11-2020)
 - The type of video player implementation used: Chromecast

**Additional context**
As far as I understand, the client should not need the backed jellyfin server at all when discovering Chromecasts? Something feels reallty fishy in the Android implementation or the server-client communication interface.

**Comment by nielsvanvelzen** [comment]
The current release is not compatible with 10.7 yet.

**Comment by idittansikte** [comment]
Alright, thanks for the info. It seemed to work decently at least, I could play stuff on the phone.

But I was surprised about the discovery since I thought it was a thing that wasn't server-dependent.

**Comment by nielsvanvelzen** [comment]
The webui normally uses a JavaScript library for casting functionality. This api doesn't work inside of a webview so we need to implement it via the webview. This is done by injecting some custom code, which doesn't work in 10.7 right now.

We've already started on fixing the support in #240. We will release a new version of the app with proper support before 10.7 is released.

**Comment by idittansikte** [comment]
Now working but I still cant use Chromecast behind proxy using 10.7 backend. But that is another topic I think.

**Comment by BongoEADGC6** [comment]
@idittansikte I believe this is partially related to the fact that the Android application does not call the Chromecast unstable branch when selected. Seems to possibly fix the issue.

Also see my comment here https://github.com/jellyfin/jellyfin/issues/4616#issuecomment-741907941 for info on how to get Chromecast to work on 10.7 behind a proxy.

**Comment by idittansikte** [comment]
> @idittansikte I believe this is partially related to the fact that the Android application does not call the Chromecast unstable branch when selected. Seems to possibly fix the issue.
> 
> Also see my comment here [jellyfin/jellyfin#4616 (comment)](https://github.com/jellyfin/jellyfin/issues/4616#issuecomment-741907941) for info on how to get Chromecast to work on 10.7 behind a proxy.

I got both web and android to work! I did not know the Chromecast "unstable/stable" setting existed, I thought it was something that was selected when building the server when I saw comments about it. Anyhow, I needed to reload the tab in web and **clear the cache** on Jellyfin app in Android application settings after setting unstable. Thanks a lot, I am so happy now having everything working behind a reverse proxy without any dirty hacks.
