### ISSUE TITLE
Gray stripe appears at camera cutout when playing video

### ISSUE THREAD

**Issue by ggdaynight** [jellyfin/jellyfin-android#255]
**Describe the bug**
Gray stripe appears at camera cutout when playing video full screen

**To Reproduce**
1. Play video of your choosing
2. Gray stripe appears on the side where the phone's camera cutout is

**Expected behavior**
The stripe which contains the camera cutout should remain black like was in version 2.0.1

**System (please complete the following information):**
 - App version: Since v2.1.0
 - Android version: Android 10
 - Device manufacturer and model: Samsung Galaxy S10e
 - Jellyfin server version: 10.5.5
 - The type of video player implementation used: [web player or integrated player (ExoPlayer)]

**Additional context**
--

**Screenshots**
* **Since version 2.1.0**
![IMG_5773](https://user-images.githubusercontent.com/11553225/100001743-e17efa80-2dc3-11eb-9a3e-eb0891a24fe6.JPG)
![IMG_5776](https://user-images.githubusercontent.com/11553225/100001833-ff4c5f80-2dc3-11eb-8d90-07869d8436f6.JPG)

---

* **Till version 2.0.1 there is no gray stripe**
![IMG_5777](https://user-images.githubusercontent.com/11553225/100001923-21de7880-2dc4-11eb-8701-a61ae6c99263.JPG)
![IMG_5768](https://user-images.githubusercontent.com/11553225/100001973-36bb0c00-2dc4-11eb-9a2f-30f15639cdfd.JPG)

**Comment by ggdaynight** [comment]
If any additional information is needed, please let me know. I will provided it to the best of my knowledge.

**Comment by grravity** [comment]
Can confirm, same issue. Has been like this on the past few updates.

**Comment by Nazar78** [comment]
I just changed from S9+ to Note20 Ultra and noticed this too.

Not sure about other phones but the Note20 has an option to hide the camera cutout under Settings->Display->Full screen apps->Advanced settings (click the 3 dots menu).

**Comment by nielsvanvelzen** [comment]
Can you try changing the preferred video player in the client settings to "Native player" and see if the gray bars are gone?

**Comment by grravity** [comment]
Native just crashes jellyfin for me

**Comment by nielsvanvelzen** [comment]
That's not supposed to happen. Is you're server up-to-date (10.6.4)? And do you perhaps have any logs of the crash?

**Comment by Nazar78** [comment]
> Can you try changing the preferred video player in the client settings to "Native player" and see if the gray bars are gone?

Yes this works too but I would like to avoid this native player for now as the subtitles offset can't be changed.

**Comment by ggdaynight** [comment]
> I just changed from S9+ to Note20 Ultra and noticed this too.
> 
> Not sure about other phones but the Note20 has an option to hide the camera cutout under Settings->Display->Full screen apps->Advanced settings (click the 3 dots menu).

I've tried that, and made no difference for me.

**Comment by ggdaynight** [comment]
> That's not supposed to happen. Is you're server up-to-date (10.6.4)? And do you perhaps have any logs of the crash?

Client version: 2.2.1
Server version: 10.6.4
With "Native Player"  **no** gray bar.

What are differences and/or benefits using native vs web player?
Is it just the subtitle offset?

**Comment by nielsvanvelzen** [comment]
The native player is still experimental but is meant to replace the web player when it's stable. It should have better and faster playback
