### ISSUE TITLE
port the project to android studio?

### ISSUE THREAD

**Issue by yeahman45** [jellyfin/jellyfin-android#257]
is there a chance porting this project to android studio? It is currently a pain to build and compile.

**Comment by thornbill** [comment]
Not in its current state. That will require a complete rewrite as the current app is built on the Cordova framework and its tooling and plugins.

**Comment by yeahman45** [comment]
ok thx for the reply. I won't contribute to the project then as it is too too much hassle.

**Comment by thornbill** [comment]
For what it’s worth we all agree that Cordova is a pain but it’s what we have for now. 😄 Until someone takes on the effort of moving to something else we are stuck with it.

**Comment by yeahman45** [comment]
Lol ok but I don't get the reasoning using cordova in the first place when there is android studio and all google efforts to make development on android easier.

**Comment by anthonylavado** [comment]
@yeahman45 This is based off the code that we had available when we forked from Emby, so that we wouldn't have to write an entire app from scratch 👍

**Comment by yeahman45** [comment]
Ok makes sense
