### ISSUE TITLE
Subtitles won't appear in latest Android app version.

### ISSUE THREAD

**Issue by dausruddin** [jellyfin/jellyfin-android#258]
Hi. I saw this on reddit and decided to try. Seems that the latest version broke something because I could no longer make the subtitle to appear. I am using external `.srt` subtitle file. It worked fine on previous version.

**Comment by JustAMan** [comment]
Does it work if you open it from mobile browser?

**Comment by dausruddin** [comment]
![PicsArt_02-18-01 27 35](https://user-images.githubusercontent.com/5763466/74675166-f3f15580-51ed-11ea-996f-3cc57d8d631a.jpg)

Yes in browser it is working fine

**Comment by xuatz** [comment]
Seems like the bug is introduce in v0.9.8

**Comment by dkanada** [comment]
This will hopefully be resolved after the server gets a new update sometime this week.

**Comment by dausruddin** [comment]
I am hoping the same. I have been using Plex since this issue appeared.

**Comment by JustAMan** [comment]
I think @thornbill found the reason of why we shipped wrong web version in Android app.
But, as @dkanada said, we're hoping to have 10.5.0 release really soon, and after it hits those issues should heal themselves automatically.

**Comment by thornbill** [comment]
Well we will need to publish a new build after 10.5.0 to resolve some of the issues since it bundles the web source. 0.9.9 was meant to revert the app to the same version as 0.9.7 but due to an issue in a build script it just used an even newer version of web. 😕

**Comment by Matt07211** [comment]
I have this trouble, but with embed ass subtitles

**Comment by Matt07211** [comment]
![Screenshot from 2020-03-07 19-19-37](https://user-images.githubusercontent.com/12839977/76139877-a9286800-604c-11ea-9522-a6676a473fc6.png)
These are the errors being spit out from the android app, I don't have any knowledge in this area but post it here as documentation of the issue

**Comment by Matt07211** [comment]
Forgot to attach log
[-1583569494766.log](https://github.com/jellyfin/jellyfin-android/files/4301563/-1583569494766.log)

**Comment by JustAMan** [comment]
@Matt07211 I believe that `.ass` not working is a different issue than `.srt` not working...

**Comment by HackingPheasant** [comment]
By the sound so it sounds like the android app fails to load the subtitles on their end, but loads fine in the web browser (same happens for me). So I assume it was a problem with how the app handles getting subtitles and not the subtitle format causing the problem. If the original poster can post more info I'll gladly create a seperate issue if it becomes clear it's a completely different problem

**Comment by Matt07211** [comment]
By the sound so it sounds like the android app fails to load the subtitles on their end, but loads fine in the web browser (same happens for me). So I assume it was a problem with how the app handles getting subtitles and not the subtitle format causing the problem. If the original poster can post more info I'll gladly create a seperate issue if it becomes clear it's a completely different problem

*Sorry for the double notification, I really should check what account I'm logged in from when commenting*

**Comment by Salusbury** [comment]
I wanted to say that I tried watching a video with subtitles on my phone's mobile browser, but I ran into the same issue where I couldn't see any subtitles.

**Comment by akhoa12** [comment]
I also experience this issue today. I was trying to play an anime episode Jellyfin for Android that has embedded ASS subtitles, but the subtitle did not show up. However, when I tried to play the same episode on Jellyfin-MPV-shim the subtitle shows up, and subtitles also work when I tried with Chrome Browser (although it needed transcoding).

I don't know how to attach logs on here and also don't know which one to attach, so I apologize for that. But below is some info that I think would be relevant.

OS: Docker, linuxserver 10.5.3
Client: Jellyfin for Android 0.9.9
Video container: mkv
Subtitle Format: ASS
Extract subtitle on the fly: ON
Burn-in Subtitle: only image formats

**Comment by dausruddin** [comment]
17 Apr will my 2-month usage of Plex. I really miss Jellyfin😭

**Comment by willymilkytron** [comment]
I don't know if or how https://github.com/jellyfin/jellyfin-android/pull/309 was tested but it doesn't really fix the issue on my Android device: ASS subtitles do not appear to be working at all, now with the added bonus of a generic error message being displayed every time i try to enable them.

![image](https://user-images.githubusercontent.com/62460473/79264199-7320a400-7e94-11ea-9864-18cf587ea719.png)

Server info:

Server: jellyfin
Version: 10.5.3
Operating System: Linux
Architecture: X64

Client info:

Android running apk downloaded from https://github.com/jellyfin/jellyfin-android/commit/8064e278ef91a871d48e49948c5da89976cceac9 artifacts

Still sticking to v0.9.8 for the time being.

**Comment by dausruddin** [comment]
Do we need to wait for an Android update or is it enough to keep Jellyfin server updated? Because subtitle still doesn't show up on latest Android app.

**Comment by JustAMan** [comment]
We need a separate app release which should be soon ™
