### ISSUE TITLE
Move to GitHub actions

### ISSUE THREAD

**Issue by nielsvanvelzen** [jellyfin/jellyfin-android#260]
Near future plan:
- [x] Move the tests to GH Actions
- [x] Move the PR/master builds to GH Actions

Far future plan:
- [x] Move publishing to GH Actions
       This means that we only use Azure for tag builds+publishing

**Comment by nielsvanvelzen** [comment]
Some interesting actions to investigate:

- https://github.com/marketplace/actions/update-gradle-wrapper-action
- https://github.com/marketplace/actions/gradle-wrapper-validation (jellyfin-androidtv uses this one already)
- https://github.com/marketplace/actions/android-app-size-difference

**Comment by Maxr1998** [comment]
Oh wow! This is finally finished now. Closing.
