### ISSUE TITLE
Download to SD card on android devices

### ISSUE THREAD

**Issue by Orybon** [jellyfin/jellyfin-android#264]
I would like to  download files to my sd card because the storage is limited on the internal card of my android devices.

I can't found any parameter to choose location and i can't move the application to my sd car in android parameters (I can for other applications like Deezer).

Application version : 2.2.2
My android version : 8.0.0
Android device model : Samsung galaxy S7

**Comment by Morgan-6Freedom** [comment]
Hello @CarlosOlivo.
I think your pull request is about installing the app on the SD card or the intern storage. 
But I think @Orybon is talking about downloading musics & videos. So the pull request might not close is issue.
Am I wrong ?

**Comment by Morgan-6Freedom** [comment]
By the way, I think it's not possible to download musics & videos from your server within the android app.

**Comment by CarlosOlivo** [comment]
@Morgan-6Freedom This is what the PR does, do you mean this or something else?

![Szui4PO8XK](https://user-images.githubusercontent.com/25919231/106021528-82bb5300-608a-11eb-81ee-eae556a161f8.gif)

**Comment by Morgan-6Freedom** [comment]
This is perfect I think. I read "Also allow Jellyfin to be installed/moved to external storage" and I thought the PR was ONLY about this. Great work thank you.
