### ISSUE TITLE
Media playback does not always respect External Player preference

### ISSUE THREAD

**Issue by eltiel** [jellyfin/jellyfin-android#265]
**Describe the bug**
Some, but not all media will default to Web Player even though Client Settings is configured to play via External Player, in my case MX Player. However, if Client Settings is configured to play via ExoPlayer, it will work properly. Additionally, this behavior is not consistent as it happens only in certain scenarios:

1. Does not happen to all media. I can't quite pinpoint why it does/doesn't work as there is no discernible pattern. However, it is not random as if it works for Media A, it always does and if doesn't work for Media B, it never does.
2. Seems to only affect TV Series but not Movies
3. Only certain conditions will trigger said behavior - A) the Play button on the bottom right of the Series thumbnail in Home page B) Play button in the Series main page. Playing the individual episode from the episode list works fine.
4. It **always** works properly when the affected media is resumed from Next Up or Continue Watching list

**To Reproduce**

I cannot determine why only certain media is affected, but if you do have affected media:
1. Configure Client Settings to play using External Player. I'm using MX Player
2. Go to Home page and tap the Play icon on series thumbnail in Latest TV Shows
3. Media will be played using Web Player, ignoring the Client Settings
4. Play media long enough so that it will be in a resumable state in Continue Watching
5. Tap on Play icon on series thumbnail again, but this time from Continue Watching instead of Latest TV Shows
6. Media will be played using MX Player, according to Client Settings

**Expected behavior**
Media should be played according to Client Settings preferences at all times

**Logs**
No error, media still plays fine

**System (please complete the following information):**
 - App version: 2.2.0
 - Android version: Android 10
 - Device manufacturer and model: Pocophone F1
 - Jellyfin server version: 10.6.4
 - The type of video player implementation used: External Player (MX Player)

**Comment by CarlosOlivo** [comment]
> 1. Does not happen to all media. I can't quite pinpoint why it does/doesn't work as there is no discernible pattern. However, it is not random as if it works for Media A, it always does and **if doesn't work for Media B, it never does**

This seems to be a different error, could you create a separate issue with the metadata and the server log of that media that does not work for you?

Can you test if the following build solves the problem you describe in point 3?

> 3\. Only certain conditions will trigger said behavior - A) the Play button on the bottom right of the Series thumbnail in Home page B) Play button in the Series main page.

1. Download [jellyfin-android.zip](https://dev.azure.com/jellyfin-project/7cce6c46-d610-45e3-9fb7-65a6bfd1b671/_apis/build/builds/20579/artifacts?artifactName=jellyfin-android&api-version=6.0&%24format=zip) and extract it
2. Install `jellyfin-android-v0.0.0-dev.1-proprietary-debug.apk` or `jellyfin-android-v0.0.0-dev.1-libre-debug.apk`
3. Try to reproduce the error with the affected media and comment if you see any changes

**Comment by eltiel** [comment]
> 
> 
> > 1. Does not happen to all media. I can't quite pinpoint why it does/doesn't work as there is no discernible pattern. However, it is not random as if it works for Media A, it always does and **if doesn't work for Media B, it never does**
> 
> This seems to be a different error, could you create a separate issue with the metadata and the server log of that media that does not work for you?
> 
> Can you test if the following build solves the problem you describe in point 3?
> 
> > 3. Only certain conditions will trigger said behavior - A) the Play button on the bottom right of the Series thumbnail in Home page B) Play button in the Series main page.
> 
>     1. Download [jellyfin-android.zip](https://dev.azure.com/jellyfin-project/7cce6c46-d610-45e3-9fb7-65a6bfd1b671/_apis/build/builds/20579/artifacts?artifactName=jellyfin-android&api-version=6.0&%24format=zip) and extract it
> 
>     2. Install `jellyfin-android-v0.0.0-dev.1-proprietary-debug.apk` or `jellyfin-android-v0.0.0-dev.1-libre-debug.apk`
> 
>     3. Try to reproduce the error with the affected media and comment if you see any changes

With the debug version, problem 1 to 3 seems to have been fixed. I can longer reproduce any of the behaviors I mentioned above. Do you still need me to create an issue for scenario 1?

**Comment by CarlosOlivo** [comment]
> Do you still need me to create an issue for scenario 1?

If you can now play all your media in external player without any error then it is no longer necessary to open a new issue
