### ISSUE TITLE
Unable to download books

### ISSUE THREAD

**Issue by FelipeYslaoker** [jellyfin/jellyfin-android#266]
I added a library of books, but when I downloaded it from the app it just didn't work. In the browser it works, but not in the app.

**Comment by ruCyberPoison** [comment]
this maybe come with this feature i thought 
https://features.jellyfin.org/posts/218/jellyfin-mobile-app-offline-downloads

Kind Regards

**Comment by Camo30** [comment]
Same here, would be great to get that feature

**Comment by thornbill** [comment]
Download support should be working since the 1.0.0 release! 🎉
