### ISSUE TITLE
10.7.0 - Playback doesn't respect player setting

### ISSUE THREAD

**Issue by jakobkukla** [jellyfin/jellyfin-android#269]
**Describe the bug**
Media playback doesn't respect ExoPlayer or external player. I can select whichever I want in settings but when I start playback it's always using the web player.

I first noticed this last week when upgrading my server to 10.7.0 and using the 2.2.2 Android App.

**To Reproduce**
1) Go into settings and select either ExoPlayer or External Player
2) Start playback

**Expected behavior**
The setting should have an effect on the chosen player.

**System (please complete the following information):**
 - App version: 2.2.3
 - Android version: Android 10
 - Device manufacturer and model: Oneplus 7 Pro
 - Jellyfin server version: 10.7.0 nightly
 - The type of video player implementation used: ExoPlayer

**Comment by jakobkukla** [comment]
I just switched servers to check with the demo server on demo.jellyfin.org/stable and after changing back to my local installation I can't reproduce this issue anymore. Even after reinstalling the issue is gone, which is odd because I uninstalled the app yesterday and updated to 2.2.3 and the issue was still present...

**Comment by nielsvanvelzen** [comment]
This might have been a caching issue.

**Comment by aHcVolle** [comment]
I've got the same pronlem. It seems to work fine on the demo but switching back to my local server makes the client use the webplayer again.

**Comment by Maxr1998** [comment]
That sounds like the plugin loading occasionally breaks. You're on 10.7 as well?

**Comment by aHcVolle** [comment]
Yes, i'm on 10.7. Rc1

**Comment by dessalines** [comment]
Has anyone figured this one out? Would the version of jellyfin web affect it at all?

I'm on 10.7.rc1 and jellyfin android 2.2.3 

The demo is able to use the native player fine, but my local jellyfin server always uses the web player.

**Comment by vegedb** [comment]
@dessalines 
> I'm on 10.7.rc1 and jellyfin android 2.2.3

Same problem. Reverted to 10.6.4 and everything works again. Definitely a **BUG** or a setting we missed since the demo works fine.

 @nielsvanvelzen 
@Maxr1998

**Comment by Maxr1998** [comment]
I think there still is a bug in the web component in RC1, wait for the next server release or use the unstable nightlies, there it should work.

**Comment by ConnorJC3** [comment]
Fixed in 10.7.0 RC2 :)

**Comment by vegedb** [comment]
@ConnorJC3 
There's no RC2 32bit arm available though.

**Comment by nielsvanvelzen** [comment]
Closing as it appears to work in RC2, please leave a comment if the issue persist and we will re-open this issue.
