### ISSUE TITLE
[Issue] Side bar doesn't appear when swipe.

### ISSUE THREAD

**Issue by ruCyberPoison** [jellyfin/jellyfin-android#271]
Hello, Devs,
I have a issue on my android smart phone (Huawei P30 Pro) when i swipe to show me the libraries the side bar doesn't appear, but when i open something like a 'Season folder' it opens correctly, BTW i suggest to do something or an approach like plex app to when you click on a Hamburger button all libraries and settings appears and you also can swipe as i have seen on plex app,

E.g :.

![image](https://user-images.githubusercontent.com/60718477/75110289-bc8b0a80-562c-11ea-8937-a84a8cafb46d.png)

So when clicking in that button (Hamburger menu) all libraries can be show, and different settings and avatar why not.

Putting Jellyfin more smoothly and more friendly user can be also a good think, (Disable Battery message and etc...)

Hope this can be fixed asap .

Kind regards

**Comment by dkanada** [comment]
This should be resolved in the next update, feel free to comment again if you are still having issues.
