### ISSUE TITLE
Google Playstore app not working

### ISSUE THREAD

**Issue by derritter88** [jellyfin/jellyfin-android#277]
Hi there,
I have downloaded the official app via Google Playstore. As soon as I try to connect to my server it won't work -> Connection failure. I have tried via proper FQDN and IP.

So I have downloaded the debug app to see if there are any log files to analyze (https://repo.jellyfin.org/releases/client/android/) and with the 0.9.9 debug app I can connect to my server without any issues.

**Comment by surdu** [comment]
It seems that I have the same issue

**Comment by surdu** [comment]
Just downgraded the server to 10.4.0 and now everything works again.

**Comment by JustAMan** [comment]
cc @dkanada @anthonylavado @thornbill

**Comment by anthonylavado** [comment]
I think we determined that part of the web rollback didn’t take effect like we thought?

That said, try with the new 10.5.0 that’s just out now.

**Comment by dkanada** [comment]
We're going to have to push a new Android release, I'll do some testing this week.

**Comment by michael9dk** [comment]
I propose a Bug Fixed tag.

Issue is solved in Android v1.0.1 with server 10.5.5
