### ISSUE TITLE
Changing subs/audio will reset playback

### ISSUE THREAD

**Issue by nextlooper42** [jellyfin/jellyfin-android#280]
When i change subtitles or audio playback will reset from any played time always to 0:00 and start whole episode/movie again.

**Comment by JustAMan** [comment]
Does it also happen when using mobile browser?
What are JF app version and JF server version?

**Comment by shawnzhou1120** [comment]
me too，and it also happen in TV app.
but its ok in PC web.

**Comment by nextlooper42** [comment]
> 
> 
> Does it also happen when using mobile browser?
> What are JF app version and JF server version?

Yes, both Android and Android TV apps.

JF server version: Stable 10.4.3.

**Comment by nextlooper42** [comment]
Android has this issue, both on phone (android 9) and tablet (android 7). Android TV (android 8) seems to be unaffected by this, at least the videos that i tried.

Jellyfin Server: 10.5.0
Android app: 0.9.9 (909 by dashboard report)
Android TV app: 0.11.1

**Comment by JustAMan** [comment]
Most likely fixed by https://github.com/jellyfin/jellyfin-web/pull/1040

**Comment by thornbill** [comment]
This should be fixed by the change referenced above.
