### ISSUE TITLE
Chromecast playback broken on 10.7.0-rc2 (app always picks stable receiver)

### ISSUE THREAD

**Issue by krutburken** [jellyfin/jellyfin-android#281]
**Describe the bug**
split from https://github.com/jellyfin/jellyfin/issues/4918

Casting from Chrome browser using Unstable client works fine. Using the Android app I'm able to connect to my Chromecast device, but any playback errors out with "MessageChromecastConnectionError". Both Stable and Unstable clients have the same issue. I'm thinking the issue appears because Unstable is not actually used even though it's selected in the application.

On Chrome, "Jellyfin for google cast beta" is displayed when using Unstable, but when using the app this does not appear even though Unstable is selected.

I'm using a nginx reverse-proxy and remote server. It works great on 10.6.4 with the same setup.

**To Reproduce**
1. Upgrade server to 10.7.0-rc2
2. Connect to Chromecast device
3. Start playback
4. MessageChromecastConnectionError gets thrown

**Expected behavior**
Playback starting

**Logs**
MessageChromecastConnectionError gets thrown on playback. No error in server logs.

**System (please complete the following information):**
 - App version: 2.2.3
 - Android version: Android 11
 - Device manufacturer and model: Google Pixel 2
 - Jellyfin server version: 10.7.0-rc2
 - The type of video player implementation used: Chromecast

**Comment by nielsvanvelzen** [comment]
I get the same error when testing but there is no proper logging in jellyfin-web for errors to find the actual cause. Stacktrace ends up at this line:

https://github.com/jellyfin/jellyfin-web/blob/eb1e501fad14b15ef3ea7d102c8caff46a4963ea/src/plugins/chromecastPlayer/plugin.js#L136

**Comment by krutburken** [comment]
Hm, that's a shame... Was hoping to be able to use rc2 as a daily driver

**Comment by zilexa** [comment]
I have the same issue with:

Server version 10.6.4 (docker).
Client is Android 10, Pixel 1 running app version 2.0.0 using the nightly driver.

(With the stable driver, Chromecast Ultra is not visible, ShieldTV is).

**Comment by hawken93** [comment]
I think this issue should track the problem that android only wants to use the default/stable receiver even though unstable is selected.

For now, stable has gotten a 10.7 fix.

**Comment by hawken93** [comment]
https://github.com/jellyfin/jellyfin-android/pull/287

**Comment by krutburken** [comment]
old crap
