### ISSUE TITLE
Jellyfin Android no audio when i play the DTS files.

### ISSUE THREAD

**Issue by shawnzhou1120** [jellyfin/jellyfin-android#282]
I download the jellyfin android in PLAY store.
There are no audio when i play the DTS files.
my phone is the Android Q
Is it global issue?

**Comment by JustAMan** [comment]
Yes, current app supports playing only what your WebView (read: phone browser) supports.
The audio should be transcoded to AAC, though, did you disable transcoding on your server?..

Also a lot more formats would be playable by app without transcoding when https://github.com/jellyfin/jellyfin-android/pull/238 lands.

**Comment by shawnzhou1120** [comment]
yes ,i have disable transconding on my server.

got it ,thanks

**Comment by JustAMan** [comment]
I'm inclined to close it for now as it's as expected.
Thoughts @shawnzhou1120 @dkanada @thornbill ?

**Comment by thornbill** [comment]
Agreed. Let’s close this one. There’s really nothing we can do if transcoding is disabled and the player doesn’t support the format (beyond changing the player which is in progress).
