### ISSUE TITLE
Video playback stutters when using bluetooth earphones

### ISSUE THREAD

**Issue by jeremyj** [jellyfin/jellyfin-android#283]
**Describe the bug**
Playback stutters when using bluetooth earphones.
Turning off the earphones, the playback resumes smoothly.
I have tried with a pair of EarFun Air TWS and Aukey GL09. 

**To Reproduce**
1. Connect bluetooth earphones to tablet
2. Play media on Jellyfin
3. Playback stops after a while, then resumes after 2-10+ seconds

**Expected behavior**
Smooth playback

**Logs**
I can provide filtered output of `adb logcat` upon request if needed

**Screenshots**
N/A

**System (please complete the following information):**
 - App version: 2.2.3
 - Android version: Android 8 (EMUI 8)
 - Device manufacturer and model: Huawei Mediapad M5 Lite 10 (BAH2-W19)
 - Jellyfin server version: 10.6.4
 - The type of video player implementation used: web player, exo, vlc

**Additional context**
N/A

**Comment by Maxr1998** [comment]
That sounds a lot like a hardware/firmware issue. I can use video playback with blueooth headphones just fine.

**Comment by jeremyj** [comment]
I agree, even though this happens only with Jellyfin, not with other streaming services  (maybe also Plex IIRC)

**Comment by fuckyoubitchuracunt** [comment]
I have had this issue recently with the Razer Barracuda X Headset, it will work just fine with the bluetooth function but not the wireless dongle and it worked just fine with the dongle before this as it started while using the dongle
