### ISSUE TITLE
Play services mandatory?

### ISSUE THREAD

**Issue by natrius** [jellyfin/jellyfin-android#284]
From what i'm able to read in this issue https://github.com/jellyfin/jellyfin-android/issues/1 it is not possible to use the android app without play-services?

So if i use my cellphone with lineageos without google-services i'm not able to use this app?

**Comment by dkanada** [comment]
You can build the F-Droid flavor to remove all requirements for play services. Unfortunately, we haven't had anyone contribute the scripts required to publish these builds on an actual F-Droid server, so they aren't published anywhere for now.

**Comment by dkanada** [comment]
See #308 for the planned F-Droid release in the next week or two without Play Services!
