### ISSUE TITLE
No assets (APK) for v0.9.10?

### ISSUE THREAD

**Issue by TwizzyDizzy** [jellyfin/jellyfin-android#294]
Possibly a broken pipeline? Initially I though this is some lateral pipeline taking its time, but since now 2 days have gone by I suspect an error.

[0.9.9](https://github.com/jellyfin/jellyfin-android/releases/tag/v0.9.9) has them, [0.9.10](https://github.com/jellyfin/jellyfin-android/releases/tag/v0.9.10) does not.

Cheers
Thomas

**Comment by dkanada** [comment]
Yeah, we've been running into build issues lately. We're actually in the process of moving everything to Azure to avoid this problem in the future, but there will be a delay before everything is back to normal.

**Comment by willymilkytron** [comment]
IIRC i built and installed v0.9.10 .apk but somehow playback was broken on my device. Also embedded subtitles won't work.

**Comment by willymilkytron** [comment]
![phoneinfo](https://user-images.githubusercontent.com/62460473/78194261-eda4f900-747c-11ea-9c9e-482931f78f7e.png)

![appinfo](https://user-images.githubusercontent.com/62460473/78194269-f39ada00-747c-11ea-9d9f-c8ab65cba97b.png)

The following error pops up as soon as i start playing .mkv files. Same files work perfectly with v0.9.9.
I should add i head the video playing under the error dialog.

![error](https://user-images.githubusercontent.com/62460473/78194407-5b512500-747d-11ea-90d9-e41170cb944f.png)

**Comment by dkanada** [comment]
We should have a new release out that fixes subtitles in the next week. Feel free to comment again if the files are missing anywhere, or open a new issue for other bugs you see. :smile:
