### ISSUE TITLE
Media Control notification only updates when interacted with

### ISSUE THREAD

**Issue by rexbron** [jellyfin/jellyfin-android#305]
The Now Playing music notification only updates when interacted with.

### Expected Behaviour
The Now Playing notification would be updated on track change.

### Screenshots
![Screenshot_20200407-103045](https://user-images.githubusercontent.com/587341/78682288-c8b8e780-78bb-11ea-955f-de8ab440a584.png)
![Screenshot_20200407-103037](https://user-images.githubusercontent.com/587341/78682300-cce50500-78bb-11ea-99f8-d89daf3cfccc.png)
Note: Now playing notification refers to first track in playlist.

![Screenshot_20200407-103147](https://user-images.githubusercontent.com/587341/78682307-cf475f00-78bb-11ea-9596-3c680fd60ee5.png)
After pausing the playback controls. 

### System Details
Server: 10.5.3
Connection: Wifi/LAN
Android Version: 10 April 5th Patch
Device: Pixel 3a

**Comment by hamburglar2160** [comment]
I think this can be closed.
