### ISSUE TITLE
Embedded mkv subtitles won't work on Android.

### ISSUE THREAD

**Issue by PedroBarcha** [jellyfin/jellyfin-android#307]
ASS subtitles don't work on my phone. SRT do work, however.
As it might be helpful to mention, I was having the same issue in the web interface for Jellyfin 10.5.2. It has been fixed on 10.5.3: https://github.com/jellyfin/jellyfin/pull/2653

**Comment by irredentist** [comment]
Possible duplicate of issue 258?
https://github.com/jellyfin/jellyfin-android/issues/258

**Comment by willymilkytron** [comment]
Embedded ASS subtitles have been broken since 0.9.9 on Android. Now 0.9.10 has been commited in "package.json" but both the release and git tag have been removed from the project: what is going on?

For the time being i am building my own 0.9.8 apk locally with custom modification and ship it to all my devices manually, which is kind of annoying.

**Comment by irredentist** [comment]
@willymilkytron would you mind sharing your apk? I just want to be able to watch my shows haha.

**Comment by willymilkytron** [comment]
@irredentist https://github.com/jellyfin/jellyfin-android/releases/tag/v0.9.8

**Comment by Artiume** [comment]
We're working on a new android release which will support ass subs properly.

**Comment by xangelix** [comment]
@irredentist It looks like this issue will be fixed soon but I've been using the Jellyfin AndroidTV app in the meantime on a phone. It's a little weird controlling it with touch, but it works well enough and doesn't have this issue or another issue I'm having with the web version on mobile.

**Comment by dkanada** [comment]
If you want to test our update now you can visit [this](https://dev.azure.com/jellyfin-project/jellyfin/_build/results?buildId=6136&view=artifacts&type=publishedArtifacts) link and install the debug version.

**Comment by xangelix** [comment]
Unfortunately I tried that exact build about an hour ago before trying the AndroidTV app.
The debug version you've linked installs successfully, but crashes on startup for me.
(Android 10, Pixel 2 XL)
I tried it right now again in case it was a different built I tapped on, but same result.
I'm not familiar with android development but if there's any easy way I could provide some logs then I would be glad to.

**Comment by dkanada** [comment]
Looks like we have a runtime error on the master branch! When I get around to fixing that in the next few days, you'll be able to download the latest debug version from there and test the change.

**Comment by Cyan101** [comment]
Just the latest run in the azure devops?

**Comment by dkanada** [comment]
We still have to update the tag for the web client I think.

**Comment by Cyan101** [comment]
Alright, well if it helps I just tested the latest debug and now my ASS
subtitles are working in the app

**Comment by idaxx** [comment]
We have any ETA for this fix? 
I tried debug apk but it closes before the start

**Comment by dkanada** [comment]
I'll be pushing an update in the next few days for Google Play and our repository. This will also be the first version to show up on F-Droid.

**Comment by idaxx** [comment]
SSA subtitles still dont show on mkv after release of last version

**Comment by PedroBarcha** [comment]
Working like a charm, thanks!
