### ISSUE TITLE
Make audiobooks available for Android Auto

### ISSUE THREAD

**Issue by teacupx** [jellyfin/jellyfin-android#314]
**Describe the feature you'd like**
Right now, only collections of type "Music" are shown in Android Auto. Showing also "Books" collections would be very useful for people who listen to audiobooks on their way to work or their travels.

**Additional context**
Audiobooks collections are meant to be organized in folders, instead of browsing through artists/albums. This needs to be taken into account.

**Comment by nielsvanvelzen** [comment]
Duplicate of #247

**Comment by teacupx** [comment]
Sorry, I did a search but that one didn't show up :)
