### ISSUE TITLE
language interface doesn't change

### ISSUE THREAD

**Issue by lelamamalgache** [jellyfin/jellyfin-android#316]
Hello,

the language interface doesn't change

as admin account

From jellyfin web
Dashbord > server > general
Preferred display language : french to english (uk)

From jellyfin android
the interface is still in french even if i close and reopen the application with the same user "admin account"

**Comment by CutterXYZ** [comment]
On Jellyfin Android, go to user settings > Display > Language. Make sure it is set to "Auto" or "English". This setting has priority over the server's preferred language AFAIK.

**Comment by lelamamalgache** [comment]
auto doesn't work
set manually a language works

thank you @CutterXYZ
