### ISSUE TITLE
buttons on "edit this user's profile, image and personal preferences" are broken

### ISSUE THREAD

**Issue by lelamamalgache** [jellyfin/jellyfin-android#317]
Hello devs,

From jellyfin android
Dashboard > Sever > Users

click on one user

then click on "edit this user's profile, image and personal preferences."

after that, all buttons are broken

**Comment by Artiume** [comment]
This is fixed in master.

**Comment by dkanada** [comment]
I'll close this for now since it should be fixed in the next Android update, but feel free to comment again if you're still having issues.
