### ISSUE TITLE
10.7 Android - Item Details - Large amount of wasted space when compared to 10.6 (or in desktop mode)

### ISSUE THREAD

**Issue by adavier** [jellyfin/jellyfin-android#317]
This is fundamentally an issue on the web client, however a possible fix is to load the desktop version of the site for landscape/tablet use. This works in browser, but not the app.
[jellyfin-web report](https://github.com/jellyfin/jellyfin-web/issues/2490)

Large amount of wasted space on 10.7 compared to 10.6 when viewing Film/TV show.
This affects the mobile view, (and the Android app), it can be somewhat resolved when set to desktop mode but this cannot be done in the android app.

**Steps To Reproduce**

Update to 10.7

**Expected Behavior**

**Screenshots**

Normal Mode, Android App is the same (10.7)
![10 7](https://user-images.githubusercontent.com/30839200/110254023-37e40380-7f85-11eb-9a29-55d2f5f9fc09.jpg)

Normal Mode 10.6, Android app on 10.6 is the same.
![10 6](https://user-images.githubusercontent.com/30839200/110254030-3ca8b780-7f85-11eb-9334-59880b3475e3.jpg)

**System (please complete the following information):**
 - Platform: Android
 - Browser: Tested in Firefox, and Android App
 - Jellyfin Version: 10.7

**Comment by nielsvanvelzen** [comment]
Thanks for reporting but we can't do anything about it on the android side. Closing in favor of the web issue (jellyfin/jellyfin-web#2490).
