### ISSUE TITLE
Videos don't resume playback but always start from the beginning.

### ISSUE THREAD

**Issue by bloodsplatter** [jellyfin/jellyfin-android#321]
I have searched both open and closed issues (keywords resume and continue) but found nothing looking vaguely relevant.

When I pause a video on the app and come back later, I can see the blue progress bar at the bottom of the thumbnail, but when I click play, the video starts from the beginning. 

In the web client, this works as expected.

* App version: 0.9.9
* Device: Samsung Galaxy S10 (SM-G973F)
* OS: Android 10

**Comment by MattSpec** [comment]
i believe this issue is being tracked here:
https://github.com/jellyfin/jellyfin-web/issues/899

**Comment by bloodsplatter** [comment]
Correct, that issue describes my situation.

**Comment by jvmonjo** [comment]
This issue and the referred one are closed but this is still an issue. Shouldn't it be reopened to follow up?

**Comment by nielsvanvelzen** [comment]
This issue is for the old Android app, which does not exist anymore.
