### ISSUE TITLE
Crashing When Native Player Is Selected

### ISSUE THREAD

**Issue by seniorm0ment** [jellyfin/jellyfin-android#321]
I can grab logcat logs tomorrow, however Jellyfin app crashes abruptly when selectong native player, then going to play anything.
Web player and external work.

I'm wondering if this could be due to something being removed upon "debloating" this device, however I cannot reformat this debice, nor do I have another device to test.

LGv40, Android 10, F-Droid JF 2.2.3

**Comment by Maxr1998** [comment]
Could you try the latest beta and grab logs if possible?
