### ISSUE TITLE
Adaptive app icons

### ISSUE THREAD

**Issue by cromefire** [jellyfin/jellyfin-android#324]
Discussion about how to implement adaptive app icons

_beauty is in the eye of the beholder_

## Adaptive

_These are used in API level 26+ (Android 8)_

The Launcher (usually set by the manufacturer) determines the shape of all apps.

The most commonly used here are square and circle.

There are 3 Versions:

### Low (looks good in squares)

<details>
<summary>
Grid
</summary>

![low grid](https://user-images.githubusercontent.com/26320625/80292309-1bb4ea80-8756-11ea-85bc-64c90f359bfe.png)

</details>

<details>
<summary>
All
</summary>

![low all](https://user-images.githubusercontent.com/26320625/80292320-3ab37c80-8756-11ea-94bc-723dd7c93de1.png)

</details>

### Medium (middleground)

<details>
<summary>
Grid
</summary>

![medium grid](https://user-images.githubusercontent.com/26320625/80292337-5d459580-8756-11ea-85c4-da60d71328f0.png)

</details>

<details>
<summary>
All
</summary>

![medium all](https://user-images.githubusercontent.com/26320625/80292342-6c2c4800-8756-11ea-8362-5de596469926.png)

</details>

### High (looks good in circles)

<details>
<summary>
Grid
</summary>

![high grid](https://user-images.githubusercontent.com/26320625/80292361-8fef8e00-8756-11ea-8d3f-15a062dac147.png)

</details>

<details>
<summary>
All
</summary>

![high all](https://user-images.githubusercontent.com/26320625/80292369-9e3daa00-8756-11ea-9c9f-0be78b4d62d2.png)

</details>

## Legacy

_Used in API level 21 (Android 7.1) or lower_

This is just about the shape, the position will be decided by the above version. The checker board is transparent.

Also I didn't make those up, those are the options provided by android studio:
![options](https://user-images.githubusercontent.com/26320625/80293189-743bb600-875d-11ea-8db5-6642dda622cc.png)

<details>
<summary>
There are 5 Versions:
</summary>

none:
![none](https://user-images.githubusercontent.com/26320625/80293007-e4493c80-875b-11ea-9cfd-10d3eec81143.png)
_(Yes that big dark square in the background belongs to the icon)_

circle:
![circle](https://user-images.githubusercontent.com/26320625/80293031-2a9e9b80-875c-11ea-81ce-cb4abc852de1.png)

square:
![square](https://user-images.githubusercontent.com/26320625/80293039-39854e00-875c-11ea-8ff0-e508ccb38ebb.png)

vertical:
![vertical](https://user-images.githubusercontent.com/26320625/80293050-486c0080-875c-11ea-9670-8c71f4c72181.png)

horizontal:
![horizontal](https://user-images.githubusercontent.com/26320625/80293056-56218600-875c-11ea-938a-fc64ffc0560c.png)

</details>

**Comment by cromefire** [comment]
Here is something to vote for stuff (in case you just want to vote for something):

**Comment by cromefire** [comment]
Low

**Comment by cromefire** [comment]
Medium

**Comment by cromefire** [comment]
High

**Comment by cromefire** [comment]
And for legacy:

**Comment by cromefire** [comment]
None

**Comment by cromefire** [comment]
Circle

**Comment by cromefire** [comment]
Square

**Comment by cromefire** [comment]
Vertical

**Comment by cromefire** [comment]
Horizontal

**Comment by cromefire** [comment]
_End of voting, comments below_

=======================

**Comment by nielsvanvelzen** [comment]
Suggestion for the legacy icon: drop the background and add shadows:
![image](https://user-images.githubusercontent.com/2305178/80301195-fa2e2000-87a2-11ea-8763-20d0462343da.png)

(Quickly made with https://romannurik.github.io/AndroidAssetStudio/icons-launcher.html)

**Comment by cromefire** [comment]
I did not include that because of readability issues on certain backgrounds and consistency

**Comment by cromefire** [comment]
![Screenshot_20200426-114342](https://user-images.githubusercontent.com/26320625/80303906-5b5def80-87b3-11ea-8989-b56837267968.jpg)
This would be still visible to a normal user but it would probably not pass accessibility and we can't control the background with a transparent icon.
(Yes this is a extreme case, but it's already harder to see on red and blue backgrounds)

**Comment by nielsvanvelzen** [comment]
I don't see any shadows in your example but I agree it might be hard to see, even with shadows.
