### ISSUE TITLE
Explain difference btwn release.apk vs libre.apk vs debug.apk in Readme.md

### ISSUE THREAD

**Issue by patogit** [jellyfin/jellyfin-android#331]
Since there's a choice of three APKs, explain the difference between them in the readme, and explain that the libre release is not yet working. This way people can understand their options and maybe even lend a hand in making the libre release work better.

**Comment by patogit** [comment]
If someone tells me the difference, or points me to a place it's explained, I'm happy to make the changes and submit a pull request.  Any hints?

**Comment by TheFrenchGhosty** [comment]
Release: Standard

Libre: No decency on Google Play Service (APK seems broken right now though: https://github.com/jellyfin/jellyfin-android/issues/327#issuecomment-620409714 )

Debug: Not for end users
