### ISSUE TITLE
Cannot click play when casting to Chromecast

### ISSUE THREAD

**Issue by owenashurst** [jellyfin/jellyfin-android#338]
When ever I start casting to Chromecast, I cannot click play on any video in the app. If I disconnect then I can play the video fine.

Device: OnePlus 5T
Android : 9
OxygenOS: 9.0.11

**Comment by owenashurst** [comment]
Some people are having the same issue here https://github.com/jellyfin/jellyfin-android/issues/79

The solution for me was what @smoebody mentioned - change 'Secure connection mode' back to 'handled by reverse proxy' and disable automatic port mapping.

It would be nice to have a decent message for this though as simply not doing anything is a bit of a bad user experience.

**Comment by stokbaek** [comment]
Had same issue. I am running it inside a Kubernetes clustere so I am behind a proxy, so I had already done the steps @owenashurst has posted, but it still didn't work.    
I had to go into "Add Server" on my phone app and add it with its public domain and chromecast started to work perfectly.

Hope this can help others, as I spend half a day figuring out what was missing.

**Comment by owenashurst** [comment]
> Had same issue. I am running it inside a Kubernetes clustere so I am behind a proxy, so I had already done the steps @owenashurst has posted, but it still didn't work.
> I had to go into "Add Server" on my phone app and add it with its public domain and chromecast started to work perfectly.
> 
> Hope this can help others, as I spend half a day figuring out what was missing.

Yeah good shout, even though I host it on my home server, I've got an nginx reverse proxy to the docker container so that I can access it over SSL on a public domain.

**Comment by thornbill** [comment]
Sounds like this is a duplicate of #79.
