### ISSUE TITLE
Quality above 1080p 15Mbps does not display an image on tablet

### ISSUE THREAD

**Issue by EliasGagnef** [jellyfin/jellyfin-android#340]
**Describe the bug**
When streaming 4k videos from Jellyfin to my Android tablet, I only get a black screen (I do hear the audio playing), however, if i lower the quality to a maximum of 1080p 15Mbps, the video functions as expected, this issue is not present on my phone or TV.

**To Reproduce**
1. Set the quality above 1080p-15Mbps
2. Get a black screen.

**Screenshots**
![4k 120 Mbps](https://user-images.githubusercontent.com/46574798/114284740-593b8200-9a52-11eb-8ea4-f40acd7641d8.jpg)
![1080p 60 Mbps](https://user-images.githubusercontent.com/46574798/114284749-66f10780-9a52-11eb-98b4-87f217d47ec3.jpg)
![1080p 15 Mbps](https://user-images.githubusercontent.com/46574798/114284763-77a17d80-9a52-11eb-992d-384150728dd1.jpg)

**System (please complete the following information):**
 - App version: [2.2.3]
 - Android version: [Android 10]
 - Device manufacturer and model: [Samsung Tab A7]
 - Jellyfin server version: [10.7.1]
 - The type of video player implementation used: [web player] (video does not start with Native player)

**Additional context**
I have tried with the Jellyfin Beta and stable client, no luck.

This issue is really weird considering it works on my phone and TV, would anybody know if this is fixable? thank you very, very much :)

**Comment by Maxr1998** [comment]
This is probably unrelated to the bitrate, and instead caused by your tablet not supporting a certain codec. Lowering the bitrate enough forces a transcode which fixes that issue.
Could you add some more (technical) information on the played file?

**Comment by EliasGagnef** [comment]
> 
> 
> This is probably unrelated to the bitrate, and instead caused by your tablet not supporting a certain codec profile/level. Lowering the bitrate enough forces a transcode which "fixes" that issue.
> Could you add some more (technical) information on the played file?

Absolutely, would this be the correct technical information?

(with 4k quality, black screen)

![4k](https://user-images.githubusercontent.com/46574798/114302818-136ed000-9acb-11eb-9095-73a53e407223.jpg)

**Comment by Maxr1998** [comment]
Sorry for the late reply, it seems the higher bitrate is also transcoding. 62 fps transcoding framerate should normally be enough, but it could still be a server issue. Does it work in a browser when streaming with quality selected?

**Comment by EliasGagnef** [comment]
> Sorry for the late reply, it seems the higher bitrate is also transcoding. 62 fps transcoding framerate should normally be enough, but it could still be a server issue. Does it work in a browser when streaming with quality selected?

Absolutely no problems (I am also sorry about the late reply, just saw the notification :p), the same black screen appears (rather just the thumbnail of the movie) when streaming via a browser when I select any quality above 1080p 20 Mbps

![bild](https://user-images.githubusercontent.com/46574798/155817934-5975db37-afb0-48d0-b4d6-5ddad72ecd9f.png)

![bild](https://user-images.githubusercontent.com/46574798/155817955-897895b8-0238-447b-b289-4d3bb131fc15.png)

**Comment by Maxr1998** [comment]
I see, it's possible the server cannot keep up with transcoding, or it's a server bug. You should check the ffmpeg transcoding logs on the server, those could give a hint on what's wrong.

**Comment by EliasGagnef** [comment]
I think my server should be keeping up with it? It has a Ryzen 5 1600x, a 1070ti and 32GB RAM, here's the transcoding log (I couldn't find anything in it)

[FFMPEG Transcode Log.txt](https://github.com/jellyfin/jellyfin-android/files/8190873/FFMPEG.Transcode.Log.txt)

**Comment by EliasGagnef** [comment]
This issue is still present :/

**Comment by EliasGagnef** [comment]
I should also add that this issue is present on the Samsung Tab A8 (2022) as well as the A7 (2020).

**Comment by EliasGagnef** [comment]
The issue is still present yo please don't remove it lol

**Comment by EliasGagnef** [comment]
pls donät close it, still happens

**Comment by Cifer9516** [comment]
Issue is present. On top of the that ExoPlayer ignores default transcode quality setting

**Comment by Cifer9516** [comment]
Might something to do with device HDR support.
Have tried multiple different android devices, some do tone mapping, and those that don't spit out an error untill you bump bitrate down to the point where it doesn't carry HDR data anymore.

**Comment by EliasGagnef** [comment]
pls no close

**Comment by EliasGagnef** [comment]
Still here

**Comment by EliasGagnef** [comment]
still happening
