### ISSUE TITLE
Doesn't reconnect when app restarted

### ISSUE THREAD

**Issue by agilob** [jellyfin/jellyfin-android#343]
**Describe the bug**

Application doesn't reconnect to chromecast when application is killed.

1. Play on chromecast
2. Klill app - even from those context apps
3. Turn on jellyfin
4. app detects chromecast but doesn't connect to it
5. disconnect from chromecast - does NOT disconnect or stop playing
6. start app
7. kill app
8. start app
9. connect to chromecast
10. finally able to control and see status of playback on chromecast

**Expected behavior**
App should reconnect to chromecast on first restart as it did in early 2020 when jellyfin was published in custom fdroid

**Screenshots**

**System (please complete the following information):**
 - App version: 2.2.3
 - Android version: 7
 - Jellyfin server version: 10.7.2

**Comment by nielsvanvelzen** [comment]
> App should reconnect to chromecast on first restart as it did in early 2020 when jellyfin was published in custom fdroid

The F-Droid release does not support casting at all and it wasn't even available in early 2020.

**Comment by agilob** [comment]
>The F-Droid release does not support casting at

Jellyfin app is installed from GP.

>and it wasn't even available in early 2020.

There was a custom fdroid repo, not the official one that supported chromecast.

**Comment by agilob** [comment]
@Maxr1998 please move to jellyfin-chromecast

**Comment by Maxr1998** [comment]
This does relate to this app, so no.

**Comment by agilob** [comment]
bad bot
