### ISSUE TITLE
Remote controlling an android device: the web client won't show metadata. Most controls missing or buggy

### ISSUE THREAD

**Issue by stormwatch** [jellyfin/jellyfin-android#344]
Please excuse me if this is a duplicate or if this belongs in the web client's repo. Also: this issue could be subdivided into many.

# What almost works
- toggle play/pause button: altough it won't change the icon accordingly. It wil always show the pause icon.
- Volume control: The volume changes to the intended value but the slidebar will return immediately to the left. Most of the time this effectively results in the audio beeing muted unless I quickly change the focus in the UI.

# What doesn't work:
- metadata: display current song title, performer, position in mm:ss.
- repeat button.
- navigation: prev, next, seekbar, show the playlist.

# remote control view on the web client
![Captura de pantalla de 2020-05-16 13-41-56](https://user-images.githubusercontent.com/824211/82125616-7d78db00-977d-11ea-8f58-431e3e341bfd.png)

# Screenshot of the dashboard
![Captura de pantalla de 2020-05-16 13-10-01](https://user-images.githubusercontent.com/824211/82125620-7eaa0800-977d-11ea-8309-1c9a7fdfd8c1.png)

**Comment by Artiume** [comment]
This might be fixed in nightly, I dont have these issues 
![image](https://user-images.githubusercontent.com/20715731/82126984-71414d80-977e-11ea-8879-1f17801fe05c.png)
