### ISSUE TITLE
Https not working (with and without a domain)

### ISSUE THREAD

**Issue by MarcelCoding** [jellyfin/jellyfin-android#344]
**Describe the feature you'd like**
Add support to use https without a domain.

**Additional context**
I have a Jellyfin in a Docker Container, in front of it is a Traefik which does https. I have a private ca for my home network. On my PC every works fine. On my mobile phone I have imported the ca and tried to use the Android App. It does not work. If I copy the link from the text field in the app to a browser on my phone, it works. (with the hostname witch is resolved by the dns server in my router) But usually on my mobile phone I use dns over https (all before was tested without dns over https), so I normally don't have access to hostnames. Android does not have a easy way to turn dns over https easy on and of. (I want to use is if I am outside.) The solution is to use the IP Address, but I am not able to use SSL with a IP Address:
![image](https://user-images.githubusercontent.com/34819524/115130324-3d565400-9fef-11eb-8960-af1e0569c2c3.png)
I've tested adding the IP address to the alt names but it didn't worked.

**Comment by nielsvanvelzen** [comment]
This is a not a feature request. Please re-open with the bug report template and provide requires information like your server, android and app versions.
