### ISSUE TITLE
basicauth for connecting to instance

### ISSUE THREAD

**Issue by calisro** [jellyfin/jellyfin-android#346]
Is it possible for this functionality to be added to the android app (and android TV but I realize that is a separate repo).  

https://github.com/jellyfin/jellyfin-kodi/issues/52

So its clear, i'm also not looking to use basicauth to authenticate users.  I'm only looking to not make the jellyfin server publicly known.

**Comment by constint** [comment]
Looks like a duplicate of https://github.com/jellyfin/jellyfin-android/issues/165
I'm interested in it too, but it doesn't seem very popular. I've never developed on this product but I might try to hack something together

**Comment by calisro** [comment]
Yes. Looks like a duplicate. I'll close those and 👍 that one.
