### ISSUE TITLE
Truncated preferences titles in client settings

### ISSUE THREAD

**Issue by ianjazz246** [jellyfin/jellyfin-android#350]
**Describe the bug**
In the Client Options page, the text of the options is truncated so the full text cannot be read.

**To Reproduce**
1. Open the Client Options page while in portrait mode

**Expected behavior**
Text should wrap or otherwise be entirely readable.

**Screenshots**

![Screenshot_20210501-200932](https://user-images.githubusercontent.com/35947093/116801151-dbe8b780-aabb-11eb-9c1b-734797ec824e.png)

**System (please complete the following information):**
 - App version: 2.2.3
 - Android version: Android 9
 - Device manufacturer and model: Motorola Moto G6
 - Jellyfin server version: 10.7.2
 - The type of video player implementation used: ExoPlayer

**Comment by Maxr1998** [comment]
Should be easy to fix, thanks for the heads-up.
