### ISSUE TITLE
Vertical videos are played horizontally

### ISSUE THREAD

**Issue by 97carmine** [jellyfin/jellyfin-android#354]
Using the mobile vertically, when playing the video, it automatically changes to horizontal and the video plays

![Screenshot_2020-06-04-21-43-08-350_org jellyfin mobile](https://user-images.githubusercontent.com/6619414/83804095-2049b880-a69d-11ea-8b4d-a8d39f030af6.jpg)

Using another player like VLC plays properly

![Screenshot_2020-06-04-21-44-01-100_org videolan vlc](https://user-images.githubusercontent.com/6619414/83804136-32c3f200-a69d-11ea-879d-44b86914f185.jpg)

**Comment by thornbill** [comment]
Duplicate of #306.
