### ISSUE TITLE
Offline mode for media (similar to Spotify and other music streaming apps)

### ISSUE THREAD

**Issue by TrentSaggus** [jellyfin/jellyfin-android#355]
**Describe the feature you'd like**
Spotify has the ability to Download media for offline consumption within the app itself. Currently Jellyfin's implimentation of this feature has the download option (which does not always appear) download the item to the device as a file on the device's file system, but the file is not available in an Offline mode within the app keeping media organised on the device. 

Additionally an option to download a whole TV season or whole Album/Playlist would also be very much appreciated (in addition to current implementation of downloading only 1 file at a time)

Spotify identifies Offline media by a green symbol consisting of a downward arrow inside a circle. The same notation could be used here.

**Additional context**
See the below screenshots for the Spotify implementation. Spotify allows for the download of entire playlists and albums. This would be good functionality in addition to individual items.

![Spotify - Combination of Downloaded and Non-Downloaded Items](https://user-images.githubusercontent.com/13411292/116963645-c1495500-acec-11eb-8182-aa1721b9c15e.jpg)
![Spotify - Download Button-Switch](https://user-images.githubusercontent.com/13411292/116963697-edfd6c80-acec-11eb-9ba5-74f7b9454450.jpg)
![Spotify - Downloading progress UI](https://user-images.githubusercontent.com/13411292/116963705-f35ab700-acec-11eb-8826-437872869f38.jpg)

See the below screenshots for the current (2.2.3) Implementation. No user feedback is given that download is taking place in current implementation.

![Jellyfin - Artist Options (No Download Option)](https://user-images.githubusercontent.com/13411292/116963720-01103c80-aced-11eb-8d16-88aaa50addcf.jpg)
![Jellyfin - Album Options (No Download Option)](https://user-images.githubusercontent.com/13411292/116963733-0a010e00-aced-11eb-8909-925274cba81d.jpg)
![Jellyfin - Track Options (Download Option Available)](https://user-images.githubusercontent.com/13411292/116963741-0f5e5880-aced-11eb-89fd-c47a5343a5f4.jpg)
![Jellyfin - Files go to Downloads and not playable within Jellyfin](https://user-images.githubusercontent.com/13411292/116963750-138a7600-aced-11eb-85ec-ad8c311f9992.jpg)

**Comment by TheKayneGame** [comment]
#139 this issue isn't too dissimilar from this one only this issue kinda died

**Comment by Maxr1998** [comment]
Not really, it's just not that easy to implement in a good way. Progress for the native client was already made in the `compose` branch and should continue soon :tm:.
