### ISSUE TITLE
Playback rate / speed option not working.

### ISSUE THREAD

**Issue by cegfault** [jellyfin/jellyfin-android#356]
**Describe the bug**

Playback speed / playback rate option is not working.  Playback rate continues at 1x regardless of setting used. This is working correctly in the web browser, but does not work on android.

**To Reproduce**

1. Go to watch any video
2. Click on settings wheel
3. Tap "Playback Rate"
4. Change playback rate to something besides "1x"
5. Observe that playback continues at 1x regardless of change in (4)

**Expected behavior**

Playback rate expected to change due to change in setting.

**Logs**

**Screenshots**

**System (please complete the following information):**
 - App version: 2.2.3
 - Android version: Android 10
 - Device manufacturer and model: Multiple phones and tables (Google pixel 5, Moto g5, Samsung SM-T510, etc)
 - Jellyfin server version: (rolling nightly release)
 - The type of video player implementation used: Integrated

**Additional context**

Opening and playing in the web browser works correctly (implying the server and web clients are working fine). This bug only exists on android app.

**Comment by Maxr1998** [comment]
Works in my tests, could you add some details on the played media is this is still an issue?

**Comment by cegfault** [comment]
This appears to be working now. Closing.
