### ISSUE TITLE
Jellyfin for Android 2.0.0 release plan

### ISSUE THREAD

**Issue by nielsvanvelzen** [jellyfin/jellyfin-android#36]
# Release plan
1. Tag release candidate 2
   - Only available via GitHub, should be tested by people that can report issues
   - When any issues arise start work on a new release candidate before proceeding
2. Create a new (public) beta channel on Google Play
3. Push the release candidate to the beta channel
   - When any issues arise start work on a new release candidate and push it to the beta channel
4. Wait at least 1 week to catch issues from late users
5. Release 2.0.0
    - Tag 2.0.0
    - Promote the beta channel to stable
    - Update app on the Amazon Appstore
5. Re-apply for F-Droid (our previous request is based on the old Cordova app which does not exist anymore)

**Comment by TheFrenchGhosty** [comment]
Any idea of how long it would take to get to the full release? 1 month? 6 month?

I'm really looking forward to it, good luck on the job that you will have to do!

**Comment by nielsvanvelzen** [comment]
Hopefully not that long for now, it seems like we do have some issues that still need to be fixed so we will be doing another release candidate for that. I can't promise anything but I'm hoping to hit stable before October.

**Comment by nielsvanvelzen** [comment]
I pushed the third release candidate! It now uses a valid semver name (the dot between rc and 3 was missing in previous releases).

https://github.com/jellyfin/jellyfin-android/releases/tag/v2.0.0-rc.3

**Comment by Maxr1998** [comment]
> edit: I'm glad we're doing the release candidates because I broke the build once again! :)

Why, but how did it pass earlier? :laughing:

**Comment by nielsvanvelzen** [comment]
See #63

**Comment by anthonylavado** [comment]
> Create a new (public) beta channel on Google Play
> Push the release candidate to the beta channel
> 
>     When any issues arise start work on a new release candidate and push it to the beta channel

ok.

![2020-08-25 15_16_49-Open testing](https://user-images.githubusercontent.com/596194/91217886-3a1bfa00-e6e6-11ea-8594-13ca6f25f44a.png)

**Comment by anthonylavado** [comment]
https://play.google.com/apps/testing/org.jellyfin.mobile

**Comment by Feral2k** [comment]
I don't know whether this has been done or planned out yet, but I think we should consider adding support for either the Fastlane or Gradle Play Publisher style metadata structure in the repo as a necessary item on the checklist. The maintainers over at F-Droid really prefer, and possibly require, this structure in the repo rather than including that metadata directly in our merge request.

**Comment by nielsvanvelzen** [comment]
We haven't really planned anything for F-Droid yet, I included it originally because I know a lot of our users care about F-Droid (I personally don't use it a lot and don't have experience on publishing on F-Droid). After releasing 2.0.0 on the stores we're available right now (Google Play / Amazon Appstore) we can work towards a proper way to release on F-Droid.

I expect adding Fastlane or Gradle Play Publisher should be a requirement when adding the F-Droid support and not for the 2.0.0 release.

**Comment by nielsvanvelzen** [comment]
https://github.com/jellyfin/jellyfin-android/releases/tag/v2.0.0-rc.4

The next release candidate is ready 🎉 . I'm quite sure we need to do another one to fix/improve the errors from #44.

@anthonylavado can you upload it to the Google Play beta channel? 😄

**Comment by nielsvanvelzen** [comment]
Unfortunately we had a major issue (#116 and #119) that caused the app to crash in RC.4. We've identified the issue and fixed it in a new version:

https://github.com/jellyfin/jellyfin-android/releases/tag/v2.0.0-rc.5

**Comment by nielsvanvelzen** [comment]
https://github.com/jellyfin/jellyfin-android/releases/tag/v2.0.0-rc.6 🥳 

---

@Maxr1998 and I decided to have promote the current RC6 to stable somewhere next week which will bump all our users from the old Cordova app to the rewrite. We're aware that not everything works perfectly and some users might have some issues, depending on how fast we release 2.1 we might release a 2.0.1 version first.

**Comment by neopc10** [comment]
Is Google Cast support planned for 2.1?

**Comment by Maxr1998** [comment]
> Is Google Cast support planned for 2.1?

Google Cast is already supported, as long as your server setup is working. There are some confirmed issues with reverse proxys right now.
However, this isn't the best place to ask such questions, if you need further details/help, I'd suggest you to jump over into our Matrix groups.

**Comment by nielsvanvelzen** [comment]
https://github.com/jellyfin/jellyfin-android/releases/tag/v2.0.0-rc.7

This should definitely be the last RC. Only if critical issues (like the discovery bug) appear we'll do another RC. Other issues will go to 2.0.1 and features are scheduled for 2.1.0.

**Comment by CarlosOlivo** [comment]
> https://github.com/jellyfin/jellyfin-android/releases/tag/v2.0.0-rc.7
> 
> This should definitely be the last RC. Only if critical issues (like the discovery bug) appear we'll do another RC. Other issues will go to 2.0.1 and features are scheduled for 2.1.0.

Like this? https://github.com/jellyfin/jellyfin-android/pull/146#issuecomment-700897931

**Comment by Maxr1998** [comment]
> Like this? [#146 (comment)](https://github.com/jellyfin/jellyfin-android/pull/146#issuecomment-700897931)

:sob:

**Comment by nielsvanvelzen** [comment]
I've made #157 to hopefully prevent these kinds of issues in the future. RC8 is ready and should again be the last one.

https://github.com/jellyfin/jellyfin-android/releases/tag/v2.0.0-rc.8

**Comment by nielsvanvelzen** [comment]
We're aiming to release 2.0.0 tomorrow. It might take a bit before it passes the review processes but hopefully it's up in around 24 hours from now.

**Comment by nielsvanvelzen** [comment]
- Release tagged (https://github.com/jellyfin/jellyfin-android/releases/tag/v2.0.0)
- Blog post published (https://jellyfin.org/posts/android-next/)

Now it's waiting time for the app stores after @anthonylavado published the app.

**Comment by nielsvanvelzen** [comment]
I'll close this issue since 2.0.0 and 2.0.1 are released now. Feel free to join or Matrix channels for release questions (although we can't give ETA's most of the time).
