### ISSUE TITLE
App crashes when trying to play a video without suitable playback methods

### ISSUE THREAD

**Issue by xd003** [jellyfin/jellyfin-android#370]
**Describe the bug**
App simply crashes when i am attempting to play a video file

**Logs**
https://del.dog/gharewylec

**System (please complete the following information):**
 - App version: v2.3.0-beta.1
 - Android version: Android 10
 - Device manufacturer and model: Redmi Note 3
 - Jellyfin server version: 10.7.5
 - The type of video player implementation used: native player (ExoPlayer)

**Additional context**
1) Media Info Screenshots below
![Screenshot_20210507-163448286_1_1](https://user-images.githubusercontent.com/26503185/117441005-6b75e680-af52-11eb-93a0-5d891a743fee.jpg)
![Screenshot_20210507-163456442_1](https://user-images.githubusercontent.com/26503185/117441022-729cf480-af52-11eb-8d3c-0f7b96f2dd48.jpg)

2) Media Playback settings
![Screenshot](https://user-images.githubusercontent.com/26503185/117469075-f666d900-af72-11eb-9b8c-39c309d18d6a.jpg)

**Comment by Maxr1998** [comment]
ExoPlayer doesn't support the audio without transcoding. Thus, playback is unsupported. Instead of crashing, it should show an error message however. Thanks for the report!

**Comment by xd003** [comment]
> ExoPlayer doesn't support the audio without transcoding. Thus, playback is unsupported. Instead of crashing, it should show an error message however. Thanks for the report!

I beleive meant audio transcoding here , ```Allow audio playback that requires transcoding``` this option is enabled in my server. I have disabled only the video transcoding as my vps is not good enough to handle that

**Comment by Maxr1998** [comment]
Remuxing video content (which is required for audio transcoding aka direct stream) counts as "video transcoding" iirc. It should work if you enable that.

**Comment by nielsvanvelzen** [comment]
I think "audio playback that requires transcoding" means audio-only files like music. If you need to transcode the audio channels inside of a video file you still need to enable transcoding for videos.

**Comment by hackmonker** [comment]
That's odd exoplayer is perfectly playing Dolby digital + in other files but transcoding in some?

**Comment by hackmonker** [comment]
emby's internal player direct plays the same file while jellyfin does not. and they both use exoplayer an the native right?

**Comment by nielsvanvelzen** [comment]
Emby is a different app

**Comment by hackmonker** [comment]
i know was not comparing, just was curious since they both use the same player but one transcodes and the other direct plays

**Comment by Maxr1998** [comment]
Our ExoPlayer doesn't support Dolby Digital since we don't bundle the ffmpeg extension *yet*.

**Comment by hackmonker** [comment]
Oh I see, thanks for clearing that out. appreciate it. any plans to include it later?

**Comment by Maxr1998** [comment]
Yes, I still need to figure out however on how to include it without making development a pain for the other contributors. Setting up the NDK and building ffmpeg is quite some extra work that casual contributors shouldn't have to do.

**Comment by hackmonker** [comment]
Ah thanks. Then the only thing is is instead of saying it is not supported, it crashes. I guess that is the only bug I faced yet
