### ISSUE TITLE
Crash when trying to play using external player

### ISSUE THREAD

**Issue by MBR-0001** [jellyfin/jellyfin-android#371]
**Describe the bug**
The app crashes when trying to play a video with `Video player type` set to `External player`, both with `External player app` set to `System default` and `VLC Player`

**To Reproduce**
1. Set video player type to external player in client settings
2. Try to play a video

**Expected behavior**
The app opens the video in the external player

**Logs**
```AndroidRuntime: FATAL EXCEPTION: main
05-07 22:05:28.108  7273  7273 E AndroidRuntime: Process: org.jellyfin.mobile, PID: 7273
05-07 22:05:28.108  7273  7273 E AndroidRuntime: java.lang.NullPointerException
05-07 22:05:28.108  7273  7273 E AndroidRuntime:        at org.jellyfin.mobile.bridge.ExternalPlayer$initPlayer$1.invokeSuspend(ExternalPlayer.kt:5)
05-07 22:05:28.108  7273  7273 E AndroidRuntime:        at n.n.k.a.a.resumeWith(ContinuationImpl.kt:3)
05-07 22:05:28.108  7273  7273 E AndroidRuntime:        at o.a.l0.run(DispatchedTask.kt:18)
05-07 22:05:28.108  7273  7273 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:938)
05-07 22:05:28.108  7273  7273 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:99)
05-07 22:05:28.108  7273  7273 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:223)
05-07 22:05:28.108  7273  7273 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:7660)
05-07 22:05:28.108  7273  7273 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
05-07 22:05:28.108  7273  7273 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
05-07 22:05:28.108  7273  7273 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

**Screenshots**

https://user-images.githubusercontent.com/55142207/117506034-3b940680-af85-11eb-8943-4c43c91a600c.mp4

**System (please complete the following information):**
 - App version: 2.3.0-beta.1
 - Android version: 11 (LineageOS 18.1)
 - Device manufacturer and model: Oneplus 3T
 - Jellyfin server version: 10.7.5
 - The type of video player implementation used: external player (VLC)

**Additional context**
Didn't happen in previous version

**Comment by nielsvanvelzen** [comment]
What type of video are you trying to play? (movie, episode etc.)
Does this issue happen for the native player too?

**Comment by MBR-0001** [comment]
Native player does not have this issue, it happens when trying to play both movies and episodes

**Comment by nielsvanvelzen** [comment]
https://github.com/jellyfin/jellyfin-android/blob/3e15ad49ba7274d13800370c9061a2159eed4ab6/app/src/main/java/org/jellyfin/mobile/bridge/ExternalPlayer.kt#L81

CC @Maxr1998 I think this line might be the culprit, you recently touched it so you might know some more about it.

**Comment by eltiel** [comment]
Same thing happening here. Both VLC and MX will crash.

**Comment by CarlosOlivo** [comment]
> https://github.com/jellyfin/jellyfin-android/blob/3e15ad49ba7274d13800370c9061a2159eed4ab6/app/src/main/java/org/jellyfin/mobile/bridge/ExternalPlayer.kt#L81
> 
> CC @Maxr1998 I think this line might be the culprit, you recently touched it so you might know some more about it.

Yup, add `options.item.playOptions.mediaSourceId = options.item.Id` before `initPlayer`

https://github.com/jellyfin/jellyfin-android/blob/382066d0643d636372dcc9c6c8579c481c9cf3eb/app/src/main/assets/native/ExternalPlayerPlugin.js#L43-L49

https://github.com/jellyfin/jellyfin-android/blob/382066d0643d636372dcc9c6c8579c481c9cf3eb/app/src/main/java/org/jellyfin/mobile/bridge/ExternalPlayer.kt#L76-L81

---

Or replicate `NativePlayer` behaviour (Probably not necessary for external players?)

https://github.com/jellyfin/jellyfin-android/blob/382066d0643d636372dcc9c6c8579c481c9cf3eb/app/src/main/assets/native/ExoPlayerPlugin.js#L24-L27

https://github.com/jellyfin/jellyfin-android/blob/382066d0643d636372dcc9c6c8579c481c9cf3eb/app/src/main/java/org/jellyfin/mobile/player/source/MediaQueueManager.kt#L45-L54
