### ISSUE TITLE
App crashes when tapping play without going to episode page first

### ISSUE THREAD

**Issue by viggy96** [jellyfin/jellyfin-android#372]
**Describe the bug**
When trying to play an episode directly from the Jellyfin home page or the season page of a show, the app crashes. This occurs with both ExoPlayer and external (using mpv at the moment). 
If I first go to the episode page, then tap the play button, crash does not occur.

**To Reproduce**

1. Go to Jellyfin home or season page of show
2. Tap play button on episode
3. App crashes (profit)

**Expected behavior**
Playback occurs normally.

**Logs**
[jellyfin-android.log](https://github.com/jellyfin/jellyfin-android/files/6445984/jellyfin-android.log)

**System (please complete the following information):**
 - App version: 2.3.0-beta.1
 - Android version: Android 10, LineageOS 17.1
 - Device manufacturer and model: Moto X4
 - Jellyfin server version: 10.7.5
 - The type of video player implementation used: mpv

**Additional context**
I have tried clearing app data. Issue still occurs.

**Comment by nielsvanvelzen** [comment]
```
05-08 10:20:59.199  7731  7731 E AndroidRuntime: FATAL EXCEPTION: main
05-08 10:20:59.199  7731  7731 E AndroidRuntime: Process: org.jellyfin.mobile, PID: 7731
05-08 10:20:59.199  7731  7731 E AndroidRuntime: java.lang.NullPointerException
05-08 10:20:59.199  7731  7731 E AndroidRuntime: 	at org.jellyfin.mobile.bridge.ExternalPlayer$initPlayer$1.invokeSuspend(ExternalPlayer.kt:5)
05-08 10:20:59.199  7731  7731 E AndroidRuntime: 	at n.n.k.a.a.resumeWith(ContinuationImpl.kt:3)
05-08 10:20:59.199  7731  7731 E AndroidRuntime: 	at o.a.l0.run(DispatchedTask.kt:18)
05-08 10:20:59.199  7731  7731 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:883)
05-08 10:20:59.199  7731  7731 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:100)
05-08 10:20:59.199  7731  7731 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:214)
05-08 10:20:59.199  7731  7731 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7356)
05-08 10:20:59.199  7731  7731 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
05-08 10:20:59.199  7731  7731 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
05-08 10:20:59.199  7731  7731 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:940)
```

This is the relevant exception from your logs. Looks the same as #371 so closing it as duplicate.
