### ISSUE TITLE
https://github.com/jellyfin/jellyfin-android/issues/373#issuecomment-837035470

### ISSUE THREAD

**Issue by willymilkytron** [jellyfin/jellyfin-android#375]
_Reading comments it's **hard** lol_ @Maxr1998 

https://github.com/jellyfin/jellyfin-android/issues/373#issuecomment-837032595

> Sure, but the non beta doesn't work with 10.7.0-1 (production) which you're pushing since you will drop in the next release, which is a really really really bad practice btw

**Comment by willymilkytron** [comment]
Also, i find locking threads more rude that all my previous comments :D

**Comment by thornbill** [comment]
This is a formal warning. This behavior is unacceptable.
