### ISSUE TITLE
bottom play bar doesn't hide

### ISSUE THREAD

**Issue by osias10** [jellyfin/jellyfin-android#379]
when I play a video with android jellyfin app, if I click the setting button(gear icon), then bottom play bar never hide

**Comment by dmitrylyzo** [comment]
Do you just open preferences and leave popup (preferences) open?

**Comment by ThibaultNocchi** [comment]
I do have the same problem when selecting a different resolution than the one I loaded the player with. If I open the gear menu, playback info or simply opening the resolutions menu, it's fine. Once I change resolution, the overlay won't disappear. But it also happens in mobile Chrome (not FF).

**Comment by Jerk-Solutions** [comment]
Same problem when pausing video. It doesn't go away unless the playback is stopped and started again

**Comment by thornbill** [comment]
This seems to be a duplicate of #377
