### ISSUE TITLE
Webview is too old, but I just installed ROM and GApps (2.3.0-beta1)

### ISSUE THREAD

**Issue by Salamandar** [jellyfin/jellyfin-android#383]
The Webview version Jellyfin-Android requires is 88. My system only provides com.android.webview 83.

The "check for updates" button redirects to the Play store, but the store doesn't seem to find the app.

Also I tried installing the webview I could find on the Play store, it's com.google.android.webview 90, but it does not help the issue.

FYI, the rom is POSP and the gapps package is NikGApps. My android knowledge isn't great, IDK if the webview you're expecting is provided by the system, the default browser, or the gapps.

**Comment by Maxr1998** [comment]
It seems that the system still uses the outdated webview. Developer Options → WebView Implementation in Android Settings.

**Comment by CarlosOlivo** [comment]
> It seems that the system still uses the outdated webview. Check Developer Options → WebView Implementation in Android Settings.

Maybe add a shortcut to "WebView Implementation" activity in the dialog? See https://developer.android.com/reference/android/provider/Settings#ACTION_WEBVIEW_SETTINGS

```
if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.N) {
        setNeutralButton("Change WebView Provider") { _, _ ->
            startActivity(Intent(Settings.ACTION_WEBVIEW_SETTINGS))
            requireActivity().finish()
        }
}
```

Also

> [On Android N-P, com.google.android.webview and com.android.chrome are mutually exclusive, due to “fallback logic.” Disabling (or enabling) Chrome will enable (or disable) the WebView stub. See Important notes for N-P for more information.](https://chromium.googlesource.com/chromium/src/+/HEAD/android_webview/docs/webview-providers.md#:~:text=On%20Android%20N-P%2C%20com.google.android.webview%20and%20com.android.chrome%20are%20mutually%20exclusive%2C%20due%20to%20%E2%80%9Cfallback%20logic.%E2%80%9D%20Disabling%20(or%20enabling)%20Chrome%20will%20enable%20(or%20disable)%20the%20WebView%20stub.%20See%20Important%20notes%20for%20N-P%20for%20more%20information.)

**Comment by Maxr1998** [comment]
Good idea. That could be added to the dialog as well.

**Comment by nielsvanvelzen** [comment]
We might want to add an "ignore" button that allows the user to still use the app. We won't provide support for the web parts in that case but some alternative webview implementations won't work otherwise.

**Comment by gappleto97** [comment]
Please do. This app is otherwise unusable on my Fire tablet

**Comment by Bandid0** [comment]
I have the same problem on my Huawei MediaPad M6 tablet

**Comment by Salamandar** [comment]
Yes, 88 is way too recent to be a requirement.

I changed the webview implem in the dev options but you can't expect the average user to do so.

**Comment by nielsvanvelzen** [comment]
I lowered the minimum version to chrome 80, which is the first release of 2020. I know jellyfin-web should work reasonably on it for webos/tizen although no guarantees on all functionality is given.

**Comment by Salamandar** [comment]
Thanks a lot @nielsvanvelzen , I think that will help a lot more support.

**Comment by nielsvanvelzen** [comment]
Second beta version is now released on the Play Store (F-Droid might take a while). This issue should be fixed, but if it's not please open a new issue.

**Comment by Salamandar** [comment]
@nielsvanvelzen The fix you provide isn't perfect as it doesn't allow the user to discard the warning message.

**Comment by nielsvanvelzen** [comment]
You can't discard the message about no webview available because the app doesn't work without one. The version check is discardable.

**Comment by Salamandar** [comment]
My bad, I thought you only reduced the required version.

**Comment by Derkades** [comment]
I'm getting this now on Android 12, does it also check for a maximum version?

**Comment by Maxr1998** [comment]
It doesn't, that sounds more like it uses a wrong WebView variant. Could you check your WebView implementation in the Android developer settings?

**Comment by Derkades** [comment]
Unfortunately not, other apps (like Pocket Casts) were giving webview errors as well so I reverted back to Android 11. Only now I see your comment..

**Comment by static-void** [comment]
Not sure if anyone is still watching this issue, but installing chrome fixed the "Webview outdated" message on my nexus 7 2012 (AOSP 7.1.2 with pico gapps). This would be a useful thing to add to the message as I didn't realise it was even related to chrome and went through reinstalling my entire ROM until I noticed the comment here from @CarlosOlivo. Previously I pressed "Ignore" and music would play but no video. 

Offtopic but: I am blown away that I can play hevc video on this tablet from 2012 with Jellyfin+NVENC transcoding, and really minimal configuration. The Jellyfin app is so responsive it's like its a new tablet. I've got 5 of these tablets and have set them up all over the house for music and video, it's so awesome!

**Comment by outusuke** [comment]
> It seems that the system still uses the outdated webview. Check Developer Options → WebView Implementation in Android Settings.

on my tv box there is no such option, and I get stuck on the home screen after configuring the host ip, webview v44

**Comment by nielsvanvelzen** [comment]
We have a [separate app](https://github.com/jellyfin/jellyfin-androidtv) for televisions.
