### ISSUE TITLE
Crash after pre-roll intro

### ISSUE THREAD

**Issue by Electry** [jellyfin/jellyfin-android#397]
**Describe the bug**
The Jellyfin app crashes after a pre-roll intro is finished. This seems to be a regression in v2.3.0-beta.2 (everything was fine in v2.3.0-beta.1).

**To Reproduce**
1. Install and configure the jellyfin-plugin-intros (https://github.com/dkanada/jellyfin-plugin-intros) on your server (I'm using local .mp4 preroll)
2. Make sure Cinema mode is enabled in Jellyfin settings -> Playback
3. Click on any video (movie/episode) to start the playback
4. The pre-roll plays just fine
5. After the pre-roll is finished, the Jellyfin app crashes (back to the android launcher). This happens even if you click the "Next" button in exoplayer while the pre-roll is playing (to continue to the actual movie/episode).

**Expected behavior**
After the pre-roll intro ends, the selected movie/episode should play.

**Logs**
```
05-22 13:53:16.437 28607 28607 E AndroidRuntime: FATAL EXCEPTION: main
05-22 13:53:16.437 28607 28607 E AndroidRuntime: Process: org.jellyfin.mobile, PID: 28607
05-22 13:53:16.437 28607 28607 E AndroidRuntime: java.lang.ClassCastException: l.r.j.a cannot be cast to org.jellyfin.mobile.player.source.JellyfinMediaSource
05-22 13:53:16.437 28607 28607 E AndroidRuntime: 	at org.jellyfin.mobile.player.source.MediaQueueManager.next(MediaQueueManager.kt:15)
05-22 13:53:16.437 28607 28607 E AndroidRuntime: 	at org.jellyfin.mobile.player.PlayerViewModel$skipToNext$1.invokeSuspend(PlayerViewModel.kt:4)
05-22 13:53:16.437 28607 28607 E AndroidRuntime: 	at l.r.k.a.a.resumeWith(ContinuationImpl.kt:3)
05-22 13:53:16.437 28607 28607 E AndroidRuntime: 	at m.a.h2.f.a(DispatchedContinuation.kt:24)
05-22 13:53:16.437 28607 28607 E AndroidRuntime: 	at k.a.a.f.G2(Unknown Source:1)
05-22 13:53:16.437 28607 28607 E AndroidRuntime: 	at m.a.c.y0(AbstractCoroutine.kt:15)
05-22 13:53:16.437 28607 28607 E AndroidRuntime: 	at k.a.a.f.I1(Unknown Source:5)
05-22 13:53:16.437 28607 28607 E AndroidRuntime: 	at k.a.a.f.J1(Unknown Source:3)
05-22 13:53:16.437 28607 28607 E AndroidRuntime: 	at org.jellyfin.mobile.player.PlayerViewModel.skipToNext(PlayerViewModel.kt:1)
05-22 13:53:16.437 28607 28607 E AndroidRuntime: 	at org.jellyfin.mobile.player.PlayerFragment.onSkipToNext(PlayerFragment.kt:1)
05-22 13:53:16.437 28607 28607 E AndroidRuntime: 	at org.jellyfin.mobile.player.PlaybackMenus._init_$lambda-1(PlaybackMenus.kt:1)
05-22 13:53:16.437 28607 28607 E AndroidRuntime: 	at b.a.b.z.g.onClick(lambda:1)
05-22 13:53:16.437 28607 28607 E AndroidRuntime: 	at android.view.View.performClick(View.java:7259)
05-22 13:53:16.437 28607 28607 E AndroidRuntime: 	at android.view.View.performClickInternal(View.java:7221)
05-22 13:53:16.437 28607 28607 E AndroidRuntime: 	at android.view.View.access$3800(View.java:821)
05-22 13:53:16.437 28607 28607 E AndroidRuntime: 	at android.view.View$PerformClick.run(View.java:27716)
05-22 13:53:16.437 28607 28607 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:883)
05-22 13:53:16.437 28607 28607 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:100)
05-22 13:53:16.437 28607 28607 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:227)
05-22 13:53:16.437 28607 28607 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7842)
05-22 13:53:16.437 28607 28607 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
05-22 13:53:16.437 28607 28607 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
05-22 13:53:16.437 28607 28607 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:980)
05-22 13:53:16.447  1790  3357 W ActivityTaskManager:   Force finishing activity org.jellyfin.mobile/.MainActivity
```

**Screenshots**
none

**System (please complete the following information):**
 - App version: v2.3.0-beta.2
 - Android version: Android 10
 - Device manufacturer and model: Realme X2 Pro
 - Jellyfin server version: 10.7.5
 - The type of video player implementation used: ExoPlayer

**Additional context**
If you disable Cinema mode, the movie/episode plays just fine (with no intro of course).

**Comment by Maxr1998** [comment]
Could you try with the debug version so that we get a better stack trace? It seems one of the smart casts fails, which shouldn't even be possible.. :thinking:

**Comment by Maxr1998** [comment]
Quite likely to be a bug in the Coroutines library in combination with inline classes like `Result`. A very similar issue is tracked as [KT-46873](https://youtrack.jetbrains.com/issue/KT-46873), however, I'm not sure whether method visibility is the underlying cause here. Marking as upstream. A workaround would be migrating away from inline classes for the result for now.
