### ISSUE TITLE
Use EditorConfig from Android TV app

### ISSUE THREAD

**Issue by nielsvanvelzen** [jellyfin/jellyfin-android#4]
We have 2 Android apps now based on Kotlin. I think it would be a good thing to have the same styling guidelines for both of them. At this moment the android-next app uses spaces as indentation while Android TV chose to use tabs.

The EditorConfig for Android TV is [here](https://github.com/jellyfin/jellyfin-androidtv/blob/master/.editorconfig). We could just copy it over and reformat all Kotlin files.

**Comment by Maxr1998** [comment]
I see, while I'm personally not a fan of using tabs for indentation, I can still pull in config if the majority of the team is in favor. I mean, I don't want to start a flame-war. 😆

**Comment by dkanada** [comment]
I'm also not a fan of tabs.

**Comment by nielsvanvelzen** [comment]
It wasn't my intention to start a discussion. We already had that when choosing the indentation for the ATV app. We could use a different indentation for both repositories but it seems more logical to have the consistency.

**Comment by thornbill** [comment]
I encourage everyone to read this post on the topic. It certainly solidified my opinion to be firmly in favor of tabs.

https://www.reddit.com/r/javascript/comments/c8drjo/nobody_talks_about_the_real_reason_to_use_tabs/

**Comment by cromefire** [comment]
There are no half tabs

**Comment by cromefire** [comment]
Here's the official code style: https://kotlinlang.org/docs/reference/coding-conventions.html

Let's just use that
