### ISSUE TITLE
Change the black background of the subtitles to a transparent background.

### ISSUE THREAD

**Issue by JulioNahum** [jellyfin/jellyfin-android#42]
I detected a "bug" when playing a movie with subtitles in the new player with exoplayer. The background of the subtitles is black, instead of a transparent one. I hope I have made this publication correctly.

I have some examples of what this problem looks like right now:

https://imgur.com/PU3M16n

https://imgur.com/dQkgniM

**Comment by JulioNahum** [comment]
Now with the new application for Android, they are implementing the Exoplayer player, and perhaps later that error that the old application's web player has will be solved.

**Comment by nielsvanvelzen** [comment]
I think the "subtitle style" is based on your Android preferences. Can you try changing it according to [this help article from Google](https://support.google.com/accessibility/android/answer/6006554)?

**Comment by JulioNahum** [comment]
Yes. I did the step to see if that was the problem, and everything works fine. Thank you very much for the tip. I did not know, I did not know it. Another thing. Are you pending that there is a bug that causes the server's IP not to be recorded causing one to put the server's IP again?

**Comment by Maxr1998** [comment]
> Yes. I did the step to see if that was the problem, and everything works fine. Thank you very much for the tip. I did not know, I did not know it. Another thing. Are you pending that there is a bug that causes the server's IP not to be recorded causing one to put the server's IP again?

If there's an error, the client deletes the server IP and requests a reconnect. Maybe we should remove that code though, that it doesn't wipe the server address when there's only a network issue.

**Comment by JulioNahum** [comment]
Exact. It always happens when you disconnect from the network the server's ip is deleted. That's why I put that Issue. :)
