### ISSUE TITLE
After Sign out and opening the app again I got blank screen. I turned Wifi off, then it refreshed page.

### ISSUE THREAD

**Issue by martdu** [jellyfin/jellyfin-android#422]
I think I signed out from my Server (local network) then some hours later I opened the app again but it only showed a blank white screen. When I turned off Wifi it refreshed the page so that I could enter my newly created Server address and port.

**Comment by Genxster1998** [comment]
+1 I can't add new server and port it just stuck at old unreachable server blank webpage .So you can't add a new server at all.there should be a floating fab button at browser to enter new server  address .
