### ISSUE TITLE
The IP of the Jellyfin server is not saved in the new Android app.

### ISSUE THREAD

**Issue by JulioNahum** [jellyfin/jellyfin-android#43]
Sometimes you have to put the server's ip again to be able to enter it. I think it is a bug that future updates will be resolved.

**Comment by Maxr1998** [comment]
Replied here: https://github.com/jellyfin/jellyfin-android/issues/42#issuecomment-678824153

**Comment by Maxr1998** [comment]
Should be fixed with #50.
