### ISSUE TITLE
ASS Subtitles not working

### ISSUE THREAD

**Issue by willymilkytron** [jellyfin/jellyfin-android#45]
Playing video with embedded ASS subtitles doesn't display anything. This is reproducible with most of my video files with ASS subs.

**Comment by willymilkytron** [comment]
Only workaround is manually set subtitles to "Off" and the select the subs track again. This somethings triggers #46

**Comment by nielsvanvelzen** [comment]
Hi, I noticed this issue does not use one of our issue templates. We provide these templates to get the information necessary in order to help. I will close this issue but I encourage you to recreate it using the template so we can help.

**Comment by willymilkytron** [comment]
@nielsvanvelzen 

> We provide these templates to get the information necessary in order to help.

AFAIK there was no such thing when i opened this issue, but there you go https://github.com/jellyfin/jellyfin-android/issues/79

**Comment by Maxr1998** [comment]
> AFAIK there was no such thing when i opened this issue, but there you go #79

Yep, we only added them afterwards. Thanks for the new issue and the additional information!
