### ISSUE TITLE
Players cannot be switched on some models

### ISSUE THREAD

**Issue by yyxida** [jellyfin/jellyfin-android#453]
**Describe the bug**
On my Xperia xz1 Xperia z3c, I can't switch to exoplayer, but oneplus 7tpro can switch normally

**To Reproduce**
1. Enter the setting and switch to exoplayer or mxplayer
2. Play the video
3. It's still an HTML player

**Expected behavior**
Switch player

**Logs**
No, I need some time to find the computer

**Screenshots**
![Screenshot_20210626-025358](https://user-images.githubusercontent.com/22792135/123472471-cd38ff80-d629-11eb-9f8f-e68e73b494f3.png)
![Screenshot_20210626-025330](https://user-images.githubusercontent.com/22792135/123472478-cf02c300-d629-11eb-93bb-4d108a7db4de.png)

**System (please complete the following information):**
 - App version: 2.3.0 beta6
 - Device manufacturer , model and Android version: 
 
 Unable to switch：
 Xperia xz1(android9) Xperia Z3 (android6) 

Normal switch：
 OnePlus7tpro(OOS11,ANDROID 11)

 - Jellyfin server version: 10.7.5
 - The type of video player implementation used: web player , native player (ExoPlayer) or external player (mpv, VLC)

**Additional context**
nothing

**Comment by exalented** [comment]
This also happens with the N960F.

**Comment by CarlosOlivo** [comment]
It may be that the version of the webview is outdated in the Xperia devices unlike the OnePlus, it's the only conclusion that I can reach with the current information, definitely a logcat would help to identify the problem.

**Comment by yyxida** [comment]
> 与 OnePlus 不同，可能是 Xperia 设备中的 webview 版本已过时，这是我可以根据当前信息得出的唯一结论，绝对可以使用 logcat 来帮助识别问题。

[xperiaxz1logcat.txt](https://github.com/jellyfin/jellyfin-android/files/6758057/xperiaxz1logcat.txt)
Sorry to wait a long time, this is the log file (from switching player to playing).

By the way, （oneplus7tpro）the function of label burn subtitles can't work normally in the web player (display tofu), and can render subtitles normally in the exoplayer. I don't know if it has something to do with the current feedback (maybe). If not, I will open another one separately.

**Comment by CarlosOlivo** [comment]
Do you remember if you ever saw an outdated webview dialog like [this](https://user-images.githubusercontent.com/2305178/118377954-b0dc8880-b5d0-11eb-997f-3b2b4c5a75de.png), if you did, do you remember if you chose the ignore option?

I can't find the version of the webview in the logcat

`07-03 16:04:49.661  1271 12379 I ExtendedNuUtils: printFileName fd(8) -> /data/app/com.google.android.webview-_SCP-iTgZU_wWtwUBNXDhQ==/base.apk`

Can you try to update the latest version available? [Here](https://play.google.com/store/apps/details?id=com.google.android.webview).

---

> By the way, （oneplus7tpro）the function of label burn subtitles can't work normally in the web player (display tofu), and can render subtitles normally in the exoplayer. I don't know if it has something to do with the current feedback (maybe). If not, I will open another one separately.

On your OnePlus7tpro try to play the same video with the burn subtitles setting but from the web browser (Chrome for Android)

If the problem happens on Chrome for Android and Jellyfin App, open a new issue on [jellyfin-web](https://github.com/jellyfin/jellyfin-web/issues).

If the problem only happens in the Jellyfin App, open a new issue on [jellyfin-android](https://github.com/jellyfin/jellyfin-android/issues).

---

`07-03 16:04:45.210 21039 21039 E WebView : Uncaught TypeError: Cannot read property 'goBack' of undefined, https://www.xxxx.com:8920/web/#!/mypreferencesmenu.html (1)`

This should not happen.
Related to #456 (same device?)
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import#browser_compatibility

https://github.com/jellyfin/jellyfin-android/blob/cf755a87336aaf9c675a484224898dcce4194e0d/app/src/main/assets/native/nativeshell.js#L18-L30

https://github.com/jellyfin/jellyfin-android/blob/cf755a87336aaf9c675a484224898dcce4194e0d/app/src/main/assets/native/NavigationPlugin.js#L1-L16

**Comment by yyxida** [comment]
> Do you remember if you ever saw an outdated webview dialog like [this](https://user-images.githubusercontent.com/2305178/118377954-b0dc8880-b5d0-11eb-997f-3b2b4c5a75de.png), if you did, do you remember if you chose the ignore option?

WebView is the latest version, and I haven't seen the dialog you said
I cleared the app data（jellyfin）. Run again, fill in the configuration, switch the player, play the video, still don't see this dialog box, the problem still exists.
[newxz1logcat.txt](https://github.com/jellyfin/jellyfin-android/files/6762044/newxz1logcat.txt)

![image](https://user-images.githubusercontent.com/22792135/124422717-5e307900-dd96-11eb-9272-f4858edc82ce.png)



> This should not happen.

I found this problem, but it's too obvious, so I think you have noticed it and didn't mention it

**Comment by CarlosOlivo** [comment]
> [newxz1logcat.txt](https://github.com/jellyfin/jellyfin-android/files/6762044/newxz1logcat.txt)

Thank you for uploading another log, I found the problem, apparently only affects the versions prior to Android 11 on some devices

```
07-05 13:51:17.855 26056 26056 E WebView : Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "text/plain". Strict MIME type checking is enforced for module scripts per HTML spec., https://www.xxxx.com:8920/native/NavigationPlugin.js (0)
07-05 13:51:17.855 26056 26056 E WebView : Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "text/plain". Strict MIME type checking is enforced for module scripts per HTML spec., https://www.xxxx.com:8920/native/ExoPlayerPlugin.js (0)
07-05 13:51:17.857 26056 26056 E WebView : Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "text/plain". Strict MIME type checking is enforced for module scripts per HTML spec., https://www.xxxx.com:8920/native/ExternalPlayerPlugin.js (0)
07-05 13:51:17.859 26056 26056 W WebView : failed loading plugins TypeError: Failed to fetch dynamically imported module: https://www.xxxx.com:8920/native/NavigationPlugin.js, https://www.xxxx.com:8920/web/main.4b4b736dbefe7c3a90ec.bundle.js?deferred=true&ts=1625464276866 (2)
```

For example, in Android 9 [source code](https://android.googlesource.com/platform/libcore/+/refs/heads/pie-r2-release/luni/src/main/java/libcore/net/MimeUtils.java), javascript MIME type is not defined.

---

> > This should not happen.
> 
> I found this problem, but it's too obvious, so I think you have noticed it and didn't mention it
> After testing, there is no such problem on oneplus 7tpro.

The problem varies according to the version of Android and the manufacturer, but I did not realize before because I had no problem on my devices

So it works without problems in:
- One Plus 7t Pro (11)
- Xiaomi Poco F1 (11)
- Xiaomi Redmi Note 3 (6)
- Xiaomi Redmi 6 (9)
- Emulator (11)

But fails in:
- Xperia xz1 (9)
- Xperia Z3 (6)
- Emulator (5)
- And more probably ...

Will be fixed in the following beta, someday ...
