### ISSUE TITLE
h.264 stream cropping causes black video in Web Player

### ISSUE THREAD

**Issue by mtnakayama** [jellyfin/jellyfin-android#454]
**Describe the bug**
In the Web Player, videos play with a black picture if they have been created with the ffmpeg `h264_metadata` `crop_top` and `crop_bottom` bitstream filters. Audio will play, and seeking works properly. (Videos play back fine if you choose a lower bitrate and have the server encode it.)

(The attached Big Buck Bunny video also crashes the Native Player, but I am not sure whether it is related to this bug or not.)

**To Reproduce**
To create the video:
`ffmpeg -i [input video] -map 0 -codec copy -bsf:v h264_metadata=crop_top=8:crop_bottom=8 [output_video]`

Copy the video onto the Jellyfin server and play it back on the Android device.

Here is a clip of Big Buck Bunny with the filter already applied: 
[big_buck_cropped.zip](https://github.com/jellyfin/jellyfin-android/files/6736930/big_buck_cropped.zip)
(c) copyright 2008, Blender Foundation / www.bigbuckbunny.org

**Expected behavior**
Video should play back with picture (and hopefully with the cropping flags respected).

**Logs**
[logcat.zip](https://github.com/jellyfin/jellyfin-android/files/6736901/logcat.zip)

**System (please complete the following information):**
 - App version: 2.2.3
 - Android version: Android 11
 - Device manufacturer and model: Galaxy S10e SM-G970U
 - Jellyfin server version: 10.7.6
 - The type of video player implementation used: Web Player

**Additional context**
I have played this video successfully with other Android video players. But let me know if I should test this video with another video player app that uses the same API as Web Player.

**Comment by Maxr1998** [comment]
Could you try playing this file in the web player with your mobile and desktop browsers, e.g. Chromium or Firefox?

Could you also test whether the file plays using the integrated video player (see client settings in the app)?

**Comment by mtnakayama** [comment]
The video plays on Fiefox 89.0.2 and Chromium 91.0.4472.114 on desktop Linux.
The video plays on Firefox 89.1.1 on Android.

The video does *not* play correctly on Chrome 91.0.4472.120 on Android.

Playing the video with Jellyfin Android's Native player *crashes* the app to the home screen.

The video plays on the Samsung Video Player 7.3.10.60 (pre-installed on my phone).
The video plays on Google Photos 5.48.0.381899534.

**Comment by CarlosOlivo** [comment]
> The video plays on Firefox 89.1.1 on Android.
> The video does _not_ play on Chrome 91.0.4472.120 on Android (black video).

The application is currently a web wrapper, that is, if it fails in the Chrome browser, it will fail in the same way in the application.
Firefox uses the Gecko engine instead of Chrome with the Blink engine, maybe that's why it works

Checking the logcat, the webview reports that it fails to request the URL of the stream from the server

```
06-29 15:25:10.256 16856 16856 I WebViewFactory: Loading com.google.android.webview version 91.0.4472.120 (code 447212033)
...
06-29 15:26:06.072 12018 12018 E WebViewClientCompat: Received WebView error at http://192.168.29.248:8096/Videos/923302b584a95d5b94665fd3ab277659/stream.mov?Static=true&mediaSourceId=923302b584a95d5b94665fd3ab277659&deviceId=TW96aWxsYS81LjAgKExpbnV4OyBBbmRyb2lkIDExOyBTTS1HOTcwVSBCdWlsZC9SUDFBLjIwMDcyMC4wMTI7IHd2KSBBcHBsZVdlYktpdC81MzcuMzYgKEtIVE1MLCBsaWtlIEdlY2tvKSBWZXJzaW9uLzQuMCBDaHJvbWUvOTEuMC40NDcyLjEwMSBNb2JpbGUgU2FmYXJpLzUzNy4zNnwxNjI0NDQwNDg3MzQx&api_key=be94566a130345b088f96d1c8c03e738&Tag=d6e9adc51a1a0ab83f99f4d13ea1a5ea: net::ERR_FAILED
...
06-29 15:26:06.146 12018 12018 E WebViewClientCompat: Received WebView error at http://192.168.29.248:8096/Videos/923302b584a95d5b94665fd3ab277659/stream.mov?Static=true&mediaSourceId=923302b584a95d5b94665fd3ab277659&deviceId=TW96aWxsYS81LjAgKExpbnV4OyBBbmRyb2lkIDExOyBTTS1HOTcwVSBCdWlsZC9SUDFBLjIwMDcyMC4wMTI7IHd2KSBBcHBsZVdlYktpdC81MzcuMzYgKEtIVE1MLCBsaWtlIEdlY2tvKSBWZXJzaW9uLzQuMCBDaHJvbWUvOTEuMC40NDcyLjEwMSBNb2JpbGUgU2FmYXJpLzUzNy4zNnwxNjI0NDQwNDg3MzQx&api_key=be94566a130345b088f96d1c8c03e738&Tag=d6e9adc51a1a0ab83f99f4d13ea1a5ea: net::ERR_FAILED
```

Could you also add some Jellyfin server logs?, one when you try to play from Chrome 91.0.4472.120 and the other from Firefox 89.1.1 to see the differences. I suspect the DeviceProfile is different.

> Playing the video with Jellyfin Android's Native player crashes the app to the home screen.

> **System (please complete the following information):**
> 
> * App version: 2.2.3

You could also try the beta versions, these have several changes that may be relevant

- [GitHub](https://github.com/jellyfin/jellyfin-android/releases/latest)
- [F-Droid](https://f-droid.org/packages/org.jellyfin.mobile/)
- [Play Store](https://play.google.com/apps/testing/org.jellyfin.mobile)

**Comment by mtnakayama** [comment]
The cropped video does not crash anymore with the Native player in Android Version 2.3.0-beta.6. 
The crop is slightly incorrect, but it does display video!

However, it still displays with a blank video with the Web player in this version.
