### ISSUE TITLE
Back button click does not work

### ISSUE THREAD

**Issue by okan35** [jellyfin/jellyfin-android#456]
**Describe the bug**

Wherever you are in the app clicking back button does not work while clicking arrow top left to go back works.

**To Reproduce**

Open app and click back button.

**Expected behavior**

Back button should take me back to previous screen or exit the app.

**Logs**

**Screenshots**

**System (please complete the following information):**
 - App version: latest from google play store
 - Android version: Android 9
 - Device manufacturer and model: Sony Xperia xz premium
 - Jellyfin server version: latest from official website
 - The type of video player implementation used: default

**Additional context**

**Comment by Maxr1998** [comment]
It does work, just not for dialogs. That's an issue in Jellyfin Web, however.
