### ISSUE TITLE
"Features" filters gets automagically selected

### ISSUE THREAD

**Issue by lmas** [jellyfin/jellyfin-android#458]
**Describe the bug**
When selecting new filters, the "Features" filter (Subtitles, Trailers, Extras etc.) gets automagically selected and can't then be unselected, resulting in an empty movie/episode list.
Only way to reset filter settings is by deleting all app data in android.

**To Reproduce**
1. Go to a library
2. Click on Filter
3. Select/unselect any filter EXCEPT for "Features" filters
4. Go back, episode/movie list is empty
5. Click on Filter
6. All "Features" filters are selected

**Expected behavior**
- Only the user-selected filters should be toggled
- Be able to unselect "Features" filters

**System (please complete the following information):**
 - App version: 2.2.3 AND 2.3.0-beta.6
 - Android version: Android 11
 - Device manufacturer and model:Samsung Galaxy S6 Lite
 - Jellyfin server version: 10.7.6
 - The type of video player implementation used: native player (ExoPlayer)

**Comment by lmas** [comment]
Hmm just saw https://github.com/jellyfin/jellyfin-web/issues/2744, which is probably related.

**Comment by Maxr1998** [comment]
Yes, this is probably a duplicate of jellyfin/jellyfin-web#2744. Nonetheless, thanks for the report and linking the issue!
