### ISSUE TITLE
Download location option in client settings cannot be changed

### ISSUE THREAD

**Issue by Morgan-6Freedom** [jellyfin/jellyfin-android#479]
**Describe the bug**
There is no way to change the download location

**To Reproduce**

1. Go to Settings
2. Go to Client Settings
3. Scroll down to Download
4. Click on Download Location
5. The path cannot be changed

**Expected behavior**
It should be an input field or something else that can be changed

**Screenshots**

https://user-images.githubusercontent.com/49686866/127926273-62ba1f31-121a-477d-8827-0a8bc027430b.mp4

**System (please complete the following information):**
 - App version: 2.3.0
 - Android version: Android 10
 - Device manufacturer and model: One Plus 6T
 - Jellyfin server version: 0.7.6

**Comment by T1C1VV** [comment]
On my app I have 2 choices, which looked to be 2 default download folders.
Possibly Phone and SD card. Would love to be able to specify own/media folder.

App version: 2.4.1

**Comment by Maxr1998** [comment]
> On my app I have 2 choices, which looked to be 2 default download folders.
> Possibly Phone and SD card. Would love to be able to specify own/media folder.
> 
> App version: 2.4.1

Right, this was implemented since the issue was opened.
Unfortunately, custom folders are not possible with how the storage APIs in Android work, and since we don't want to request unnecessary permissions, we'll have to keep it the way it is.

**Comment by Paillat-dev** [comment]
It would be nice to be able to choose tho
