### ISSUE TITLE
Black screen when latest server is not available

### ISSUE THREAD

**Issue by DragoSpiro98** [jellyfin/jellyfin-android#506]
### Describe the bug

As I said in the title, if the last server is no longer accessible then at the start of the app appears a completely black screen (without allowing you to select a new server). The only way to "fix" this bug is to erase the app’s data and reopen the app.

### To Reproduce
_The best way to reproduce this bug is by using a mobile hotspot._
1. Active a mobile hotspot from another device
2. Connect your server (in my case it's my laptop) to the hotspot
3. Connect your android device to the hotspot
4. Enter in the server from your client (for now it works fine)
6. Close Jellyfin app
7. Restart the hotspot (switch off and power on)
8. Connect your server (you can also restart the server, it's the same for the bug because it's a client bug not a server bug)
9. Connect your android device to the hotspot
10. Open Jellyfin app

Now a black screen will appear because the server IP has changed and the client cannot connect to the previous IP.

### Application version

2.3.0

### Where did you install the app from?

Google Play

### Device information

Samsung Galaxy Tab S6 Lite

### Android version

Android 11

### Jellyfin server version

10.7.6

### Which video player implementations does this bug apply to?

- [ ] Web player (default)
- [ ] Integrated player (ExoPlayer)
- [ ] External player (VLC, mpv, MX Player)

**Comment by Maxr1998** [comment]
For 5., what do you mean with "close app"? Just putting the app into the background with the home button or exiting it with the back button?

Is the hotspot really necessary to reproduce it? How did you "connect" your server to the hotspot?

**Comment by DragoSpiro98** [comment]
> For 5., what do you mean with "close app"? Just putting the app into the background with the home button or exiting it with the back button?
> 
> Is the hotspot really necessary to reproduce it? How did you "connect" your server to the hotspot?
> 
> Shouldn't the server IP stay the same, too?

With "close app" I mean remove from recent app view, but you can also close by forcing it in the settings or with a restart/shutdown of the client.

I don't know, I think the bug occurs every time the latest server is unavailable. I wrote about using the hotspot because that’s what I use for now, so I am 100% sure that the problem is reproducible in the way I wrote. 

I connect the server through Wi-Fi (it's a simple android hotspot)

I'm not sure, probabily it's possible, but it's difficult to have static IP on an android hotspot (and as I said, for now I have only this). Also, the solution to use static IP "hides" the problem, it doesn’t solve it, because Jellyfin should give me the option to select another server if the latter is not available.

**Comment by Maxr1998** [comment]
I think I understand the issue now - you connected to the server running on a specific IP, which is saved to the settings, and then, when the server IP (not necessarily the client) changes, the stored IP doesn't work anymore but breaks the app. It should definitely show the server connection window in that case - there must be another bug in our connection logic. Actually, I was never able to reproduce this issue until earlier (where I only got it randomly), I didn't expect this issue to be so widespread.

**Comment by Maxr1998** [comment]
It looks that this black screen issue isn't even a direct fault of the app, but a result of an incorrectly entered server URL/problematic network setup, and the app not detecting those errors properly. I've improved the error handling in the app now  (so that it properly opens the connection screen on errors) and will open a PR shortly.

**Comment by DragoSpiro98** [comment]
Unfortunately the problem was not solved with #507

**Comment by Maxr1998** [comment]
Yeah, we're still tracking this in #493.
