### ISSUE TITLE
Android app no more connect after to config https access

### ISSUE THREAD

**Issue by jerome-diver** [jellyfin/jellyfin-android#511]
### Describe the bug

I have a Jellyfin server on Raspberry Pi 4B working nicely (installed from Raspbian package sources). Without HTTPS enabled it was working fine from my Android tablet device (Android-8.0.0).
Later on:
1. i installed "certbot" application helper client for Letsencrypt CA, 
2. then get a no-ip reverse DNS name pointing on my WAN dynamic IPv4 router address, 
3. then port forwarded 8096,8920,80,443. 
4. Then get certificat and keys from Letsencrypt with certbot tool in standalone mode (no NGINX or Apache used), 
5. then create/convert with onpenssl the PKCSK12 certificat including all that is required.
6. Created a bash script to get converted PKCS12 certificat and user name and group and read/write/exec access to 600 to this key for Jellyfin
6. Then, enable and start certbot.timer service with a post-hook on certbot to this script created.
7. Config Jellyfin network part to used this HTTPS with Letsencrypt CA PKCS12 created.
8. So tested it and it is working fine to rich a https from web browser from anywhere.

But now, from my Android jellyfin application, i get an infinite running time black screen.
I was supposed to attempt for the page about address to rich the server... 

PS: the options on Jellyfin config is to force HTTPS to be used

### Logs

```shell
How to get the log from my Android device ? (you are asking for the client logs... right ?)
```

### Application version

2.3.2

### Where did you install the app from?

Google Play

### Device information

Huawei Mediapad M5

### Android version

Android EMUI-8.0.0.360

### Jellyfin server version

10.7.6-1

### Which video player implementations does this bug apply to?

- [ ] Web player (default)
- [ ] Integrated player (ExoPlayer)
- [ ] External player (VLC, mpv, MX Player)

**Comment by Maxr1998** [comment]
Yes, client logs would be required. You can read more about them [here](https://wiki.lineageos.org/how-to/logcat).

**Comment by jerome-diver** [comment]
@Maxr1998 thank you for your help.
Well... from Termux application on my device, i can not access nothing (it is not a rooted device). And from a kind of files browser, i can not find any logcat.txt file. There is no "find" application TUI to use to find any file on the device too... It seems to be very complicate to do anything more than use application locked with such kind of device as log as not rooted (looks like it is not really mine actually... but...).
i will try to use adb to connect through USB to the device and try to get something more....

Question: is there a specific place to find Jellyfin specific log files somewhere in Android device (it should reduce my time toinvestigate  to try to find something useful) ?

**Comment by Maxr1998** [comment]
The logs don't exist in a file generally, but are stored by the Android system. Using the "adb logcat" tool from a computer will dump those logs, which you can write into a file to upload then.

It's a bit convoluted, Jellyfin should probably get an inbuilt option to capture logs eventually..

**Comment by jerome-diver** [comment]
# update status

ok, i find a kind of "Microsoft dumb way to fix" this problem:
1. uninstall Jellyfin android app
2. re-install it

# effect
can enter the new HTTPS server address (full address https://my_address:8920/my_subdirectory)
then, it can now access fine to the server.

# suspected "use case" problem

Maybe when a config has been done already with the address to access server, if no access or something around, it doesn't go to ask an other server address. So ity looks like locked inside a "no way" end path.

I hope this can help some other in the same situation than me, or maybe dev to investigate in this "use case" to find if the problem is really from there and to fix this problem the way users doesn't have to uninstall/install it back to fix the problem.

**Comment by jerome-diver** [comment]
Instead of close an issue, better to send an automatic alert to dev team the way they can test if this use case bug is still existing. What is the logic to close an issue report who has not been fixed ?

**Comment by Maxr1998** [comment]
I mean, it's on the reporter to reproduce this issue, as we cannot replicate your local environment. And after the bot posts, you still have 21 days before the issue is closed. 

Regardless, could you check if your issue is the same as #571 maybe? If not, let us know, I'll reopen this issue then.

**Comment by jerome-diver** [comment]
No @Maxr1998, it is not the same as the issue 571.
Read carefully and as you can see, it is a use case issue (so it is all about the design of the application for this specific use case).
To replicate, you have first to try to replicate it... it will be the same on your environment (but you have to try before to answer).
The use case is as i described: The problem occur when you have a config without an https access and after that, you switch to an https access. The use case doesn't care to ask for a new config to access the server... it is a use case design problem.
Do you get it ?
