### ISSUE TITLE
Jellyfin 2.3.2 Disconnected for no reason. 

### ISSUE THREAD

**Issue by martadinata666** [jellyfin/jellyfin-android#513]
Jellyfin android 2.3.2 show disconnected pop up to reconnect server on video playback, yet browse library working flawlessly. Can someone help confirm this?

reverting to ver 2.3.1 work fine as usual.

phone used
Nokia 3 (android 9)
Mi 6X (miui 12)

**Comment by Maxr1998** [comment]
Could you share logs when it happens? What kind of player do you use?

Also, please use the bug report template in the future, thank you.

**Comment by martadinata666** [comment]
Sorry, for not using the template, im creating issue from github mobile client, seems doesn't show bug template. Let add some additional info.

## Logs
```
----
```

## Application Version
```
2.3.2
```

## Where did you install the app from?
```
Play store
```

## Device Information
```
Nokia 3
Mi 6X
```

## Android version
```
Android 9 stock image
MIUI 12 Android 10
```
Jellyfin server version
```
10.8 Commit [ e5cbafdb6b47377052e0d638908ef96e30a997d6](https://github.com/jellyfin/jellyfin/commit/e5cbafdb6b47377052e0d638908ef96e30a997d6)
```

Which video player implementations does this bug apply to?
```
Exo player
```

Edit : Closed, clean application data and cache, then setup from scratch solved the disconnecting error.

**Comment by Maxr1998** [comment]
Alright, please reopen this issue if the bug returns.
