### ISSUE TITLE
Gesture hint is white on Android 10

### ISSUE THREAD

**Issue by Tomik167** [jellyfin/jellyfin-android#52]
As shown in picture on Samsung devices running Android 10 there is white line on the bottom of the screen and it doesn't look nice with Jellyfin dark UI.
[Picture](https://pasteboard.co/JnTC7Sn.png)
It would be nice to make it transparent like on Iphones

**Comment by Maxr1998** [comment]
I think the color is set by Samsung, on my Essential PH-1 the navigation bar/gesture hint is black. Having it transparent would definitely be nicer though, I'll look into that.
