### ISSUE TITLE
The web player under app cannot load subtitles correctly

### ISSUE THREAD

**Issue by yyxida** [jellyfin/jellyfin-android#523]
### Describe the bug

When android app uses web player, subtitles cannot be displayed normally (tofu, incorrect timeline)
There is no such problem when using exoplayer. There is no such problem when using Chrome web (PC, Android)
The font file is configured correctly,Opened label burn subtitles(all type)

![image](https://user-images.githubusercontent.com/22792135/132098078-71329dbf-9d8f-47c7-b715-3e84e29d6bd5.png)
![image](https://user-images.githubusercontent.com/22792135/132098083-41bfcce4-fe66-4866-96ee-4e22795f1c9b.png)

### Logs

[web sub.txt](https://github.com/jellyfin/jellyfin-android/files/7110040/web.sub.txt)

### Application version

2.3.2

### Where did you install the app from?

Google Play

### Device information

sony xz1 , oneplus7tpro

### Android version

Android10(sony)/11(Oxygenos)

### Jellyfin server version

10.7.6

### Which video player implementations does this bug apply to?

- [X] Web player (default)
- [ ] Integrated player (ExoPlayer)
- [ ] External player (VLC, mpv, MX Player)

**Comment by Maxr1998** [comment]
Looks like it's an encoding issue or missing fonts in the webapp. Considering that the web player will eventually be replaced by ExoPlayer anyway, I'm not sure it's worth investigating this.
What specifically stops you from using ExoPlayer (I know there's still a few features missing, I just wonder where I should lie my focus on next)?

**Comment by yyxida** [comment]
> Looks like it's an encoding issue or missing fonts in the webapp. Considering that the web player will eventually be replaced by ExoPlayer anyway, I'm not sure it's worth investigating this.
> What specifically stops you from using ExoPlayer? (I know there's still a few features missing, I just wonder where I should focus on next.)
Exoplayer is a very good and promising player. I like it very much. I discovered this problem [two months](https://github.com/jellyfin/jellyfin-android/issues/453#issuecomment-873367366) ago, but because exoplayer can use plug-in subtitles normally, I didn't care about it
In some recent videos, subtitles are part of the video, but subtitle files are also hung in the file, so they will overlap. Exoplayer seems to have some problems in switching or turning off subtitles. So I restart using the web player

**Comment by Maxr1998** [comment]
Ah right, that issue should be fixed. For subtitle toggling, wait for the next release, I reworked the track selection again yesterday. You should be able to disable subtitles then.

**Comment by yyxida** [comment]
> Ah right, that issue should be fixed. For subtitle toggling, wait for the next release, I reworked the track selection again yesterday. You should be able to disable subtitles then.

Thank you very much a, have a nice day
