### ISSUE TITLE
2.3.3: still black screen on start with OnePlus 7T

### ISSUE THREAD

**Issue by jakobroehrl** [jellyfin/jellyfin-android#527]
### Describe the bug

Thanks!

### Application version

2.3.3

### Where did you install the app from?

Google Play

### Device information

OnePlus 7T

### Android version

11

### Jellyfin server version

10.7.7

### Which video player implementations does this bug apply to?

- [ ] Web player (default)
- [ ] Integrated player (ExoPlayer)
- [ ] External player (VLC, mpv, MX Player)

**Comment by Maxr1998** [comment]
Try to clear the data once, that's necessary after you upgraded from 2.3.2 with the issue active.

**Comment by jakobroehrl** [comment]
Deleted an reinstalled the 2.3.3, now it works. :)
Thanks a lot!
