### ISSUE TITLE
Exoplayer cannot switch subtitles

### ISSUE THREAD

**Issue by yyxida** [jellyfin/jellyfin-android#530]
### Describe the bug

1. Play video with exoplay
2. Switch subtitles
3. Unable to switch

Whether selecting subtitles before playing or switching subtitles during playing cannot operate normally
Sometimes the subtitle selected is A, but the subtitle played is B
![image](https://user-images.githubusercontent.com/22792135/132823163-f8dde970-c759-48fe-9bc3-640517e5726e.png)

### Logs

[logcat1.txt](https://github.com/jellyfin/jellyfin-android/files/7142355/logcat1.txt)

### Application version

2.3.3

### Where did you install the app from?

Google Play

### Device information

sony xz1 , oneplus7tpro

### Android version

Android10(sony)/11(Oxygenos)

### Jellyfin server version

10.7.6

### Which video player implementations does this bug apply to?

- [ ] Web player (default)
- [X] Integrated player (ExoPlayer)
- [ ] External player (VLC, mpv, MX Player)

**Comment by Maxr1998** [comment]
What kind of subtitle is it? It's possible that they aren't supported by the app.

The app should properly show supported/unsupported subtitles and not allow the selection of unsupported ones. I'll look into the matter.

**Comment by yyxida** [comment]
> What kind of subtitle is it? It's possible that they aren't supported by the app.
> 
> The app should properly show supported/unsupported subtitles and not allow the selection of unsupported ones. I'll look into the matter.

The pink subtitle in the picture is a part of the video, and the white subtitle is encapsulated in the MKV file. This is a Japanese subtitle commonly used in Blu ray in Japan. It may be a picture or vector font?
There is also a problem with the subtitle switching of the ass file, which cannot be switched correctly. For example, there are sub1.ass and sub2.ass. selecting sub1 can correctly display sub1, selecting sub2 still displays sub1, and selecting close displays sub2 instead

I started subtitle burning because the original method cannot display Chinese。 (I correctly configured the Chinese font under "/ usr / share / fonts", which can be displayed normally on PC and web)It's mentioned [here](https://github.com/jellyfin/jellyfin-android/issues/523)

**Comment by vinpa64** [comment]
I'm having similar subtitle/language issues. (jellyfin 10.7.7, jellyfin-android 2.3.3, various android devices). In general, exoplayer seems to ignore whatever language/subtitle selections I make during playback. It also ignores language/subtitle selections I make before pressing play.

If I change my preferred subtitle language/preferred audio language through the settings menu, exoplayer seems to respect those choices. But, this method doesn't work if, for example, I want to choose from among multiple subtitle tracks of the same language.

I wonder if this is somehow related to transcoding, as jellyfin-android seems to insist on transcoding nearly everything I play, even though my tablet, for example, should support decoing the necessary codecs.

**Comment by wlritchi** [comment]
I'm experiencing this issue with Jellyfin 10.8.0 and Jellyfin Android 2.4.4. I have an MKV file with embedded subrip subs in Finnish, and external English subrip subs in a `.en.srt` file. In the web player, all subtitles behave as expected. In ExoPlayer, selecting "English - SUBRIP - External" shows the Finnish subs, while selecting "Finnish - SUBRIP" shows no subs at all.
