### ISSUE TITLE
Cannot connect to my server

### ISSUE THREAD

**Issue by Xyz00777** [jellyfin/jellyfin-android#533]
### Describe the bug

Since a one or two version I'm not able to connect to my server anymore (depending https://github.com/jellyfin/jellyfin-android/issues/493#issuecomment-901505092) sorry for late response.
I'm already tried out the newest release in github but it's also not working.
The web version and also the Google TV app is working without any problem (beside of that the android version is squishy sometimes :D)
I'm using an jellyfin server (newest version) behind an cloudflare reverse proxy with with nginx.
When you say me where I can find the log of the debug app version I can give you the logs :)
An friend of me who also use the Google version also can't connect anymore to my server with the android client.... Please help

Greetings 

### Application version

2.3.x

### Where did you install the app from?

Google Play

### Device information

Oneplus 8t other device also not eorking

### Android version

Android 11

### Jellyfin server version

10.7.6

### Which video player implementations does this bug apply to?

- [ ] Web player (default)
- [ ] Integrated player (ExoPlayer)
- [ ] External player (VLC, mpv, MX Player)

**Comment by RoryNesbitt** [comment]
I am also having this issue, not sure how long it's been going on though. It very much sounds the same as #172
I've tested from two phones, both oneplus, both running android 11 with app version 2.3.3.
I can connect though http using the ip address but not through https with the url. The cert is from cloudflare and the reverse proxy is nginx

**Comment by cikeZ00** [comment]
Same here, locally it works, however going through SSL via the cloudflare cert fails. Same configuration.

**Comment by Xyz00777** [comment]
@RoryNesbitt @cikeZ00 check if your server is on the newest version. My server had an outdated apt key and couldn't update because of that to the newest jellyfin version. On my system it's working now
