### ISSUE TITLE
Cannot auto burn subtitles on android app

### ISSUE THREAD

**Issue by SummonHIM** [jellyfin/jellyfin-android#534]
### Describe the bug

When i turn burn subtitles to "All Complex Formats" on website. it can auto burn subtitles to video
but this function is not working on android app

### Logs

```shell
just normally FFmpeg transcode log
```

### Application version

2.3.3

### Where did you install the app from?

Google Play

### Device information

Xiaomi Redmi K30 5G

### Android version

A11 DotOS v5.1.3(custom rom)

### Jellyfin server version

10.7.7

### Which video player implementations does this bug apply to?

- [ ] Web player (default)
- [ ] Integrated player (ExoPlayer)
- [ ] External player (VLC, mpv, MX Player)

**Comment by CarlosOlivo** [comment]
With which player? Web or Integrated? Or both?
From what I remember, this option only works with the Web player (for now).

**Comment by SummonHIM** [comment]
> With which player? Web or Integrated? Or both? From what I remember, this option only works with the Web player (for now).

is jellyfin android app default player

**Comment by Adam5Wu** [comment]
I am experiencing this problem as well:
- Burn in subtitles election has no effect if using the Web player in Android app. Subtitles are always streamed and rendered on the client.
- With integrated player, subtitle does get burned in, however switching subtitles during playback has no effect, only the initial language selection is honored.
