### ISSUE TITLE
m4v audio issue

### ISSUE THREAD

**Issue by Cyan101** [jellyfin/jellyfin-android#536]
### Describe the bug

Playing an m4v file seems to lead to an audio issue, even when swapping between stereo and 5.1 in both settings and audio tracks in the m4v file itself.
This causes an ear piercing noise constantly, this noise continues EVEN if the video is paused weirdly.

### Application version

2.3.3

### Where did you install the app from?

Google Play

### Device information

S20 FE

### Android version

Android 11

### Jellyfin server version

10.7.7

### Which video player implementations does this bug apply to?

- [ ] Web player (default)
- [ ] Integrated player (ExoPlayer)
- [ ] External player (VLC, mpv, MX Player)

**Comment by cph4cker** [comment]
I have the same error. Same system.
