### ISSUE TITLE
Connect to Server with IPv6

### ISSUE THREAD

**Issue by genofire** [jellyfin/jellyfin-android#549]
### Describe the bug

1. Open Jellyfin App
1. Connect to Server appear
1. Enter DNS-Name (which only has ipv6 Adresses / AAAA-Records <- which work in browser fne)
1. "Tried 5 candidates for input, without success." appear

### Application version

2.3.3

### Where did you install the app from?

F-Droid

### Device information

FP3

### Android version

11

### Jellyfin server version

10.7.5

### Which video player implementations does this bug apply to?

- [X] Web player (default)
- [ ] Integrated player (ExoPlayer)
- [ ] External player (VLC, mpv, MX Player)

**Comment by lancenty** [comment]
I get the same issue. How can I collect the log when I cannot connect the server and login?

**Comment by genofire** [comment]
it was just a wrong configurated whitelist
