### ISSUE TITLE
Unnecessary x265 transcoding

### ISSUE THREAD

**Issue by imjustarandomguy** [jellyfin/jellyfin-android#55]
**Describe the bug**
When trying to play a x265 10 bit file using the jellyfin android app v2.0.0-rc2 the file is being transcoded with the given reason : VideoCodecNotSupported when I know for a fact that my phone (Xiaomi Mi 9T) supports it. When trying to play the same file using Plex or Emby it is able to direct play.

**To Reproduce**
1. Try to play x265 10bit file on android app.
2. Go to dashboard and see that the file is being transcoded with reason: VideoCodecNotSupported 

**Expected behavior**
The file should direct play.

**Logs**
Logs of transcode : [Log.txt](https://github.com/jellyfin/jellyfin-android/files/5120486/Log.txt)

**Screenshots**

**System (please complete the following information):**
 - App version: 2.0.0-rc.2
 - Android version: Android 10
 - Device manufacturer and model: Xiaomi Mi 9T
 - Jellyfin server version: 10.6.3
 - The type of video player implementation used: Jellyfin android player

**Additional context**

**Comment by Maxr1998** [comment]
With "jellyfin android player", you mean the web player embedded into the app? As in, you didn't enable the native player in the client settings?

**Comment by imjustarandomguy** [comment]
Yes, sorry that's what I meant. I just tried with the native player option (ExoPlayer) that you mentioned but the file wouldn't play, I got a black screen and pressing the play button didnt't do anything even tho the dashboard said that I was transcoding the file.

Logs with ExoPlayer : [Log_exoplayer.txt](https://github.com/jellyfin/jellyfin-android/files/5120579/Log_exoplayer.txt)

You can see an error at the end of the log file that I though was caused by hardware acceleration. I disabled hardware acceleration on my server to see if it would fix the problem but it didn't.

Logs with ExoPlayer and no hardware acceleration : [Log_exoplayer_without_hw_transcoding.txt](https://github.com/jellyfin/jellyfin-android/files/5120593/Log_exoplayer_without_hw_transcoding.txt)

Even with ExoPlayer it would still try to transcode and it seemed to be even worse since it not only gave the reason VideoCodecNotSupported but also AudioCodecNotSupported.

**Comment by Maxr1998** [comment]
> Yes, sorry that's what I meant. I just tried with the native player option (ExoPlayer) that you mentioned but the file wouldn't play, I got a black screen and pressing the play button didnt't do anything even tho the dashboard said that I was transcoding the file.
> 
> Logs with ExoPlayer : [Log_exoplayer.txt](https://github.com/jellyfin/jellyfin-android/files/5120579/Log_exoplayer.txt)
> 
> You can see an error at the end of the log file that I though was caused by hardware acceleration. I disabled hardware acceleration on my server to see if it would fix the problem but it didn't.
> 
> Logs with ExoPlayer and no hardware acceleration : [Log_exoplayer_without_hw_transcoding.txt](https://github.com/jellyfin/jellyfin-android/files/5120593/Log_exoplayer_without_hw_transcoding.txt)
> 
> Even with ExoPlayer it would still try to transcode and it seemed to be even worse since it not only gave the reason VideoCodecNotSupported but also AudioCodecNotSupported.

Yes, the player profile published by ExoPlayer (and possibly its handling on the server side?) is still bugged, that is already tracked at #28.
