### ISSUE TITLE
Missing Skip Ahead/Back Buttons During Playback

### ISSUE THREAD

**Issue by MovieWiz** [jellyfin/jellyfin-android#554]
### Describe the bug

There are client options to specify the number of seconds for skip ahead and skip back but the skip ahead/back buttons have not been available during playback for a few releases now, including the 2.4.0 release that I downloaded earlier today.  In fact, the release notes for 2.4.0 mentions a change about exoplayer skip ahead/back following the configured number of seconds in the settings.

Just wondering if the button are supposed to be missing.  Is there some other way to do skip ahead/back that I'm too dense to see?  Currently, the only seek ability appears to be using the progress bar which can be really hard to control when you want to skip a specific amount of time (like skipping a commercial).

### Application version

2.40

### Where did you install the app from?

Sideloaded APK (libre build)

### Device information

Redmi 5 Plus

### Android version

8.1 (MIUI Global 11.0.2)

### Jellyfin server version

10.7.7

### Which video player implementations does this bug apply to?

- [X] Web player (default)
- [X] Integrated player (ExoPlayer)
- [ ] External player (VLC, mpv, MX Player)

**Comment by Maxr1998** [comment]
At least in ExoPlayer, you skip forward/backward by double tapping on the respective side of the screen, just like in the YouTube app. The buttons on screen are not seek buttons, but previous/next if you have a playlist running (e.g. when playing a whole season of a show).

**Comment by MovieWiz** [comment]
Thanks for that.  Sorry for my denseness -- I don't actually use YouTube that much and when I do, it's on my computer and I use the left/right arrows to skip back/ahead.

**Comment by Maxr1998** [comment]
Don't worry, it's not that intuitive when I think about it. I believe YouTube shows a textual hint even. Maybe we should do something like that too..

**Comment by Maxr1998** [comment]
Since it isn't a bug, I'll close this issue now.
