### ISSUE TITLE
[bug] ExoPlayer crashes when changing subtitle

### ISSUE THREAD

**Issue by vinpa64** [jellyfin/jellyfin-android#558]
### Describe the bug

jellyfin 10.7.7, jellyfin-android 2.4.0

1. Play media file that includes more than one subtitle through direct play.
2. Attempt to change/turn on subtitle during playback.
3. Crash

This only seems to occur if the file includes multiple subtitles (different languages, or an SDH subtitle, etc.) This does not occur during transcoding playback, where attempts to change the subtitle are simply ignored.

### Application version

2.4.0

### Where did you install the app from?

Google Play

### Device information

Various recent Samsung devices

### Android version

Android 10 - 11

### Jellyfin server version

10.7.7

### Which video player implementations does this bug apply to?

- [ ] Web player (default)
- [X] Integrated player (ExoPlayer)
- [ ] External player (VLC, mpv, MX Player)

**Comment by Maxr1998** [comment]
Thanks for the investigation, I'll try to fix this tonight and release a new build.

**Comment by Maxr1998** [comment]
Fixed in #560.
