### ISSUE TITLE
ExoPlayer crashes occasionally, and subtitle and audio track selection are invalid.

### ISSUE THREAD

**Issue by shaino** [jellyfin/jellyfin-android#563]
### Describe the bug

When some transcoded videos are played with exoplayer, switching subtitles or audio will cause crashes.
Other videos fail because they report too many errors.
All this happened on the 10.7.7 server version.
On the 10.8.0 server version, there is no crash and playback fails, but subtitles and audio cannot be switched.

### Application version

2.4.1

### Device information

Huawei Mate40 pro

### Android version

Android 10

### Jellyfin server version

10.7.7 , 10.8.0

### Which video player implementations does this bug apply to?

- [ ] Web player (default)
- [X] Integrated player (ExoPlayer)
- [ ] External player (VLC, mpv, MX Player)

**Comment by Maxr1998** [comment]
Well, this is awkward, the audio/subtitle switching crash should've been fixed in 2.4.1. I tested it, but maybe I missed a crash case.
Let me investigate this further.

10.8 is not yet supported by the app, so I can't comment on those issues.

**Comment by shaino** [comment]
I'm very sorry. Maybe I got the wrong version.
On the 10.7.7 server version, switching subtitles and tracks using multiple video tests 2.4.1 did not crash.
But , After switching subtitles and audio, the display has been switched, but the actual subtitles and audio have not changed.

BTW, Exoplayer cannot control the bitstream? The bitstream limit set by the client is invalid for ExoPlayer. It must be realized by using the Internet streaming media transmission bit rate limit on the server.

Maybe my device does not support DTS. When "TS H264 DTS" is displayed, my device has no sound. "TS H264 MP3" or "TS H264 AC3" is ok. How does ExoPlayer determine whether the device supports AC3 and DTS? Any AC3 or DTS are both passthrough?

thx...

**Comment by Maxr1998** [comment]
Thanks for the update, then the crashes should actually be fixed.

Selecting subtitle and audio streams while transcoding is still broken, but will hopefully be implemented soon, along with bitrate limit support.
And yes, right now, ExoPlayer ignores the bitrate limit set in the client settings.

DTS should be supported through the ExoPlayer ffmpeg extension, but possibly it doesn't work for all variants or on all devices. AC3 is also handled by the extension, ExoPlayer decodes the audio data itself. Passthrough generally only makes sense for something like a TV where the audio can be forwarded to an audio receiver/TV that supports the codecs itself.
