### ISSUE TITLE
A proper guide on how to compile the android app. 

### ISSUE THREAD

**Issue by omgitsheaven** [jellyfin/jellyfin-android#57]
Could someone improve the current guide on how to compile the android app

**Comment by joshuaboniface** [comment]
It's not a guide per-se, but the `build` and `docker-build.sh` scripts give a rundown of how the build actually happens. Specifically, assuming your environment is acceptable (see the `Dockerfile`), `docker-build.sh` should run normally in your shell of choice and result in an APK. Though the docker build using `build` is recommended.

**Comment by dkanada** [comment]
We updated the `README` with better guidelines on how to compile the app so we should be fine now. @joshuaboniface is also right, the dockerfile is the source of truth since we use it to build the releases.
