### ISSUE TITLE
Android app - Unable to connect from WAN 

### ISSUE THREAD

**Issue by DuvelCorp** [jellyfin/jellyfin-android#571]
### My Config

JellyFin 10.7.7 running on Debian in my DMZ.
The main gate is a pfSense Firewall. The port 443 is open and HTTPS traffic is redirected to a reverse proxy in the DMZ (Debian/Apache and not the same server as the Jellyfin instance). Only HTTPS is allowed from WAN.
The reverse proxy handle HTTPS decryption and redirection in HTTP  on the proper server/port of the DMZ, depending on URL.  The cert (LetsEncrypt renewed 2 days ago) is  thus on the reverse proxy. 

Say the URL  is _https://mydomain.name/jellyfin_
Config in the reverse proxy is : 
```
ProxyPass /jellyfin http://192.168.2.4:8096/jellyfin
ProxyPassReverse /jellyfin http://192.168.2.4:8096/jellyfin
```
I also have a reverse DNS in the firewall that take care of redirecting my own _https://mydomain.name/jellyfin_ from LAN to the DMZ.

And finally, got 5 friend users connecting to my Jellyfin (thus from WAN) mostly everyday.

### With that said : 

- Everything is working perfectly from WAN and LAN from **Browser** clients (Firefox, Chrome, Safari, Edge...)
- Got a raspberrypi/openelec box running Jellyfin addon in my LAN, configured with the servers DMZ's IP, not URL, and it is working fine too.
- **Android app is not working for any of us, whether its in WAN or LAN, unless we apply a stupid trick.**

### The bug (and the trick)

When we try to connect with android app, (from WAN or LAN), with URL https://mydomain.name/jellyfin, it says it can't reach the server.
I can see the 443 packets flowing through the firewall to the reverse proxy, but I can't see anything landing in the Jellyfin logs (I might have missed something).
I can make it working, but only if I apply [the following trick](https://www.reddit.com/r/jellyfin/comments/m3ixl7/comment/gqrdt0r/?utm_source=share&utm_medium=web2x&context=3): first establish a connection to https://demo.jellyfin.org/stable/, which always work, then connect to my own server. In this case it works 100%. But once the app got disconnected, the trick should be applied again.

Got the issue with latest Jellyfin Android App from my phone (LineageOS 18.1 / Android 11) , and a friend that has a fresh MI Box has the exact same issue, and the trick works for him as well. When he is finally logged, he says that everything is running sweet and that the performance is great.

Here we are. I searched a lot before discovering the trick on reddit, and only this worked.
So at this stage I am unable to tell if the issue really is in your Android App, or in my pipes. However the reddit answer proves that I am not the only one to experience this issue and that its there for some months.

I can do some tests and provide you with more info and logs if needed.

Cheers and keep up the great work 👍 

### Application version

2.4.0

### Where did you install the app from?

Google Play

### Device information

Moto G7

### Android version

Android 11, LineageOS 18.1 

### Jellyfin server version

10.7.7

### Which video player implementations does this bug apply to?

- [ ] Web player (default)
- [ ] Integrated player (ExoPlayer)
- [ ] External player (VLC, mpv, MX Player)

**Comment by nielsvanvelzen** [comment]
What is the response you get when going to `https://mydomain.name/jellyfin/system/info/public`?

**Comment by DuvelCorp** [comment]
> 
I don't want to publish my real server name and folder or I will be spotted instantlywith a google serach ;)  

So let's say I called it "Netflix", it gives

```
{
"LocalAddress":"http://192.168.2.4:8096/netflix",
"ServerName":"Netflix",
"Version":"10.7.7",
"ProductName":"JellyfinServer",
"OperatingSystem":"Linux",
"Id":"2961cac6981a4cf7bdba123798d8bcbc",
"StartupWizardCompleted":true
}
```

**Comment by nielsvanvelzen** [comment]
The value for `ProductName` is invalid. It should be `Jellyfin Server` (with a space). This can cause the app to fail to connect.

**Comment by DuvelCorp** [comment]
> 

It has the space. I just lost it when editing the json in my post after copy/pasting. I edited my post.

**Comment by nielsvanvelzen** [comment]
Ok, everything else in the response looks fine so to find the issue we need app logs. They should give us some more information about what's going on behind the "can't reach server" message.

This page explains how to get these logs: https://wiki.lineageos.org/how-to/logcat

**Comment by DuvelCorp** [comment]
I got the logcat.  
However I am a bit reluctant to post this here as it contains personal stuff and the public URL of my servers that I will never expose to expose to the world. Is it OK if I remove some info and mass replace my jellyfin url? I am smart enough to not remove the clues  you need ;) Or I send you the full file in private.

**Comment by DuvelCorp** [comment]
ok her'es the log file edited. What I did : launched the android app (previously disconnected), and tried to connect to my server. 
Once the connection issue triggered, I downloaded the logcat.
The logcat begins on app startup and I have mass replaced my domain with  **mydomain.name** and my jellyfin instance (folder) name with "**/netflix** "

I see some bad SSL stuff in there

> 11-19 20:22:40.290  4702  4752 I cr_X509Util: Failed to validate the certificate chain, error: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
> 11-19 20:22:40.321  4702  4752 I cr_X509Util: Failed to validate the certificate chain, error: Unacceptable certificate: CN=R3, O=Let's Encrypt, C=US
> 11-19 20:22:40.335  4702  4775 E chromium: [ERROR:ssl_client_socket_impl.cc(980)] handshake failed; returned -1, SSL error code 1, net_error -202
> 11-19 20:22:40.345  4702  4702 E WebViewFragment$initialize: Received SSL error: primary error: 3 certificate: Issued to: CN=mydomain.name;
> 11-19 20:22:40.345  4702  4702 E WebViewFragment$initialize: Issued by: CN=R3,O=Let's Encrypt,C=US;
> 11-19 20:22:40.345  4702  4702 E WebViewFragment$initialize:  on URL: https://mydomain.name/netflix
> 11-19 20:22:40.419  4702  4740 W System.err: SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
> 11-19 20:22:40.419  4702  4740 W System.err: SLF4J: Defaulting to no-operation (NOP) logger implementation

But I swear that my cert is fine, at least I have n,o issues in browser. If you want to do a test on my install from your devices, we do this in private
[logcat2.txt](https://github.com/jellyfin/jellyfin-android/files/7572639/logcat2.txt)
.

**Comment by nielsvanvelzen** [comment]
Your certificate is, actually, invalid. Let's Encrypt X3 is not trusted anymore. See https://letsencrypt.org/docs/dst-root-ca-x3-expiration-september-2021/ and the a discussion about this issue in our server repository https://github.com/jellyfin/jellyfin/issues/6650

**Comment by DuvelCorp** [comment]
Wait... do not burry the problem that fast.... 
As I told you, my cert is valid, and you ware welcome to come here and test it.

![image](https://user-images.githubusercontent.com/33682764/142718748-2f7ab30f-d1d4-4816-b872-b4837b352bee.png)

**Comment by DuvelCorp** [comment]
Note that I made a test with https://www.ssllabs.com/ssltest

![image](https://user-images.githubusercontent.com/33682764/142721435-ab8987ea-8964-41ed-8f01-ac1e4a966eaf.png)

So I admit its not totally fine. Looking on my side to solve this but I still would like some feedback from you about my previous thoughts.

**Comment by Maxr1998** [comment]
Yes, it seems like you incorrectly configured your server and picked the wrong certificate file.
Let's Encrypt should provide a fullchain.pem, that's what you need to setup on your server.

As [this serverfault answer](https://serverfault.com/a/628063) explains, browsers typically have intermediate certificates cached as well, whereas Android only has the root certs available, thus requiring a full certificate chain to verify a certs validity. Your "trick" works because the demo server also uses a (correctly configured) Let's Encrypt certificate with the intermediate certificates included, and the WebView will apparently remember those for the rest of the session.

**Comment by DuvelCorp** [comment]
OK that makes perfect sense now. You can indeed close it because this was the explanation and  my issue is solved.
I added the LetsEncrypt intermediate cert to my reverse proxy config, and android app now works perfectly

thanks for the help :)

**Comment by Maxr1998** [comment]
Sure, glad it works now. Also good to know in case someone has issues with their certificate in the future. :+1:
