### ISSUE TITLE
Could not connect to Host when using localhost for urls import in custom CSS in the Host settings. 

### ISSUE THREAD

**Issue by mafflerbach** [jellyfin/jellyfin-android#574]
### Describe the bug

When I played with custom css, I observe that the android client cannot connect to the host, when using a http import to localhost:

For testing I used a localhost address to fetch an external css to import my customs. The Css is existing under this address, and the Web interface of the Host is able to load this css.  
```
@import url("http://localhost:8000/test.css") 
```

This caused the error message, that the android app could not connect to the Host. 
I am aware, that this was a mistake by me when I use the localhost address, but I think the App should react in a different way, if its not able to load external sources from localhost like this.

This causing only problems with css http imports from localhost. 

If I try a not existing file, the App is loading like expected:

```
@import url("nonExisting.css") 
```
If i try 
```
@import url("http://example.com:8000/test.css") 
```
the App is loading like expected as well. 
### how to

On the Server:
Dashboard -> General 

scroll down to `Custom CSS` and enter 
```
@import url("http://localhost:8000/test.css") 
```

### Application version

2.4.1

### Where did you install the app from?

Google Play

### Device information

Huawai p20 lite

### Android version

Android 9

### Jellyfin server version

10.7.7

### Which video player implementations does this bug apply to?

- [ ] Web player (default)
- [ ] Integrated player (ExoPlayer)
- [ ] External player (VLC, mpv, MX Player)

**Comment by nielsvanvelzen** [comment]
"localhost" means the local host (like the name implies). If you just want it to work in your LAN you can use a local ip address.

I'm closing the issue because this is not a problem with the app.

**Comment by mafflerbach** [comment]
I disagree with "that its not a bug". Because it seems that the app is try to load something from localhost (in this case it would be the mobilephone) and this is causing that I cannot use the app at all. 

I am more willing to accept that this is more or less a total edge case and that its maybe not worth the time. ¯\_(ツ)_/¯
