### ISSUE TITLE
Gray bar while video playback

### ISSUE THREAD

**Issue by Demian98** [jellyfin/jellyfin-android#576]
### Describe the bug

While playing any video with the default web player of the android app, the video is not really in fullscreen mode. There is always a gray bar at the top (real top if the phone, where the camera is). It is just a gray bar, without time, notification and battery information of the phone.

I also tried to put the jellyfin app to fullscreen mode (android setting). But still the same.

Here is screenshot, which shows the issue:
![20211128_210522](https://user-images.githubusercontent.com/77210091/143784092-a6fbb749-14f3-4187-bf5e-153a74f1a369.jpg)

If would be great if that can be fixed to have a real fullscreen, while video playback.

### Application version

2.4.1

### Where did you install the app from?

Google Play

### Device information

Samsung Galaxy Note 10+, SM-N975F

### Android version

Android 10

### Jellyfin server version

10.7.7

### Which video player implementations does this bug apply to?

- [X] Web player (default)
- [ ] Integrated player (ExoPlayer)
- [ ] External player (VLC, mpv, MX Player)

**Comment by Maxr1998** [comment]
Right, that's a known issue with the web player. I recommend trying out the integrated player instead, which allows real Fullscreen.

**Comment by Demian98** [comment]
Thank you, I already did this for now. But the issue will get fixed in the future?

**Comment by Maxr1998** [comment]
Actually, once we're at a point when the integrated player can fully replace the web player, we'll remove that one. But I don't know yet when that'll be.
