### ISSUE TITLE
Integrated player: Duration / Runtime seems to be taken from metadata instead of the actual data

### ISSUE THREAD

**Issue by rluetzner** [jellyfin/jellyfin-android#585]
### Describe the bug

1. Add two different versions of a movie (having different runtimes).
2. Play both versions and check the runtime. Both runtimes should be equal, so one of them is off.

The only explanation I can think of is that the runtime is not actually determined by the data, but from the metadata instead.

This only happens with the integrated player. The web player and any external players are fine. When seeking, this will also cause issues as the progress is not mapped accurately to the actual position in the stream. 

### Application version

2.4.2

### Where did you install the app from?

F-Droid

### Device information

Realms 7

### Android version

Android 11

### Jellyfin server version

10.7.7

### Which video player implementations does this bug apply to?

- [ ] Web player (default)
- [X] Integrated player (ExoPlayer)
- [ ] External player (VLC, mpv, MX Player)

**Comment by mingyech** [comment]
In my testing, it seems like the problem is not just that the duration is wrong, but it is playing the wrong version of the video entirely.

**Comment by Maxr1998** [comment]
@mingyech that seems to be the case. I thought I had handled the multiple versions in the integrated player, but it's possible that I broke them again.
