### ISSUE TITLE
Native ExoPlayer does not honor subtitle configuration

### ISSUE THREAD

**Issue by ngosang** [jellyfin/jellyfin-android#586]
### Describe the bug

This issue is almost the same as #252 but with SRT subtitles.
In Jellyfin configuration I have disabled the back shadow/background. It's working well in the Web Player but not in the ExoPlayer.
Could you change the subtitle background configuration in ExoPlayer?

Web Player
![image](https://user-images.githubusercontent.com/10577978/145238267-82cd02ef-498f-4f44-b3a7-2c47ed35ba1b.png)

ExoPlayer Native
![image](https://user-images.githubusercontent.com/10577978/145238245-7493ca71-264b-408a-bb78-74bc6e10d49d.png)

### Application version

2.4.2

### Where did you install the app from?

Google Play

### Device information

OnePlus 8T

### Android version

11

### Jellyfin server version

10.7.7

### Which video player implementations does this bug apply to?

- [X] Web player (default)
- [X] Integrated player (ExoPlayer)
- [ ] External player (VLC, mpv, MX Player)

**Comment by WouterKr** [comment]
+1

I also would like the possibility to configure the background coloraturas for the androidtv app.

Version : 0.12.3
Amazon

**Comment by WouterKr** [comment]
Hope this will be added anytime soon.

**Comment by ngosang** [comment]
It's not fixed and I'm still interested in this issue.

**Comment by m33ts4k0z** [comment]
The subtitle configuration through the ExoPlayer is controlled through Android's own settings and not through the JellyFin app: https://support.google.com/accessibility/android/answer/6006554

**Comment by YodaQ** [comment]
Thanks for that its definitely googles fault i just fixed it myself and can confirm this is not a bug.
