### ISSUE TITLE
Download/cache songs/albums/playlists/(videos?)

### ISSUE THREAD

**Issue by Irubataru** [jellyfin/jellyfin-android#59]
**Describe the feature you'd like**
The only thing I really miss with this app is some sort of download/cache mechanism similar to what you find in e.g. Spotify. At the moment it is possible do download individual media by clicking the download button, but this is downloaded as a regular download and not a cache, so if you then play the media from the app it is still streamed. This would be really useful for when you are travelling and want you favourite album or a film ready to be watched. For me this is most important for audio, but I can see that people would find it useful to be able to cache video as well like you can with e.g. Netflix.

If it was possible to then filter by "downloaded only" that would be extra useful.

**Comment by JulioNahum** [comment]
It would be nice to be able to download the content and only play it in the Jellyfin app. How does Netflix and its content. Oh is it very "closed" in your opinion?

**Comment by nielsvanvelzen** [comment]
Closing in favor of https://features.jellyfin.org/posts/218/jellyfin-mobile-app-offline-downloads

**Comment by Irubataru** [comment]
Sorry, didn't realise that feature requests were handled elsewhere.

**Comment by Maxr1998** [comment]
> Sorry, didn't realise that feature requests were handled elsewhere.

They aren't generally, but in this case, this is more related to the web client and server architecture, thus better tracked elsewhere. The Android client still mostly wraps the web UI.
