### ISSUE TITLE
Switching Audio on ExoPlayer no longer works

### ISSUE THREAD

**Issue by xNinjaKittyx** [jellyfin/jellyfin-android#595]
### Describe the bug

1. Open video with 2 audio tracks
2. Change to other audio track
3. Does not try to change audio tracks (before it used to briefly re-encode or just stutter a bit before continuing).

Requires app restart or changing to a different video, then back for the audio track to go into effect.

~~Started happening with 2.4.2, I downloaded 2.4.1-debug and it does not have this problem. I'm guessing it's related to the fix for #555 submitted for 2.4.2~~ I didn't have the right player on 2.4.1 - Going to check other versions. 2.4.1 didn't work either. - EDIT: It doesn't work with 2.3.0, but I'm pretty sure this used to work - It may have been an android update or something other than jellyfin that broke the functionality. It does work on Web Player, and works fine on desktop app & desktop web app.

I tried with 2 different video files. One of them was 5.1 Ch AAC -> 2 Ch AAC. The other one was 2 Ch Opus -> 2 Ch Opus. Both didn't work.

### Application version

2.4.2

### Where did you install the app from?

Google Play

### Device information

Google Pixel 5

### Android version

Android 12

### Jellyfin server version

10.7.7

### Which video player implementations does this bug apply to?

- [ ] Web player (default)
- [X] Integrated player (ExoPlayer)
- [ ] External player (VLC, mpv, MX Player)

**Comment by YShow** [comment]
Same issue, webplayer works fine but exoplayer has problems

**Comment by ArchemedIan** [comment]
same problem, 2.4.4, web player does it fine, integrated player doesnt. no problem in web browser or windows app.

upgrading from 10.7.7 + ffmpeg4 to 10.8.0b3 + ffmpeg5 did not solve.

**Comment by silentTeee** [comment]
Same problem on Pixel 6 with app version 2.4.4,  server version 10.8.0. The Web player is able to switch audio tracks correctly but the Integrated player won't honor it. This happens whether you set the audio while the episode is playing (i.e. from the player interface) or the episode description page. Closing the app seems to get it to actually honor the change, so maybe it's a caching issue?

**Comment by xNinjaKittyx** [comment]
I don't see this issue happening with every video now

Updated Environment - 
**Application version**
2.4.4
**Where did you install the app from?**
Google Play
**Device information**
Google Pixel 7 Pro
**Android version**
Android 13
**Jellyfin server version**
10.8.8


Audio streams of the videos that do happen to work
- AAC LC (6 Ch, 48 kHz) / AAC LC (6 Ch, 48kHz)
- AC-3  (Dolby Digital, 6 Ch, 48 kHz) / AC-3 (Dolby Digital, 6 Ch, 48 kHz) 

Audio streams of the videos that don't work
- E-AC-3 (Dolby Digital Plus, 6Ch, 48kHz) / E-AC-3 (Dolby Digital Plus, 6Ch, 48kHz)
- AAC LC (6 Ch, 48 kHz) / Opus (2 Ch, 48 kHz)

**Comment by Maxr1998** [comment]
Should be fixed since 2.5.0.
