### ISSUE TITLE
Remove modifications to the Cordova Android platform

### ISSUE THREAD

**Issue by thornbill** [jellyfin/jellyfin-android#6]
There are a significant number of modifications made in `platforms/android`. The `platforms` directory should not be included in the repository at all, because it should only contain the output generated by `cordova build`.

These changes prevent the Android platform (and by extension Cordova) from being upgraded to new versions. Also, this native Android code would not be supported on any other platform, most notably iOS.

Any code written there should be migrated to a plugin or removed.

**Comment by dkanada** [comment]
resolved in #61
