### ISSUE TITLE
Stop time in ExternalPlayer

### ISSUE THREAD

**Issue by hailong259** [jellyfin/jellyfin-android#602]
### Describe the bug

I used MX player PRO as external player and i had the same problem as issue #565:
https://github.com/jellyfin/jellyfin-android/issues/565

It looks like the sum of the previous time stamps.

### Application version

2.4.2

### Where did you install the app from?

Google Play

### Device information

Redmi K20

### Android version

Android 11

### Jellyfin server version

10.7.7

### Which video player implementations does this bug apply to?

- [ ] Web player (default)
- [ ] Integrated player (ExoPlayer)
- [X] External player (VLC, mpv, MX Player)

**Comment by roeii** [comment]
Just adding to this issue, tested on 2.4.2 with server version 10.7.7 as well on OS Android 12 One UI 12.
It seems to effect all external players; The ones I tested and confirmed to have this issue were: MPV Player, VLC, MX Free.

**Comment by Maxr1998** [comment]
Strange. Could you check the admin UI on a separate device to see whether it's direct playing or transcoding?

**Comment by roeii** [comment]
Hi @Maxr1998 the admin UI displays it as direct playing.

**Comment by Maxr1998** [comment]
I see. I'll give this another look then. I've been running 10.7 too when fixing this, and confirmed it working, so I can't really explain the issue..

**Comment by Maxr1998** [comment]
Reopened the original issue, thus I'm closing this one as a duplicate.
