### ISSUE TITLE
Fullscreen landscape video not centered after screen rotation during Android dropdown menu

### ISSUE THREAD

**Issue by jcstaudt** [jellyfin/jellyfin-android#605]
### Test videos

Video: 1080p VP9 SDR
Audio: English - OPUS - Stereo - Default
Subtitles: Off

Video: 1080p HEVC SDR
Audio: English - AAC - Stereo - Default
Subtitles: Off

### Steps to reproduce

1. Launch Jellyfin
2. Stream a video
3. Rotate the phone such that the video is in portrait mode (it can be playing or paused)
4. Swipe down to show the Android settings dropdown menu
5. While the menu is still shown, rotate the phone such that the video is playing in landscape mode

After step 5, you may notice that the fullscreen video is no longer centered. Rotating back to portrait and then to landscape while not having the dropdown menu open corrects the video position. Steps 3-5 can be repeated with the same results. The bug only occurs when going portrait -> landscape and not landscape -> portrait.

### Application version

2.4.2

### Where did you install the app from?

F-Droid

### Device information

Google Pixel 2

### Android version

Android 11 (security update 10/5/20)

### Jellyfin server version

10.7.7

### Which video player implementations does this bug apply to?

- [x] Web player (default)
- [ ] Integrated player (ExoPlayer)
- [ ] External player (VLC, mpv, MX Player)

**Comment by nielsvanvelzen** [comment]
Please answer the "Which video player implementations does this bug apply to?" question.

**Comment by jcstaudt** [comment]
> Please answer the "Which video player implementations does this bug apply to?" question.

I'll tick a box but left it empty because the web player vs integrated player nomenclature is a bit confusing. I'm using the default Android application's player, which appears to be embedded in the app, as opposed to running in a web browser. I assume this means that it is ExoPlayer?

**Comment by nielsvanvelzen** [comment]
Open the app, click your profile picture on the top right and go to "client settings". It then shows an option for the video player.

**Comment by jcstaudt** [comment]
Perfect! I updated the comment. (Could this please be described in the issue template to help fellow newcomers?)

**Comment by nielsvanvelzen** [comment]
> Could this please be described in the issue template to help fellow newcomers?

It already does, "Video player can be switched in the client settings of the app."

**Comment by jcstaudt** [comment]
That's a fair point, but I respectfully suggest it could be made a little clearer. Maybe something like:

Video player implementation settings can be found in the client settings of the app (Profile icon -> Client Settings -> Video player type)

**Comment by jcstaudt** [comment]
I'm still experiencing this bug. (Bumping to avoid auto-closure.)
