### ISSUE TITLE
Android Auto no transcoding 

### ISSUE THREAD

**Issue by DJWhitegold** [jellyfin/jellyfin-android#607]
Playing via android auto does not transcode. 

To reproduce, use jellyfin for android app on a mobile Internet connection (4G), set playback / Internet music quality to 256 kbs, play flac (high bitrate) music and you'll see from the server it's correctly transcoding to to 256kbs, confirmed with log (excellent)... 

However, repeat process but play via android auto and jellyfin does not transcode, creates no log and burns through data. 

Jellyfin 10.7.6
Jellyfin for android 2.4.2
Android auto 7.1.614574
Android 11
Pixel 3a

**Comment by DJWhitegold** [comment]
Issue still exists is jellyfin android app v2.4.4
So does a separate issue of audio skipping when playing if screen is off or if another app viewed. These issues make the official jellyfin app unusable for my requirements. Thankfully another app exists called Yatse, which works perfectly with the jellyfin server and I use that instead, hence why I've just uninstalled the jellyfin android app.

**Comment by rlichtenwalter** [comment]
This is definitely still a (really unfortunate "gotcha") issue.

To reproduce for me:

1. Start with a library of large files (e.g., FLAC music library).
2. Set Jellyfin to restrict bandwidth over Internet to 96 kbps for audio streams.
3. Connect my phone via USB to support Android Auto on car.
4. Watch data usage at about 30 MB/song.
5. Check logs and verify that no transcoding is being performed.

THEN disconnect from Android Auto and connect just via Bluetooth with the same phone to the same car and see 3 MB/song and see transcoding in the logs.

I can switch back and forth, and this behavior is 100% reliable.
Jellyfin server: Latest (I keep it up to date - I can freeze version to troubleshoot)
Jellyfin client: Latest (I keep it up to date - I can freeze version to troubleshoot)
Phone: Motorola Moto G7 Power (2019)
Car: 2016 Ford C-Max Energi
