### ISSUE TITLE
Can't find chromecast on version 2.4.3

### ISSUE THREAD

**Issue by dessalines** [jellyfin/jellyfin-android#634]
### Describe the bug

I just updated jellyfin to the newest version on the play store, and now it can no longer find my chromecast.

### Application version

2.4.3

### Where did you install the app from?

Google Play

### Device information

xiaomi poco x3 

### Android version

android 12

### Jellyfin server version

10.7.7

### Which video player implementations does this bug apply to?

- [ ] Web player (default)
- [ ] Integrated player (ExoPlayer)
- [X] External player (VLC, mpv, MX Player)

**Comment by nielsvanvelzen** [comment]
We've found the issue and are working on a hotfix. We'll release a new version later today.
