### ISSUE TITLE
Bug: 4.4 client doesn't connect to server

### ISSUE THREAD

**Issue by SenorSmartyPants** [jellyfin/jellyfin-android#64]
Trying to manually add server to android client.

Jellyfin client 2.8.54 on Android 4.4 **does not** connect to server.
Jellyfin client 2.8.54 on Android 5.1 **does** connect to server.

Jellyfin server 10.1.0 docker ARM.

Jellyfin port is set to 8196, running along side emby on 8096.

I changed port number in both android clients. Tried with both server name and IP number. Neither worked on 4.4.

**Comment by SenorSmartyPants** [comment]
I was able to add a server and connect using the unminified beta1. I tried Release beta1 first, but it did not connect. So then I tried unminified version.

**Comment by dkanada** [comment]
We have another beta release out, can you uninstall the current app and then reinstall the normal (minified) apk and see if it works? Thanks.

**Comment by SenorSmartyPants** [comment]
Another release after the 30-Jan-2019 04:41 dated ones on https://repo.jellyfin.org/releases/client/android/ ?

That's the unminified one I'm running right now.

**Comment by anthonylavado** [comment]
Specifically try the minified one, also known as “release”:

https://repo.jellyfin.org/releases/client/android/jellyfin-android_release_beta1.apk

**Comment by SenorSmartyPants** [comment]
I just redownloaded all the beta1 releases dated 30-Jan-2019.

Uninstalled the version I was running.

Release installs, Cannot connect using either name or IP of server.
Debug installs. Connects using either name or IP of server.
Unminified installs. Connects using either name or IP of server.

**Comment by SenorSmartyPants** [comment]
I tried the same procedure in the previous comment with beta2, no change in the results. Release still does not connect.

**Comment by dkanada** [comment]
If that's the case I am probably going to need some logs. Do you have experience getting system logs for Android devices?

**Comment by SenorSmartyPants** [comment]
Not that I recall. Some direction on that would be appreciated.

**Comment by dkanada** [comment]
If your phone isn't rooted you'll either need Android Studio or [adb](https://developer.android.com/studio/command-line/adb) installed to grab any system logs. Android Studio will find your device automatically and there is a tab for logs, if you try adb you will need to install an app like Matlog off F-Droid to grab the logs off your phone. If I can't find anything in those logs I might also need all your WebView logs which you can find with [chrome](https://developers.google.com/web/tools/chrome-devtools/remote-debugging/) or chromium, which has the same feature.

**Comment by SenorSmartyPants** [comment]
Tablet is rooted. Do I just look in the right folder for the logs? What folder would that be?

**Comment by dkanada** [comment]
If you're rooted I would still use Matlog, it just won't require any special steps to work. You can get the logs if you run it once, open Jellyfin and wait a bit, then go back to the logging app and save the logs to a file.

**Comment by mazzystr** [comment]
I'm unable to connect to my jellyfin server as well ...
Server: Version 10.2.1
Client: Both beta6.apk clients from [here](https://repo.jellyfin.org/releases/client/android/)

*unminified_release_beta5.apk app looks A-OK!

**Comment by dkanada** [comment]
Could everyone here try beta7 for this issue? @Matt07211 identifed an issue that sounds very similar to this one which he fixed in the latest update.

**Comment by mazzystr** [comment]
Server connection success confirmed

Device: Motorola XT1687
OS: Android 9
Server: Version 10.2.1
Client: android_unminified_release_beta7

**Comment by SenorSmartyPants** [comment]
Device: Amazon Otter (Kindle Fire Original)
OS: Android 4.4
Server: Version 10.2.2

I uninstalled JF between switching any versions. Both android_unminified_release_beta7 and android_release_beta7 hang on start up. No UI is ever displayed. This is worse than when I initially created this issue. 

Trying release_beta6 version displays add server UI, but cannot connect.
beta6_unminified_release displays add server UI, and connects correctly.

I haven't been able to grab a log for you yet, I will try to do that this weekend.

**Comment by SenorSmartyPants** [comment]
I've attached my first matlog attempt. This includes installing release_beta6 and adding a server, which fails to connect.

Please let me know if you need me to alter any matlog settings or run this in a different way.

[logs-2019-03-16-11-16-10.zip](https://github.com/jellyfin/jellyfin-android/files/2974081/logs-2019-03-16-11-16-10.zip)

**Comment by dkanada** [comment]
@SenorSmartyPants we have fixed the minification but this is now an issue with the WebView on older devices, so we will track progress over at #28 from now on.
