### ISSUE TITLE
Improve Jellyfin's offline app

### ISSUE THREAD

**Issue by Nuckerr** [jellyfin/jellyfin-android#642]
**Describe the feature you'd like**
When you do not have an internet connection on your phone, Jellyfin will currently complain that it cannot connect to your server.
Instead I would like to suggest that instead you can browse your downloads (see #641 ) or check server connection.

**Comment by Morgan-6Freedom** [comment]
I think it's a duplicate of https://github.com/jellyfin/jellyfin-android/issues/139

**Comment by Maxr1998** [comment]
Indeed, closing as duplicate.
