### ISSUE TITLE
Unnecessary x265 transcoding and broken transcode playback (blackscreen)

### ISSUE THREAD

**Issue by JulioNahum** [jellyfin/jellyfin-android#65]
When playing a video in HEVC format the player transcodes to H.264 but does not reproduce image. The same happens when transcoding a video due to problems with internet speed. When lowering the quality, this black screen BUG happens and does not reproduce image. My device supports H.265 and other audio and video codecs.

**Screenshots**
 https://imgur.com/EgG4sZ5

**System (please complete the following information):**
 - App version: [2.0.0-rc.3]
 - Android version: [ Android 9.0]
 - Device manufacturer and model: [LG G4]
 - Jellyfin server version: [10.6.3]
 - The type of video player implementation used: [Integrated player (ExoPlayer)]

**Comment by Maxr1998** [comment]
See #28 for more information on that, there's still some more work to do. Also, it seems your screenshot link doesn't work, so if you wanted to add one, could you fix it please?

**Comment by JulioNahum** [comment]
> See #28 for more information on that, there's still some more work to do. Also, it seems your screenshot link doesn't work, so if you wanted to add one, could you fix it please?

https://imgur.com/EgG4sZ5

Excuse me. I already fixed the link of the image.

**Comment by Electry** [comment]
I have the same issue with h264 content played remotely (and transcoded to bitrate that fits within my download speed).
Black screen, just like in @JulioNahum's pictures, and the video never starts. Admin dashboard shows "Transcoding" and is stuck at 0:00.

If I start the same video file without restricting the bitrate, it direct plays just fine. Transcoding worked with the previous web-based player.

I can provide more info if you need, just let me know what to do.
