### ISSUE TITLE
MRMC fork as basis for Android app?

### ISSUE THREAD

**Issue by mobamoba** [jellyfin/jellyfin-android#65]
I'm not a coder but I was playing around with my Fire TV system (which uses Android) this past week and noticed MRMC, which is a stripped-down and rebranded Kodi for Android that uses an Emby for Kodi plugin (can't tell if it's forked from original Emby or their own code) to connect to an Emby server.

It worked flawlessly and it made me wonder if this might not be an easier starting point for an Android app than building one from scratch, i.e. using a stripped-down Kodi rebranded with Jellyfin and thus using Kodi's player and the Emby/Jellyfin plugin.

Love what you guys are doing - especially since Emby decided to strip out a working feature (transcoding) in order to make users pay for it in the latest release which is really appalling behavior IMHO - and wanted to make the Jellyfin developers aware of this option in case they weren't already.

Here's the MRMC git in case it's helpful: https://github.com/MrMC/mrmc

**Comment by anthonylavado** [comment]
We are going to be providing the MrMC devs with access to a Jellyfin server so they can hopefully add compatibility.

Also in future, the current apps will be replaced by a larger set of apps that are built with React-Native. This gives us the power to build for iOS, tvOS, Android, Android TV from a common base.
