### ISSUE TITLE
Video control bars cannot be adjusted in some videos when using the exo player

### ISSUE THREAD

**Issue by CodeName393** [jellyfin/jellyfin-android#650]
### Describe the bug

I can't adjust it like the picture.
Also, if I skip, etc., it will be initialized to 0 seconds.
It's only like this in a few video
![Screenshot_20220424-154009_Jellyfin](https://user-images.githubusercontent.com/62503817/164960280-f414dc56-4dd4-4f8d-a015-1f94fe99a934.png)

### Application version

2.4.4

### Where did you install the app from?

Google Play

### Device information

Galaxy Fold 3

### Android version

Android 12 / OneUI 4.1

### Jellyfin server version

10.7.6

### Which video player implementations does this bug apply to?

- [ ] Web player (default)
- [X] Integrated player (ExoPlayer)
- [ ] External player (VLC, mpv, MX Player)

**Comment by Maxr1998** [comment]
The videos are probably not seekable. I suggest using a container format that supports seeking like Matroska.
