### ISSUE TITLE
Media Playback Controls are hidden when Casting

### ISSUE THREAD

**Issue by bengalih** [jellyfin/jellyfin-android#678]
### Describe the bug

Describe the bug

When casting to a google device media playback controls are not exposed to the user without effort, making the cast appear to not function.

To Reproduce

- Begin cast playback from 2.4.4 app.
- Toast of playback will appear on bottom of screen for maybe 0.25-1 second
- No other indicator that cast is successful is shown.  In order to verify that playback is happening, user must choose Cast icon again from top of app and then "Remote Control".  This will bring up the remote control window which shows the playback status of the media.

Expected behavior

- The remote control window should open immediately upon playback of the media without further user interaction.  Current behavior makes it appear that cast is unsuccessful/terminated.

I first reported this in https://github.com/jellyfin/jellyfin-android/issues/600, it looks like that bug was "solved" simply be removing the ability to cast during playback, but only prior to.  Regardless, this issue still exists.

### Application version

2.4.4

### Where did you install the app from?

Google Play

### Device information

Pixel 3XL

### Android version

Android 11

### Jellyfin server version

10.7.7

### Which video player implementations does this bug apply to?

- [X] Web player (default)
- [ ] Integrated player (ExoPlayer)
- [ ] External player (VLC, mpv, MX Player)

**Comment by bengalih** [comment]
This issue still affects 2.4.4.  There have been no updates to change this.

**Comment by vincegre** [comment]
+1 on this ! and controls in Android notificatior for Jellyfin are inoperative too :(
