### ISSUE TITLE
What is the reason of creating separate property for every View?

### ISSUE THREAD

**Issue by shalva97** [jellyfin/jellyfin-android#683]
Hi, sorry for not using your templates for this issue... hope its fine.

I have a question about the way ViewBinding is used in the app. So for example, in `ConnectFragment` every property of the binding is assigned to the class's properties.

https://github.com/jellyfin/jellyfin-android/blob/6ea9bf684532b7ff9476ee9d82500da5098814eb/app/src/main/java/org/jellyfin/mobile/setup/ConnectFragment.kt#L46-L53

What is the reason of creating separate property for every View? Same pattern is in `PlayerFragment`

**Comment by nielsvanvelzen** [comment]
I guess this is a left-over from when the app used `findViewById` calls. Relevant PR would be #50. @Maxr1998 should know for sure though.

**Comment by Maxr1998** [comment]
Well, it's mostly syntactic sugar to make the code more readable. Note that in the Fragments it doesn't really create properties, it only creates a getter *without a backing property*. Thus, every call is directly delegated to the ViewBinding object. I hope that answers your question.

**Comment by shalva97** [comment]
> Note that in the Fragments it doesn't really create properties

Okay, nice. 

Ummm, I believe I can refactor this and it will be a bit better... will you consider a PR on this? I know this might be the lowest priority... but I want to work on this :D

**Comment by Maxr1998** [comment]
Sure, if you have an idea on how to improve it, feel free to open a PR.
