### ISSUE TITLE
Android 10's 3 button navigation buttons cover the audio playback controls

### ISSUE THREAD

**Issue by chenichadowitz** [jellyfin/jellyfin-android#69]
**Describe the bug**

In Android 10, I'm using the 3-button system navigation setting (not gestures). These 3 buttons remain visible and active on top of Jellyfin's playback progress bar and play/pause/next controls. I believe they should either autohide or the UI should end above this section of the screen.

**To Reproduce**

0. Use 3 button system navigation (System Settings > System > Gestures > System Navigation)
1. Install Jellyfin (Beta) for Android from the Play Store (beta channel)
2. Start Jellyfin and connect/login to your server
3. Observe while browsing media that the 3 navigation buttons are transparently overlaid on top of the Jellyfin UI
4. Choose a song to play
5. Observe that the playback controls/display at the bottom appear underneath the transparent system navigation buttons

**Expected behavior**

I think it makes sense to use the full screen for video playback (with auto-hide navigation buttons), but for audio playback or browsing it may make more sense to limit the UI to just above the navigation buttons.

**Screenshots**

![jellyfin_android_screenshot](https://user-images.githubusercontent.com/3758336/91328283-b1a86280-e794-11ea-9e53-e551a4bf3831.png)

**System (please complete the following information):**
 - App version: 2.0.0-rc.3
 - Android version: Android 10
 - Device manufacturer and model: Google Pixel 4a
 - Jellyfin server version: 10.6.3
 - The type of video player implementation used: web player.

**Additional context**

I did enable the `Make music player notification always display` option.

**Comment by nielsvanvelzen** [comment]
I think this can be fixed by using the [env()](https://developer.mozilla.org/en-US/docs/Web/CSS/env) function in the CSS of the web UI. @MrTimscampi what do you think?

**Comment by Maxr1998** [comment]
Oops, this was introduced in #54. I didn't think of the music controls when testing, the other components were looking fine. I could revert the WebView drawing behind the navigation bar, but fixing it in the webapp would be neater :thinking:
Maybe inject custom CSS only in the app?

**Comment by MrTimscampi** [comment]
> Maybe inject custom CSS only in the app?

That's the way we do it on iOS, I believe. Maybe @thornbill can confirm ?

**Comment by thornbill** [comment]
I’m not injecting any custom css for iOS.
