### ISSUE TITLE
Music playback stops after some time when app is in background.

### ISSUE THREAD

**Issue by JohnDowson** [jellyfin/jellyfin-android#70]
**Describe the bug**
Playback abruptly stops some time after pulling another app to the foreground.

**To Reproduce**
1. Start playback
2. Open a different app in foreground
3. Wait

**System (please complete the following information):**
 - App version: master at 811d911
 - Android version: Android 9
 - Device manufacturer and model: Xiaomi Redmi Redmi S2
 - Jellyfin server version: 10.6.3

**Additional context**
Judging by disappearing notification and app reloading when switching back to it, looks like it gets suspended, but all battery optimisations are disabled and system has plenty of memory left. Version present in play store has same issue, but much more often, about every minute, and even when Jellyfin was in foreground.

**Comment by Maxr1998** [comment]
This is very likely the extremely aggressive memory management from MIUI. Not sure if we can do something about this in the short term, a webapp is always more heavy on memory than other apps.
If you only want to play music, I can recommend dkanada/gelli as an alternative.

**Comment by JohnDowson** [comment]
> If you only want to play music, I can recommend [dkanada/gelli](https://github.com/dkanada/gelli) as an alternative.
Welp, that doesn't work at all. Guess that's as good a reason as any to flash a sane android build
