### ISSUE TITLE
black sceen when i open app with Pixel 3 XL 

### ISSUE THREAD

**Issue by Astate** [jellyfin/jellyfin-android#70]
I only open the jellyfin and immediately i have black screen with my Google Pixel 3 and Jellyfin beta1 version

**Comment by anthonylavado** [comment]
Hi there! 👋 
Which version did you install?

Thanks!

**Comment by Astate** [comment]
Jellyfin Android release beta1

**Comment by thornbill** [comment]
Hey @Astate 👋 Have you tried this in the latest beta? Hopefully this was fixed for you, but if not it may help to have some additional information about your Android version and the webview version your phone is using. Thanks!

**Comment by Astate** [comment]
Hi @thornbill, the last beta correct the problem. I use last version of Android 9

**Comment by thornbill** [comment]
Closing this since the latest beta corrected the problem.
