### ISSUE TITLE
Integrated player plays theme/background videos in foreground

### ISSUE THREAD

**Issue by kace** [jellyfin/jellyfin-android#706]
Quick thanks to everyone who works on this project!

### Describe the bug

When enabled in _Display_ settings, theme videos will play in the foreground on Android clients configured to use the integrated player. Theme videos work on Android clients using the web player (they play in the background behind the episode selection w/ slight transparency). I haven't confirmed the behavior when using an external player. Also not sure if this is relevant, but this seems independent of the source theme video format as I've seen this w/ .mp4 and .mkv theme videos.

### Application version

2.4.4

### Where did you install the app from?

Google Play

### Device information

Samsung S8+

### Android version

Android 9

### Jellyfin server version

10.7.7

### Which video player implementations does this bug apply to?

- [ ] Web player (default)
- [X] Integrated player (ExoPlayer)
- [ ] External player (VLC, mpv, MX Player)

**Comment by GlassedSilver** [comment]
Unstale please, still an annoying issue to this day.

**Comment by nielsvanvelzen** [comment]
I just reviewed & pressed the merge button. Credits go to @Maxr1998.

**Comment by GlassedSilver** [comment]
You're correct of course, I already hearted @Maxr1998's PR and whilst the credit goes to them for sure I also want to thank you for the quick merge! :)

Looking forward to the next release now. 🎉
