### ISSUE TITLE
Watched TV shows should not have a permanent checkmark 

### ISSUE THREAD

**Issue by mdinger** [jellyfin/jellyfin-android#714]
### Describe the bug

1. Go to a TV show library with watched and unwatched shows
2. The unwatched shows will have a blue number of episodes remaining
3. The watched shows will have a blue checkmark

The blue checkmark should be removed or at least temporary. The number of episodes to watch is useful because it tells you how much remains. A watched show needs no extra information to highlight it is unwatched anymore.

When browsing, they actually make it harder to notice which show you have not seen because all shows have a blue mark. Plex leaves watched shows blank which makes browsing easier to parse visually.

### Application version

2.4.4

### Where did you install the app from?

Google Play

### Device information

Google Pixel 4a

### Android version

Android 12

### Jellyfin server version

10.8.0

### Which video player implementations does this bug apply to?

- [ ] Web player (default)
- [ ] Integrated player (ExoPlayer)
- [ ] External player (VLC, mpv, MX Player)

**Comment by mdinger** [comment]
Still an issue

**Comment by susonthapa** [comment]
@mdinger I don't think this has anything to do with the app. The app basically renders the Jellyfin web UI so this issue might be a better candidate [here](https://github.com/jellyfin/jellyfin-web).

**Comment by mdinger** [comment]
Okay thanks
