### ISSUE TITLE
Tablet home screen show small, poor resolution images 

### ISSUE THREAD

**Issue by SenorSmartyPants** [jellyfin/jellyfin-android#72]
Android 4.4 Slimkat - Amazon OtterX (Kindle Fire First gen)
Screen resolution 1024 × 600 - density 169 ppi
Jellyfin beta 1 - unminified.

If Jellyfin is started in portrait orientation show images are very small, not much text is visible per item.
![screenshot_2019-02-03-13-34-33](https://user-images.githubusercontent.com/991618/52185433-462f2680-27e5-11e9-8889-4e4889718e62.png)
 
Rotate to landscape while Jellyfin is still running. Images are larger but very pixelated.
![screenshot_2019-02-03-13-33-09](https://user-images.githubusercontent.com/991618/52185464-7b3b7900-27e5-11e9-8fdd-701d62eb8141.png)

Close Jellyfin app, Restart in landscape orientation. Images are no longer as pixelated. Click into these images to notice the difference.
![screenshot_2019-02-03-13-33-45](https://user-images.githubusercontent.com/991618/52185484-a756fa00-27e5-11e9-8200-2bbe9a6788fd.png)

Portrait mode on tablet should display larger images with more text displayed.

I'm imagining that when the app is started in portrait mode, it requests images at a certain resolution. Landscape should have a higher res image, but doesn't requests a new copy.

**Comment by dkanada** [comment]
this might have been fixed by #88, which should be in the next beta

**Comment by dkanada** [comment]
@SenorSmartyPants could you confirm that beta7 fixes this issue?

**Comment by SenorSmartyPants** [comment]
IDK about beta7, (see issue #64, can't connect using release beta7) but this is fixed in beta 6. First fixed in which ever beta included the "mobile" layout stuff.

![Screenshot_2019-03-14-15-23-53](https://user-images.githubusercontent.com/991618/54389093-50a6d080-466d-11e9-8b48-e12b9192cb2b.png)
