### ISSUE TITLE
Allow app to work without network internet connection 

### ISSUE THREAD

**Issue by seversonic** [jellyfin/jellyfin-android#729]
Prevent app from kicking a user to the connection screen when no internet is available. 

I moved into a new place and didn't have internet for a few days. I setup my server (docker) so I could watch some shows. 

When I would try to connect to the server with my app it would load, and then kick me out repeatedly. Definitely not a caching issue, as when I watched things through a web browser and then tried the app again, the most recent watched show was updated. 

I'm fully able to watch shows through any web browser while my network does not have an internet connection, but unable to use the app. App connects to server but then disconnects. 

![Screenshot_20220708-081510_Jellyfin.jpg](https://user-images.githubusercontent.com/43625790/178009866-ad22103c-dd5e-4c3c-b4a7-856c0f6c6c0f.jpg)

This image pops up after being connected for several seconds, and does reconnect when you press the button.

**Comment by nielsvanvelzen** [comment]
Are you perhaps using custom CSS?

**Comment by Seversonic** [comment]
> Are you perhaps using custom CSS?

The only thing I've changed from stock is the theme. I'm not sure if that counts?

**Comment by Seversonic** [comment]
> If the theme uses external resources they will fail to load and make the app think the connection to the server is lost.

You are 100% correct! Removed the CSS that was importing the theme and it worked! 

Thank you
