### ISSUE TITLE
ExoPlayer not playing Jpn AAC file

### ISSUE THREAD

**Issue by animegasan** [jellyfin/jellyfin-android#73]
**Describe the bug**

I can't play anime files with Jpn AAC audio description. But if the audio file like the one below can run smoothly.

**Screenshots**

![Screenshot_20200830_030246](https://user-images.githubusercontent.com/14136053/91645528-e9066000-ea6f-11ea-909e-4f10e247f9fb.jpg)
![Screenshot_20200830_032008](https://user-images.githubusercontent.com/14136053/91645531-ec015080-ea6f-11ea-9031-5843aab4fd73.jpg)

**System (please complete the following information):**
 - App version: 2.0.0-rc.3
 - Android version: Android 8.1
 - Device manufacturer and model: Vivo V7
 - Jellyfin server version: 10.6.2
 - The type of video player implementation used: Integrated player (ExoPlayer)

**Comment by Maxr1998** [comment]
Does it just stay on a black screen? Could you provide me logs of when the issue occurs?

**Comment by animegasan** [comment]
> Does it just stay on a black screen? Could you provide me logs for when the issue occurs?

Yes. Just black screen 

http://192.168.20.2:8096/videos/98e5f0e4-7132-4c36-71a6-2dc1cf877dae/hls1/main/0.ts?DeviceId=TW96aWxsYS81LjAgKFgxMTsgVWJ1bnR1OyBMaW51eCB4ODZfNjQ7IHJ2Ojc3LjApIEdlY2tvLzIwMTAwMTAxIEZpcmVmb3gvNzcuMHwxNTk4NzMyMDczNTc2&MediaSourceId=98e5f0e471324c3671a62dc1cf877dae&VideoCodec=h264&AudioCodec=mp3,aac&AudioStreamIndex=1&SubtitleStreamIndex=2&VideoBitrate=139808000&AudioBitrate=192000&PlaySessionId=cbdd0b0106ca45138767389c49fb7033&api_key=aea52ffc939a46ae916a28fdc3590292&SubtitleMethod=Encode&TranscodingMaxAudioChannels=2&RequireAvc=false&Tag=bb9925f7f0ab979039aa3a11a77545ac&SegmentContainer=ts&MinSegments=1&BreakOnNonKeyFrames=True&h264-profile=high,main,baseline,constrainedbaseline&h264-level=51&h264-deinterlace=true&TranscodeReasons=SubtitleCodecNotSupported&allowVideoStreamCopy=false

{"Protocol":"File","Id":"98e5f0e471324c3671a62dc1cf877dae","Path":"/nas-hdd/hdd-01/Anime/TVs/Akkun to Kanojo/Akkun to Kanojo S01E01.mkv","Type":"Default","Container":"mkv,webm","Size":30405741,"Name":"Akkun to Kanojo S01E01","IsRemote":false,"ETag":"bb9925f7f0ab979039aa3a11a77545ac","RunTimeTicks":2139350000,"ReadAtNativeFramerate":false,"IgnoreDts":false,"IgnoreIndex":false,"GenPtsInput":false,"SupportsTranscoding":true,"SupportsDirectStream":true,"SupportsDirectPlay":true,"IsInfiniteStream":false,"RequiresOpening":false,"RequiresClosing":false,"RequiresLooping":false,"SupportsProbing":true,"VideoType":"VideoFile","MediaStreams":[{"Codec":"h264","Language":"eng","TimeBase":"1/1000","CodecTimeBase":"1001/48000","Title":"[Quinime] Akkun to Kanojo - 01","VideoRange":"SDR","DisplayTitle":"720p H264","NalLengthSize":"0","IsInterlaced":false,"IsAVC":false,"BitRate":1137008,"BitDepth":10,"RefFrames":1,"IsDefault":true,"IsForced":false,"Height":720,"Width":1280,"AverageFrameRate":23.976025,"RealFrameRate":23.976025,"Profile":"High 10","Type":"Video","AspectRatio":"16:9","Index":0,"IsExternal":false,"IsTextSubtitleStream":false,"SupportsExternalStream":false,"PixelFormat":"yuv420p10le","Level":50},{"Codec":"aac","Language":"jpn","TimeBase":"1/1000","CodecTimeBase":"1/44100","Title":"[Quinime] Akkun to Kanojo - 01","DisplayTitle":"Jpn AAC stereo Default","IsInterlaced":false,"ChannelLayout":"stereo","BitRate":192000,"Channels":2,"SampleRate":44100,"IsDefault":true,"IsForced":false,"Profile":"HE-AAC","Type":"Audio","Index":1,"IsExternal":false,"IsTextSubtitleStream":false,"SupportsExternalStream":false,"Level":0},{"Codec":"ass","Language":"ind","TimeBase":"1/1000","CodecTimeBase":"0/1","Title":"[Quinime] Akkun to Kanojo - 01","localizedUndefined":"Undefined","localizedDefault":"Default","localizedForced":"Forced","DisplayTitle":"[Quinime] Akkun to Kanojo - 01 - Ind - Default","IsInterlaced":false,"IsDefault":true,"IsForced":false,"Type":"Subtitle","Index":2,"IsExternal":false,"IsTextSubtitleStream":true,"SupportsExternalStream":true,"Level":0}],"MediaAttachments":[{"Codec":"ttf","CodecTag":"[0][0][0][0]","Index":3,"FileName":"comicbd.ttf","MimeType":"application/x-truetype-font"},{"Codec":"otf","CodecTag":"[0][0][0][0]","Index":4,"FileName":"MetaPro-Bold.otf","MimeType":"application/vnd.ms-opentype"},{"Codec":"ttf","CodecTag":"[0][0][0][0]","Index":5,"FileName":"MrsKate (1).ttf","MimeType":"application/x-truetype-font"},{"Codec":"ttf","CodecTag":"[0][0][0][0]","Index":6,"FileName":"OpenSans-Semibold.ttf","MimeType":"application/x-truetype-font"},{"Codec":"ttf","CodecTag":"[0][0][0][0]","Index":7,"FileName":"vermin_vibes.ttf","MimeType":"application/x-truetype-font"},{"Codec":"ttf","CodecTag":"[0][0][0][0]","Index":8,"FileName":"AGENCYB.TTF","MimeType":"application/x-truetype-font"}],"Formats":[],"Bitrate":1329008,"RequiredHttpHeaders":{}}

/usr/lib/jellyfin-ffmpeg/ffmpeg -fflags +genpts -f matroska,webm -i file:"/nas-hdd/hdd-01/Anime/TVs/Akkun to Kanojo/Akkun to Kanojo S01E01.mkv" -map_metadata -1 -map_chapters -1 -threads 1 -map 0:0 -map 0:1 -codec:v:0 copy -vsync -1 -codec:a:0 copy -copyts -avoid_negative_ts disabled -f hls -max_delay 5000000 -hls_time 6 -individual_header_trailer 0 -hls_segment_type mpegts -start_number 0 -hls_segment_filename "/var/lib/jellyfin/transcodes/0a2695a04d81766df358f5aad5cabb11%d.ts" -hls_playlist_type vod -hls_list_size 0 -y "/var/lib/jellyfin/transcodes/0a2695a04d81766df358f5aad5cabb11.m3u8"


ffmpeg version 4.3.1 Copyright (c) 2000-2020 the FFmpeg developers
  built with gcc 8 (Debian 8.3.0-6)
  configuration: --prefix=/usr/lib/jellyfin-ffmpeg --target-os=linux --disable-doc --disable-ffplay --disable-shared --disable-libxcb --disable-sdl2 --disable-xlib --enable-gpl --enable-version3 --enable-static --enable-libfontconfig --enable-fontconfig --enable-gmp --enable-gnutls --enable-libass --enable-libbluray --enable-libdrm --enable-libfreetype --enable-libfribidi --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libwebp --enable-libx264 --enable-libx265 --enable-libzvbi --arch=amd64 --enable-libzimg --enable-opencl --enable-vaapi --enable-amf --enable-libmfx --enable-vdpau --enable-cuda --enable-cuda-llvm --enable-cuvid --enable-nvenc --enable-nvdec --enable-ffnvcodec --enable-libdav1d
  libavutil      56. 51.100 / 56. 51.100
  libavcodec     58. 91.100 / 58. 91.100
  libavformat    58. 45.100 / 58. 45.100
  libavdevice    58. 10.100 / 58. 10.100
  libavfilter     7. 85.100 /  7. 85.100
  libswscale      5.  7.100 /  5.  7.100
  libswresample   3.  7.100 /  3.  7.100
  libpostproc    55.  7.100 / 55.  7.100
Input #0, matroska,webm, from 'file:/nas-hdd/hdd-01/Anime/TVs/Akkun to Kanojo/Akkun to Kanojo S01E01.mkv':
  Metadata:
    encoder         : libebml v1.3.5 + libmatroska v1.4.8
    creation_time   : 2018-04-06T19:27:57.000000Z
  Duration: 00:03:33.94, start: 0.000000, bitrate: 1137 kb/s
    Chapter #0:0: start 0.000000, end 54.000000
    Metadata:
      title           : Quinime - OP
    Chapter #0:1: start 54.000000, end 209.000000
    Metadata:
      title           : Quinime - Main
    Chapter #0:2: start 209.000000, end 213.935000
    Metadata:
      title           : Quinime - ED
    Stream #0:0(eng): Video: h264 (High 10), yuv420p10le(progressive), 1280x720 [SAR 1:1 DAR 16:9], 23.98 fps, 23.98 tbr, 1k tbn, 47.95 tbc (default)
    Metadata:
      title           : [Quinime] Akkun to Kanojo - 01
      BPS             : 1043359
      BPS-eng         : 1043359
      DURATION        : 00:03:33.839000000
      DURATION-eng    : 00:03:33.839000000
      NUMBER_OF_FRAMES: 5127
      NUMBER_OF_FRAMES-eng: 5127
      NUMBER_OF_BYTES : 27888877
      NUMBER_OF_BYTES-eng: 27888877
      _STATISTICS_WRITING_APP: mkvmerge v17.0.0 ('Be Ur Friend') 64-bit
      _STATISTICS_WRITING_APP-eng: mkvmerge v17.0.0 ('Be Ur Friend') 64-bit
      _STATISTICS_WRITING_DATE_UTC: 2018-04-06 19:27:57
      _STATISTICS_WRITING_DATE_UTC-eng: 2018-04-06 19:27:57
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
    Stream #0:1(jpn): Audio: aac (HE-AAC), 44100 Hz, stereo, fltp (default)
    Metadata:
      title           : [Quinime] Akkun to Kanojo - 01
      BPS             : 64033
      BPS-eng         : 64033
      DURATION        : 00:03:33.902000000
      DURATION-eng    : 00:03:33.902000000
      NUMBER_OF_FRAMES: 4606
      NUMBER_OF_FRAMES-eng: 4606
      NUMBER_OF_BYTES : 1712111
      NUMBER_OF_BYTES-eng: 1712111
      _STATISTICS_WRITING_APP: mkvmerge v17.0.0 ('Be Ur Friend') 64-bit
      _STATISTICS_WRITING_APP-eng: mkvmerge v17.0.0 ('Be Ur Friend') 64-bit
      _STATISTICS_WRITING_DATE_UTC: 2018-04-06 19:27:57
      _STATISTICS_WRITING_DATE_UTC-eng: 2018-04-06 19:27:57
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
    Stream #0:2(ind): Subtitle: ass (default)
    Metadata:
      title           : [Quinime] Akkun to Kanojo - 01
      BPS             : 213
      BPS-eng         : 213
      DURATION        : 00:02:33.410000000
      DURATION-eng    : 00:02:33.410000000
      NUMBER_OF_FRAMES: 59
      NUMBER_OF_FRAMES-eng: 59
      NUMBER_OF_BYTES : 4095
      NUMBER_OF_BYTES-eng: 4095
      _STATISTICS_WRITING_APP: mkvmerge v17.0.0 ('Be Ur Friend') 64-bit
      _STATISTICS_WRITING_APP-eng: mkvmerge v17.0.0 ('Be Ur Friend') 64-bit
      _STATISTICS_WRITING_DATE_UTC: 2018-04-06 19:27:57
      _STATISTICS_WRITING_DATE_UTC-eng: 2018-04-06 19:27:57
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
    Stream #0:3: Attachment: ttf
    Metadata:
      filename        : comicbd.ttf
      mimetype        : application/x-truetype-font
    Stream #0:4: Attachment: otf
    Metadata:
      filename        : MetaPro-Bold.otf
      mimetype        : application/vnd.ms-opentype
    Stream #0:5: Attachment: ttf
    Metadata:
      filename        : MrsKate (1).ttf
      mimetype        : application/x-truetype-font
    Stream #0:6: Attachment: ttf
    Metadata:
      filename        : OpenSans-Semibold.ttf
      mimetype        : application/x-truetype-font
    Stream #0:7: Attachment: ttf
    Metadata:
      filename        : vermin_vibes.ttf
      mimetype        : application/x-truetype-font
    Stream #0:8: Attachment: ttf
    Metadata:
      filename        : AGENCYB.TTF
      mimetype        : application/x-truetype-font
Output #0, hls, to '/var/lib/jellyfin/transcodes/0a2695a04d81766df358f5aad5cabb11.m3u8':
  Metadata:
    encoder         : Lavf58.45.100
    Stream #0:0: Video: h264 (High 10), yuv420p10le(progressive), 1280x720 [SAR 1:1 DAR 16:9], q=2-31, 23.98 fps, 23.98 tbr, 90k tbn, 23.98 tbc (default)
    Stream #0:1: Audio: aac (HE-AAC), 44100 Hz, stereo, fltp (default)
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #0:1 -> #0:1 (copy)
Press [q] to stop, [?] for help
[hls @ 0x564a5f073140] Opening '/var/lib/jellyfin/transcodes/0a2695a04d81766df358f5aad5cabb110.ts' for writing
[hls @ 0x564a5f073140] Opening '/var/lib/jellyfin/transcodes/0a2695a04d81766df358f5aad5cabb111.ts' for writing
[hls @ 0x564a5f073140] Opening '/var/lib/jellyfin/transcodes/0a2695a04d81766df358f5aad5cabb112.ts' for writing
[hls @ 0x564a5f073140] Opening '/var/lib/jellyfin/transcodes/0a2695a04d81766df358f5aad5cabb113.ts' for writing
[hls @ 0x564a5f073140] Opening '/var/lib/jellyfin/transcodes/0a2695a04d81766df358f5aad5cabb114.ts' for writing
[hls @ 0x564a5f073140] Opening '/var/lib/jellyfin/transcodes/0a2695a04d81766df358f5aad5cabb115.ts' for writing
[hls @ 0x564a5f073140] Opening '/var/lib/jellyfin/transcodes/0a2695a04d81766df358f5aad5cabb116.ts' for writing
[hls @ 0x564a5f073140] Opening '/var/lib/jellyfin/transcodes/0a2695a04d81766df358f5aad5cabb117.ts' for writing
[hls @ 0x564a5f073140] Opening '/var/lib/jellyfin/transcodes/0a2695a04d81766df358f5aad5cabb118.ts' for writing
[hls @ 0x564a5f073140] Opening '/var/lib/jellyfin/transcodes/0a2695a04d81766df358f5aad5cabb119.ts' for writing
[hls @ 0x564a5f073140] Opening '/var/lib/jellyfin/transcodes/0a2695a04d81766df358f5aad5cabb1110.ts' for writing
[hls @ 0x564a5f073140] Opening '/var/lib/jellyfin/transcodes/0a2695a04d81766df358f5aad5cabb1111.ts' for writing
[hls @ 0x564a5f073140] Opening '/var/lib/jellyfin/transcodes/0a2695a04d81766df358f5aad5cabb1112.ts' for writing
[hls @ 0x564a5f073140] Opening '/var/lib/jellyfin/transcodes/0a2695a04d81766df358f5aad5cabb1113.ts' for writing
[hls @ 0x564a5f073140] Opening '/var/lib/jellyfin/transcodes/0a2695a04d81766df358f5aad5cabb1114.ts' for writing
[hls @ 0x564a5f073140] Opening '/var/lib/jellyfin/transcodes/0a2695a04d81766df358f5aad5cabb1115.ts' for writing
[hls @ 0x564a5f073140] Opening '/var/lib/jellyfin/transcodes/0a2695a04d81766df358f5aad5cabb1116.ts' for writing
[hls @ 0x564a5f073140] Opening '/var/lib/jellyfin/transcodes/0a2695a04d81766df358f5aad5cabb1117.ts' for writing
[hls @ 0x564a5f073140] Opening '/var/lib/jellyfin/transcodes/0a2695a04d81766df358f5aad5cabb1118.ts' for writing
[hls @ 0x564a5f073140] Opening '/var/lib/jellyfin/transcodes/0a2695a04d81766df358f5aad5cabb1119.ts' for writing
[hls @ 0x564a5f073140] Opening '/var/lib/jellyfin/transcodes/0a2695a04d81766df358f5aad5cabb1120.ts' for writing
[hls @ 0x564a5f073140] Opening '/var/lib/jellyfin/transcodes/0a2695a04d81766df358f5aad5cabb1121.ts' for writing
[hls @ 0x564a5f073140] Opening '/var/lib/jellyfin/transcodes/0a2695a04d81766df358f5aad5cabb1122.ts' for writing
[hls @ 0x564a5f073140] Opening '/var/lib/jellyfin/transcodes/0a2695a04d81766df358f5aad5cabb1123.ts' for writing
[hls @ 0x564a5f073140] Opening '/var/lib/jellyfin/transcodes/0a2695a04d81766df358f5aad5cabb1124.ts' for writing
[hls @ 0x564a5f073140] Opening '/var/lib/jellyfin/transcodes/0a2695a04d81766df358f5aad5cabb1125.ts' for writing
[hls @ 0x564a5f073140] Opening '/var/lib/jellyfin/transcodes/0a2695a04d81766df358f5aad5cabb1126.ts' for writing
[hls @ 0x564a5f073140] Opening '/var/lib/jellyfin/transcodes/0a2695a04d81766df358f5aad5cabb1127.ts' for writing
[hls @ 0x564a5f073140] Opening '/var/lib/jellyfin/transcodes/0a2695a04d81766df358f5aad5cabb1128.ts' for writing
[hls @ 0x564a5f073140] Opening '/var/lib/jellyfin/transcodes/0a2695a04d81766df358f5aad5cabb1129.ts' for writing
[hls @ 0x564a5f073140] Opening '/var/lib/jellyfin/transcodes/0a2695a04d81766df358f5aad5cabb1130.ts' for writing
[hls @ 0x564a5f073140] Opening '/var/lib/jellyfin/transcodes/0a2695a04d81766df358f5aad5cabb1131.ts' for writing
[hls @ 0x564a5f073140] Opening '/var/lib/jellyfin/transcodes/0a2695a04d81766df358f5aad5cabb1132.ts' for writing
[hls @ 0x564a5f073140] Opening '/var/lib/jellyfin/transcodes/0a2695a04d81766df358f5aad5cabb1133.ts' for writing
[hls @ 0x564a5f073140] Opening '/var/lib/jellyfin/transcodes/0a2695a04d81766df358f5aad5cabb1134.ts' for writing
frame= 5127 fps=0.0 q=-1.0 Lsize=N/A time=00:03:33.88 bitrate=N/A speed= 714x    
video:27235kB audio:1672kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown

**Comment by misterbit-pro** [comment]
I have a similar problem, but in my case the video is green. Subtitles come up though.
![Screenshot_20201025-214257_Jellyfin.jpg](https://user-images.githubusercontent.com/47662866/97118743-230c7f00-170c-11eb-9ba9-1f4e3dc115e4.jpg)
