### ISSUE TITLE
External player (VLC) not adding to playback queue

### ISSUE THREAD

**Issue by TechInMD** [jellyfin/jellyfin-android#755]
When using VLC as an external player (I prefer VLC as the codecs allow direct play for most content) I have experienced that after every file played, it returns back to the web UI. Skipping episodes, shuffle, etc. all result in returning to the web UI. ExoPlayer and The WebUI player both function normally, but usually result in transcoding the content. I also see the rotating cone throughout the playback as if it was buffering the content. I'm not sure what information you would require from me as far as device information, and I am able to reproduce with multiple Android devices, so i will do my best to provide as much as possible.

Client version: 2.4.4
Device: Multiple Android devices and versions.
VLC version: 3.5.0 installed from Play Store
JF Server version: 10.8.3 Linux Debian x64 installed from JF repo.

**Comment by Maxr1998** [comment]
Does this still happen on the latest 2.5.0 beta release?
