### ISSUE TITLE
ExoPlayer: Add SW/HW decoding toggle

### ISSUE THREAD

**Issue by LazyGeniusMan** [jellyfin/jellyfin-android#760]
**Describe the feature you'd like**

It would be nice if there's a toggle button to switch between SW and HW decoding in the player UI when using ExoPlayer.

**Additional context**

Based on my observation, looks like currently ExoPlayer in Jellyfin Android choose either automatically or HW decoding since there's a video that will lag in my device if it's played using HW decoding (it's playing smoothly if using SW decoding). Other alternative that has been tried and it's problem experienced by me:
- Web Player: didn't have the toggle. Can't direct play for HEVC files.
- MPV: have the toggle ~~but can't play eac3 audio files in my device (the player just flashing and then closed).~~ It can, the problem was another thing. MPV fulfill my requirement, but it's still nice to have in the ExoPlayer since it's more integrated.
- VLC: didn't have the toggle in the player but it's in the app setting. Video files using external subtitle didn't detected in my device.

**Comment by susonthapa** [comment]
I think this feature will be helpful for many users and I am willing to work on it. I was thinking of adding a button (a simple toggle) to the controls section.
<img width="418" alt="image" src="https://user-images.githubusercontent.com/33973551/201466583-ffab3c0b-87a3-476f-aa48-c14f71e1c012.png">
I would be grateful if @Maxr1998 could share some thoughts on this. I think the app is already cluttered with a lot of buttons and it would be nice if all of the settings related to the playback can be grouped into a simple overlay but that would require quite some work. Something to do in the future.

**Comment by Maxr1998** [comment]
I agree such a toggle would make sense, I'd also (preferably) put it into a popup menu though. We'll probably habe to rewrite most of the Player UI relatively soon since Google deprecated some prebuilt UI components in ExoPlayer. Thus, we'd need to make our own and at that point I'd consider moving most of it to Jetpack Compose. Unfortunately, my time is just terribly limited these days.

**Comment by susonthapa** [comment]
@Maxr1998 Thank you for your quick reply despite your busy schedule. I agree with you. I will try to implement that toggle similarly to how the video quality option is implemented. If we have to rewrite the Player UI then I can research that and see if I can do that. We can talk about that in another issue once I implement this.

**Comment by Maxr1998** [comment]
Alright, thanks for your help! The compose migration is a bit of a bigger task that still requires a lot of preparation but it's not too urgent anyways.
