### ISSUE TITLE
Exoplayer with LiveTV stream no sound and keep streaming after close client

### ISSUE THREAD

**Issue by yongman** [jellyfin/jellyfin-android#764]
### Describe the bug

Watching LiveTV using ExoPlayer,  audio stream have mp2 format, but no sound in device.

And when I exit client, the stream keep going in server, and xteve not stopped (using web client xteve streaming stopped after client exit)

```
Input #0, mpegts, from 'http://192.168.31.15:8096/LiveTv/LiveStreamFiles/712f8e2018f246559e1aa09e72aed0cb/stream.ts':
  Duration: N/A, start: 1.440000, bitrate: N/A
  Program 1 
    Metadata:
      service_name    : live
      service_provider: FFmpeg
  Stream #0:0[0x100]: Video: h264 (High) ([27][0][0][0] / 0x001B), yuv420p(progressive), 1920x1080 [SAR 1:1 DAR 16:9], 25 fps, 25 tbr, 90k tbn
  Stream #0:1[0x101]: Audio: mp2 ([3][0][0][0] / 0x0003), 48000 Hz, stereo, fltp, 192 kb/s
Output #0, hls, to '/media/cache/jellyfin/transcodes/89d95469be403f8cccb9470185cf7560.m3u8':
  Metadata:
    encoder         : Lavf59.27.100
  Stream #0:0: Video: h264 (High) ([27][0][0][0] / 0x001B), yuv420p(progressive), 1920x1080 [SAR 1:1 DAR 16:9], q=2-31, 25 fps, 25 tbr, 90k tbn
  Stream #0:1: Audio: mp2 ([3][0][0][0] / 0x0003), 48000 Hz, stereo, fltp, 192 kb/s
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #0:1 -> #0:1 (copy)
```

### Application version

2.4.4

### Where did you install the app from?

Sideloaded APK (libre build)

### Device information

Android 12, OnePlus 9Pro

### Android version

Android 12

### Jellyfin server version

10.8.4

### Which video player implementations does this bug apply to?

- [x] Web player (default)
- [X] Integrated player (ExoPlayer)
- [ ] External player (VLC, mpv, MX Player)

**Comment by lomion0815** [comment]
Can confirm this behaviour. 
Additionally when using the Web player there is no sound for mp2 streams. When switching to ac3 (which gets transcoded to aac) sound is there. Can you force mp2 to get transcoded?

**Comment by lomion0815** [comment]
Update:
Option 1: This works when using the Web Player. Changed jellyfin-web on my server. Doesn't need change in Jellyfin-Android.
Option 2: Have a changed version which already requests a transcoded stream (without mp2) but I can not test it because I always receive a player_error_network_failure when starting the Exoplayer for transcoded stream (DirectPlay works). This seems not to be related to this problem but I can not test any fix.

**Comment by eglia** [comment]
The issuen is still present in the latest master branch.
[A demo file is available here](https://mega.nz/file/9atSmZ6S#mt4Lab9ab3akiexMR3ob1HEHwMThwDb8l_h5Nu2WJyY) .

**Comment by VladlenO** [comment]
I have same problem
