### ISSUE TITLE
Add "screen lock" feature

### ISSUE THREAD

**Issue by jakobkukla** [jellyfin/jellyfin-android#77]
**Describe the feature you'd like**
Add a button in the video controls to lock the screen from accidental touch inputs. MX Player had this feature for years and Netflix recently added this too. Would love to have it in the Jellyfin app as well.

**Additional context**
Here are some screenshots from Netflix and MX Player:

![Screenshot_20200830-163607](https://user-images.githubusercontent.com/10260599/91661890-163e2700-eadf-11ea-9bbb-454f08abf05c.jpg)

![Screenshot_20200420_170917 0](https://user-images.githubusercontent.com/10260599/91661901-28b86080-eadf-11ea-89ba-7d7fdf50fa5e.jpg)

**Comment by Maxr1998** [comment]
Should be possible, at least for the native player.

**Comment by jakobkukla** [comment]
Would be nice to see it in the ExoPlayer implementation too. I'm looking forward to use it more in the future since it's much more stable than the native player for me. :)

**Comment by JulioNahum** [comment]
> 
> 
> Would be nice to see it in the ExoPlayer implementation too. I'm looking forward to use it more in the future since it's much more stable than the native player for me. :)

Of course. The day will come when the Exoplayer player is 100% operational, with all the bugs corrected and improvements, it will have the possibility of replacing the web player. That is the idea as I see it, and it would be a great success.

**Comment by Maxr1998** [comment]
> Would be nice to see it in the ExoPlayer implementation too. I'm looking forward to use it more in the future since it's much more stable than the native player for me. :)

With native player, I specifically mean the ExoPlayer ^^
For the web player, that need to be adressed in jellyfin-web.

**Comment by jakobkukla** [comment]
> 
> With native player, I specifically mean the ExoPlayer ^^
> For the web player, that need to be adressed in jellyfin-web.

Got it.
