### ISSUE TITLE
Chromecast pause stops working during longer video playbacks.

### ISSUE THREAD

**Issue by exptom** [jellyfin/jellyfin-android#785]
### Describe the bug

When casting longer content for a while (> 45mins or so)  (to a Google Chromecast) and then trying to pause it the Chromecast does not respond to the pause request.
The only way to stop it is to go into the "Google Home" app and press stop casting. The current watch progress is then usually lost as well.

This has been a problem since I started using Jellyfin over a year ago and affected my previous android phone as well. (My wife's phone is also affected).

### Application version

2.4.4

### Where did you install the app from?

Google Play

### Device information

Google Pixel 4a

### Android version

Android 13

### Jellyfin server version

10.8.4

### Which video player implementations does this bug apply to?

- [ ] Web player (default)
- [ ] Integrated player (ExoPlayer)
- [ ] External player (VLC, mpv, MX Player)

**Comment by rohityadavcloud** [comment]
+1 I'm getting the same issue with the latest version on Google TV

**Comment by exptom** [comment]
Just to add I've noticed that the built in Jellyfin play/pause progress bar controls that appear at the bottom of the jellyfin window are only there for a few seconds and then disappear. After that point you can only use the limited android control that appears as a persistent notification until that stops working as well.

**Comment by tristanmccarthy** [comment]
Also encountering this issue with jellyfish v10.8.9 running in Linux.
Using Android 13 on a Pixel 6 and v2.4.4 of the jellyfin android app.
Cast controls only seem to work for a few minutes before the progress indicator stops working and I'm unable to pause/ seek, either in the app or on the Android media control

**Comment by exptom** [comment]
I still have this issue all the time and playback on Chromecast is a real pain as you cannot pause or easily seek to different timestamps.

**Comment by danielsdeboer** [comment]
Same here, except I see this behaviour after 10 minutes or so. Casting from Android, server's Ubuntu 22.04.

**Comment by V1DEOJAMES** [comment]
Same issue with the following 
Jellyfin, Linux,10.8.13
Pixel 7 Pro, app version 2.6.0
Chromecast 2.1.0

Activity log seems to suggest the phone never remains connected for longer than 4 minutes.
