### ISSUE TITLE
Add a dead zone to gesture controls

### ISSUE THREAD

**Issue by PolicyPuma4** [jellyfin/jellyfin-android#793]
When using the Android integrated player with gesture controls in horizontal view, it's impossible to swipe from the bottom to bring up the Android navigation bar without triggering the gesture controls.

Please may a dead zone be added to the bottom of the screen for gesture controls while in full screen horizontal view, preferably with a user settable amount of pixels?

**Comment by Maxr1998** [comment]
Good point, I noticed this too already and wanted to fix it for a while. Thanks for creating an issue for it.
