### ISSUE TITLE
HD Chromecast with Google TV has OLD Jellyfin version in app store

### ISSUE THREAD

**Issue by certainlysylvia** [jellyfin/jellyfin-android#814]
I apologise is not the correct place for this, but I cannot get Jellyfin to wok on my Chromecast with Goodgle TV (HD) due to the version installed. I has 0.14.3 ... seriously -- never going to work with my server at 10.8.0

Who handles submitting new versions - or perhaps the Chromecast app store refuses newer versions for some reason?

If possible, I would greatly appreciate someone submitting a more recent versions - save me from the messy side loading.

Again, apologies if not the right place.

Kate

**Comment by nielsvanvelzen** [comment]
0.14.3 is the latest version for TV, do some research before incorrectly blaming people.

**Comment by certainlysylvia** [comment]
I didn't blame anyone - and I realised I'd read a confusing post elsewhere, gotten turn around and here I was moments late to delete. I fucked up - so sorry.
