### ISSUE TITLE
"Client settings" parameter page not following the user display language

### ISSUE THREAD

**Issue by ThibaultNocchi** [jellyfin/jellyfin-android#83]
**Describe the bug**
The "client settings" parameter page doesn't follow the display language used by the logged user but the language used by Android.

**To Reproduce**

1. Set a display language different than the phone's
2. Restart the app to apply the changes
3. Go to "client settings" and see the strings displayed in the phone's language

**Expected behavior**
It should use the display language specified by the user.

**System (please complete the following information):**
 - App version: 2.0.0-rc.3
 - Android version: Android 8
 - Device manufacturer and model: Samsung Galaxy A5 2017
 - Jellyfin server version: 10.6.4
 - The type of video player implementation used: N/A

**Comment by nielsvanvelzen** [comment]
Description from a developer perspective: the web ui allows setting a language which will be used. The native part doesn't use that but will use the system language instead. This causes the user to get inconsistent localization between native and web parts.

I think the best option would be to:
1. Use the system language by default
2. Change the app language after a user signs in to the display language

Some things to consider:
- Changes need to be made to the nativeshell
- Is it possible to change an app language without restarting in Android? (activity restart should work too)

**Comment by Maxr1998** [comment]
> * Is it possible to change an app language without restarting in Android? (activity restart should work too)

Since the settings cannot be opened before you signed into the webapp (and thus know the language after the necessary NativeShell changes), this shouldn't be an issue.
