### ISSUE TITLE
Can't adjust the progress bar when watching the .mkv media

### ISSUE THREAD

**Issue by Karmylr** [jellyfin/jellyfin-android#831]
### Describe the bug

After uploading a video in mkv format, I found that the integrated player of the Android client cannot adjust the progress bar

### Application version

2.4.4.

### Where did you install the app from?

Google Play

### Device information

oppo phone

### Android version

android 12

### Jellyfin server version

10.8.5

### Which video player implementations does this bug apply to?

- [ ] Web player (default)
- [X] Integrated player (ExoPlayer)
- [ ] External player (VLC, mpv, MX Player)

**Comment by Maxr1998** [comment]
It might be a ExoPlayer related issue for this specific media file. For my MKVs, I have yet to experience any where I cannot seek.

Could you check if the player is direct playing or transcoding, and send the output of mediainfo for that file?

**Comment by Karmylr** [comment]
direct play
![image](https://user-images.githubusercontent.com/69903376/194206843-bd31174a-14f2-4fc6-9905-6cc0397007aa.png)

**Comment by Giorey01** [comment]
i also got this problem

**Comment by Karmylr** [comment]
1
