### ISSUE TITLE
[Issue]: Basque language not available

### ISSUE THREAD

**Issue by urtzai** [jellyfin/jellyfin-android#835]
### Describe the bug

The basque language is not available even 96% is translated. Can you enable the menu option, please?

### Application version

2.4.4

### Where did you install the app from?

Google Play

### Device information

Xiaomi A2

### Android version

Android 10

### Jellyfin server version

10.8.5

### Which video player implementations does this bug apply to?

- [ ] Web player (default)
- [ ] Integrated player (ExoPlayer)
- [ ] External player (VLC, mpv, MX Player)

**Comment by nielsvanvelzen** [comment]
All the Basque translations have been added after the latest version. They will show up on the next release.

**Comment by urtzai** [comment]
Nice! Thank you! So I guess I don't need to open a issue for other clients like androidTV etc, right?

**Comment by nielsvanvelzen** [comment]
No need - most clients automatically pick up new languages. Just wait for the next release.
