### ISSUE TITLE
Use chromecast volume when casting

### ISSUE THREAD

**Issue by Froghut** [jellyfin/jellyfin-android#84]
When casting to chromecast and changing the volume the app will use the "internal" volume instead of changing the actual "chomecast volume". If you check the volume in the Google Home app you will see the actual chromecast volume has not changed.
When using a different app to cast something (i.e. Youtube) and changeing the chromecast volume to lets say 10%, then switch to Jellyfin and set the volume to 50% in the app it will not change the chromecast volume, so you get 50% of 10% actual volume.
It would be better to just use the chromecast volume when casting, like basically every other app that can cast does.

**Comment by Froghut** [comment]
will be fixed with 10.3 release (PR https://github.com/jellyfin/jellyfin-web/pull/219)

**Comment by ferferga** [comment]
It is already in beta 9
