### ISSUE TITLE
Skip forward and back doesn't follow settings in exoplayer

### ISSUE THREAD

**Issue by jorritsmit** [jellyfin/jellyfin-android#84]
Pressing the right side of the screen doesn't skip the set 30s but only 5s

**To Reproduce**
1. Set forward and back skip to 30 seconds in settings
2. Start video
3. Skip forward and backward by double tapping the sides of the screen

**System (please complete the following information):**
 - App version: 2.0.0-rc.2
 - Android version: Android 10
 - Device manufacturer and model: OnePlus 6t
 - Jellyfin server version: 10.6.3
 - The type of video player implementation use: integrated player (Exoplayer)

**Comment by Maxr1998** [comment]
Yes, I'm using a default 5 second skip duration right now. I have to investigate if and how I can get the value Jellyfin settings. Thanks for filing an issue, kinda forgot about this :sweat_smile:

**Comment by jorritsmit** [comment]
Ok excellent. You are really on top of things. I'll check if I can fix this myself but I have 0 experience with c# and Android development

**Comment by nielsvanvelzen** [comment]
I think we should get this information using the apiclient, but I don't think we have access to the access token from the Kotlin side right now.

**Comment by jorritsmit** [comment]
Could it be that this skipForwardLength and skipBackLength can be got from DisplayPreferencesService/CustomPreferences?
