### ISSUE TITLE
TranscodeReason=SubtitleCodecNotSupported

### ISSUE THREAD

**Issue by Giorey01** [jellyfin/jellyfin-android#849]
### Describe the bug

1. disable transcoding
2. Reproduce this Chainsaw man release by erai-raws
3. Media cannot be played by this device

<img width="283" alt="sub" src="https://user-images.githubusercontent.com/61801344/196511314-892616ac-40e3-42c3-a4ce-fe13a8dd50f1.png">
<img width="223" alt="video" src="https://user-images.githubusercontent.com/61801344/196511321-fa9679dd-272c-4dde-a717-f2a04ea69a58.png">

Seems like ass subs are not supported from my smartphone?

### Logs

```shell
StreamBuilder.BuildVideoItem( Profile="Jellyfin Android", Path="/media/4tb/Anime/Chainsaw Man/Season 1/[Erai-raws] Chainsaw Man - 01 [1080p][Multiple Subtitle][6F20C80A].mkv", AudioStreamIndex=null, SubtitleStreamIndex=null ) => ( PlayMethod=Transcode, TranscodeReason=SubtitleCodecNotSupported ) "media:/videos/375f4395-643c-6939-5b54-1d291a66bb72/stream?MediaSourceId=375f4395643c69395b541d291a66bb72&AudioStreamIndex=1&SubtitleStreamIndex=9&api_key=<token>&SubtitleMethod=Encode&RequireAvc=false&Tag=6ab6ebfe9ea5170f30777e9623867afd&TranscodeReasons=SubtitleCodecNotSupported"
```

### Application version

2.4.4

### Where did you install the app from?

Google Play

### Device information

oppo a94

### Android version

Android 12

### Jellyfin server version

10.8.5

### Which video player implementations does this bug apply to?

- [ ] Web player (default)
- [X] Integrated player (ExoPlayer)
- [ ] External player (VLC, mpv, MX Player)

**Comment by nielsvanvelzen** [comment]
This is not a bug, you need to transcode these subtitles because they're not supported in the app.

**Comment by Giorey01** [comment]
> This is not a bug, you need to transcode these subtitles because they're not supported in the app.

Is it possibile to only allow subtitles transcode? Without enabling all video transcoding, because I'm using jellyfin on a very poor piece of hardware, it works super fine for direct playing but can transcode nothing

**Comment by nielsvanvelzen** [comment]
No, to bake in the subtitles the video needs to be transcoded.
