### ISSUE TITLE
Going back after coming from PiP doesn't return to Jellyfin

### ISSUE THREAD

**Issue by jorritsmit** [jellyfin/jellyfin-android#85]
**Describe the bug**
When coming out of PIP, when i press back (or 'gesture' back in my case), i return to the homescreen of my phone instead of to jellyfin. 

**To Reproduce**
1. Play video
2. Press home to go to PiP mode
3. Return to fullscreen video
4. Press back

**Expected behavior**
Pressing back should return to jellyfin (specifically the last view) instead of to the android homescreen

**System (please complete the following information):**
 - App version: 2.0.0-rc.3
 - Android version: Android 10
 - Device manufacturer and model: Oneplus 6T
 - Jellyfin server version: 10.6.3
 - The type of video player implementation used: ExoPlayer

**Comment by Maxr1998** [comment]
This is unfortunately a "bug" (feature?) in the Android framework. If you enter PiP mode, the system detaches the activity from its stack, resulting in such behaviour. See here for more information: https://stackoverflow.com/questions/45187961/task-list-and-back-stack-with-android-o-picture-in-picture-mode

(I coincidentally googled this issue just yesterday, and found that link in my research.

**Comment by jorritsmit** [comment]
Could it not be possible to reattach to the stack when returning to fullscreen mode?

**Comment by Maxr1998** [comment]
I fear not, because the intent to re-open the activity is controlled by the system, and I don't know whether the necessary APIs exist for that.

**Comment by jorritsmit** [comment]
Is it possible to open the jellyfin app to a certain episode? Then you could create a back button that doesn't back but opens the app to that episode

**Comment by joshuaboniface** [comment]
Confirmed as well with 2.0.0 release.

**Comment by Maxr1998** [comment]
We're aiming to fix that in the next major release. #166 already provides a foundation for that.

**Comment by jorritsmit** [comment]
Amazing work again. I am going to study the commits in hopes of being able to contribute to the project myself later on
