### ISSUE TITLE
Trigger automatic password fill from password authentication

### ISSUE THREAD

**Issue by dlgeraghty** [jellyfin/jellyfin-android#859]
**Describe the feature you'd like**

Dear team,
I'd much appreciate if you'd consider adding support for using some external application to fill in the password, this would be very useful for me as I have a password manager that contains the username and password for my personal jellyfin server.  
Right now I have to go into the password manager and manually copy the password to the jellyfin password prompt box.
I'd be glad to help in whatever way I can, I know how to write code
Regards,
David

**Additional context**

Little pop up appears when you click the password box (in other applications, for example in web browser)

**Comment by nielsvanvelzen** [comment]
I've checked this with the stable release, using Bitwarden the password field shows the auto-fill popup like expected. So I can login with my password manager just fine. Can you explain more about your setup? (Android version, password manager, install method etc.)

**Comment by dlgeraghty** [comment]
Dear,
I see, personally my setup is the following:
- Password manager: Bitwarden (as said before, the auto completion does work with other apps)
- Jellyfin app: Installed through F-Droid, version is 2.4.4
- Jellyfin server: Installed in my raspberry pi (don't know if this has something to do)
- OS version: Android 10

For the quick connect option it is true that I can see the button there in the app, but for some reason the pop-up doesn't have any number on it, but don't worry about this as I have to do a bit more digging.

Thank you for your support.

Regards,

**Comment by dlgeraghty** [comment]
Dear,
I have noticed that this doesn't happen just with jellyfin but with other apps too, I will review my setup
Thank you very much for the support.

Regards
