### ISSUE TITLE
[BUG] GUI is shown behind phone's navigationbar

### ISSUE THREAD

**Issue by michael9dk** [jellyfin/jellyfin-android#88]
**Describe the bug**

Jellyfin's main UI frame is displayed under the phones navigation bar, making it impossible to open the play-cueue at the bottom. The screenshot explains it better.

**To Reproduce**

Play a music album.
Try to open the playcueue at the bottom.

**Expected behavior**

Jellyfin stays out of the phones navigation bar area.

**Logs**

**Screenshots**

![Screenshot_20200902-185444~2](https://user-images.githubusercontent.com/61046533/92014811-1db83700-ed50-11ea-9dbe-54b6d092de8d.png)

**System (please complete the following information):**
 - App version: 2.0.0-rc.3
 - Android version: Android 10
 - Device manufacturer and model: Nikia 7.2
 - Jellyfin server version: 10.6.4
 - The type of video player implementation used: Default settings.

**Additional context**

**Comment by chenichadowitz** [comment]
This looks like a likely duplicate of #69, which appears to have been fixed for the next beta release? Feel free to correct me if I'm wrong.

**Comment by michael9dk** [comment]
Correct. I missed that one in my search.
