### ISSUE TITLE
Add a use file name as title feature/option

### ISSUE THREAD

**Issue by ghost** [jellyfin/jellyfin-android#881]
I have a show, let's say The office. The file names are as follows: `The.Office.year.S01E01.Title.Etc.etc.etc.`. With most shows, these titles are named properly, with the season and episodes displayed, `The.Office.year.S01E01` and thus it is easier to keep track of them. But for some reason sometimes Jellyfin lists all the episodes without the numbers, i.e `The.Office`. All of them have this name. I have no idea why this happens, but now I cant differentiate between episodes and they are listed randomly. If I wanted to start with the first episode I would have to search for the first one. I cannot get them in order by sorting, because there are no "Sort by file name" option. I propose add an option to display every file's title as the name of the media to circumvent this.

**Comment by momala454** [comment]
interested too

**Comment by momala454** [comment]
my problem is somehow different, i want to always show filename and not the movie name. But also showing both on the detail page.

Which folder type should I set to have movie infos and keep filename instead of movie name ?

**Comment by ticklemyIP** [comment]
Would be great to have this.

**Comment by YouROK** [comment]
This function is present in emby. Very comfortably

**Comment by Karkunow** [comment]
Please add this

**Comment by mcpedro99** [comment]
3 years and for some reason this is still not implemented. How hard is it to just parse the file name? I sure do love going inside a folder with 148 episodes all with just the title of the show and having to randomly guess which file is the correct episode for me to watch

**Comment by Sargon1729** [comment]
This is something I really need for obscure shows that don't have data in most databases. Please add this!
