### ISSUE TITLE
Media cannot be played by this device. External MPV Player: SubtitleCodecNotSupported

### ISSUE THREAD

**Issue by vegedb** [jellyfin/jellyfin-android#885]
### Issue
Jellyfin refuses to play giving error "Media cannot be played by this device". I've tried playing copying the file locally and SMB playback and it works fine using MPV Player! With Subtitles too!

Seems like this is a bug, it won't even attempt to start the video or push it to the external player. I've tried swiftfin-ios, jellyfin-androidtv and jellyfin media player. All worked fine!

Weirdly enough, Integrated player plays back the video, BUT without any subtitles.

### Codec
DVDSUB subtitles IDX/SUB

### Log
AudioStreamIndex=null, SubtitleStreamIndex=null ) => ( PlayMethod=Transcode, TranscodeReason=SubtitleCodecNotSupported

### Application version

latest

### Where did you install the app from?

Sideloaded APK (libre build)

### Device information

S21

### Android version

Android 12

### Jellyfin server version

10.8.7

### Which video player implementations does this bug apply to?

- [ ] Web player (default)
- [ ] Integrated player (ExoPlayer)
- [X] External player (VLC, mpv, MX Player)

**Comment by d-k-bo** [comment]
I am experiencing the same issue for some time now with videos that have a default/forced DVDSUB/VobSub track.

> Changing [Subtitles>Subtitle Mode>None] and it starts pushing to external player again

That indeed seems too bypass this problem. Thanks!

I think that this should reopened and marked as a bug. The claim “Media cannot be played by this device” is certainly wrong in this specific case.
