### ISSUE TITLE
Subtitles out of sync

### ISSUE THREAD

**Issue by Mruser0** [jellyfin/jellyfin-android#892]
### Describe the bug

1. Currently, it is found that ipad uses the built-in html web player when using the client, and the subtitles are set by default. When playing various videos, the subtitles are synchronized, and the fast-forward and drag progress bar can be synchronized normally.
2. The subtitles can be synchronized normally when you log in the web page with Google Browser, and the dragging progress is also normal. Subtitles are not synchronized when you log in to the computer using 360 browser to play the video, dragging the progress and changing the subtitle Settings are not synchronized.
3. When using jellyfin2.4.4 Android official app to play video, subtitles are not synchronized when selecting the default html player and dragging progress is not synchronized. Subtitles can be synchronized when setting burning subtitles as all, but they will not be synchronized when dragging progress.
4. When using exoplayer or third-party player on Android client, subtitles can be synchronized normally and dragging progress is OK, but when exoplayer is playing, subtitles will have black background and cannot be switched bit rate.
5. Try to log in the web page to play video with the Android phone browser, but the system default browser and Google browser cannot synchronize subtitles.

Expect the next release to fix the out-of-sync subtitle issue, as well as add the built-in exoplayer bitrate switch and optimize the black background of subtitles

### Application version

2.4.4

### Where did you install the app from?

Google Play

### Device information

OnePlus 6T

### Android version

Android 11 ,H2OS 11.1.1.1

### Jellyfin server version

10.8.6

### Which video player implementations does this bug apply to?

- [X] Web player (default)
- [ ] Integrated player (ExoPlayer)
- [ ] External player (VLC, mpv, MX Player)

**Comment by susonthapa** [comment]
@Mruser0 You are saying that the bug exists on both the Android phone's browser and the Jellyfin app, right? If so there is very little that we can do. We basically use the WebView(an embedded browser) that comes with Android and if that has any issues then we can do nothing.

If this is something that happened recently after an update to the phone then you can look into [this](https://github.com/jellyfin/jellyfin-android/issues/853) issue instead.

**Comment by Mruser0** [comment]
> @Mruser0 You are saying that the bug exists on both the Android phone's browser and the Jellyfin app, right? If so there is very little that we can do. We basically use the WebView(an embedded browser) that comes with Android and if that has any issues then we can do nothing.
> 
> If this is something that happened recently after an update to the phone then you can look into [this](https://github.com/jellyfin/jellyfin-android/issues/853) issue instead.

Thank you.I hope the next version of the built-in exo player fix the black background of subtitles when playing videos, add a back button when playing videos, and add a bit rate switch. This will solve the problem of out-of-sync subtitles.

**Comment by susonthapa** [comment]
@Mruser0 That would be great. Feel free to close this issue. You can open another issue for the back button and bit rate switch. Please verify that there isn't an issue already opened with the same feature request.

**Comment by Mruser0** [comment]
okay

**Comment by Maxr1998** [comment]
Fixing the subtitle issues on the webplayer might still be nice, but this is tracked in #46 already so this can stay closed.
