### ISSUE TITLE
Suggestions for the integrated player

### ISSUE THREAD

**Issue by Mruser0** [jellyfin/jellyfin-android#896]
I hope the next version of the built-in exo player fix the black background of subtitles when playing videos, add a back button when playing videos, and add a bit rate switch.

This function can effectively improve the built-in exo player's movie-watching experience, perfectly replace the built-in html player, and solve the bugs such as out-of-sync subtitles when using the built-in html player

**Comment by Maxr1998** [comment]
On the topic of subtitles, you can already customize the style yourself in the Android settings. In the future, we'll add a link to the Jellyfin settings to access that page more easily.

A bitrate switcher is implemented and will be rolled out in the next version. A back button makes sense as well, I wonder why I didn't add that yet..

**Comment by susonthapa** [comment]
@Maxr1998 I can take a look into adding the back button.

**Comment by Mruser0** [comment]
thank you
