### ISSUE TITLE
 [Issue]: Deserialization error on some videos

### ISSUE THREAD

**Issue by AnonymousWebHacker** [jellyfin/jellyfin-android#898]
### Describe the bug

Occurs on android clients, not on jellyfin desktop or web clients

Read more: https://github.com/jarnedemeulemeester/findroid/issues/185#issuecomment-1323140900

https://github.com/jarnedemeulemeester/findroid/issues/185#issuecomment-1323140900

### Application version

Lasted

### Device information

Redmi 9A

### Android version

Android 11

### Jellyfin server version

lasted

### Which video player implementations does this bug apply to?

- [X] Web player (default)
- [X] Integrated player (ExoPlayer)
- [X] External player (VLC, mpv, MX Player)

**Comment by nielsvanvelzen** [comment]
This is the repository for issues with the official Android app. Please post logs specific for our app. We do not provide support for third part apps like Findroid.

**Comment by AnonymousWebHacker** [comment]
I specified a problem with both findroid and jellyfin android client 
Pleas read: https://github.com/jarnedemeulemeester/findroid/issues/185#issuecomment-1323140900

In the case of jellyfin android client, with the exoplayer, it is not able to play an mp4 with double subtitle .
I will try to reproduce the error, to give you more information
