### ISSUE TITLE
Subtitles broken

### ISSUE THREAD

**Issue by yuukieve** [jellyfin/jellyfin-android#90]
Subtitle support, both on-the-fly extraction and burn-in via transcoding seems to be broken in Jellyfin-Android. It works for me with [Emby 3.0.21](https://www.apkmirror.com/apk/emby-media/emby-for-android/emby-for-android-3-0-21-release/) but simply displays nothing on Jellyfin. 

I compiled the latest commit ~1 hour ago and it's fully functional, otherwise.

**Comment by vitorsemeano** [comment]
The PR #89 should fix this.

**Comment by RazeLighter777** [comment]
Can confirm. Issue is fixed by building it from master. You should probably release a new build.

**Comment by yuukieve** [comment]
Closing this as fixed, since PR #89 was merged, fixing the problem.

**Comment by Mardiie** [comment]
With the 0.9.9 version that's available on the play store this issue seems to have returned. Using Android 10 and OxygenOS. Viewing through browser on the same device does show subtitles.
