### ISSUE TITLE
Don't try connecting to the server automaticaly on app startup

### ISSUE THREAD

**Issue by CodeCubeNeo** [jellyfin/jellyfin-android#900]
Hello! I think it would be useful, that before trying to connect to the server on app startup, the user can change the server route, meaning a user has to click the connect button. That is useful in cases where the server route has changed or the server isnt there at all, because now, when you start the app, there is just a black screen and you have to turn off the wifi in order to change the server route. Also maybe add a cancel button for connecting to the server if you misspelled the server location.

**Comment by susonthapa** [comment]
I don't understand your use case, can you please elaborate? In my case, if the app can't connect to the server I get this screen which is what I expect. 

<img width="385" alt="image" src="https://user-images.githubusercontent.com/33973551/203685155-d79449e4-1ada-49b3-ab81-8b4d27cfd2c7.png">

**Comment by CodeCubeNeo** [comment]
Yes, but you have to wait like 5 seconds in order to change the server location

**Comment by susonthapa** [comment]
Can you please send a screen recording of that? I am having a hard time figuring it out. I have Jellyfin running locally and I'm not able to replicate this.

**Comment by CodeCubeNeo** [comment]
Sure I can, sorry for a but of unimaginable explanation. Hope this helps. I dont have a server running and it is trying to connect (ig the timeout is 5 seconds) so I have to wait (aka black screen) for the timeout time in order to change the server location.

https://user-images.githubusercontent.com/61159092/203852435-e0c8a47f-c85b-4455-91e8-ed7ac092efc0.mp4

**Comment by susonthapa** [comment]
@CodeCubeNeo I got it. I think we need a splash screen as well. I will add the splash screen and a loading indicator. I think adding a cancel button beneath the loading indicator is possible but I don't know if it is worth it. For most people, I think they rarely change the server.

**Comment by Maxr1998** [comment]
We should already have a splash screen on the current version, not sure why it doesn't show though. We could add a cancel button there I think, maybe with a smaller timeout.

**Comment by susonthapa** [comment]
I looked into the code and didn't see a splash screen. We might have a different understanding of when a splash screen is. My understanding of the splash screen is from [here](https://medium.com/swlh/splash-screen-in-android-8ab250e40190). I am working on adding a loading indicator. I will see if I can find the issue with the splash screen.

**Comment by CodeCubeNeo** [comment]
Thanks. But please add a cancel button (it doesn't have to be complex). It helps for users who are setting up their instance and are experimenting with different locations, so they don't have to wait every time. (how about no splash screen, meaning on an app open, there is just the normal change server location page with the connect button (but then ig the user has to click connect every time they open the app?))

**Comment by susonthapa** [comment]
I think the splash screen is pretty important coz, not all devices load the app at the same time. For slow devices, the splash screen gives hint to the user that the app is loading. I will add the cancel button and see what others think.

**Comment by CodeCubeNeo** [comment]
Ok thanks, i agree a splash screen is important, but i meant it in the sense that on app launch the user sees the "connect to server" page and has to click connect and then while the app is connecting there is a splash screen, instead of trying to connect to the server immediately on app startup, but this is just an idea. For me a cancel button will suffice and i think no one is much against it, since it doesnt hurt anybody i think.

**Comment by susonthapa** [comment]
I think you might have misunderstood the splash screen. The splash screen will be shown when you launch the app. It will basically show the Jellyfin logo instead of the black screen.

**Comment by CodeCubeNeo** [comment]
Yes, i know, with splash screen i meant the "loading screen" (for when connecting to the server). I just proposed a different idea for the approach.

**Comment by Maxr1998** [comment]
> I looked into the code and didn't see a splash screen.

Yeah, my bad, I forgot that the splash screen I was seeing is coming from Android 13.
We do, however, already have a loading indicator that shows after one second of loading activity. After 5 seconds, the timeout will trigger and show the connection screen.

https://user-images.githubusercontent.com/5903699/205510186-5bea568f-0742-4fa0-93f4-4e8ac5b61a28.mp4

@CodeCubeNeo which version of the app are you currently on? The loading indicator was added in 2.4.0 (with #514).

**Comment by CodeCubeNeo** [comment]
I am using the latest version 2.4.4. And there is no indicator on my android 9. I would most like a cancel button.

**Comment by Maxr1998** [comment]
I think a cancel button makes a lot of sense. I'll look into adding one this week. Shouldn't be too hard.

**Comment by CodeCubeNeo** [comment]
Any updates?

**Comment by Maxr1998** [comment]
Not yet, but I'll look into it.
