### ISSUE TITLE
ExoPlayer transcode media but the default player direct streams it

### ISSUE THREAD

**Issue by rshxyz** [jellyfin/jellyfin-android#904]
### Describe the bug

I am not sure if this is entended but the ExoPlayer is transcoding media while the default player direct streams it. 

Transcoding
The media is being converted into a format that is compatible with the device that is playing the media.
Framerate: 37fps

21.7 Mbps TS H264 MP3

Reason for transcoding:
The subtitle codec is not supported

```
Subtitle
Title: English - Default - Forced - ASS
Language: eng
Codec: ASS
Default: Yes
Forced: Yes
External: No

Audio
Title: Stéréo - Japanese - PCM_S24LE - 2 ch - Default
Language: jpn
Codec: PCM_S24LE
Channels: 2 ch
Bitrate: 2304 kbps
Sample rate: 48000 Hz
Bit depth: 24 bit
Default: Yes
Forced: No
External: No

Video
Title: 1080i H264 SDR
Codec: H264
AVC: Yes
Profile: High
Level: 41
Resolution: 1920x1080
Aspect ratio: 16:9
Interlaced: Yes
Framerate: 29.97003
Bitrate: 21305 kbps
Bit depth: 8 bit
Video range: SDR
Video range type: SDR
Pixel format: yuv420p
Ref frames: 1
NAL: 4

Subtitle
Title: Fre - ASS
Language: fre
Codec: ASS
Default: No
Forced: No
External: No

Subtitle
Title: Italian - ASS
Language: ita
Codec: ASS
Default: No
Forced: No
External: No

```

### Application version

2.4.4

### Where did you install the app from?

Google Play

### Device information

Google Pixel 6

### Android version

13.0.0 (TP1A.221105.002, Nov 2022)

### Jellyfin server version

10.8.7

### Which video player implementations does this bug apply to?

- [ ] Web player (default)
- [X] Integrated player (ExoPlayer)
- [ ] External player (VLC, mpv, MX Player)

**Comment by nielsvanvelzen** [comment]
The subtitles require baking so yes this is normal.
