### ISSUE TITLE
VLC Player Crash

### ISSUE THREAD

**Issue by Angel23320123** [jellyfin/jellyfin-android#912]
### Describe the bug

I'm on a Galaxy Tab S8 Plus (tablet) running android 13, I've got the jellyfin android app installed with the video player set to external.
The external video player selected is VLC Player. 
When I hit play on any video the app crashes to desktop (home screen) with no error code.
When I relaunch the app it says it crashed and offers to clear cache but doing this does not help. 
I've tried the Web player, Exo player and MPV (external) and all three work. Only VLC player causes this crash.
Have used VLC as external on other devices with no issues, only encountered this after trying it on my new tablet. 

### Application version

2.4.4

### Where did you install the app from?

Google Play

### Device information

Galaxy Tab S8 Plus

### Android version

Android 13

### Jellyfin server version

10.8.7

### Which video player implementations does this bug apply to?

- [ ] Web player (default)
- [ ] Integrated player (ExoPlayer)
- [X] External player (VLC, mpv, MX Player)

**Comment by Maxr1998** [comment]
This is unfortunately the result of a [behavior change in Android 13](https://developer.android.com/about/versions/13/behavior-changes-all#intents) and a [bug in VLC Media Player](https://code.videolan.org/videolan/vlc-android/-/issues/2776). We can't really fix this without breaking playback resumption, which is also far from ideal.

**Comment by Angel23320123** [comment]
That's unfortunate, well I've moved to using MPV Player instead, and that works flawlessly. I guess this can just be added to the known issues list. You're welcome to close this ticket.

**Comment by Maxr1998** [comment]
Using MPV is likely the best option in the meantime, yes. However, a bug report was submitted to VLC and I commented with some additional info there, so I hope this will be fixed on VLC's end soon-ish. Until then, I'd like to keep this issue open for other people to see.
