### ISSUE TITLE
Remove Delete Functionality

### ISSUE THREAD

**Issue by wlau2929** [jellyfin/jellyfin-android#922]
It seems the scope  of the Android client should be to USE the Jellyfin server, not to MANAGE it. While it makes sense for some stuff to have a delete function (like Live TV recordings) it doesn't for actual media. Please consider removing deletion except for Live TV.

**Comment by nielsvanvelzen** [comment]
The mobile app uses the webui which contains this feature for server management so we won't be removing the feature until we move to native UI.
