### ISSUE TITLE
Volume buttons do not change volume while casting

### ISSUE THREAD

**Issue by P-Daddy** [jellyfin/jellyfin-android#93]
**Describe the bug**

When casting to Chromecast, the volume buttons show the volume slider on the phone, but don't affect the volume of the Chromecast.  Continuing to press or hold the volume buttons changes the position of the slider, but the Chromecast's volume remains unaffected.  However, dragging the on-screen slider _does_ change the Chromecast's volume.

**To Reproduce**

1. Cast to a Chromecast
2. Play a video (I haven't tried with audio)
3. Press a volume button, volume slider appears
4. Continue pressing or holding button, the Chromecast's volume doesn't change
5. Drag the volume slider on the screen, the Chromecast's volume changes

**Expected behavior**

Volume button changes result in a volume change on the Chromecast (or perhaps a message on the Chromecast saying that surround sound is enabled, telling me to use my TV's remote control to change the volume, but one issue at a time).

**Logs**

N/A

**Screenshots**

Here's what the slider looks like after pressing the `volume up` button several times and holding it a little bit.  The on-screen slider has responded and has turned up quite a bit, but nothing has happened on the Chromecast.

![image](https://user-images.githubusercontent.com/13328313/92279652-c3d97d80-eec5-11ea-8b6d-ef2bc1ab9ef6.png)

Here, I've dragged the slider around a little with my finger.  You can see an additional graphic that represents the actual volume change request being sent to the Chromecast.

![image](https://user-images.githubusercontent.com/13328313/92279628-b3c19e00-eec5-11ea-811d-15bf29695ef9.png)

**System (please complete the following information):**
 - App version: ? (current Play Store Beta release)
 - Android version: 9
 - Device manufacturer and model: Google Pixel 2
 - Jellyfin server version: 10.6.3-1
 - The type of video player implementation used: Chromecast

**Additional context**

**Comment by neopc10** [comment]
You're using an outdated Chromecast client and outdated Android client. You can switch to the newer Chromecast client in the playback settings and enroll in the Jellyfin Beta in the Google Play Store. However, casting doesn't work on the new Android client. When it does, you'll be able to control the volume.

**Comment by P-Daddy** [comment]
I already enrolled in the beta program.  Note that I mentioned I'm using the current Play Store Beta release.  In fact, this bug isn't present in the Cordova-based client.

I tried switching to the nightly version of the Chromecast client, but that version is currently crashing on the Chromecast and causing the Android app to crash, too.

Casting with the stable Chromecast client does work, and works pretty much the same as it does with the Cordova client, as far as I've noticed so far, with the exception of this bug.

**Comment by nielsvanvelzen** [comment]
The current beta version is v2.0.0-rc.3 fyi, thanks for the detailed report!

**Comment by neopc10** [comment]
It'll be best to report issues with the unstable client from here on out since the stable/legacy client is a monolith from before receiver clients existed.

**Comment by P-Daddy** [comment]
Thanks, that's good to know.  Unfortunately, the unstable client doesn't seem to work at all right now.  I tried it 2 or 3 days ago from the old Cordova client and it worked fine (I'm assuming the stable and nightly Chromecast clients you can choose from are the same from both Android clients, but correct me if I'm wrong).

**Comment by michael9dk** [comment]
I have the same issue in the current version.

- Android beta 2.0.0.rc.5
- Jellyfin server 1.6.4

The physical volume-buttons don't send events to update the touch-volume/player-volume, when using 'Play To' to anything except 'My Device'.

**Comment by michael9dk** [comment]
Same in 2.0.0.final.

**Comment by greatwroth** [comment]
Same issue with 2.0.1 (current Google Play beta) and if I expand the volume notification while casting I see 2 cast volume sliders labeled "Jellyfin"; one that the volume buttons control that does not effect casting volume and a second that works if I drag the slider.

**Comment by EXOgreen** [comment]
Just want to bring this up again, using a one plus 9 pro and Google cast on a Vizio TV. I've tried changing alot of my settings. Chromecast stable (2.1.0 is what the dashboard reports) Chromecast unstable (doesn't even work) changing players. As stated in the original post, the volume rocker on the side bring up the volume menu but doesn't actually change unless you use the touch screen.

**Comment by dinther** [comment]
Hopefully someone important sees this and reopens the case again. Three similar issues were closed in short succession so I am not sure where to turn now.

This is the android client 2.3.3 running on android 8 on my trusty Galaxy S7. I run jellyfin server 10.7.7 on windows with NGINX as a reverse proxy.

When I adjust the volume what the movie is playing you see a single volumebar but when you tap arrow down to expand the volume sliders you can see there are two jellyfin sliders. The bottom slider responds to the phone volume buttons but does not change the volume. When I manually move the bottom slider then the one above syncs along with a little lag. That top jellyfin slider does change the volume.

It has been an issue for ages but now I think it might help to track the volume issues down. Let me know if you need more data.

https://user-images.githubusercontent.com/1192916/136715404-2c16477f-de9a-420c-94b8-0dffbb6c61e8.mp4
