### ISSUE TITLE
Bug on ExoPlayer when cloud direct stream

### ISSUE THREAD

**Issue by 6im0n** [jellyfin/jellyfin-android#934]
### Describe the bug

Hello, 
on android the cloud direct stream (with .strm) not working the player not load the stream with the integrated player
on the web player it's working... but not very usefull...

I tested on an IOS device and it's working normaly !

### Application version

2.4.4

### Where did you install the app from?

Google Play

### Device information

Galaxy S10+ 

### Android version

Android 12

### Jellyfin server version

10.8.8

### Which video player implementations does this bug apply to?

- [ ] Web player (default)
- [X] Integrated player (ExoPlayer)
- [ ] External player (VLC, mpv, MX Player)

**Comment by nielsvanvelzen** [comment]
The Android app does not support strm files.
