### ISSUE TITLE
[Android] Black screen, 4k movies

### ISSUE THREAD

**Issue by Chuppaaa** [jellyfin/jellyfin-android#938]
Hello, 
All 4k movies have problems, no matter if it's low or high bitrate.  
There is a black picture and sound.  
In one video sometimes the image with a glitch was loaded, please help. 

 Lenovo tab m10 plus 3rd gen tablet with snapdragon processor, Android 12. 
I bought new equipment to watch movies in jellyfin. on the old phone, a few years old (Android 10), all 4k movies work properly on the built-in jellyfin player.  everything played Direct Play, the displayed video adapts to the resolution of the screen.  jellyfin works fine on laptop too.  

could it be a missing codec on the new android? can something be done about it?

[EDIT] 
according to the cpu specs, 4k videos should work.

**Comment by Maxr1998** [comment]
Maybe the codec that's used isn't supported by the device. Could you check if transcoded playback works on the new 2.5.0 beta? Just lower the quality selector until it switches to transcoded playback.

**Comment by Chuppaaa** [comment]
people from the internet write about glitches with 4k movies as they did the update to android 12. I checked different players and each has the same problem only with 4k movies, with and without HDR, low and high bitrate.

it's a problem with hardware acceleration/codec from 4k videos.
  The jellyfin player must be using something from the system that has a bug. For my part, I can't change anything, is it possible for Jellyfin to improve the built-in player so that it uses the correct codec and not the one that has android 12?

On the second new tablet there are also problems with 4k movies.
On the old phone with Android 10 everything works fine.

Direct playback should work without problems, the tablet processor supports codecs

"Maximum Display resolution 2520 x 1080 pixels
Video encoding Resolution 4K (Ultra HD), 2K, FullHD, max FPS 60. Codec: H.264/AVC,H.265/HEVC, VP8, VP9"

**Comment by Maxr1998** [comment]
On 2.5.0 we added an option to switch to ExoPlayer to software decoding, maybe this works for you?

**Comment by Maxr1998** [comment]
And could you run `mediainfo` on the file you're trying to play? Even if i.e. H.264 is supported, a specific variant of it may not be supported on that device (there are various levels of H.264, fwiw).

**Comment by Maxr1998** [comment]
See https://github.com/jellyfin/jellyfin-android/releases.

**Comment by Chuppaaa** [comment]
on the built-in player, the movie starts and I have a black screen.
after switching to external player (VLC) I have a gray image with glitches (screenshot) (https://ibb.co/qR8LPBx).
Sometimes it will appear correctly for 1 second.

**Example:**
**Movie #1** 
Format                                   : Matroska
Format version                           : Version 4
File size                                : 17,7 GB
Duration                                 : 2 h 10 min
Overall bit rate                         : 19,3 Mb/s
Writing application                      : mkvmerge v68.0.0 ('The Curtain') 64-bit
Writing library                          : libebml v1.4.2 + libmatroska v1.6.4

Wideo
ID                                       : 1
Format                                   : HEVC
Format/Info                              : High Efficiency Video Coding
Format profile                           : Main 10@L5@Main
HDR format                               : Dolby Vision, Version 1.0, dvhe.08.06, BL+RPU, HDR10 compatible / SMPTE ST 2086, HDR10 compatible
Codec ID                                 : V_MPEGH/ISO/HEVC
Duration                                 : 2 h 8 min
Bit rate                                 : 18,2 Mb/s
Width                                    : 3.840 pikseli
Height                                   : 2.160 pikseli
Display aspect ratio                     : 16:9
Frame rate mode                          : Stały
Frame rate                               : 24,000 kl/s
Color space                              : YUV
Chroma subsampling                       : 4:2:0 (Type 2)
Bit depth                                : 10 bitów
Bits/(Pixel*Frame)                       : 0.091
Stream size                              : 16,4 GB (93%)
Default                                  : Tak
Forced                                   : Nie
Color range                              : Limited
Color primaries                          : BT.2020
Transfer characteristics                 : PQ
Matrix coefficients                      : BT.2020 non-constant
Mastering display color primaries        : Display P3
Mastering display luminance              : min: 0.0001 cd/m2, max: 1000 cd/m2
Maximum Content Light Level              : 756 cd/m2
Maximum Frame-Average Light Level        : 242 cd/m2

Audio #1
ID                                       : 2
Format                                   : E-AC-3
Format/Info                              : Enhanced AC-3
Commercial name                          : Dolby Digital Plus
Codec ID                                 : A_EAC3
Duration                                 : 2 h 10 min
Bit rate mode                            : Stała
Bit rate                                 : 640 kb/s
Channel(s)                               : 6 kanałów
Channel layout                           : L R C LFE Ls Rs
Sampling rate                            : 48,0 kHz
Frame rate                               : 31,250 kl/s (1536 SPF)
Compression mode                         : Lossy
Stream size                              : 599 MiB (3%)
Language                                 : Polski
Service kind                             : Complete Main
Default                                  : Tak
Forced                                   : Nie

Audio #2
ID                                       : 3
Format                                   : E-AC-3 JOC
Format/Info                              : Enhanced AC-3 with Joint Object Coding
Commercial name                          : Dolby Digital Plus with Dolby Atmos
Codec ID                                 : A_EAC3
Duration                                 : 2 h 10 min
Bit rate mode                            : Stała
Bit rate                                 : 768 kb/s
Channel(s)                               : 6 kanałów
Channel layout                           : L R C LFE Ls Rs
Sampling rate                            : 48,0 kHz
Frame rate                               : 31,250 kl/s (1536 SPF)
Compression mode                         : Lossy
Stream size                              : 719 MiB (4%)
Language                                 : Angielski
Service kind                             : Complete Main
Default                                  : Nie
Forced                                   : Nie
Complexity index                         : 16
Number of dynamic objects                : 15
Bed channel count                        : 1 kanał
Bed channel configuration                : LFE

**Another file:**
Format                                   : Matroska
Format version                           : Version 4
File size                                : 6,00 GB
Duration                                 : 1 h 6 min
Overall bit rate                         : 12,8 Mb/s
Encoded date                             : UTC 2022-12-27 18:07:58
Writing application                      : mkvmerge v72.0.0 ('Minuano (Six-eight)') 64-bit
Writing library                          : libebml v1.4.4 + libmatroska v1.7.1
Wykonane przez                           : TV4TG

Wideo
ID                                       : 1
Format                                   : HEVC
Format/Info                              : High Efficiency Video Coding
Format profile                           : Main 10@L5@High
Codec ID                                 : V_MPEGH/ISO/HEVC
Duration                                 : 1 h 6 min
Bit rate                                 : 12,0 Mb/s
Width                                    : 3.840 pikseli
Height                                   : 2.160 pikseli
Display aspect ratio                     : 16:9
Frame rate mode                          : Stały
Frame rate                               : 23,976 kl/s
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 10 bitów
Bits/(Pixel*Frame)                       : 0.060
Stream size                              : 5,61 GB (93%)
Default                                  : Tak
Forced                                   : Nie
Color range                              : Limited
Color primaries                          : BT.709
Transfer characteristics                 : BT.709
Matrix coefficients                      : BT.709

Audio #1
ID                                       : 2
Format                                   : AC-3
Format/Info                              : Audio Coding 3
Commercial name                          : Dolby Digital
Codec ID                                 : A_AC3
Duration                                 : 1 h 6 min
Bit rate mode                            : Stała
Bit rate                                 : 192 kb/s
Channel(s)                               : 2 kanały
Channel layout                           : L R
Sampling rate                            : 48,0 kHz
Frame rate                               : 31,250 kl/s (1536 SPF)
Compression mode                         : Lossy
Stream size                              : 92,0 MiB (1%)
Language                                 : Polski
Service kind                             : Complete Main
Default                                  : Tak
Forced                                   : Nie

Audio #2
ID                                       : 3
Format                                   : E-AC-3
Format/Info                              : Enhanced AC-3
Commercial name                          : Dolby Digital Plus
Codec ID                                 : A_EAC3
Duration                                 : 1 h 6 min
Bit rate mode                            : Stała
Bit rate                                 : 640 kb/s
Channel(s)                               : 6 kanałów
Channel layout                           : L R C LFE Ls Rs
Sampling rate                            : 48,0 kHz
Frame rate                               : 31,250 kl/s (1536 SPF)
Compression mode                         : Lossy
Stream size                              : 307 MiB (5%)
Language                                 : Angielski
Service kind                             : Complete Main
Default                                  : Nie
Forced                                   : Nie

**Comment by Chuppaaa** [comment]
I installed the version 2.5.0 beta,
 i changed the player from the web version to the built-in exoplayer, the effect is the same after starting the black screen, but now a message appears at the bottom of the screen for a moment

MediCodecVideoRenderer error, index=0, format=Format(1, null, null, video/dolby-vision, hev1.08.06, -1, und, [3840,2160,-1.0], [-1,-1]), format_support...

https://ibb.co/GnCcNpd

**Comment by Chuppaaa** [comment]
in VLC after disabling the OPENGL ES2 option I also have a black screen.  when I turn on opengl the movie appears but with glitches in the image, I can't watch it like that.  I don't know if this will help, but this option has some meaning with this display.

**Comment by Chuppaaa** [comment]
I didn't write it sooner it was late and I was mad at it all

at the moment I have a tablet Lenovo Tab M10 Plus (3rd Gen) (Snapdragon 680) in my hand for these film tests, 
this version of the tablet appeared about a month ago, I had a few updates to do after switching on, the company promised next year that there will be an update from Android 12 to Android 13.

On the second new tablet, there were also problems with 4k movies, but now I won't say exactly what's going on there. I had to install jellyfin through some intermediary's application because it's a huawei tablet and there is no official Jelly installer in their store. Let's focus on the Lenovo I care about more and have it in my hands.

If there's anything else I can check to change, let me know. I really want jellyfin to work.

**Comment by Chuppaaa** [comment]
I did a test on an old tablet with android 8 and a "snapdragon 660" processor worse than the current one. everything in jellyfin works, big 4k videos too. What people wrote that they had such problems with movies after switching to android 12 may be true. If you could improve in your application so that 4k hevc movies what they use -have it permanently in the application and not take it from android, that would be great. Rather small chance that I will see a repair update from lenovo.

**Comment by Chuppaaa** [comment]
I made a screenshot of the system codecs, look...
hardware acceleration disabled? max res? max bitrate? ..what is going on here...

https://ibb.co/sVKm852
https://ibb.co/Zcwr49k

The processor supports HEVC and it should work
Display and Audio 
Maximum Display resolution: 2520 x 1080 pix
Video encoding: Resolution 4K (Ultra HD), 2K, FullHD, max FPS 60. Codec: H.264/AVC,H.265/HEVC, VP8, VP9

**I know it's not your player's fault and you don't have to do it, but if you could somehow bypass this problem in the next Jellyfin update, I'd be very grateful.**

**Comment by Chuppaaa** [comment]
In another tablet, the newer P11, which supports the codec and probably has android 12, someone also reported the same to lenovo that hardware acceleration is turned off and movies do not work, later another person also wrote about the same on another lenovo tablet. The case was ignored by support on the official lenovo forum and there is little chance that they will fix this problem for me.

**You are my only hope** that you will somehow work around this problem with your software.

**Comment by Maxr1998** [comment]
I believe having software only decoders is normal and intended (it's Android's default software decoder), what would be interesting if there's also a hardware-accelerated decoder. The `OMX.*` decoders are usually the hardware-accelerated one's provided by Qualcomm.

**Comment by Chuppaaa** [comment]
https://www.cpu-monkey.com/en/cpu-qualcomm_snapdragon_680_4g
here's a nice chart that this CPU and GPU can handle. 

The worse old tablet that I have on the old android 8, plays all movies without any problems and a 5 year old phone too.

on **ExoPlayer** I don't have any options and even the interface doesn't match the display well. The video doesn't play, it's black.
Exactly the same I have in **Jellyfin** because it uses _Exo_.
In **MXplayer** I have a poor quality image with some dots in the background and very slow.
In **VLC**, the image has glitches, gray background, pixels, sometimes it will appear correctly but there is no chance to watch it.

_All players have one thing in common that they are in Software Acc. mode because they cannot switch to Hardware Acc._

It seems that in Android 12 some options are disabled, probably so that more devices can switch to this system without problems. And in tablets and phones that meet the requirements for more demanding options, companies that sell such equipment can enable them. 

Until I can switch to Hardware Acceleration these videos will not work and I'm afraid that in Android 13 it will be exactly the same.

**Comment by Chuppaaa** [comment]
Oplayer and Xplayer are doing the best of all I've checked, still can't switch to HW but with SW they do what they can.

In Xplayer the image is displayed without artifacts and the sound too, but it is slowed down, it's like watching at 0.5x speed.

In Oplayer, the sound and picture go smoothly almost all the time, sometimes it freezes and for a large part of the time everything looks good, then suddenly artifacts, pixels, a gray picture appear.

In SW mode, these players work best, I still can't watch these movies, but maybe someone will find this information useful.

**Comment by eygraber** [comment]
I'm running into this issue using ExoPlayer with Lenovo tab m10 plus 3rd gen tablet with snapdragon processor, Android 12.

Playing the same file on my Pixel 7 Android 13 works fine and Direct Plays.

**Comment by Cifer9516** [comment]
The issue is probably with HDR support on per device basis. Have tried multiple phones and tablets. Those that don't do HDR tonemapping don't play the video or spit out an error untill you bump down transcode bitrate to a point where video signal doesn't carry HDR data anymore. 
For example.
Lenovo tab P11 doesn't tonemap, Huawei nova 5T does.
