### ISSUE TITLE
ExoPlayer Bitrate Selection prompt doesn't start with a value

### ISSUE THREAD

**Issue by silentTeee** [jellyfin/jellyfin-android#939]
### Describe the bug

With the new Bitrate Selection option that's embedded into the Integrated Player UI, none of the Radio Button options are selected when playback starts. 

### Steps to Reproduce

1. Select "Integrated Player" in Client Setting option
2. Play a video file
3. Press the Bitrate Selection button (the cog icon)

### Expected Behavior

One of the Radio Buttons should be selected, ideally it is based on the values set in the "Video Quality" fields in the Playback Settings menu

### Actual Behavior

None of the Radio Buttons are selected.
![bitrate-selection-empty](https://user-images.githubusercontent.com/20748060/210093451-3c153540-05b1-4c39-9b83-4deb2552b65c.png)

### Application version

2.5.0-beta.1

### Where did you install the app from?

Sideloaded APK (proprietary build)

### Device information

Google Pixel 7

### Android version

Android 13

### Jellyfin server version

10.8.8

### Which video player implementations does this bug apply to?

- [ ] Web player (default)
- [X] Integrated player (ExoPlayer)
- [ ] External player (VLC, mpv, MX Player)

**Comment by Maxr1998** [comment]
Right, by default it's auto, that should be selected on start.
