### ISSUE TITLE
Cannot skip forward or backward when casting

### ISSUE THREAD

**Issue by P-Daddy** [jellyfin/jellyfin-android#94]
**Describe the bug**

When casting a video to Chromecast, it's not possible to skip forward or backward in the video except by dragging the seek bar.  

The remote control interface lacks buttons for this functionality, having only buttons whose purpose is presumably to skip to the next or previous video (but which don't seem to work, and whose intended purpose is less clear when playing a move versus a TV show .. maybe they only work when playing a video from a play list?).

The notification has buttons which look like they should perform this function, but when you press them, the Chromecast player seems to hang on a black screen.  The only ways to recover seem to be to seek manually with the slider at the bottom or to exit and restart the video.

**To Reproduce**

1. Cast to a Chromecast
2. Start a video (I haven't tried with audio)
3. Pull down the notifications drawer
4. Tap the forward or backward skip button
5. The video on the Chromecast is gone

**Expected behavior**

Tapping these buttons should skip forward _x_ seconds (default 30) or backward _y_ seconds (default 10), and the video should resume playing.

**Logs**

N/A

**Screenshots**

The ⏩ and ⏪ buttons in this notification are the ones I assume are for skipping _x_ and _y_ seconds within the current video.  The ⏭️ and ⏮ buttons don't seem to do anything.

![image](https://user-images.githubusercontent.com/13328313/92282247-34cf6400-eecb-11ea-9afc-36405f66b2a0.png)

After pressing one of the skip buttons, the video seems to be stuck at 0:00.

![image](https://user-images.githubusercontent.com/13328313/92282510-bb844100-eecb-11ea-9a09-7678e0d6da2c.png)

**System (please complete the following information):**
 - App version: v2.0.0-rc.
 - Android version: Android 9
 - Device manufacturer and model: Google Pixel 2
 - Jellyfin server version: 10.6.3-1
 - The type of video player implementation used: Chromecast

**Additional context**

There is [a similar issue][similar] currently open for the Cordova client.  It doesn't appear that the reporter of that issue tried the skip buttons in the notification, however, I've experienced the same behavior in the Cordova client as I've reported here for the new client.

[similar]: https://github.com/jellyfin-archive/jellyfin-android-original/issues/390

**Comment by greatwroth** [comment]
I can confirm this on Android app version 1.0.2

**Comment by michael9dk** [comment]
The design has changed i latest version (2.0.0.rc.5 with server 1.6.4) to a progressbar for skipping.

The 'Next track' and 'Previous track' buttons work if you have more than one movie in the queue. 

![Screenshot_20200921-142920](https://user-images.githubusercontent.com/61046533/93767488-66109980-fc18-11ea-9235-a6be2462da5d.png)

**Comment by michael9dk** [comment]
I propose a Close issue.

- the UI has changed and no longer have the Skip-buttons.
- Previous/next-buttons work as intended.

**Comment by monkybrain** [comment]
I think skip forward/backward is an essential feature for a media player, e.g. when someone interrupts you and you just want hear the last sentence again. Doing that with a progress is almost impossible. You always end up going back too far.

**Comment by Maxr1998** [comment]
> I think skip forward/backward is an essential feature for a media player, e.g. when someone interrupts you and you just want hear the last sentence again. Doing that with a progress is almost impossible. You always end up going back too far.

That's a good point, maybe we can make it dependent on media type (e.g. audio books and podcasts get the skip buttons, music doesn't), or dependent on track length.

**Comment by P-Daddy** [comment]
I can't imagine ever not wanting the skip forward/backward buttons.  Why wouldn't you want to be able to skip back and forward in music?  "Oh, what was that lyric?  Let me rewind a few seconds and listen to it again."  And the only reason the track length should determine the visibility of skip buttons might be if the length of the track were shorter than the skip, but IMO, special casing that would be unnecessary complexity in the code and potentially confusing to the user.

Please provide skip buttons all the time.  So far, this issue has only progressed backward, as they've been removed from the one place they existed.  This is the opposite of what I was hoping for.

**Comment by shimeike** [comment]
My vote would definitely be to have fast forward/rewind buttons present at all times. I find myself wanting to make small skips in movies / TV shows all the time, but doing so the progress bar is pretty much impossible. They're present in the web player for video - why not make the interfaces consistent?

**Comment by SudoNova** [comment]
Does it mean this feature isn't considered?
This is desparately needed when playing podcasts/audiobooks.

![Screenshot_2022-06-08-03-52-04-065_com android chrome](https://user-images.githubusercontent.com/61787053/172499451-c080a900-8018-46f6-8061-030a7b33213a.jpg)

![Screenshot_2022-06-08-03-52-12-668_org jellyfin mobile](https://user-images.githubusercontent.com/61787053/172499460-8d1e59ed-fed0-419b-bfe2-c1a294368367.jpg)

**Comment by Maxr1998** [comment]
It was closed due to inactivity, I'll reopen it.

**Comment by vincegre** [comment]
Wow I'm so disappointed to discover that Jellyfin developpers don't see an interest in Next/previous buttons ! I probably was too naive to think Jellyfin was a media player but it looks more like Plex in developing stuffs without taking care it works or what users need/want ! Right now I have discovered that Jellyfin client on Android is unusable to listen music on a cast device ! Next/skip buttons don't show up in Jellyfin interface (how is that even possible for a media player ???) and basically player stops always at end of first track played and next/stop that shows up in Android notifications of Jellyfin are inoperative !

**Comment by shimeike** [comment]
Any update on this topic?
This issue still applies.
Buttons that skip forward/backward by some small number of seconds are needed when casting video to a Chromecast device.

**Comment by nielsvanvelzen** [comment]
We don't have any developer working on Google Cast related projects right now. So no updates.
