### ISSUE TITLE
Dolby TrueHD Audio doesn't play in Integrated Player

### ISSUE THREAD

**Issue by silentTeee** [jellyfin/jellyfin-android#940]
### Describe the bug

First off, congrats on the release of 2.5.0-beta.1! Lots of good improvements.

It seems that in the Integrated Player, Dolby Digital audio streams will work just fine, but the Dolby TrueHD audio streams will not play. The video will play without any sound.

In checking the [doc's Client Support table](https://jellyfin.org/docs/general/clients/codec-support/#wikipedias-audio-codec-tables), I see that Dolby TrueHD isn't supported by any of our clients, but I also see on [this FFmpeg page](https://trac.ffmpeg.org/wiki/Encode/HighQualityAudio) that we can transcode it to something else. In fact I believe transcoding is applied correctly when streaming to the Android TV, as I recall audio previously being playable on that client for these files while the TrueHD stream was selected.

#### Test File Details:

Mob Psycho 100 S01E01
Container: mkv
Path: /srv/dev-disk-by-uuid-5824daec-cdc4-44f8-8767-f15ddce525df/appdata/jellyfin/shows/Mob Psycho 100/Season 1/Mob Psycho 100 S01E01.mkv
Size: 4576 MB

Subtitle
Title: Forced Only - English - PGSSUB
Language: eng
Codec: PGSSUB
Default: No
Forced: Yes
External: No

Audio
Title: Surround 5.1 - English - TRUEHD - Default
Language: eng
Codec: TRUEHD
Layout: 5.1
Channels: 6 ch
Bitrate: 2821 kbps
Sample rate: 48000 Hz
Bit depth: 24 bit
Default: Yes
Forced: No
External: No

Video
Title: 1080p H264 SDR
Codec: H264
AVC: Yes
Profile: High
Level: 41
Resolution: 1920x1080
Aspect ratio: 16:9
Interlaced: No
Framerate: 23.976025
Bitrate: 26439 kbps
Bit depth: 8 bit
Video range: SDR
Video range type: SDR
Pixel format: yuv420p
Ref frames: 1
NAL: 4

Audio
Title: Surround 5.1 - English - Dolby Digital
Language: eng
Codec: AC3
Layout: 5.1
Channels: 6 ch
Bitrate: 448 kbps
Sample rate: 48000 Hz
Default: No
Forced: No
External: No

Audio
Title: Stereo - Japanese - TRUEHD
Language: jpn
Codec: TRUEHD
Layout: stereo
Channels: 2 ch
Bitrate: 888 kbps
Sample rate: 48000 Hz
Bit depth: 24 bit
Default: No
Forced: No
External: No

Audio
Title: Stereo - Japanese - Dolby Digital
Language: jpn
Codec: AC3
Layout: stereo
Channels: 2 ch
Bitrate: 192 kbps
Sample rate: 48000 Hz
Default: No
Forced: No
External: No

Subtitle
Title: English - PGSSUB
Language: eng
Codec: PGSSUB
Default: No
Forced: No
External: No

### Application version

2.5.0-beta.1

### Where did you install the app from?

Sideloaded APK (proprietary build)

### Device information

Google Pixel 7

### Android version

Android 13

### Jellyfin server version

10.8.8

### Which video player implementations does this bug apply to?

- [ ] Web player (default)
- [X] Integrated player (ExoPlayer)
- [ ] External player (VLC, mpv, MX Player)

**Comment by Maxr1998** [comment]
TrueHD should be supported. I just tested with some [Dolby samples](https://thedigitaltheater.com/dolby-trailers/) (namely "Amaze" and "City Redux") and sound worked fine for me. Do these work for you? If yes, could you maybe send me a small sample from the file you're trying to play?

**Comment by silentTeee** [comment]
@Maxr1998 huh, I grabbed the 7.1 sample you see and a 5.1 sample from the same site, and both worked...let me see if I can make a shorter sample of one of the files that gave me a hard time for us to test with.v

**Comment by silentTeee** [comment]
Okay, I figured out how to make a 30 second sample that has the exact same structure (same streams, same stream indexing, same quality, etc). What's the best way to send it?

### Some interesting observations made during the process of creating it:

 When I first created it, I tried to place it in a separate "shows/Test" folder and giving it a name "Mob Psycho 100 S01E01 Sample.mkv", and it treated it as a Special, and it would not play _any_ audio stream. So I tried to rename it to just "Sample.mkv" and left it in the same folder; same issue occurred. Then I decided to move it into the "shows/Mob Psycho 100/Season 01" folder and name it "Mob Psycho 100 S01E01.mkv" and back up the actual file. Only then did the Dolby Digital English and Japanese audio work, while the TrueHD audio still failed silently.

**Comment by Maxr1998** [comment]
I *think* you could just upload it here on GitHub (if the file isn't too large), or any other hosting site like Mega or Google Drive.

**Comment by silentTeee** [comment]
@Maxr1998 sent you a Google Drive link, seems even a 30 second video was too big for GitHub.

**Comment by silentTeee** [comment]
I was able to capture the logcat output for playing the sample I provided to @Maxr1998 while checked out on the master branch. 

[jellyfin-android-ticket-940-logcat.log](https://github.com/jellyfin/jellyfin-android/files/10333635/jellyfin-android-ticket-940-logcat.log)

### Actions taken during the capture:
1. Navigated to "Shows" category
2. Navigated to "Mob Psycho 100" show entry
3. Navigated to Season 1, Episode 1 item,
4. Ensured that Japanese TrueHD Stereo was selected for audio and English was selected for subtitles
    a. I specifically did this because when I first discovered this issue, I also noticed changing the subtitles to "None" in the Integrated Player causes a toast to come up saying "Streaming error", and wanted to avoid conflating several possible bugs. Will try to characterize this further later.
5. Pressed "play" icon
6. Observed playback with no audio.
7. Checked that bitrate was set to "auto" in the in-player bitrate selection prompt just to make sure that wasn't interfering
8. Backed out of the player

**Comment by silentTeee** [comment]
I didn't realize it before, but could this perhaps have been influenced by [8666](https://github.com/jellyfin/jellyfin/pull/8666)? At first I thought that wouldn't be the case since the UI where the value was being set was different, but now I am not so sure...

**Comment by silentTeee** [comment]
This issue also looks very likely to be the actual cause:

https://github.com/jellyfin/jellyfin/pull/9029

**Comment by silentTeee** [comment]
This issue also looks very likely to be the actual cause:

https://github.com/jellyfin/jellyfin/issues/8804

**Comment by Visserr2** [comment]
Got some problems with TrueHD too.

Stream mapping:
  Stream #0:0 -> #0:0 (hevc (native) -> hevc (hevc_qsv))
  Stream #0:1 -> #0:1 (truehd (native) -> truehd (native))
Press [q] to stop, [?] for help
[truehd @ 0x55dca65aed80] The encoder 'truehd' is experimental but experimental codecs are not enabled, add '-strict -2' if you want to use it.
[hevc @ 0x55dca64a0580] Skipping NAL unit 63
    Last message repeated 16 times

**Comment by silentTeee** [comment]
@Maxr1998 just wanted to let you know, the stability of handling the experimental TrueHD and DTS(HD) codecs has improved tremendously since the release of server version/10.8.10! So far with default settings I have not seen transcoding issues on any of my files with tracks that use those codecs in the mobile client. I would be willing to close this ticket. 🙂

**Comment by Maxr1998** [comment]
Happy to hear! Let's close this, then. Just comment if this occurs again or if you have a very similar issue, then I can re-open it. Otherwise, feel free to raise a new issue in case of problems.
