### ISSUE TITLE
Problem with subtitles in beta version 2.5.0

### ISSUE THREAD

**Issue by Chuppaaa** [jellyfin/jellyfin-android#942]
### Describe the bug

so far in the settings there was a tab with subtitles, you could set the subtitles and their position there.  this tab is still there but since there is a new place to customize the subtitles in the client options, the settings in the application do not react.  the settings from the client tab that takes you to the settings in the android system work.  "customize subtitle style" cannot be disabled.  in the system settings it is not possible to change the position of the subtitles, which makes them display too high, changing the size from normal to small is a huge too big difference in size.  please add the ability to disable the system subtitle settings so that the subtitle settings in the application still work, where you can change the height of the subtitle display.  at the moment only the system setting works and the one that was in the application does not.

### Application version

2.5.0 beta1

### Where did you install the app from?

Sideloaded APK (proprietary build)

### Device information

Lenovo tab m10 plus 3 gen. (snapdragon 680)

### Android version

Android 12

### Jellyfin server version

10.8.8

### Which video player implementations does this bug apply to?

- [ ] Web player (default)
- [X] Integrated player (ExoPlayer)
- [ ] External player (VLC, mpv, MX Player)

**Comment by Chuppaaa** [comment]
![Screenshot_20230105-164903](https://user-images.githubusercontent.com/119754886/210822827-720c95bd-6925-4e75-ac31-9d1818f3ad5a.jpg)
![Screenshot_20230105-164916](https://user-images.githubusercontent.com/119754886/210822840-393ba89c-1533-4545-9ea5-a8317db8d77d.jpg)

on the screens, setting the subtitles in the application and the second screen how they are displayed in the movie (these are .srt subtitles).  in the system settings of android, I set no background but it is still black and I can't lower the display space.  I need a button to disable the system settings so that the player listens to the application settings.

**Comment by Maxr1998** [comment]
The subtitle settings in Jellyfin Web only apply to the web player. The integrated player has always used the style defined in the Android system settings, but in the last version we added a shortcut to quickly open that screen to our app's client settings. I'm not entirely sure why the background option doesn't work, maybe you need to change the transparency in those settings as well? Regarding the vertical position of the subtitle lines, this is currently defined by ExoPlayer, we're planning to make that customizable though.

**Comment by Chuppaaa** [comment]
see in the picture how the system shows me that the subtitles should be displayed and then go back to the previous picture.  completely different.

![Screenshot_20230106-163119](https://user-images.githubusercontent.com/119754886/211044884-17309f8c-7752-4b76-ac5d-2c2e7ed4641e.jpg)

**Comment by Chuppaaa** [comment]
ok, I'm waiting for the ability to change the settings myself, the style of subtitles something like for your webplayer would be perfect.  I am waiting patiently for the next versions.  
let the force be with you

**Comment by Chuppaaa** [comment]
I reinstalled the app and changed the system subtitles settings and then went back to the same settings I had. There is no black background anymore. The subtitles are still too big and a little too high, but there are no appropriate settings for this in the system. I'm waiting for the next versions of Jellyfin :)

Greetings
