### ISSUE TITLE
It bothers me when a music player requires the app window to be open to play music

### ISSUE THREAD

**Issue by styromaniac** [jellyfin/jellyfin-android#948]
### Describe the bug

1. Open Jellyfin
2. Play a song
3. Go into Android's app list view
4. Close Jellyfin's app window

I expect music to keep playing, but it doesn't. This is a feature of the Emby app to keep playing regardless of the app window being closed.

### Application version

2.4.4

### Where did you install the app from?

Google Play

### Device information

Samsung Galaxy S21 Ultra 5G

### Android version

13

### Jellyfin server version

10.8.8

### Which video player implementations does this bug apply to?

- [x] Web player (default)
- [X] Integrated player (ExoPlayer)
- [X] External player (VLC, mpv, MX Player)

**Comment by Farbklex** [comment]
Can you check what battery saver option is set by the OS for Jellyfin? In the android settings, go to apps -> Jellyfin -> Battery.

**Comment by styromaniac** [comment]
It's Unrestricted.

**Comment by DevinDuricka** [comment]
When you say "close the app window", are you saying launching the "recently used apps and swiping it away", or just hitting the home button and "minimizing" the app? (if that makes sense?)

**Comment by styromaniac** [comment]
> When you say "close the app window", are you saying launching the "recently used apps and swiping it away", or just hitting the home button and "minimizing" the app? (if that makes sense?)

Launching the "recently used apps and swiping it away.

**Comment by pouncer29** [comment]
I was also experiencing this issue.

Jellyfin server: 10.8.9

Device : Galaxy S8
Android Version: 9
App Version: 2.4.4


Setting power usage to allow background data andsetting optimized battery usage to "not optimized" seems to have fixed this for me.
