### ISSUE TITLE
App doesn't work with my subdomain that is produced through a URL redirect record (via Namecheap)

### ISSUE THREAD

**Issue by styromaniac** [jellyfin/jellyfin-android#949]
### Describe the bug

The app doesn't connect to jellyfin.styromaniac.com. It's a mask over styromaniac.com:8096. Jellyfin.styromaniac.com works in browsers, however.

(You won't be able to load the site without Yggdrasil Network: https://yggdrasil-network.github.io/)

### Application version

2.4.4

### Where did you install the app from?

Google Play

### Device information

Samsung Galaxy S21 Ultra 5G

### Android version

13

### Jellyfin server version

10.8.8

### Which video player implementations does this bug apply to?

- [X] Web player (default)
- [X] Integrated player (ExoPlayer)
- [X] External player (VLC, mpv, MX Player)

**Comment by Farbklex** [comment]
So far I can't reach your server via a web brwoser as well.
I installed the yggdrasil client on an android emulator and added some peers from the public list and a DNS address. Do we need to configure more to reach your server?

**Comment by styromaniac** [comment]
> So far I can't reach your server via a web browser as well. I installed the yggdrasil client on an android emulator and added some peers from the public list and a DNS address. Do we need to configure more to reach your server?

Sorry. I believe I deleted the entry in my Namecheap Advanced DNS configuration. I forgot about this bug report. I'll re-add it soon.

**Comment by oczkoisse** [comment]
I'm hitting the same issue. I've an HTTP redirect set to the Jellyfin server. Works great on browsers with http as well as https, even on LG webos app. The android client, however, refuses to follow the redirect URL and instead lists the tried candidates:

```
Tried 5 candidates for input, without success.

Unable to reach server:
- https://subdomain.domain.com
- https://subdomain.domain.com:8096
- https://subdomain.domain.com:8920
- http://subdomain.domain.com
- http://subdomain.domain.com:8096
```

Please let me know if I should create a new issue instead. Thanks.
