### ISSUE TITLE
Intermittent black screen for a second or so

### ISSUE THREAD

**Issue by brianjmurrell** [jellyfin/jellyfin-android#959]
### Describe the bug

I start playing a stream and for the most part it plays but at varying intervals -- sometimes longish and other times annoyingly short -- the screen will just go black for a second or so while the audio continues to play.

I had to switch to the LG WebOS player as the above was annoying the crap out of us too much.  The LG WebOS player does not have this problem

As for video player (default, ExoPlayer) I am not sure.  I don't know that I have done anything to change the video player.

### Application version

0.15.1

### Where did you install the app from?

Google Play

### Device information

Chromecast with Google TV

### Android version

12

### Jellyfin server version

10.8.8

### Which video player implementations does this bug apply to?

- [ ] Web player (default)
- [ ] Integrated player (ExoPlayer)
- [ ] External player (VLC, mpv, MX Player)

**Comment by Maxr1998** [comment]
I'm only seeing this late, but note that the app you're using is the Jellyfin Android TV app, not Android app for phones. Thus, you may want to report your issue at https://github.com/jellyfin/jellyfin-androidtv instead.

**Comment by deprale** [comment]
Same issue on Apple TV lol
