### ISSUE TITLE
Ability to show a video in portrait mode

### ISSUE THREAD

**Issue by atsen-dev** [jellyfin/jellyfin-android#965]
**Ability to show a video in portrait mode**
I think it would be great to be able to show video on portrait mode, maybe by à button on the player to exit fullscreen landscape mode

If any developer can tell me if It's a feature that we can add easlily or not theus feature, I can show to work on it. 

What do you think about that ? 
Thanks !

**Comment by Maxr1998** [comment]
This is already supported if you use the integrated player. You can switch to that player in the app's client settings (openable from the settings in Jellyfin).
