### ISSUE TITLE
latest jellyfin on samsung tab A8 not playing

### ISSUE THREAD

**Issue by satstarter** [jellyfin/jellyfin-android#966]
### Describe the bug

start jellyfin go to episode start play i get background but nothings start to play
with webplayer and also not with build in player
only player that works is external vlc player

it started with the latest samsung update on the samsung A8 tablet

with build in player i get some hevc 10 bit error what is strange because the user is allowed to transcode?
also when going to webbrowser nothing starts to play

### Application version

2.5.0-beta.1

### Where did you install the app from?

Sideloaded APK (proprietary build)

### Device information

Samsung A8 tablet

### Android version

android 13

### Jellyfin server version

10.8.9

### Which video player implementations does this bug apply to?

- [X] Web player (default)
- [X] Integrated player (ExoPlayer)
- [ ] External player (VLC, mpv, MX Player)

**Comment by satstarter** [comment]
when i look in the info both webplayer and internal player says file is compatible with device?
i'm sure thats not the true.

**Comment by satstarter** [comment]
Hoi, after some testing i know now its a 10bit problem everything works h.264 hevc (h.265) x.264
but only in 8bit 10bit encodings give this problem
thanx

**Comment by satstarter** [comment]
Hoi, is there something i can do about this?
i have a lot off series that are in 10 bit
now i select external player (vlc) to play these files but by bingwatching i have to start manually each episode
and in webplayer or internall player it just wont play in 10bit
so if theres nothing i can do i have to reencode a lot of files
thanx in advance

**Comment by satstarter** [comment]
sobody knows what this means ?

     encoder         : Lavc59.37.100 libfdk_aac
frame=    1 fps=0.0 q=-1.0 size=       0kB time=00:00:00.00 bitrate=4063.5kbits/s speed=5.73x    
frame=  617 fps=0.0 q=-1.0 size=   13056kB time=00:00:24.82 bitrate=4308.9kbits/s speed=49.6x    
frame= 1210 fps=1209 q=-1.0 size=   30976kB time=00:00:48.50 bitrate=5231.9kbits/s speed=48.5x    
frame= 1822 fps=1214 q=-1.0 size=   46080kB time=00:01:13.05 bitrate=5167.1kbits/s speed=48.7x    
frame= 2452 fps=1225 q=-1.0 size=   67072kB time=00:01:38.10 bitrate=5600.9kbits/s speed=  49x    
frame= 3031 fps=1212 q=-1.0 size=   83200kB time=00:02:01.33 bitrate=5617.4kbits/s speed=48.5x    
frame= 3679 fps=1225 q=-1.0 size=  113664kB time=00:02:27.12 bitrate=6328.9kbits/s speed=  49x    
frame= 4297 fps=1226 q=-1.0 size=  125440kB time=00:02:51.89 bitrate=5978.2kbits/s speed=49.1x    
frame= 4945 fps=1235 q=-1.0 size=  157184kB time=00:03:17.87 bitrate=6507.3kbits/s speed=49.4x    
frame= 5600 fps=1243 q=-1.0 size=  179712kB time=00:03:44.03 bitrate=6571.4kbits/s speed=49.7x    
frame= 6365 fps=1271 q=-1.0 size=  196352kB time=00:04:14.70 bitrate=6315.1kbits/s speed=50.9x    
frame= 7065 fps=1283 q=-1.0 size=  215552kB time=00:04:42.74 bitrate=6245.3kbits/s speed=51.3x    
frame= 7854 fps=1307 q=-1.0 size=  232448kB time=00:05:14.29 bitrate=6058.7kbits/s speed=52.3x    
frame= 7992 fps=1228 q=-1.0 size=  240640kB time=00:05:19.66 bitrate=6166.8kbits/s speed=49.1x    
frame= 8602 fps=1227 q=-1.0 size=  252928kB time=00:05:44.16 bitrate=6020.4kbits/s speed=49.1x    
frame= 9246 fps=1231 q=-1.0 size=  269824kB time=00:06:10.01 bitrate=5973.8kbits/s speed=49.3x    
frame= 9825 fps=1227 q=-1.0 size=  288256kB time=00:06:33.12 bitrate=6006.8kbits/s speed=49.1x    
frame=10468 fps=1230 q=-1.0 size=  309248kB time=00:06:58.78 bitrate=6049.3kbits/s speed=49.2x    
frame=11129 fps=1235 q=-1.0 size=  318976kB time=00:07:25.28 bitrate=5868.3kbits/s speed=49.4x    
frame=11780 fps=1239 q=-1.0 size=  333056kB time=00:07:51.32 bitrate=5788.7kbits/s speed=49.6x    
frame=12469 fps=1246 q=-1.0 size=  344832kB time=00:08:18.86 bitrate=5662.5kbits/s speed=49.8x    
frame=13090 fps=1246 q=-1.0 size=  364288kB time=00:08:43.70 bitrate=5698.4kbits/s speed=49.8x    
frame=13739 fps=1248 q=-1.0 size=  379648kB time=00:09:09.62 bitrate=5658.6kbits/s speed=49.9x    
frame=14367 fps=1248 q=-1.0 size=  394240kB time=00:09:34.77 bitrate=5618.9kbits/s speed=49.9x    

[q] command received. Exiting.

frame=14789 fps=1254 q=-1.0 Lsize=  405657kB time=00:09:51.75 bitrate=5615.7kbits/s speed=50.2x    
video:377777kB audio:27740kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.034411%

**Comment by EliasGagnef** [comment]
I have the exact same issue on my Tab A8, if I go into the integrated player and choose 360p it will play, not even in the web interface...

**Comment by EliasGagnef** [comment]
So it seems like maybe transcoding has stopped working? Here's some screenshots of 1 show and 2 movies that I know needed transcoding before, but aren't functional anymore now:

![Screenshot_20230210_125816_Jellyfin](https://user-images.githubusercontent.com/46574798/218088276-7289062e-3bda-492d-8115-858e093ac1a8.png)
![Screenshot_20230210_125833_Jellyfin](https://user-images.githubusercontent.com/46574798/218088286-a6936113-9059-4371-af27-4d7b9e122036.png)
![Screenshot_20230210_125848_Jellyfin](https://user-images.githubusercontent.com/46574798/218088304-7ab28a5d-79b9-4d99-9ff7-30bb5396d0db.png)

Also, in the web player (that usually works better for me) the same thing happens, except that it freezes on the image of the movie after you press play

**Comment by satstarter** [comment]
thats right i installed on my other pc jellyfin server 10.8.8 and then it's working as before
so its a server problem something is broken in jellyfin server 10.8.9.

**Comment by JulioQc** [comment]
Same problem on Samsung A7 (SM-T500) on either integrated, web player or in Chrome with HEVC 10 bits. Works fine when using VLC for playback. 

Server side log shows when broken: 

`StreamBuilder.BuildVideoItem( Profile="Jellyfin Android", Path="/mnt/media/Video/TV Shows/The Office (US)/Season 2/The Office (US) - S02E01 - The Dundies Bluray-1080p.mp4", AudioStreamIndex=null, SubtitleStreamIndex=null ) => ( PlayMethod=DirectPlay, TranscodeReason=0 ) `

When playing same file from Chrome on my desktop:

`treamBuilder.BuildVideoItem( Profile="Anonymous Profile", Path="/mnt/media/Video/TV Shows/The Office (US)/Season 2/The Office (US) - S02E01 - The Dundies Bluray-1080p.mp4", AudioStreamIndex=null, SubtitleStreamIndex=null ) => ( PlayMethod=Transcode, TranscodeReason=VideoCodecNotSupported ) `

Anyhow, bug now seems to be mentioned in the documentation ([2](https://jellyfin.org/docs/general/clients/codec-support/#wikipedias-video-codec-tables )). Doc is missing the workaround however (use external player).

**Comment by satstarter** [comment]
> Anyhow, bug now seems to be mentioned in the documentation ([2](https://jellyfin.org/docs/general/clients/codec-support/#wikipedias-video-codec-tables)). Doc is missing the workaround however (use external player).

i saw this also however the docs saying this is whit H.265 8 bit and 10 bit but thats not true 8 bit just plays fine
and playing a file on android tv app with ass subtitles and exoplayer also not transcoding anymore

**Comment by JulioQc** [comment]
hmm ya I guess that doc would need a little update :)

**Comment by neingeist** [comment]
I also have issues on the Samsung Galaxy Tab A8.

✔️  Jellyfin Android on an old Android 10 phone plays most media fine using the integrated player, most using DirectPlay

❌ Jellyfin Android on the new Androd 13 table (Samsung Galaxy Tab A8) using the integrated player has lots of playback issues, it seems it's all related to HEVC media. But not all HEVC media.

**Comment by neingeist** [comment]
> x Jellyfin Android on the new Androd 13 table (Samsung Galaxy Tab A8) using the integrated player has lots of playback issues, it seems it's all related to HEVC media. But not all HEVC media.

Confirmed: It's all HEVC 10 bit media that DON'T PLAY on the Samsung Galaxy Tab A8 (Android 13), using Jellyfin Android App integrated player. Same media plays fine in the integrated player on my old Android 10 phone.

**Comment by satstarter** [comment]
oke one more thing its for sure a server problem i tested it with server version 10.8.8 and then 10 bit hevc plays
with version 10.8.9 10bit hevc is broken. on Samsung Galaxy Tab A8 (Android 13)

**Comment by neingeist** [comment]
> oke one more thing its for sure a server problem i tested it with server version 10.8.8 and then 10 bit hevc plays with version 10.8.9 10bit hevc is broken. on Samsung Galaxy Tab A8 (Android 13)

Doesn't work for me with server version 10.8.8 neither.

**Comment by satstarter** [comment]
> Doesn't work for me with server version 10.8.8 neither.

strange do you mean it dont transcode then or do you mean direct play ?

**Comment by neingeist** [comment]
> > Doesn't work for me with server version 10.8.8 neither.
> strange do you mean it dont transcode then or do you mean direct play ?

it tries to direct play but fails (without an error message, just doesn't play).

**Comment by satstarter** [comment]
ok for me it plays in 10.8.8 only transcoded not direct play but my problem is
from the moment that i updadet it to 10.8.9 it doesnt transcode anymore it tries to direct play
but in 10.8.8 i am 100% sure it transcode

**Comment by satstarter** [comment]
player: html video player
play method: transcode
protocol: http
streamtype: Video

transcode info
video codec: H264
audio codec: AAC

reason for transcode container not supported

its hevc 10bit video file playing whit webplayer on samsung a8 tablet

**Comment by neingeist** [comment]
I was testing with the integrated player, not the web player, so this adds to the confusion.

Meanwhile I was testing playing HEVC 10 bit videos outside of Jellyfin Android: The Samsung Galaxy Tab A8 does not play them in the Samsung(?) Video Player app and MX player does not it play it using HW decoding (SW decoding only). The A8 has a Mali G52 GPU, so it *should* play them using HW, AFAICS, but it doesn't. 

Test videos:
https://www.larmoire.info/jellyfish/

**Comment by satstarter** [comment]
Ok but i think the samsung A8 cant play hevc 10 bit thats where the jellyfin server supposed to jump in and transcode
the video in a playable format for the client (tab A8) and thats my problem in server 10.8.8 this was possible but not anymore in 10.8.9

**Comment by neingeist** [comment]
My version of the A8 has a ARM Mali-G52 GPU, which AFAICT has a Mali-V52 video processor, which should be able to decode HEVC 10 bit. I write "should" because apparently it doesn't. 

Nevertheless, I think Jellyfin should transcode (or I should be able to force transcoding.)

(Btw, the default web/HTML player used by the App does not play without stuttering... But at least 10.8.8 server does transcode.)

**Comment by peliopoulos** [comment]
My A7 Lite now works with version 2.50 of the app

**Comment by neingeist** [comment]
> This is crazy, I got the Tab A9+ and still have the same problem. Went from a Mediatek P22 to a Snapdragon 695, GPU is entirely different too. What is causing this????

Check if the tablet is playing the 10 bit files here: https://repo.jellyfin.org/jellyfish/

Can't speak for the A9+ but not playing HEVC-10bit is very common among the cheap tablets. For whatever reason, perhaps it's just the vendor not setting up the firmware completely.

**Comment by peliopoulos** [comment]
> > Still a problem for my A7 Lite - too bad cause it's making me think I should get a new tablet.
> 
> This is crazy, I got the Tab A9+ and still have the same problem. Went from a Mediatek P22 to a Snapdragon 695, GPU is entirely different too. What is causing this????

Web player seems to work fine, false alarm here.  Thanks!
