### ISSUE TITLE
Playing audio files crashes app

### ISSUE THREAD

**Issue by flowlee** [jellyfin/jellyfin-android#97]
When playing any audio file with the latest beta (beta6) the app crashes instantly. The notification remains but does not respond to any playback commands.

Here is the relevant log file:
https://pastebin.com/HCszK71e

Playback works fine with the same configuration in beta5.

Edit:
This link was mentioned by vitorsemeano on Riot as being relevant:
https://issuetracker.google.com/issues/79478779

The device this happens on is running Android Pie.

**Comment by cesalo** [comment]
Same here .. just installed beta6 and I'm having the same issues - Will try beta5.

**Comment by hefistion** [comment]
same, beta 6, tested on android 8.0.1

with beta 5 works well

**Comment by Cupbox** [comment]
Same here. Beta 6. Android 7. ARM device.

**Comment by vitorsemeano** [comment]
#107 Should fix this.

**Comment by dkanada** [comment]
@flowlee @cesalo @Cupbox beta7 should fix this, try it out and report back when you can :)

**Comment by cesalo** [comment]
Thanks I just installed it and played some music with no issues. I did
notice that when the song is minimized is not showing the picture of the
album in the lower left corner like in beta 5.

**Comment by Cupbox** [comment]
Working perfectly.
Thank you.

**Comment by cesalo** [comment]
Not sure if this the correct place to put this but beta 7 has fixed a lot of graphical/formatting issues in my tablet (Pixel Slate), the high resolution display was making using the app very difficult .. texts too big, few pictures overlapping, etc. Beta 7 has fixed all of this .. excellent work guys.

**Comment by dkanada** [comment]
@cesalo I have also fixed the missing album art recently :) I will mark this issue as resolved.
