### ISSUE TITLE
Discouraging external player from playing some videos

### ISSUE THREAD

**Issue by Cnotech** [jellyfin/jellyfin-android#970]
### Describe the bug

When using external players(MX Player Pro for me), some videos can't be played by clicking the "play" icon in Jellyfin app.It toasts "Media cannot be played by this device".

![Snipaste_2023-02-09_23-02-01](https://user-images.githubusercontent.com/53827731/217849685-add42ec7-b512-4a49-990e-41faaff993b9.png)

But if you "Copy stream URL" and use MX Player to play, MX Player actually could play that normally.

Even if using the "Web player" or "Integrated player" that works fine!

After checking the source code I found it was caused by the `DeviceProfileBuilder.getExternalPlayerProfile()` created a `DeviceProfile` declares far few play profiles decoders than MX Player (or VLC) has.

![Snipaste_2023-02-09_22-23-15](https://user-images.githubusercontent.com/53827731/217849987-99086fa6-cbc9-492e-a4a8-44e2e4b66357.png)

![Snipaste_2023-02-09_22-19-33](https://user-images.githubusercontent.com/53827731/217849991-011668a2-35cb-4fc2-90dc-307a75128378.png)

, so when request `mediaInfoApi.getPostedPlaybackInfo()` with that play profile, server returns 

```
    ...
    "SupportsTranscoding": false,
    "SupportsDirectStream": false,
    "SupportsDirectPlay": false,
    ...
```

,then `JellyfinMediaSource` failed to find a valid play method and throw `"No play method found for $name ($itemId)"`

The temporary solution is to change the generator for `externalPlayerProfile` in class `ExternalPlayer`, use `deviceProfileBuilder.getDeviceProfile()` since external players could play videos supported by the device,I would put a new pull request later.But a better solution is to let `JellyfinMediaSource` know whether `appPreferences.videoPlayerType == VideoPlayerType.EXTERNAL_PLAYER` and let it go when "No play method found",since external players are generally strong,like this :
![Snipaste_2023-02-09_23-11-14](https://user-images.githubusercontent.com/53827731/217852570-d06e1424-3ec1-42ff-844f-a8ec89611fa5.png)

I'm not familiar with Kotlin so I didn't do so.Looking forward to your suggestion!

### Logs

```shell
E/MediaSourceResolver: Cannot create JellyfinMediaSource
    java.lang.IllegalArgumentException: No play method found for VIDEO_TITLE_HERE (ITEM_ID_HERE)
        at org.jellyfin.mobile.player.source.JellyfinMediaSource.<init>(JellyfinMediaSource.kt:29)
        at org.jellyfin.mobile.player.source.MediaSourceResolver.resolveMediaSource-eH_QyT8(MediaSourceResolver.kt:71)
        at org.jellyfin.mobile.player.source.MediaSourceResolver$resolveMediaSource$1.invokeSuspend(Unknown Source:21)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at android.os.Handler.handleCallback(Handler.java:942)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7872)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
```

### Application version

2.5.0

### Where did you install the app from?

Sideloaded APK (libre build)

### Device information

Xiaomi 10, Pixel 6 Pro(VM)

### Android version

Android 12(MIUI 13), Android 13

### Jellyfin server version

10.8.7

### Which video player implementations does this bug apply to?

- [ ] Web player (default)
- [ ] Integrated player (ExoPlayer)
- [X] External player (VLC, mpv, MX Player)

**Comment by IDisposable** [comment]
Excellent report. I also like the idea of just using `deviceProfileBuilder.getDeviceProfile()`. Don't really see any downsides

**Comment by Maxr1998** [comment]
With the way Jellyfin works, a direct play profile that keeps container and codecs unset can be matched with all media and should support everything. Why the server returns a `SupportsDirectPlay` isn't obvious to me at the moment, maybe it's related to the media or a bitrate limit..

**Comment by kevinmatthe** [comment]
So how's this issue going? Still not fixed? It seems to be not the same code.

**Comment by IDisposable** [comment]
This seems like a real issue, which I would be happy to submit a PR for, but not seeing the project owners weighing in makes it likely it would get orphaned and not merged.

**Comment by Maxr1998** [comment]
Using the device profile made for ExoPlayer doesn't seem like a good solution, especially since the external player already only supports direct play, and no transcoded playback.

The device profile for the external player should have been fine, but maybe there were some behavior changes in recent server versions that require some rework.

**Comment by Maxr1998** [comment]
I do however wonder why the server decides that direct play is not allowed. Maybe the bitrate limit kicks in and prevents playback? @Cnotech could you send me your server logs after attempting to play a file that doesn't work? That should provide me with a reason for this issue.
