### ISSUE TITLE
Cannot play DTS-encoded WAV format

### ISSUE THREAD

**Issue by AxIauk** [jellyfin/jellyfin-android#974]
### Describe the bug

1. The jellyfin windows client plays well,
2. The jellyfin androidtv can pass-through the power amplifier to decode and light up DTS to play very well.
3. I tried to install VLC from google store, playback via DLNA is fine.
Problem: The mobile client cannot decode. The speakers are rustling, obviously not decoding correctly, I tried with Web player (default).Integrated player (ExoPlayer).External player (VLC) all the same.
Music format information is relatively rare.
The file extension is .wav
The encoding format is standard DTS-ES 6.1 Discrete

Format                      : Wave
File size                   : 39.9 MiB
Duration                    : 3 min 57 s
Overall bit rate mode       : Constant
Overall bit rate            : 1 411 kb/s
IsTruncated                 : Yes

Audio
Format                      : DTS ES XXCH
Format/Info                 : Digital Theater Systems
Commercial name             : DTS-ES Discrete
Codec ID                    : 1
Duration                    : 3 min 57 s
Bit rate mode               : Constant
Bit rate                    : 1 411.2 kb/s
Channel(s)                  : 7 channels
Channel layout              : C L R Ls Rs Cb LFE
Sampling rate               : 44.1 kHz
Frame rate                  : 43.066 FPS (1024 SPF)
Bit depth                   : 16 bits
Compression mode            : Lossy
Stream size                 : 39.9 MiB (100%)

### Application version

2.5.0-beta.1

### Where did you install the app from?

None

### Device information

OnePlus 9P

### Android version

Android13 OxygenOS

### Jellyfin server version

10.8.9

### Which video player implementations does this bug apply to?

- [X] Web player (default)
- [X] Integrated player (ExoPlayer)
- [X] External player (VLC, mpv, MX Player)

**Comment by Maxr1998** [comment]
Are you actually using the video players to play this? Your file seems to be audio only which is always played by the web player, and thus, impacted by #39. Closing this as a duplicate.
