### ISSUE TITLE
Books (pdf)

### ISSUE THREAD

**Issue by Zourlo** [jellyfin/jellyfin-android#977]
### Describe the bug

When I tried to read a pdf (scanned book / images), it is difficult to read the text. It is too blurry.
If I open the pdf with a pdf reader on my android, I do not have this problem. 
Can I change a setting to avoid compression, increase the quality, etc... I didn't find it.
Thank you.

### Application version

2.4.4

### Where did you install the app from?

Google Play

### Device information

Aquos Wish

### Android version

Abdroid 12

### Jellyfin server version

10.8.9

### Which video player implementations does this bug apply to?

- [ ] Web player (default)
- [ ] Integrated player (ExoPlayer)
- [ ] External player (VLC, mpv, MX Player)

**Comment by Zourlo** [comment]
Just to add more details.

I checked a pdf from the web UI, the pdf is still blurry. But if I use "desktop mode", I can read the text on the pdf without difficulty.

**Comment by Zourlo** [comment]
![Screenshot_20230212-133122~2](https://user-images.githubusercontent.com/7470935/218293121-e4ee92d6-9246-43d8-b0e6-f24e9ab46d0c.png)
![Screenshot_20230212-133018~2](https://user-images.githubusercontent.com/7470935/218293122-4cd023fa-2768-454a-8042-57f17983d80d.png)

2 screenshots, from the web version on my android phone 
first one "desktop mode", second one mobile mode 

the android app as the same issue, I think the scaling should not be done by jellyfin and the problem will be fixed.

**Comment by Maxr1998** [comment]
Probably fixed by jellyfin/jellyfin-web#4347, closing.
