### ISSUE TITLE
Casting Volume Control Doesn't Work

### ISSUE THREAD

**Issue by seniorm0ment** [jellyfin/jellyfin-android#980]
When casting music (specifically casting to device runnung Jellyfin Web, also tried with Mopidy), volume control om Android doesn't adjust volume of casted audio. It shows the cast volume and I can turn it all the way up or down with no audible change in volume.

Pixel 6 Pro
Jellyfin FDroid
GrapheneOS

**Comment by seniorm0ment** [comment]
Relevant

**Comment by JosefRypacek** [comment]
Physical volume buttons on Samsung Galaxy S22 does not adjust volume when casting to chromecast. I need to press volume up/down to show touch volume control and then use touch control to change the volume.
