### ISSUE TITLE
Plugins support - jellyscrub and intro-skipper

### ISSUE THREAD

**Issue by UnknownVariableTeam** [jellyfin/jellyfin-android#985]
**Describe the feature you'd like**
You did a very nice job adding support for these two plugins in the desktop version of JMP. I think adding support for androdia would also be a good option. Not for android web becouse it exist. I think for android application https://play.google.com/store/apps/details?id=org.jellyfin.mobile maybe Starting out in beta? 
- adding a button to skip intro 
- When scrolling, chapters are shown, and additionally jellyscrub support. 

**Additional context**

**Comment by nielsvanvelzen** [comment]
JMP release notes

> Note: Adding support for this is intended to alleviate the alternative which is people manually patching the client. Please do not bother other Jellyfin client maintainers to add unofficial plugin support. In the event that official Jellyfin functionality replaces unofficial plugins or renders them unusable, unofficial plugins will be dropped.
